### ISSUE TITLE
Bug: When I launch the game through reloaded it never load and for some reason the .exe file completely deletes itself from the folder

### ISSUE THREAD

**Issue by McManners** [Reloaded-Project/Reloaded-II#100]
When I try and launch Sonic Heroes through Reloaded, the game doesn't launch and for some odd reason, the .exe file deletes itself from the folder, including its shortcut from my desktop. I don't why this is happening and I'm not exactly sure how to check how this happens besides launching the game through Reloaded.

**Comment by Sewer56** [comment]
I'd suggest checking your Antivirus logs; it's probably throwing a false positive and trying to delete Reloaded.
