### ISSUE TITLE
Help: When I go to the Download Mods page there are no applications

### ISSUE THREAD

**Issue by battleman1** [Reloaded-Project/Reloaded-II#102]
When I open the "Download Mods" page in the application nothing shows up. I have all prerequisites.
![image](https://user-images.githubusercontent.com/89323056/130336872-4bc477b4-abb5-40ba-a074-49e2dde8f065.png)

**Comment by Sewer56** [comment]
Can you access http://packages.sewer56.moe:5000 from your web browser?

Usually in the Configure Sources menu, the default URL is set to `http://packages.sewer56.moe:5000/v3/index.json`
![image](https://user-images.githubusercontent.com/6697380/130343054-ee856e1b-e6b1-4691-8336-2ddbbd3391d1.png); if it is not there, or you have removed it for whatever reason; that's all you'll need to do.

**Comment by battleman1** [comment]
Thanks, this worked.
