### ISSUE TITLE
Bug happens seemingly every day?

### ISSUE THREAD

**Issue by TLHunter312** [Reloaded-Project/Reloaded-II#103]
![Github](https://user-images.githubusercontent.com/89611078/131036047-86b60720-dd58-48e0-be90-caa4aeea93db.JPG)

This for some reason started happening yesterday, I'm not sure why or anything, It was fine from Saturday Aug. 21 (when I started playing Persona 4 using mods) until yesterday when I tried to play. It happens when I try to launch the Reloaded-II.exe; I've attached a screenshot of what it says.
EDIT: It seemingly happens at random, not sure if it's daily but seemingly every time I turn on my computer or every other time.

**Comment by Sewer56** [comment]
Sorry for the late response. 
Can you tell me the nature in which the Reloaded Launcher is normally closed?

- Are you killing it from task manager?
- Shutting down Windows?
- Closing it normally?

This seems really abnormal.

**Comment by TLHunter312** [comment]
Closing it normally I'm pretty sure, though I do think when I've shut my computer off for the night that I might be doing so before closing R2.

**Comment by TLHunter312** [comment]
I would like to add recently I did close it normal and the problem still happened where the game wouldn't fully close for whatever reason, even Microsoft process manager couldn't close it for some strange reason, the only solution was to restart my computer.

**Comment by Sewer56** [comment]
This is fixed in next update.
