### ISSUE TITLE
Failed to parse Reloaded-II launcher configuration

### ISSUE THREAD

**Issue by AeonicX7** [Reloaded-Project/Reloaded-II#107]
https://media.discordapp.net/attachments/797265659679211540/935276837939085312/unknown.png <-- error message

I woke my computer from sleep, booted up Steam and launched p4g through my library before remembering I had to launch it through the mod loader. I closed out of the game and opened Reloaded-II.exe, which led to the error popup. Opening the program again opened a terminal that gave the following error message:
[modloader:XactRedirector] W [mods\SND\BGM\1023.raw.txth Duration is not aligned properly, it may not play correctly ingame!
However, the game booted up normally with no issues.

**Comment by Sewer56** [comment]
This is already fixed in the latest preview, which should roll out to everyone not long from now.
