### ISSUE TITLE
Bug: Failed to Load the Reloaded-II when using relative executable paths

### ISSUE THREAD

**Issue by marcussacana** [Reloaded-Project/Reloaded-II#110]
**Describe the Bug**
I'm trying make my game mod setup portable by puting a relative executable path at the `AppLocation` field.

**To Reproduce**
Since I put the Reloaded-II directory side-a-side with the root game dir, I must back one folder with `\..\`
Edit the AppConfig.json to a relative path like `.\..\gamesubdir\gamemain.exe`

**Screenshots**
![image](https://user-images.githubusercontent.com/10576957/154827953-096e6902-fcd7-403b-9134-301bbc4e718d.png)

**Comment by Hadkan** [comment]
I myself am currently facing this problem and was wondering if you have found a solution yet or are we gonna wait together?

**Comment by marcussacana** [comment]
No lucky, I just removed the reloaded-2 and made my mod standalone.

**Comment by Hadkan** [comment]
The sad thing is that modding P4g needs reloaded-2 so Im just waiting for a fix on this problem

**Comment by marcussacana** [comment]
Not all mods, if are mods to replace the file you can just repack the game files manually, this is my stuff to mod the P4G
[P4G Tools.7z.zip](https://github.com/Reloaded-Project/Reloaded-II/files/8124032/P4G.Tools.7z.zip)
The repacker is the preappfile tool, and is included a version that I modified, the preappfile_rep, in this preappfile_rep the --append function don't only append files, but replace as well, if the file already exists then the tool will replace, if is a new file the file will be appended.
you can use with: `preappfile_rep -i C:\DirToPack -a C:\Games\P4G\Days\data_e.cpk --pac-index 7 -o C:\Games\P4G\Days\data_e_new.cpk` after run this command you maybe will need rename the genareted .pac file to match with the dataXXXXX.pac files, in the case I used --pac-index 7 then should be data00007.pac for example.
With that you can mod the game and still portable :)

**Comment by Sewer56** [comment]
I was sick with COVID, therefore I didn't respond previously. I am mostly if not recovered by now.
Needless to say, `Relative Paths` are a huge can of worms. 

The meaning of a `Relative Path` varies depending on where the code is executed. 
This path is used from multiple contexts, including: 
- The Launcher.
- External Utilities.
- The Application/Game(s) Themselves.

I could probably make the path relative to the config file itself (`App.json`); however anything else would require a bunch of hacks.

**Comment by marcussacana** [comment]
looks fine to me in that way.

**Comment by Sewer56** [comment]
![image](https://user-images.githubusercontent.com/6697380/155383975-43371fa6-9ac3-4635-82b0-a3902f3713e2.png)

You can try this build of Reloaded-II. [Release.zip](https://github.com/Reloaded-Project/Reloaded-II/files/8127090/Release.zip)
I haven't fully tested support for relative paths; but the core components do seem to work properly.

Just please note that the path is relative to the folder of the application configuration (`Apps/p4g.exe/AppConfig.json`) or your equivalent.

**Comment by marcussacana** [comment]
Working, thanks
