### ISSUE TITLE
Help: Please help me with this error

### ISSUE THREAD

**Issue by Veitaserum4** [Reloaded-Project/Reloaded-II#113]
**Did you install the Prerequisites?**
yes
**Describe the Issue**
been searching for hours, tried everything but I keep getting this error
**Screenshots**
![image](https://user-images.githubusercontent.com/63559389/169376217-fd9b4224-c7c8-44ab-a7a5-9c673eef4c86.png)
![image](https://user-images.githubusercontent.com/63559389/169376345-d9ec426a-6f5b-4e74-adeb-991debed03ad.png)
![image](https://user-images.githubusercontent.com/63559389/169376379-8f865974-53ce-4dcd-a2ef-67f8e689d856.png)

**Additional Resources**
[2022-05-19 14.39.47 ~ Tsonic_win.txt](https://github.com/Reloaded-Project/Reloaded-II/files/8732961/2022-05-19.14.39.47.Tsonic_win.txt)

**Comment by Sewer56** [comment]
Try deleting this mod from the launcher:
![image](https://user-images.githubusercontent.com/6697380/169377264-dcea437d-6ec1-4aa7-bc5a-4c3bb1eb52b2.png)

The launcher should automatically try to re-download it.

**Comment by Veitaserum4** [comment]
![image](https://user-images.githubusercontent.com/63559389/169381103-c314d32a-36bf-41a8-a7c2-6b6342b88f00.png)
i got this error when i did, then reloaded crashed
after i rebooted it did a download, now when i boot up sonic heroes, I see "loading" then it crashes

**Comment by Sewer56** [comment]
Guessing the crash happened because the game was running (or for some other reason DLL was still in use).
Kill `TSonic_win.exe` if it still exists in the manager and close the Reloaded launcher.

Then delete the mod manually, i.e. delete `reloaded.sharedlib.hooks` in Reloaded's `Mods` Folder.

**Comment by Veitaserum4** [comment]
No Tsonic win in task manager, i closed reloaded, deleted reloaded.sharedlib.hooks from the mods folder
it redownloaded reloaded.sharedlib.hooks, i launched the game and still the same crash
Never tabbed out and there's no scripts folder in the game directory.

**Comment by Sewer56** [comment]
Yeah, try enabling mods one by one. Maybe there's some kind of conflict. 
Feel free to also screenshot the console window, or upload the latest log before the crash:

![image](https://user-images.githubusercontent.com/6697380/169384198-0f4c7cad-01bb-4a49-b2eb-a242689096b5.png)

You can access logs in this way.

**Comment by Veitaserum4** [comment]
![image](https://user-images.githubusercontent.com/63559389/169385215-80a151da-3a0b-4757-99f8-2abd2f03b011.png)

I disabled tonerr and only ran the other SH essentials dependencies, it worked, but I need tonerr to run SH: graphics essentials and widescreen revamp
When i run SH essentials without tonerr, i still get the same crash

**Comment by Sewer56** [comment]
Can you get a crash log for when it crashes with TONERR enabled?

**Comment by Veitaserum4** [comment]
[2022-05-19 15.21.00 ~ Tsonic_win.txt](https://github.com/Reloaded-Project/Reloaded-II/files/8733652/2022-05-19.15.21.00.Tsonic_win.txt)

**Comment by Sewer56** [comment]
The issue is in the error log
`Unable to load DLL 'dlang-prs32.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)`

Try removing `reloaded.sharedlib.csharp.prs` from your mods folder then letting Reloaded re-download it.
If it still doesn't work, check your Antivirus logs. I've heard reports of this file being incorrectly flagged on some AV software in the past.

**Comment by Veitaserum4** [comment]
It redownloaded it and the game now runs with tonerr enabled
Going to try with SH essentials

**Comment by Veitaserum4** [comment]
It works now!!!!!!!!!!!! thanks so much!

**Comment by Sewer56** [comment]
Have fun :P
