### ISSUE TITLE
Help: the installer gives me an error at 16 and doesnt install i installed net and vd C++ but i tried the manual one and it says there is no net i installed it still does not work.

### ISSUE THREAD

**Issue by user983093** [Reloaded-Project/Reloaded-II#118]
**Did you install the Prerequisites?**
You can see them right beside the download button on each official download. 
You'll need all of them as stated.

**As seen on GitHub**:
![image](https://user-images.githubusercontent.com/6697380/90259427-e71e8900-de41-11ea-87aa-0ff27cf5e486.png)

**As seen on GameBanana**:
![image](https://user-images.githubusercontent.com/6697380/90259465-f8679580-de41-11ea-9ef9-08eb3e9c4a2e.png)

**Describe the Issue**
A clear and concise description of what you would like help with.

**Screenshots**

**Additional Resources**
If the issue is related to any external resource e.g. specific version of a mod or pack, consider stating the version or linking the resource in question. Preferably though, mod specific issues should go in their own GitHub repositories as I in most cases would not be able to help.
![Screenshot 2022-06-23 045236](https://user-images.githubusercontent.com/108041846/175197023-3e1d39f3-2601-4037-aeb1-61954a55fd93.png)

**Comment by Sewer56** [comment]
Are you in an unusual setup, like a company network that prohibits writing to Desktop?

This is a pretty unusual error, aa the installer itself runs as admin and thus should be able to access Desktop.

(PS. You can also manually install Reloaded by downloading `Release.zip` from the Releases page and extracting it.)

**Comment by user983093** [comment]
oh i fixed it ty
