### ISSUE TITLE
Help: Please help me with mod loader dll not found

### ISSUE THREAD

**Issue by CerealMastery** [Reloaded-Project/Reloaded-II#123]
When trying to launch a game I get an error with the below message:

![image](https://user-images.githubusercontent.com/108477550/177328329-7ce63206-2bb4-4410-896f-11238dcff3f9.png)

The games runs after that but none of the mods seem to be active. I have the game installed on an external hdd but running it off of an internal drive doesn't change anything.

**Comment by Sewer56** [comment]
This error means:

File `Reloaded II/Loader/Reloaded.Mod.Loader.dll` does not exist.  
I suggest re-extracting Reloaded.  

If you have Unicode (non-standard) characters in your path to Reloaded, or username, let me know. Might be part of the issue.

**Comment by Sewer56** [comment]
Seems I broke Unicode paths [in the C++ side] in last update; already rolling an update to fix that. All good.

**Comment by CerealMastery** [comment]
Yeah everything works well now, thanks! But reloaded always starts the game in a window, is there a way to force fullscreen on start-up?

**Comment by CerealMastery** [comment]
Nvm figured it out. Issue solved
