### ISSUE TITLE
Request: Ability to disable Wine Compatibilty Notice

### ISSUE THREAD

**Issue by GameEnder** [Reloaded-Project/Reloaded-II#124]
I am using Reloaded for Persona 4 in Linux and am using it in ASI injector mode to be able to launch it through steam. It is a minor annoyance but it comes up with the Wine Compatibility Notice prompt every time I start the game. Is it possible to add a config option to skip wine check or have it stop after the first time it shows?

**Comment by Sewer56** [comment]
Sure, I'll add a toggle in the launcher for next update.  

=====

On a technical note.  

Launching from the launcher actually doesn't work under Wine last I checked. When you have ASI Loader it works purely by coincidence. This is because, the launcher resumes the game and then ASI Loader loads Reloaded from inside the game when it gets loaded.  It's a funny thing.

**Comment by GameEnder** [comment]
> Sure, I'll add a toggle in the launcher for next update.
> 
> =====
> 
> On a technical note.
> 
> Launching from the launcher actually doesn't work under Wine last I checked. When you have ASI Loader it works purely by coincidence. This is because, the launcher resumes the game and then ASI Loader loads Reloaded from inside the game when it gets loaded. It's a funny thing.

Yeah I encountered that. The ASI loader was the only way I could get it to work on Linux at all, is kinda jank loading up twice but it works so that is all the matters. At lest the main app starts so I can set everything up, the Persona 4 mod manager Aemulus is completely broken in Wine so I have to build the mods on Windows and copy them over.

**Comment by Sewer56** [comment]
I added this setting in 3c76d6902397605e9e312a0da13e3001bd2c1a66 . 
Will be in a future release.  

It's currently accessible via editing `SkipWineLaunchWarning` in `%appdata%/Reloaded-Mod-Loader-II/Reloaded-II.json`.
