### ISSUE TITLE
Help: I need help with installing the Prerequisetes on steam deck

### ISSUE THREAD

**Issue by CraftDMine** [Reloaded-Project/Reloaded-II#127]
**Did you install the Prerequisites?**
No
**As seen on GitHub**:
![image](https://user-images.githubusercontent.com/6697380/90259427-e71e8900-de41-11ea-87aa-0ff27cf5e486.png)

**As seen on GameBanana**:
![image](https://user-images.githubusercontent.com/6697380/90259465-f8679580-de41-11ea-9ef9-08eb3e9c4a2e.png)

**Describe the Issue**
Hi, I am very new to Linux and am currently trying to get reloaded II running on my steam deck to mod Persona 4. So far what I have done is: 
Download the latest Release.zip and extract it
Add Reloaded-II.exe as a non steam game and enabled proton and ran it and was met with a error telling me to download .NET
Opened protontricks, selected Reloaded-II, and work my way to the "Install a Windows DLL or component" option and select it
I download the .NET core 3.1 desktop runtime and the Visual C++ 2015-19 libraries.
It installs and a few errors begin to pop up but I click ok through them and eventually the Installers pop up and I am able to install everything as normal.
When everything is done I open Reloaded and am told that "The framework 'Microsoft.WindowsDesktop.App', version '5.0.1' was not found.
There is no option to download that version of .NET in Protontricks so I need help with being able to get this installed.
I have tried downloading the installers and right clicking them, open with protontricks but when I select Reloaded I am met with a lengthy error that is not very clear about what went wrong. Any help would be great, Thank You!

**Comment by CraftDMine** [comment]
Ok Figured It out. I went into Flatseal then to Protontricks and checked Everything in the Filesystem area.

**Comment by Sewer56** [comment]
[Since people will eventually end up here from searches, I've also put up a general purpose guide for this on the wiki.](https://reloaded-project.github.io/Reloaded-II/LinuxSetupGuide)
