### ISSUE TITLE
Bug: <Y Happens> when <X>

### ISSUE THREAD

**Issue by arink22** [Reloaded-Project/Reloaded-II#129]
hey i was trying to put mods to sonic heroes and it was working perfectly but some time later it apears me an error of reloaded.gamefiles.rodring
how do i fix that?

*
![Screenshot_1](https://user-images.githubusercontent.com/111252217/184556774-c9983a53-8fac-4a47-a3e5-5fd3db322081.png)

**Comment by Sewer56** [comment]
Download the other mod in the HD Rings page on GameBanana. One mod uses the other.

I've asked the mod author to fix this before as it's possible for Reloaded to do this download automatically if you correctly publish a mod but it's still not yet fixed.
