### ISSUE TITLE
how to fix issue?

### ISSUE THREAD

**Issue by arink22** [Reloaded-Project/Reloaded-II#131]
reloaded doesnt open me sonic heroes 
![image](https://user-images.githubusercontent.com/111252217/186790912-01ccb40a-1a19-44bb-946a-ca753106f8f6.png)
and it appears me sonic heroes logo but is an r and the mods doesnt show his image

**Comment by Sewer56** [comment]
![image](https://user-images.githubusercontent.com/6697380/186791007-a682f045-5d1c-4ae5-99b7-294d6d44739b.png)
![image](https://user-images.githubusercontent.com/6697380/186791020-9f755ca1-c05a-4b06-860c-1d5ce8438d08.png)

Select path to `TSonic_win.exe`.

You probably moved the folder where your game is installed after adding it to Reloaded; so need to update it.
