### ISSUE TITLE
Sonic Heroes wont load with mods

### ISSUE THREAD

**Issue by Dekuscrub23** [Reloaded-Project/Reloaded-II#132]
Hello!

I've been trying to play Sonic Heroes, but it hasn't been loading the mods, only the application itself.
When I try to load the application with mods, it gives me a lot of error messages. 
Any way to fix this? 
![Screenshot (165)](https://user-images.githubusercontent.com/112790642/188295655-31b55a2a-0b6f-4cdf-bbaf-31000386eb6c.png)

**Comment by Sewer56** [comment]
Forgot to respond.

Can't tell which mod is the culprit from this screenshot since the full log isn't included, but I'd suggest trying to disable individual mods or checking which mod failed in the log.

Then delete and redownload that mod.
