### ISSUE TITLE
.NET error?

### ISSUE THREAD

**Issue by spherix3** [Reloaded-Project/Reloaded-II#135]
Hiya, I downloaded Reloaded-II on a fresh computer, and I keep getting this error message.
![image](https://user-images.githubusercontent.com/114131553/191665639-84cd7e79-8dd0-4153-b8cd-bc9e35d97110.png)
The curious thing is that I made sure to download both the x64 and x86 runtimes, and it still won't launch. Is there some other problem here, or am I just being braindead?

**Comment by Jakob423** [comment]
You have to download .Net 5.0 versions. Reloaded II does not know how to use .Net 6.0 it has an bug so it will not be supported, however .Net 7.0 will be in Reloaded II once .Net 7.0 officially release and it will be plan for the next version.

**Comment by Sewer56** [comment]
Assuming you skipped the installer and manually downloaded Reloaded, you'll need .NET 5.0 Desktop Runtime x86 and x64

https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-5.0.17-windows-x86-installer

https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-5.0.17-windows-x64-installer
