### ISSUE TITLE
Bug: Crash/error message when loading from shortcut in Sonic Heroes

### ISSUE THREAD

**Issue by hermaherp** [Reloaded-Project/Reloaded-II#136]
**Describe the Bug**
Reloaded experiences a crash after loading, when run through a shortcut

**To Reproduce**
Steps to reproduce the behaviour:
1. Apply any mod configuration to Sonic Heroes
2. Generate a shortcut to the game using Reloaded's app screen
3. Close Reloaded
4. Open the shortcut, message will pop after mods are loaded

**Expected Behaviour**
No error message, game loads without issues

**Screenshots**
![imagen](https://user-images.githubusercontent.com/17995927/193902541-e3616dfa-9964-4e06-9b60-d436154aae70.png)
![imagen](https://user-images.githubusercontent.com/17995927/193902713-348366dc-c1d5-4f82-aee0-241013e54fb1.png)

**Additional Context**
Found on fresh Reloaded install, version 1.20.8, 64 bit. Error seems to be non-fatal as mod injection is seemingly correct, game runs without any apparent issues

**Comment by Sewer56** [comment]
Can you grab the crash info?

You can do so like this:  
- Open Event Viewer
- Go to `Windows Logs -> Application`
- Find latest `Error` (red) with `.NET Runtime` as Source.
- Right click, save to a file and send.

![image](https://user-images.githubusercontent.com/6697380/193903966-878c67ef-1f46-4f07-9b65-9e11744d4c81.png)

Chances are it'll probably be an easy fix.

**Comment by hermaherp** [comment]
Event log for Reloaded when the error shows up

[reloadedIIeventlog.zip](https://github.com/Reloaded-Project/Reloaded-II/files/9709886/reloadedIIeventlog.zip)

**Comment by Sewer56** [comment]
Seems to be the same issue that caused crashes after updating for some people; seems R2 really doesn't like it if you close it before the first window shows up. I'll try to fix it for next feature update.

**Comment by Sewer56** [comment]
I believe I fixed this in the latest development builds, we'll see soon enough 👍

**Comment by hermaherp** [comment]
I haven't had any error show up so far on my end so I am inclined to agree it is fixed 😃
