### ISSUE TITLE
Help: So I downloaded Reloaded ll on my pc after fully resseting it (I had it downloaded before). Since that Reloaded keeps crashing after just a few seconds. I can send the crash report as well if anyone needs it.

### ISSUE THREAD

**Issue by xCroaTix** [Reloaded-Project/Reloaded-II#137]
**Did you install the Prerequisites?**
You can see them right beside the download button on each official download. 
You'll need all of them as stated.

**As seen on GitHub**:
![image](https://user-images.githubusercontent.com/6697380/90259427-e71e8900-de41-11ea-87aa-0ff27cf5e486.png)

**As seen on GameBanana**:
![image](https://user-images.githubusercontent.com/6697380/90259465-f8679580-de41-11ea-9ef9-08eb3e9c4a2e.png)

**Describe the Issue**
A clear and concise description of what you would like help with.

**Screenshots**

**Additional Resources**
If the issue is related to any external resource e.g. specific version of a mod or pack, consider stating the version or linking the resource in question. Preferably though, mod specific issues should go in their own GitHub repositories as I in most cases would not be able to help.

**Comment by Sewer56** [comment]
Crash report and/or any accompanying screenshots would be useful, yeah. Otherwise can't really tell what's going on.

**Comment by Sewer56** [comment]
Closing as 'dead'.

Probably related to that DirectInput issue with some HID devices.

If you run into something like this, open the config at (`AppData/Roaming/Reloaded-Mod-Loader-II/Reloaded-II.json`) and change it such that `DisableDInput` is `true` in text editor in config. That may be one cause of such issue.
