### ISSUE TITLE
Help: Missing .NET core 7.0 after install<X>

### ISSUE THREAD

**Issue by JohnGhostly** [Reloaded-Project/Reloaded-II#143]
After Installing the most recent version of reloaded II and all of it's prerequisites on launch I am met with this error. Assuming either it cannot detect .net core 7.0 or it did not install correctly 

https://i.imgur.com/6yjmuAs.png

**Comment by Sewer56** [comment]
Does launching 32-bit titles work properly if you just close the window and ignore the message? Am kinds curious.

**Comment by JohnGhostly** [comment]
Seems updating through the in program updater fixed the issue

**Comment by Sewer56** [comment]
Alright
