### ISSUE TITLE
Help: missing x86 version of .NET Core error

### ISSUE THREAD

**Issue by MarkKoz** [Reloaded-Project/Reloaded-II#144]
**Did you install the Prerequisites?**
Yes. Both manually and by using the Reloaded II setup.

**Describe the Issue**
Launching P4G with Community Enhancement Pack results in the game not launching and the following error

```
Warning: You are probably missing the x86 version of .NET Core, 32-bit applications will not work.
Please re-check the requirements listed on the download page.
Actual Error: Failed to acquire address of GetProcAddress for x86.
  at Reloaded.Mod.Launcher.Lib.Utility.BasicDllInjector.Getx86LoadLibraryAddress()
  at Reloaded.Mod.Launcher.Lib.Utility.BasicDllInjector.<>c.<PreloadAddresses>.b__2_1()
  at Reloaded.Mod.Launcher.Lib.Utility.ActionWrappers.TryCatch(Action action)
```

The error is only shown for the first launch attempt after opening Reloaded II. If launched directly via Steam, the game works perfectly fine.

**Screenshots**
Installed prerequisites:
![bild](https://user-images.githubusercontent.com/1515135/197686495-8c7d37ea-aa67-4b2b-9a7b-4882c0ba17c9.png)
![bild](https://user-images.githubusercontent.com/1515135/197686575-4fc88a80-94b1-4fa5-b115-f4be65ca14a0.png)

**Additional Resources**
- Windows 10 22H2
- Reloaded II 1.21.4
- Community Enhancement Pack 10.2.5
- Persona 4 Golden rev 2033

**Comment by Sewer56** [comment]
This error means that `Loader/Kernel32AddressDumper.exe` in your Reloaded folder didn't work quite right; I'd suggest the following:  
- Download latest release.zip from [Releases](https://github.com/Reloaded-Project/Reloaded-II/releases/latest).  

If it still doesn't work:  
- Restart your machine.  
- Check Antivirus Logs (maybe your AV got in the way and deleted a file somewhere).

**Comment by MarkKoz** [comment]
I tried redownloading it, but I still get the same error. I even tried adding `portable.txt` to the newly extracted download, and adding the P4G app but without CEP/any mods, and still the same error appears.

> Restart your machine.

Still the same error after restarting.

> Check Antivirus Logs

Nothing detected. Logs are clear.

I tried 1.20.8 and that works fine.

**Comment by Sewer56** [comment]
If you shift click the empty space in explorer and run Terminal/Command Prompt/Shell
![image](https://user-images.githubusercontent.com/6697380/197728261-1f5aa610-5e17-4d33-ad0e-c61fa73882c5.png)

And then run `Kernel32AddressDumper.exe` like so 
![image](https://user-images.githubusercontent.com/6697380/197728412-2a56cc9c-1a75-4735-88ca-848049f5510b.png)

Do you get any error?
It shouldn't print anything, just silently exit; but I'm curious.

**Comment by MarkKoz** [comment]
There are no errors. It exits silently like you said.

**Comment by MarkKoz** [comment]
I fixed it. I had .NET 6 SDK installed twice: once from Visual Studio and again from scoop. After uninstalling the SDK via scoop, the error from Reloaded II went away and the game could launch.

I discovered this by trying to compile `Kernel32AddressDumper`. Despite installing the .NET 7 SDK and `dotnet` pointing to it, `dotnet build` was somehow using .NET 6 SDK, which resulted in an error that it cannot target .NET 7. One thing led to another and here we are with a fix.

**Comment by Sewer56** [comment]
Oh, that's interesting. Was the scoop install somehow doing shenanigans to hide the other .NET versions? [by having custom install path etc.]

I'm kinda curious how that happened really.

**Comment by MarkKoz** [comment]
@Sewer56 I'm not sure. I didn't look into it deeply. According to [the help page](https://learn.microsoft.com/en-us/dotnet/core/tools/sdk-errors/netsdk1045#msbuildsdkpath-environment-variable) for the compile error I was getting, the `MSBuildSDKPath` env var could cause issues. Scoop doesn't set this, but it does set a very similarly named env var [here](https://github.com/ScoopInstaller/Main/blob/b80ba0e691be6946d691fe52a893b58ca5f05935/bucket/dotnet-sdk.json). Overall, the scoop manifest is quite simple, so it was most likely one of these two env vars causing problems.

**Comment by zeebo30** [comment]
I'm having this same error but i don't have scoop or .net 6 so that solution will not work for me
