### ISSUE TITLE
Bug: Adding exe on CIFS shares

### ISSUE THREAD

**Issue by DistantThunder** [Reloaded-Project/Reloaded-II#145]
**Describe the Bug**
Can't  add Exes from a CIFS share. It throws an exception.

**To Reproduce**
1. Put a game on network share
2. Map the share (drive letter or not)
3. Try to add exe from share pathh

**Expected Behaviour**
Normal execution

**Screenshots**
![image](https://user-images.githubusercontent.com/3923810/197894928-3ccd9b1b-7d52-49d3-a9d8-3e2330751a5c.png)

**Additional Context**
Windows 10 VM on Linux host. Wine doesn't work requires runtime 7 even after dotnet48 install.

**Comment by Sewer56** [comment]
Oh boy, this will be fun...
I should probably add a fallback for when it can't properly read the EXE, will see when I get up.

**Comment by Sewer56** [comment]
This might be fixed in latest build; no guarantees though :x

**Comment by DistantThunder** [comment]
Ah thanks a lot! Was super fast!! :)
It now seems to work and let me do things through lots of warning. Can't believe .Net of all things doesn't know how to handle CIFS/UNC paths on Windows itself lol.

Still, I hadn't realized this utility wasn't able to repack P5R CPKs, looking at all the problems I had to run it with Wine/Proton, I guess I need to look for CPK repack utilities.
