### ISSUE TITLE
Help : It seems i can't install roloaded II 

### ISSUE THREAD

**Issue by zakaria2011** [Reloaded-Project/Reloaded-II#146]
So i waned to update through the app and it didn't seem to work , so instead i deleted it and tried to download manually the new version and i got this while opening setup.exe
![image](https://user-images.githubusercontent.com/74078047/197923828-a552b195-b89d-48a1-bfe0-b4b181292d9e.png)

**Comment by Sewer56** [comment]
I think you probably hit GitHub rate limit (it only allows for like 60 requests per hour).
If it's not that, consider clearing your wininet cache (Internet Explorer cache in Windows, google it).

That said, if you've got the runtimes you can just extract the latest version [Release.zip from the Releases page](https://github.com/reloaded-project/reloaded-ii/releases/latest).

**Comment by CLPSAW** [comment]
Don't know what to ask this, I downloaded ver. 1.21.5 an hour ago just prior to the update (hillarious I know) and I have 1 question and an issue to report.
During installation, it got stuck on 22% on Downloading and Installing Runtimes, a desktop folder was successfully created but I just cancelled what it was doing and the program launched fine from my Downlaods folder where, apparently, it also created its files on.
And my question is, when I launch my game (SH2, SH3) where are my save files stored? And why couldn't I load my previous saves?
Thanks for the attention and thanks for this awesome mod loader!!!

**Comment by Sewer56** [comment]
I can't comment on SH2 but I didn't have any save related issues with SH3 when Tainaka had me testing the AFS plugin. There shouldn't be a difference as R2 shouldn't be doing anything save file related and the current directory for the application remains unchanged.

**Comment by CLPSAW** [comment]
Yeah, sorry, I found the issue "When running this game without elevated privileges (Run as administrator option), write operations against a location below [%PROGRAMFILES%] [...] might be redirected to [%LOCALAPPDATA%]\VirtualStore on Windows Vista and later.
So it had nothing to do with Reloaded-II, simply my save files were not in the game's proper savedata folder.
