### ISSUE TITLE
Request: Be able to load Reloaded without the console appearing 

### ISSUE THREAD

**Issue by SakifX9** [Reloaded-Project/Reloaded-II#147]
Reloaded causes my game to switch back and forth windows while using the Steam In-Home Streaming feature because it is switching back and forth the game window and the reloaded console window 
I have loaded Reloaded via Special K and Ultimate ASI Loader and have come to the conclusion that it is the console window interfering.

**Comment by Sewer56** [comment]
You can toggle the console under the Settings drop-down in the settings page of the launcher.

**Comment by SakifX9** [comment]
Thanks for the quick response, this is my first time using this program so I overlooked that button. 

> You can toggle the console under the Settings drop-down in the settings page (where it opens) of the launcher.
