### ISSUE TITLE
Bug: Reloaded-II.exe fails to run on Linux when the DOTNET_ROOT environment variable is set

### ISSUE THREAD

**Issue by Drenn1** [Reloaded-Project/Reloaded-II#148]
I managed to work around this problem, and it's not really a bug in Reloaded-II so I'll just close the issue immediately. But I'm making this issue so that it can be searchable in case someone else runs into it. (And maybe a note could be added in the Linux setup guide?)

When attempting to run Reloaded II on Linux according to the instructions on the website (https://reloaded-project.github.io/Reloaded-II/LinuxSetupGuide/), it may not work correctly if the linux version of .NET Core is installed.

**To Reproduce**
- Have some version of .NET Core installed on Linux
- Have the "DOTNET_ROOT" environment variable set to something (Arch seems to do this automatically)
- Install .NET 4.8 in the wineprefix (as explained in the linux guide)
- Run "Setup.exe"
- It basically seems to work correctly, but fails when attempting to launch Reloaded II. Wine shows this error message:
```
A fatal error occurred, the required library hostfxr.dll could not be found in [Z:\usr\share\dotnet\host\fxr\7.0.0-rc.2.22472.3]
```
And then this message pops up asking you to install the .NET Desktop Runtime, even though it was just installed by Setup.exe:
![image](https://user-images.githubusercontent.com/3671681/198159722-8a3db6df-cad2-4121-9b22-3680bf534752.png)

**Solution**
Wine is being misled into trying to use the Linux version of .NET Core instead of the Windows version it just installed. So, set the DOTNET_ROOT variable to something empty, like so:
```
DOTNET_ROOT= wine Reloaded-II.exe
```

**Other Notes**
I'm using Arch Linux (btw).

Interestingly, the issue is not manifesting on Proton, only on normal wine. Maybe Valve had similar problems.

Anyway, I appreciate you going out of your way to support Linux, it took me an evening but I've got Persona 5 modding up and running!

**Comment by RVOtakuMike** [comment]
You sure you should close this? I had this issue too and found this issue by coincidence... At the very least I think it should be added to the Linux Guide.
