### ISSUE TITLE
Bug: Persona 5 Royal doesn't open

### ISSUE THREAD

**Issue by depressowo** [Reloaded-Project/Reloaded-II#149]
I've tried to let it run for over an hour but it never launches. I'm not sure what to do, is there any possible way to fix it?

https://user-images.githubusercontent.com/116830421/198346959-9b71bd01-a625-4546-9aa9-260a4a424224.mp4

**Comment by depressowo** [comment]
![image](https://user-images.githubusercontent.com/116830421/198351002-69f3b6c3-df08-44e8-8760-19fdaae3b176.png)
Update I guess, not sure what to do now

**Comment by Sewer56** [comment]
I'm not home but related message/thread on Discord server https://discord.com/channels/745936626236129352/745946574722433065/1035097255813849118

**Comment by depressowo** [comment]
The renaming worked, thank you so much :)
