### ISSUE TITLE
Error every time I open R2

### ISSUE THREAD

**Issue by xdJTyler** [Reloaded-Project/Reloaded-II#156]
![Screenshot (3)](https://user-images.githubusercontent.com/92241054/199669526-c3d67916-fc9e-4f95-96c9-7b75225c5347.png)
So I don't know what happened but I open up R2 today and I got this error I uninstalled it and tried again and got it again, and it only happens with p5r I just tried it with p4g and I didn't get the error but as soon as I install the mods I want for p5r this error show up if some one could please help because I don't know what I did.

**Comment by Sewer56** [comment]
You can ignore it for now.

**Comment by xdJTyler** [comment]
oh ok thank you
