### ISSUE TITLE
Wi-Fi disconnects when closing reloaded II after playing persona 5 royal. 

### ISSUE THREAD

**Issue by John-Corbin** [Reloaded-Project/Reloaded-II#159]
**Describe the Bug**
As the title says my Wi-Fi disconnects when closing reloaded II and I have to do a full network reset to get it working again.

**To Reproduce**
Open reloaded II
launch P5R 
close game
Wi-Fi is disconnected and requires a network reset.

**Expected Behavior**
My Wi-Fi not being disconnected.

**Screenshots**

**Additional Context**
I have to launch a game for this to happen, just opening the reloaded II launch causes no issues.

**Comment by Sewer56** [comment]
After playing a game through Reloaded or simply after playing game?

This sounds *really, really, really* weird, Reloaded's Loader doesn't make any network requests at all, only the Launcher ever talks to the internet.

**Comment by John-Corbin** [comment]
I get the issue after launching the game through Reloaded, when launching the game through steam I get no issues.

**Comment by Sewer56** [comment]
Is this constantly reproducible? 

The actual Reloaded Loader that gets loaded into the game really has no network related functionality of any kind.

Does it happen with any other program? (e.g. Add notepad to Reloaded). I have no idea how I'd even start debugging something like this.

**Comment by John-Corbin** [comment]
It has happened 5 times now, but after testing it I noticed that it has to be running for several minutes before anything happens. This issue has only happened with P5R and reloaded but I'll test it some more and get back to you. 

Do you think I might have installed reloaded incorrectly?

**Comment by Sewer56** [comment]
No, I think the issue is likely to be unrelated to either Reloaded, Steam or P5R. It's a really weird one.

**Comment by John-Corbin** [comment]
oh well, thanks for responding so quickly. 
If I figure out what's causing the issue, I'll post it in case anyone else is having the same problem.
