### ISSUE TITLE
DLANG-PRS32.dll false positive?

### ISSUE THREAD

**Issue by megatails** [Reloaded-Project/Reloaded-II#160]
DLANG-PRS32.DLL is seen as malware through malware bytes
![Screenshot_1](https://user-images.githubusercontent.com/64613374/201492997-7f708322-0648-4eda-8a7e-e41ec11fb3a8.png)

**Comment by Sewer56** [comment]
Classic, just whitelist and report as a false positive.

If they have a comment section to include with the report, link source code: https://github.com/Sewer56/dlang-prs
