### ISSUE TITLE
Help: I keep getting a error when install reloaded 2 

### ISSUE THREAD

**Issue by RealSnak3** [Reloaded-Project/Reloaded-II#162]
so i have all of the Dependencies and prerequisites installed and I reinstalled all of  them and I keep getting this error
![image](https://user-images.githubusercontent.com/109180957/202113425-674ab34c-d812-4584-a3fc-d7ee618c8977.png)

**Comment by Sewer56** [comment]
Duplicate of 
https://github.com/Reloaded-Project/Reloaded-II/issues/158#issuecomment-1304546471
