### ISSUE TITLE
Help With Setup 1.22.8

### ISSUE THREAD

**Issue by lordki304** [Reloaded-Project/Reloaded-II#164]
Tried to set Reloaded II up today and my computer keeps telling me there is a virus in it when I download Setup.exe.
![Screenshot (975)](https://user-images.githubusercontent.com/118575738/202820059-04447ed5-d1e3-422c-8872-8fffb094a794.png)

**Comment by Sewer56** [comment]
Temporarily disable AV if required. Report a false positive. 
Link this GitHub page in the notes (if provided).
