### ISSUE TITLE
Bug: Nothing happened when trying to start the game

### ISSUE THREAD

**Issue by AsrielDewitt** [Reloaded-Project/Reloaded-II#165]
**Describe the Bug**
The latest update breaks Persona 4 Golden, when attempting to launch the game with PC Mod Loader, Tiny Fixes, XP Share, and Tiny Addition

Process momentarily shows a Process Id and it disappear, nothing happened after

**To Reproduce**
Steps to reproduce the behaviour:
1. Set up Persona 4 Golden
2. Install Persona 4 Golden PC Mod Loader from the Download Mods tab
3. Go back to the game tab, and then launch application
4. *insert crickets noise*

**Expected Behaviour**
The game just launches with the mods applied

![image](https://user-images.githubusercontent.com/48144566/202832883-ba1a52be-7154-4136-bc56-6910867aad8c.png)

Note: if you asking if there's logs, there is non, As in, there's literally no files at all beside a zip called OldLogs which is empty

**Comment by Sewer56** [comment]
The creator of CEP had this too, so I tried to work with them, though they want to finish up with something else before continuing to debug this; as we couldn't get anywhere without a crash dump.

Currently as is, I'm not able to personally reproduce, despite following the exact same steps on a virtual machine.

**Comment by AsrielDewitt** [comment]
> The creator of CEP had this too, so I tried to work with them, though they want to finish up with something else before continuing to debug this; as we couldn't get anywhere without a crash dump.
> 
> Currently as is, I'm not able to personally reproduce, despite following the exact same steps on a virtual machine.

For now, the only solution is by downgrading a version before. Because that still works

**Comment by Sewer56** [comment]
By version before, which version do you specifically mean? Am curious.

**Comment by AsrielDewitt** [comment]
> By version before, which version do you specifically mean? Am curious.

Version 1.22.7, I used that version to get it working properly

**Comment by Sewer56** [comment]
The only change in 1.22.8 is changing the text displayed by a certain error message. This shouldn't make any difference especially when the loader isn't going to display that error.

Are you sure it might not be due to an external cause like an Antivirus false positive?

**Comment by AsrielDewitt** [comment]
> 

No, If it was, I would've gotten a notification or something. The odd part is that it's not logging anything..just..blank

**Comment by Sewer56** [comment]
Literally the only Loader related change in 1.22.8 
![image](https://user-images.githubusercontent.com/6697380/202842366-d438913c-b52b-4ea9-b7d1-aa8bb9529d00.png)

This is really, really strange.

**Comment by Sewer56** [comment]
Can you grab a crash dump and upload the .`dmp` file?
https://helpx.adobe.com/uk/xd/kb/how-to-generate-crash-dump-on-windows-machine.html

[weirdly the best advice on how to do this is on Adobe's site]

**Comment by AsrielDewitt** [comment]
It's...working now...what the hell?

This is after it notice me to install .net 7.0 x86

which btw, off note. Why do you guys required .net core, desktop and runtime for both 64 and 86?

**Comment by Sewer56** [comment]
x64 is required for launcher & x64 (64-bit) games.
x86 Is required for x86 (32-bit) games.

It's that simple.

**Comment by AsrielDewitt** [comment]
> x64 is required for launcher & x64 (64-bit) games. x86 Is required for x86 (32-bit) games.
> 
> It's that simple.

Ah, alright. That make sense. Well, tell the dude on CEP to try install those missing dependancy. Which, weirdly enough wasn't informed when I made the issue


Oh and uninstall the release candidate for 7.0

**Comment by angelicshadowdemon** [comment]
I'm getting an identical issue, with the system ID showing different random numbers every time I try. Only downloaded today in an attempt to get one specific mod working following the tutorial on gamebanana so I'm very new to this program. I'm not getting any notifications to install anything like AsrielDewitt.

**Comment by Sewer56** [comment]
> I'm getting an identical issue, with the system ID showing different random numbers every time I try. Only downloaded today in an attempt to get one specific mod working following the tutorial on gamebanana so I'm very new to this program. I'm not getting any notifications to install anything like AsrielDewitt.
> 
> Edit: Only other difference I can think of is I'm running a second, low-intensity steam game at the same time.

Can you elaborate? Take a screenshot of said system id, or whatever you're seeing.

**Comment by angelicshadowdemon** [comment]
The system ID only appears for a brief second, too fast for me to screenshot. There was also a notification from trend micro that it was blocking a kernel of some kind, I can't find how to whitelist it in case that was the problem. It launches through the Aemulus Package manager but doesn't respond (last place I saw the kernel notification).
![image](https://user-images.githubusercontent.com/118941763/203662911-928aeca4-af9a-4924-b523-68b6b8cb10f0.png)
This is what I'm seeing after installing the package manager.

**Comment by Sewer56** [comment]
Maybe your Antivirus blocked Kernel32AddressDumper which made Reloaded unable to perform DLL Injection to load itself.

That's what I'm guessing.

**Comment by angelicshadowdemon** [comment]
Yep, that sounds right. Any idea how to whitelist it or something? I'm not finding much on google but then again, I'm not too savvy on what exactly I should be looking for.

**Comment by Sewer56** [comment]
It varies with different AV software so you'd probably need to Google it.

**Comment by angelicshadowdemon** [comment]
Where would the kernel be located?

**Comment by Sewer56** [comment]
Check your antivirus logs, it would be in there.
It's usually found in Loader folder in Reloaded folder.

**Comment by angelicshadowdemon** [comment]
The security alert hasn't popped up again, though I have managed to 'run' the game from the launcher. I'm just getting the same result as if I use the package manager though.
![image](https://user-images.githubusercontent.com/118941763/203666034-3dc71c38-402f-4ff6-89e3-823b67732a72.png)

Launcher looks like this while it's open 
![image](https://user-images.githubusercontent.com/118941763/203666081-c772a42b-3ec7-4969-90bc-cf57648117a1.png)

**Comment by Sewer56** [comment]
Actually here's a question, can you re-enable console?
(It's in a dropdown in default/settings page of the launcher)

See if it prints anything unusual.

**Comment by angelicshadowdemon** [comment]
I'm getting this, plus a whole lot of blank space below.
![image](https://user-images.githubusercontent.com/118941763/203666724-9ea3b5ab-36fd-4f51-9198-b16ca5d8eb58.png)

**Comment by Sewer56** [comment]
Nothing unusual here, weird

**Comment by angelicshadowdemon** [comment]
I assume it likely has something to do with the kernel that I can't figure out how to properly whitelist. Would a reinstall cause it to pop up again, you think?

**Comment by Sewer56** [comment]
Well according to this log anyway, everything loaded correctly. I'll ask in Persona server for someone to come out here, maybe some mod specific incompatibility I"m not aware of (because on R2 side everything is working fine)

**Comment by AsrielDewitt** [comment]
> I assume it likely has something to do with the kernel that I can't figure out how to properly whitelist. Would a reinstall cause it to pop up again, you think?

My suggestion, try running the game through steam first

might not work, but try

**Comment by angelicshadowdemon** [comment]
Uh oh, won't run through steam either.

**Comment by angelicshadowdemon** [comment]
Any ideas on a fix? Or should I delete and reinstall the packages?
