### ISSUE TITLE
Help: Phantom Error

### ISSUE THREAD

**Issue by FlambingoSucks** [Reloaded-Project/Reloaded-II#167]
Hey, so whenever I attempt to launch Persona 5 Royal (the Steam version) via Reloaded with literally any mod installed, I get this error every single time. This only happens when a mod is enabled. Both my Reloaded and P5R are fresh. I have installed all prerequisites. I have attempted to run Persona 4 Golden with a mod enabled as well, and didn't run into this problem.

![reloaded error](https://user-images.githubusercontent.com/118870210/203463956-0f8a8c29-c892-49b7-bff6-60002ed17981.png)

**Comment by Sewer56** [comment]
Try removing the following Mod(s):

- File Emulation Framework Base Mod
- Reloaded Memory Sigscan Shared Library

(They should have names similar to this).

Chances are you have a borked download of one of these. They'll redownload when you next try to start game.

**Comment by FlambingoSucks** [comment]
I tried deleting File Emulation Framework before to no avail, but deleting both it and Sigscan fixed my problem. Thanks!
