### ISSUE TITLE
Bug: Games launch without Reloaded when using the --launch argument through programs 

### ISSUE THREAD

**Issue by AnimatedSwine37** [Reloaded-Project/Reloaded-II#169]
**Describe the Bug**
When trying to launch a game with Reloaded using the --launch "gamePath" argument through programs such as Steam (as a non steam game), and G Hub (as a macro action) the game launches normally, no Reloaded console pops up or anything.  (It works fine if run directly through a shortcut by the user though)

I've tested this with P4G and P5R using Steam and a Logitech G Hub macro although I assume this will happen with any game launched through another program.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add Reloaded as a non-Steam game in Steam
2. Set the argument to --launch "pathToSomeGame.exe"
3. Launch the non-Steam game
4. Be sad that it's just the regular game :(

**Expected Behaviour**
The Reloaded console should pop up (I have it enabled) and the game should launch with Reloaded stuff injected.

**Screenshots**
N\A

**Additional Context**
I've done some digging and found that this broke on commit 7fb61dbf2d0f9e48713e751e84da08ca8283a551 where the bootstrapper was switched to not use json. Checking out this commit the behaviour occurs although instead of the game launching without Reloaded nothing launches at all. Using the latest release the game launches without Reloaded like described so something else must have changed between then.

I also found that Reloaded is throwing an error in the [Application Injector](https://github.com/Reloaded-Project/Reloaded-II/blob/9ce3d90f8be22ece6371989cfd9a2fd126b5bdc2/source/Reloaded.Mod.Launcher.Lib/Utility/ApplicationInjector.cs#L33) as the handle being returned is 0. I don't really have the knowledge to investigate further than that but hopefully it's a good start :)

**Comment by Sewer56** [comment]
This should hopefully be remedied to some extent in the update I just pushed out, we'll see how it goes.

**Comment by AnimatedSwine37** [comment]
Yep, it's working as it should for me now. Thanks ❤️
