### ISSUE TITLE
P4G: Failed to obtain port for Reloaded Instance

### ISSUE THREAD

**Issue by Thatdudeinhoodie** [Reloaded-Project/Reloaded-II#170]
Hey all, I'm currently trying to set up P4G with the community pack, but keep encountering the same issue with Reloaded II. Whenever I launch P4G through it, the process window will appear for a few moments, but then an error stating that it 'failed to obtain port for Reloaded instance in process', and P4G never launches. I have had one instance in which it did manage to launch P4G, but my controller wasn't detected during it. I've added Reloaded II to my antivirus exceptions and haven't installed any other mods beyond the stuff in the community pack. Here's the latest log file from my attempt, as well as a screenshot of the error.

![Screenshot_105](https://user-images.githubusercontent.com/119356353/204365502-57772ee3-548e-4427-83b1-b5947db197e1.png)

[2022-11-28 19.35.26 ~ P4G.txt](https://github.com/Reloaded-Project/Reloaded-II/files/10106887/2022-11-28.19.35.26.P4G.txt)

**Comment by Sewer56** [comment]
Have you tried the guidance in the message box?
If so, try version 1.22.9 [Release.zip](https://github.com/Reloaded-Project/Reloaded-II/releases/tag/1.22.9), see how it goes .

**Comment by Thatdudeinhoodie** [comment]
> Have you tried the guidance in the message box? If so, try version 1.22.9 [Release.zip](https://github.com/Reloaded-Project/Reloaded-II/releases/tag/1.22.9), see how it goes .

I have tried everything stated in the guidance multiple times, and no dice. I'll give that older version a try though, thanks Sewer!

**Comment by Thatdudeinhoodie** [comment]
Alright, so, with the older version, it launches just fine. However, the game still cannot detect my controller. I don't use any third party input software, so not sure what's happening there.

**Comment by Sewer56** [comment]
Does newer version run when [VCRedist](https://aka.ms/vs/17/release/vc_redist.x64.exe( is installed?

**Comment by Thatdudeinhoodie** [comment]
I have that installed on my computer already seemingly, and no, newer version still didn't work last time I tried it about an hour or two ago.

**Comment by Sewer56** [comment]
There was an issue related to an unsafe optimisation I used to save 1kB from the bootstrapper DLL, it had issues with Wine, but maybe it's related if 1.22.9 works.

I'll roll out an update in the next 30 minutes, let me know how it goes post update.

**Comment by Thatdudeinhoodie** [comment]
> There was an issue related to an unsafe optimisation I used to save 1kB from the bootstrapper DLL, it had issues with Wine, but maybe it's related if 1.22.9 works.
> 
> I'll roll out an update in the next 30 minutes, let me know how it goes post update.

Yo, so, I tested out the latest version, and, it works without a hitch! Game launches just fine. Controller still isn't reading, but I figure that may be a different problem rather than with Reloaded itself.

**Comment by Sewer56** [comment]
If I were to have a guess it's probably something silly like Steam stealing the controller from other programs; I've seen that happen before. You might get some luck if you poke around and disable Controller Support from Steam.
