### ISSUE TITLE
Bug: Error in installing reloaded

### ISSUE THREAD

**Issue by Tchooi** [Reloaded-Project/Reloaded-II#171]
Unable to install Reloaded as the screenshot below shown. Any help would be appreciated
![error](https://user-images.githubusercontent.com/119443374/204605053-69c3f43e-6b6e-4a1c-a698-54437e3a3663.png)

**Comment by Sewer56** [comment]
See either https://github.com/Reloaded-Project/Reloaded-II/issues/146 or https://github.com/Reloaded-Project/Reloaded-II/issues/158
