### ISSUE TITLE
P5R: Fatal error while logging another fatal error

### ISSUE THREAD

**Issue by flow54** [Reloaded-Project/Reloaded-II#172]
Hello, I've run into an issue with the newest update of Reloaded II when trying to launch P5R. I can launch the game through Reloaded II perfectly fine but only if I disable all of my mods. If even one mod is active it will read out:

![image](https://user-images.githubusercontent.com/108194260/204657196-c2f28460-90cc-4435-9487-36ed74fa68fd.png)

I've changed nothing and never had this issue before, it simply happened when I updated Reloaded II to 1.23.7. Any help would be greatly appreciated.

**Comment by nonrelent** [comment]
Same Error, Same game.

I can enable 
* AWB Emulator for File Emulation Framework (Current Version 2.1.2) 
* CRI Filesystem V2 Hook (Current Version 2.1.2)

All other mods result in the above error.  I have attached a logfile with full debug information enabled for the two above, the two default mods, and 2 mods enabled.  No problems before the recent update; running as administrator did not resolve.

There are numerous lines of:
15:37:28] [FileAccessServer] Can't get final file name.
[15:37:28] [FileAccessServer] Can't get final file name.
[15:37:28] [FileAccessServer] Accessing: 1424, C:\Program Files (x86)\Steam\steamapps\appmanifest_1020470.acf, Route: C:\Program Files (x86)\Steam\steamapps\appmanifest_1020470.acf

[2022-11-29 22.37.28 ~ P5R.txt](https://github.com/Reloaded-Project/Reloaded-II/files/10117884/2022-11-29.22.37.28.P5R.txt)

**Comment by Sewer56** [comment]
Delete following mod

![](https://media.discordapp.net/attachments/745946574722433065/1047205549906866247/Reloaded-II_vAJFLTiYev.png)

By removing all files inside folder.
Someone (me) did an oopsie and didn't set up updates right for this thing correctly, which means that when a breaking change happened in base mod, the sub mod wasn't able to update.

Reloaded doesn't have a way of forcing mod updates on users (for security reasons), so I'm trying to think of a way to remedy this.

**Comment by flow54** [comment]
Thank you very much!

**Comment by Sewer56** [comment]
I added an error message in update to base mod (CRIFS V2 Hook) if the extension is outdated, should hopefully be sufficient in the meantime.

**Comment by nonrelent** [comment]
This resolved the issue for me as well! Thank you.
