### ISSUE TITLE
Bug: Game frequently crashes and Reloader bug info notepad  says CrashAddress": "41E373", "FaultingModulePath": "D:\SH3\sh3.exe"

### ISSUE THREAD

**Issue by Midnightszzz** [Reloaded-Project/Reloaded-II#177]
**Describe the Bug**
Every so often in  a cutscene or just randomly my game just crashes and freezes and  when i check the note pad it says 
  "CrashAddress": "41E373",
  "FaultingModulePath": "D:\\SH3\\sh3.exe"
fairly unsure what  to do to fix it and i  am using the correct application for the gmae
**To Reproduce**
Steps to reproduce the behaviour:
to reproduce the bug it seems to be random at first it was in one constant spot in the game but then i went into windowed mode and it seemed to be fine im not sure if its just a full screen issue or something else

**Expected Behaviour**
The expected behaviour is either no crashes or minimal not frequent
**Additional Context**

{
  "EnabledMods": [
    "Silent Hill 3 Audio Enhancement Pack"
  ],
  "RunningMods": [
    {
      "ModId": "reloaded.sharedlib.hooks",
      "State": "Running",
      "Version": "1.14.4"
    },
    {
      "ModId": "Reloaded.Memory.SigScan.ReloadedII",
      "State": "Running",
      "Version": "1.2.10"
    },
    {
      "ModId": "criware.filesystem.hook",
      "State": "Running",
      "Version": "1.1.10"
    },
    {
      "ModId": "reloaded.universal.fileemulationframework",
      "State": "Running",
      "Version": "2.1.2"
    },
    {
      "ModId": "reloaded.universal.fileemulationframework.afs",
      "State": "Running",
      "Version": "2.0.2"
    },
    {
      "ModId": "reloaded.universal.redirector",
      "State": "Running",
      "Version": "1.2.6"
    },
    {
      "ModId": "Silent Hill 3 Audio Enhancement Pack",
      "State": "Running",
      "Version": "2.0.9"
    }
  ],
  "CrashAddress": "41CBA8",
  "FaultingModulePath": "D:\\SH3\\sh3.exe"
}

**Comment by Sewer56** [comment]
Given crash address, probably happens in game code.
I haven't really played this game, other than writing the emulator that's used to inject audio.

Does this crash reproduce without mods enabled?

**Comment by Midnightszzz** [comment]
It appears to have fixed itself, therefore it appears to be a game error most likely ,  thanks for the help anyways tho!
