### ISSUE TITLE
Bug: Crash Happens when Updating mods

### ISSUE THREAD

**Issue by witherpiggy** [Reloaded-Project/Reloaded-II#179]
**Describe the Bug**
When clicking the update button, nothing happens and the application fully crashes a few seconds later.
![20230110_030230](https://user-images.githubusercontent.com/69535111/211453235-3c286a2d-5ccd-4c68-84ed-6e4293385e50.jpg)

This only occurs on my steam deck as well, not my windows computer.

**Comment by Sewer56** [comment]
User error on mod uploader's part.
Was fixed since.
