### ISSUE TITLE
ASI Loader not generating Version.dll

### ISSUE THREAD

**Issue by eight85** [Reloaded-Project/Reloaded-II#180]
Kubuntu 22.10, Lutris and Silent Hill 3

 Reloaded 2 is installed in a wine prefix managed by Lutris. ASI Loader is making Reloaded.Mod.Launcher.Bootstrapper.asi in the proper script folder but not generating VERSION.dll. Because of that im not able to add a DLL override in lutris. The instructions here suggest what i should expect [here](https://reloaded-project.github.io/Reloaded-II/LinuxSetupGuide/#using-asi-loader). I'm attempting to use this [mod](https://www.moddb.com/mods/silent-hill-3-audio-enhancement-pack/downloads/silent-hill-3-audio-enhancement-pack-version-206) 

**To Reproduce**
Steps to reproduce the behaviour:
1. Edit Application -> Advanced Tools & Options -> Deploy ASI Launcher
2. No VERSION.dll is available

**Expected Behaviour**
VERSION.dll should be generated to add as an override

![Screenshot_20230113_234950](https://user-images.githubusercontent.com/60632993/212458055-885f6bdf-fb38-4865-8405-81f9df6c29dc.png)

**Comment by Sewer56** [comment]
This means most likely you already have some sort of ASI Loader installed, and thus the launcher did not add an additional one to your folder. 

What the ASI Loader Deployer does is check for already existing `scripts` or `plugins` folder, and if they already have `.asi` files, it assumes that an ASI Loader is already present, and thus does not need to be installed. 

Check your game folder, if there's a DLL that's around 2MB in size, that's probably `Ultimate ASI Loader` and the DLL you're looking for.

**Comment by eight85** [comment]
> This means most likely you already have some sort of ASI Loader installed, and thus the launcher did not add an additional one to your folder.
> 
> What the ASI Loader Deployer does is check for already existing `scripts` or `plugins` folder, and if they already have `.asi` files, it assumes that an ASI Loader is already present, and thus does not need to be installed.
> 
> Check your game folder, if there's a DLL that's around 2MB in size, that's probably `Ultimate ASI Loader` and the DLL you're looking for.
I have installed the [widescreen patch](https://github.com/ThirteenAG/WidescreenFixesPack/releases/tag/sh3) and [Controller support Xinput](https://www.pcgamingwiki.com/wiki/Silent_Hill_3) beforehand. My Lutris override looks like this and do you have any recommendations to make it work?
![Screenshot_20230113_231205](https://user-images.githubusercontent.com/60632993/212458741-df04e266-3568-4647-904f-4222d2ad3283.png)
![Screenshot_20230114_001612](https://user-images.githubusercontent.com/60632993/212458780-42c42151-93c6-4c51-b6bc-10031e753da6.png)

**Comment by Sewer56** [comment]
Based on file size, d3d8.dll is probably Ultimate ASI Loader and you want to use that in your DLL overrides.
