### ISSUE TITLE
Bug: Crash when updating mods

### ISSUE THREAD

**Issue by Antaluster** [Reloaded-Project/Reloaded-II#181]
Trying to update mods through the "Mod Updates Available" Pop-up causes this crash.
![image](https://user-images.githubusercontent.com/88401704/213613450-c93b6764-3c81-4431-9a9e-be05d0f4f9ea.png)
![image](https://user-images.githubusercontent.com/88401704/213613483-2e066c52-f9b4-4cfe-9afb-cf78a9fbcb01.png)

**Comment by Sewer56** [comment]
Does this error reproduce consistently? 

For now I can at least patch it up so the error doesn't appear for you by ignoring the collision that causes it, that said, this is probably indicative of an issue elsewhere that I ought to diagnose.

If you can consistently reproduce this, would you be able to upload your 'Mods' folder?

**Comment by Antaluster** [comment]
> Does this error reproduce consistently?
> 
> For now I can at least patch it up so the error doesn't appear for you by ignoring the collision that causes it, that said, this is probably indicative of an issue elsewhere that I ought to diagnose.
> 
> If you can consistently reproduce this, would you be able to upload your 'Mods' folder?

After attempting to update the mods manually, the crash stopped appearing, and I haven't managed to recreate it since then. Seems like it may have been an issue on my end, but I'm not entirely sure. I will see if regressing my changes causes the crash to reappear, but for now it doesn't appear to be an issue any longer.

**Comment by Antaluster** [comment]
The crash is appearing again, without any input from me. Seems like the only reason it stopped appearing was because no mods needed updating. The error message is slightly different this time, though. It happens when trying to update ANY mod. Even unchecking all of the update boxes- essentially the same as not updating any of them at all- and clicking update causes the crash. The only way to get around it is to not update the mods or update them manually.
![image](https://user-images.githubusercontent.com/88401704/213843282-b9e4753b-8379-41f6-8b33-a50c37d42942.png)
![image](https://user-images.githubusercontent.com/88401704/213843295-ccedce61-5e19-4eed-852d-4f248790f607.png)
I also tried to zip up the mods folder to upload it, but got THIS error message.
![image](https://user-images.githubusercontent.com/88401704/213843421-6b474940-5897-4dec-8076-a79c501bac38.png)
Is there a better way for me to get you my mods folder? I'm unsure on how to proceed from here.

**Comment by Antaluster** [comment]
Crash reappeared, without any input on my end. Seems like the crashes only stopped because there weren't any mods in need of updates. This happens when trying to update ANY mod. Even unchecking all of the update boxes and clicking download causes this. Error message is slightly different this time, though.
![image](https://user-images.githubusercontent.com/88401704/213844869-39dfa2b7-beaa-4bbc-ada5-66778b987935.png)
![image](https://user-images.githubusercontent.com/88401704/213844907-bcc1076f-e112-40c1-ab3b-59095127bfc0.png)
I tried to compress my mods folder to upload and this error happened.
![eror](https://user-images.githubusercontent.com/88401704/213844918-e2ccee69-a5b4-4f48-8750-b18a2e1ad95b.PNG)
Is there any other way I can get my mods folder to you? Does this error help at all in figuring out the original crash?

**Comment by Sewer56** [comment]
IIRC I patched this a while back; if it still occurs let me know
