### ISSUE TITLE
Bug: Reloaded Fails to Load when attempting to launch Persona 4 Golden 

### ISSUE THREAD

**Issue by TomSully** [Reloaded-Project/Reloaded-II#182]
**Describe the Bug**
Fails to Load Reloaded-II.
Error popup says "Arithmetic operation resulted in an overflow"

**To Reproduce**
Steps to reproduce the behaviour:
1. Open 'Aemulus Package Manager'
2. Click on 'Launch Persona 4 Golden'
3. See error 

**Expected Behaviour**
The game launches without any problems.

**Screenshots**
![p4error](https://user-images.githubusercontent.com/55521574/213845705-855e9916-3efa-4924-a826-f1b54782a817.PNG)
![p4error2](https://user-images.githubusercontent.com/55521574/213845715-3415e42e-5617-4c72-89bd-7b6293958d0b.PNG)
![p4error3](https://user-images.githubusercontent.com/55521574/213845724-15c28f90-f80d-4493-b100-0493a5bf6760.PNG)

**Additional Context**
Sometimes the game launches without the mods, and other times it doesn't launch at all.

Reloaded recently updated after a few tries, and now its just not loading

**Comment by Sewer56** [comment]
Not a Reloaded issue; what happened is Persona 4 Golden was updated and replaced with a completely new port that turns the game 64-bit and also changes some file formats around, rendering existing mods useless.

If you want to downgrade, you can try Steam Console or Depot Downloader. I think the manifest for the latest 32 bit version is `7421594391039072174` so you could try e.g. `DepotDownloader.exe -app 1113000 -depot 1113001 -manifest 7421594391039072174 -filelist -username steamUsername -password steamPassword`

**Comment by TomSully** [comment]
> 

ah i see, thanks for letting me know
