### ISSUE TITLE
Bug: Stalls when launching P5R on the Steam Deck when the game language is set to Chinese

### ISSUE THREAD

**Issue by erikchan002** [Reloaded-Project/Reloaded-II#183]
**Describe the Bug**
Reloaded-II 1.23.7 stalls when launching Persona 5 Royal via Steam with ASI Loader on the Steam Deck, when the game language is set to Simplified Chinese or Traditional Chinese under game properties in Steam.
- If the console is enabled it will be stuck with just the RII logo and the versioning info, and the game will not launch. The P5R process will keep using CPU resources. If the Deck is in gaming mode the console will be the only window under the game.
- If the console is not enable the game simply will not launch, while the steam process will start using more CPU resources. If the Deck is in gaming mode the launch will be stuck and cannot be aborted. The Deck will need to be restarted.

This issue does not appear when the game is set to any other language.
This issue also does not appear on Windows when the game is set to Simplified Chinese or Traditional Chinese.

**To Reproduce**
Steps to reproduce the behaviour:
1. Setup Reloaded-II for Personal 5 Royal on the Steam Deck (I followed [this guide](https://gamebanana.com/tuts/15409) except I grabbed the .NET 7.0.3 runtimes instead)
2. Set the game language to Simplified Chinese or Traditional Chinese under game properties in Steam
3. Launch the game via Steam

**Expected Behaviour**
The game should launch, like with the other languages or on Windows

**Comment by Sewer56** [comment]
I am unable to personally reproduce this: 
![image](https://user-images.githubusercontent.com/6697380/213882892-bf1ac776-20a8-4622-b269-80cbfd6d0fd2.png)

At least on Windows.

**Comment by erikchan002** [comment]
I retried launching the game without changing anything and somehow it now works with Chinese. I'm not sure if there were any updates but I am on SteamOS stable so there shouldn't be. Originally the guide writer termdisc was also able to reproduce the issue but they don't currently have a Steam Deck to retry. Since I can no longer reproduce the issue as well, I'll just close this.
