### ISSUE TITLE
Bug: Launching P5R through Reloaded II results in stuttering and framerate drops

### ISSUE THREAD

**Issue by Jax765** [Reloaded-Project/Reloaded-II#186]
**Describe the Bug**
As described in the title, performance takes a noticeable hit when launching into the game with Reloaded II, even with all mods unchecked.

**To Reproduce**
Steps to reproduce the behaviour:
Launch the game through Reloaded II. Load up an area like Central Street and run around while also swinging the camera around. After a few seconds or so, the microstutter will become more noticeable and the framerate will drop. I play at an uncapped framerate with gsync. Vanilla fps hovers around 100-120fps with barely any stutter, with Reloaded II it drops to around 80fps with bad microstutter.

**Expected Behaviour**
Launching the game without Reloaded II doesn't result in stuttering or large fps drops.

**Additional Context**
Tested on the Steam version of the game. This issue seems to have cropped up after the recent game update. I don't recall having any such issues prior to it.

**Comment by Sewer56** [comment]
Note: This issue belongs in https://github.com/Sewer56/CriFs.V2.Hook.ReloadedII , it's specific to that mod.

I'm already working on fixing it, but for now; that would require that something else is first done before hand; it might take a week or two.

**Comment by Jax765** [comment]
Can confirm that this issue now appears to be fixed after the recent updates to reloaded II, file emulation framework, shared lib hooks and the game itself.

**Comment by Sewer56** [comment]
I did recently push a minor update to `FileEmulationFramework` that would help improve perf a bit; but the main factor limiting load time performance still remains unfixed. It requires me to complete work on Virtual File System which is still not yet complete.

**Comment by Sewer56** [comment]
This was fixed around August IIRC, with complete rewrite of CRI Hooking Code to not need rely on a VFS.
