### ISSUE TITLE
How do I fix this Arimethic Operation error? 

### ISSUE THREAD

**Issue by taxislube** [Reloaded-Project/Reloaded-II#187]
**Describe the Bug**
I’ve followed the guide on how to mod persona 4 golden on game banana that everyone refers to but everytime I try to do the steps and finish to the end where I launch the application It just does not work and I’m not sure what I did wrong . The pre requisite has been installed and re installed several times and I’ve restarted and it still does not work.

**Comment by taxislube** [comment]
![Uploading F4CE750C-1BA1-4E7A-9F56-A8F78EC273C0.jpeg…]()

**Comment by Sewer56** [comment]
You're trying to run mods for the legacy 32-bit version of Persona 4 Golden PC with the recently released 64-bit version which reworked the game internally; leading to your issue.

**Comment by taxislube** [comment]
Is there a way to fix this issue? Are there files I’m supposed to select
someplace else or something else I can refer to fix it?

**Comment by taxislube** [comment]
Is there a way to downgrade the game? I’ve never delved this deeply into modding before with Steam

**Comment by Sewer56** [comment]
You can use DepotDownloader <https://github.com/SteamRE/DepotDownloader/releases/latest> or Steam's Console to do it.

In case of DepotDownloader you could download older version using: 
`DepotDownloader.exe -app 1113000 -depot 1113001 -manifest 353219949322617300 -filelist -username YourSteamUsername -password YourSteamPassword`
