### ISSUE TITLE
Help: When opening auto-installer, I'm getting an error

### ISSUE THREAD

**Issue by Huddsto** [Reloaded-Project/Reloaded-II#190]
**Did you install the Prerequisites?**
Yes I did

**Screenshots**
Here's the screenshot of an error
![image](https://user-images.githubusercontent.com/101352910/220374842-c6e563aa-14f0-411a-b330-695c09a8a73d.png)

**Comment by Sewer56** [comment]
You can try manually downloading the current release: https://github.com/Reloaded-Project/Reloaded-II/releases/download/1.23.7/Release.zip and simply extracting it to a folder.

I cannot guarantee things would work however; since Reloaded-II runs on latest runtime and .NET 7 itself dropped support for Windows 7 after Microsoft did.

**Comment by Huddsto** [comment]
I see, thanks for help👍

**Comment by AlmightyLks** [comment]
FYI
Same issue occurs for me on Windows 10

.NET info on my system:

> PS C:\Users\Wholesome> dotnet --info
.NET SDK:
 Version:   7.0.200
 Commit:    534117727b

> Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.200\

> Host:
  Version:      7.0.3
  Architecture: x64
  Commit:       0a2bda10e8

> .NET SDKs installed:
  6.0.406 [C:\Program Files\dotnet\sdk]
  7.0.200 [C:\Program Files\dotnet\sdk]

> .NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
