### ISSUE TITLE
Request: Please Add an option to specify a working directory for games

### ISSUE THREAD

**Issue by AlmightyLks** [Reloaded-Project/Reloaded-II#191]
## Is your feature request related to a problem? Please describe.
The Game "Assault Cube" is normally ran via a .bat file. All the .bat does is run the game from a subdirectory with specific parameters.  
As Reloaded II only accepts .exe's, I chose the .exe game file directly, however due to how the game is normally executed, the working directory would've be within the parent folder, from where it loads further dependencies (assets it seems).  

![image](https://user-images.githubusercontent.com/54688434/221375262-2c5f5437-8b78-4ad0-9c6d-8656e2aeec71.png)

![image](https://user-images.githubusercontent.com/54688434/221375283-0dfca826-e753-4a6e-9ac3-778474e277d8.png)

---

## Describe the solution you'd like

Adding another textbox input for the working directory. Either set it to the file directory by default, or leave it empty  
![image](https://user-images.githubusercontent.com/54688434/221375362-4c9a0b83-ac0a-4e89-9a53-1b2191795d15.png)

Quick recap on the implementation:  
In the native function `CreateProcessW`, there is the parameter `lpCurrentDirectory` for the working directory.  

https://github.com/Reloaded-Project/Reloaded-II/blob/7a614a2cfd50a5af7c28bf700ceb59d3cd0c473a/source/Reloaded.Mod.Launcher.Lib/Utility/ApplicationLauncher.cs#L89

As of now, the file's directory is hardcoded as working directory
https://github.com/Reloaded-Project/Reloaded-II/blob/7a614a2cfd50a5af7c28bf700ceb59d3cd0c473a/source/Reloaded.Mod.Launcher.Lib/Utility/ApplicationLauncher.cs#L55

could be added quickly by throwing the field and ctor parameter in it
https://github.com/Reloaded-Project/Reloaded-II/blob/7a614a2cfd50a5af7c28bf700ceb59d3cd0c473a/source/Reloaded.Mod.Launcher.Lib/Utility/ApplicationLauncher.cs#L8-L17
and ensured via a 
```cs
// Either always set it before hand, or make it optional (nullable) and set it to the game's directory
_workingDirectory ??= Path.GetDirectoryName(_location)!;
```

**Comment by AlmightyLks** [comment]
If you're okay with the feature, I'd be willing to do the work and make a PR 😄

**Comment by Sewer56** [comment]
Proposed solution works for me 👍 

On a funny note; the original Reloaded (back in 2018) actually had this option; but it confused end users so I didn't bring it back. That said with the game details being relegated to a separate page and adding games mostly 1-click I think this is A-OK 👌

**Comment by AlmightyLks** [comment]
Can I just fork master, or do you have a preferred dev branch?

**Comment by Sewer56** [comment]
Just forking master is alright.
I usually work with master directly unless there are large features being worked on.

**Comment by AlmightyLks** [comment]
Turns out that it doesnt want me to build it

![image](https://user-images.githubusercontent.com/54688434/221390702-91773cb1-0a5e-4c00-8a56-2d679a3d2819.png)

![image](https://user-images.githubusercontent.com/54688434/221390736-eff5b7cb-00ec-4994-bb3a-8b687177b465.png)

![image](https://user-images.githubusercontent.com/54688434/221391670-c0188aba-4460-4bc2-9484-ef119de2f01c.png)

**Comment by Sewer56** [comment]
Ah the pain of building native components.
Can't really comment there, restart the IDE if you haven't already, maybe manually specify version in the drop-down.

I myself don't have enough experience debugging these things, it usually works out of the box for me with a new VS install

**Comment by AlmightyLks** [comment]
Found out that the missing v142 platform toolset was causing this issue 🤦

**Comment by AlmightyLks** [comment]
Above PR was merged
