### ISSUE TITLE
How do I fix thix?

### ISSUE THREAD

**Issue by Master999999999** [Reloaded-Project/Reloaded-II#193]
![góno](https://user-images.githubusercontent.com/120255494/222204957-251ce97d-acbd-4f23-b280-f563ac25a22f.PNG)
It happens every time i launch game. For the first time it worked after that it doesnt.

**Comment by Sewer56** [comment]
Some JSON file out there is corrupted; I'm guessing this one

![Reloaded-II_dQbvJvCK3H](https://user-images.githubusercontent.com/6697380/222206444-41992e24-c632-46b1-9161-129b2724a512.png)
![Reloaded-II_qgF04HK7J7](https://user-images.githubusercontent.com/6697380/222206454-c08e
![explorer_xOA2Lk0iYp](https://user-images.githubusercontent.com/6697380/222206460-ca72cd2c-4864-4aa1-90b1-ac6ae038f4bb.png)
5a2d-7abd-446f-9f2c-f8f88152f5ba.png)

Just delete it; see how it goes.

**Comment by Master999999999** [comment]
I completeleu uinstalled and I cant even install it again.
![gówno](https://user-images.githubusercontent.com/120255494/222208617-1b790885-b943-40d1-a54f-169ed77c90dc.PNG)

**Comment by Sewer56** [comment]
Blame GitHub; they only allow 60 requests per hour per IP.

You can grab the latest `Release.zip` from here https://github.com/Reloaded-Project/Reloaded-II/releases/latest, and extract it to some folder; should be okay.

**Comment by Sewer56** [comment]
Alternative download method was added in 1.25.7, to avoid the GitHub issue, and config issues were resolved before then. All done here.
