### ISSUE TITLE
False flag for Windows Defender when attempting to update?

### ISSUE THREAD

**Issue by Knux5577** [Reloaded-Project/Reloaded-II#194]
I haven't opened Reloaded 2 in a long time and now it is being detected as Trojan:Script/Wacatac.B!ml when I tried to update it.

![image](https://user-images.githubusercontent.com/46169123/222619548-af2a73d9-f999-4e10-b350-c338b2ca9255.png)

this is what virus total had to say about the files
https://www.virustotal.com/gui/file/9d56af5d5ea8f28a37b54a7a15e9fb1b1a0bd36025479357c1d7350f67aa2ff1/detection

**Comment by arjunagbt** [comment]
+1
Fresh install also same issue 
![image](https://user-images.githubusercontent.com/42469507/222620314-29927c53-4214-4936-bb9e-e9b75ffc1061.png)

**Comment by Knux5577** [comment]
> +1 It wouldn't let me install because it's being flagged ![image](https://user-images.githubusercontent.com/42469507/222620314-29927c53-4214-4936-bb9e-e9b75ffc1061.png)

Okay so it's not just me either.
Hopefully it's actually a false flag, because this virus it's being detected as is "SEVERE" according to windows defender

**Comment by Knux5577** [comment]
Also, I didn't include it but I also got a long string error popup from reloaded 2 itself

**Comment by Sewer56** [comment]
The only change in 1.23.8 was a community addition to allow specifying an explicit working directory for a game. I manually reviewed and pushed this change to an update.

Getting false flagged by AV software is nothing new; it's been annoying me for years :(

**Comment by arjunagbt** [comment]
not sure why but installing from 1.23.9 works for me. no warnings whatsoever

**Comment by Sewer56** [comment]
Machine learning based AVs can be funny.
