### ISSUE TITLE
Bug: P5R not being added when I select the exe

### ISSUE THREAD

**Issue by Gixinn** [Reloaded-Project/Reloaded-II#195]
When I click on "add an application" and select my P5R.exe found in ProgramFiles(x86)/steam/steamapps/common/P5R, and then click save, it doesn't add the application. After about 1-5 minutes it pops up a new window asking me to select the desired game (the only option being Persona 5 Royal) and hit OK, which I do and it still does nothing. If I try again and click the "other game" option instead in that same popup, it DOES add the program but it tells me there is a mismatched hash and only Steam is supported (which I am using) and it doesn't let me download any mods. Anyone know why this is? I'm using the latest version of Reloaded II.

**Comment by Sewer56** [comment]
You can ignore any mismatched hash messages, just means game was either updated on Steam and not in the database or you got an older version.

I'm guessing internet connectivity is somewhat possibly borked for your Proton/Wine instance of Reloaded; hence the symptoms of waiting. Just download+extract mods manually and you'll probably be okay.
