### ISSUE TITLE
Help: selecting .local on linux with protontricks

### ISSUE THREAD

**Issue by slgardiner** [Reloaded-Project/Reloaded-II#199]
On Steam deck games are stored in the .local file however when running reloaded via protontricks and trying to add a game there seems to be no way to view folders starting with dots. Navigation to /home/user is fine but then it seems to not be possible to view .local (which contains steam apps)

**Comment by slgardiner** [comment]
Ok to fix you go to protontricks, select default wineprefix, run winecfg then follow instructions on the docs, namely you go to drives and tick show dot files

**Comment by Sewer56** [comment]
I think this is actually already mentioned in the R2 wiki for Linux setup guide too.
