### ISSUE TITLE
Bug: Black Screen When Playing P5R

### ISSUE THREAD

**Issue by Futurescroll99** [Reloaded-Project/Reloaded-II#201]
When loading up P5R, having Joker's persona level up, or fusing a new persona, the game just goes black and the cade just goes crazy, listing the error (as seen below) constantly without ever fixing the issue.

The error (when booting up the game ) looks like this:
 # CRI # W2007060101:Can not open file. (err = 3, path = MODEL\CHARACTER\0001\C0001_048_01.GMD)
 # CRI # W2007060101:Can not open file. (err = 3, path = MODEL\CHARACTER\0001\C0001_048_01.GMD)

Is there anything i can do to fix it?

**Comment by Jayman340** [comment]
Run Reloaded as administrator.
