### ISSUE TITLE
Documentation: Mods is not Documented

### ISSUE THREAD

**Issue by Parallel22** [Reloaded-Project/Reloaded-II#203]
how do i make my mods?
where do i put my mods?
even if my mod is compiled with the template done is not appearing in the app.

**Comment by Sewer56** [comment]
Is the documentation on main page/wiki not sufficient?

- [Making Code Mods](https://reloaded-project.github.io/Reloaded-II/DevelopmentEnvironmentSetup/)

Projects are usually built to `Reloaded-II/Mods/<your.mod.id.here>` and should appear in launcher right after compiling.

Maybe your game/title is missing from [SupportedAppId](https://reloaded-project.github.io/Reloaded-II/ProjectSetup/#metadata-file-modconfigjson)
