### ISSUE TITLE
I cant install Reloaded 2

### ISSUE THREAD

**Issue by LilCabba** [Reloaded-Project/Reloaded-II#204]
![reloaded](https://user-images.githubusercontent.com/128668199/227108046-bc30911f-393c-4481-8c5a-ac72d7828fd9.png)

**Comment by Sewer56** [comment]
Seems you're already running Reloaded and running the installer, or aren't allowed to write files to your desktop. Have you tried a quick machine reboot?

**Comment by LilCabba** [comment]
oh my bad ,i tried rebooting and it works thanks for the reminder
