### ISSUE TITLE
Help: One of the required functions is missing. CRI FS version in this game is incompatible.

### ISSUE THREAD

**Issue by Amalgamation-Combonation** [Reloaded-Project/Reloaded-II#205]
When running Reload II it loads normally at first but then I'm met with the following message of, **"One of the required functions is missing. CRI FS version in this game is incompatible."** I don't know much about modding P4G but I followed the instructions of how to mod it precisely. Apologies if this is a simple issue to fix as stated before I have no idea about what I'm doing.

![Screenshot (48)](https://user-images.githubusercontent.com/86982017/227624117-4983a058-6364-442b-9775-68439103d81f.png)

**Comment by Sewer56** [comment]
You're using P4G 64-bit mod(s) with 32-bit game.

**Comment by Amalgamation-Combonation** [comment]
Ah my mistake then thanks for the help!
