### ISSUE TITLE
Reloaded II won't open.

### ISSUE THREAD

**Issue by OblivionWarp** [Reloaded-Project/Reloaded-II#21]
I've installed everything in the Prerequisites section on the main page, and I have tried opening it as an admin, but it doesn't work. It just doesn't open at all.

**Comment by Sewer56** [comment]
Can you run the launcher from the command prompt?
In your explorer window, click the address bar, type `cmd` and press Enter.

Then inside, type `dotnet Reloaded-II.dll`, and press Enter.
Screenshot the output.

**Comment by OblivionWarp** [comment]
![Annotation 2020-03-18 120512](https://user-images.githubusercontent.com/18045537/76915276-e32d2000-6910-11ea-8a34-9e4a89ce62a3.png)
it didnt work

**Comment by OblivionWarp** [comment]
![Annotation 2020-03-18 120512](https://user-images.githubusercontent.com/18045537/76915558-d78e2900-6911-11ea-8b80-2554f07abbf5.png)
it didnt work

**Comment by Sewer56** [comment]
`dotnet` is the standard commandline utility that ships with every version of .NET Core, it should be recognized the moment core is installed as the core install directory would be added to your PATH
.
I'd check your .NET Core installation. Maybe you only installed x86 and it didn't get registered in your PATH.

**Comment by OblivionWarp** [comment]
I installed both.

**Comment by Sewer56** [comment]
Hmm, weird.

Does `C:\Program Files\dotnet` exist?
Is it in PATH (System Environment Variable)?

Example:
![image](https://user-images.githubusercontent.com/6697380/76986302-68c4c600-6939-11ea-8777-c30c7eb9a8ab.png)
![image](https://user-images.githubusercontent.com/6697380/76986331-70846a80-6939-11ea-9bc6-e712d39acf9a.png)
![image](https://user-images.githubusercontent.com/6697380/76986453-93af1a00-6939-11ea-8d05-be9e06c75748.png)
![image](https://user-images.githubusercontent.com/6697380/76986481-9c9feb80-6939-11ea-824d-59fd4542bbcb.png)

**Comment by OblivionWarp** [comment]
Hm, it seems that it doesn’t exist. Should I try and reinstall it?

**Comment by OblivionWarp** [comment]
And no, it’s understandably not in path.

**Comment by OblivionWarp** [comment]
I somewhat fixed it.
I installed the .net sdk and that made my computer actually see it, but then when i tried putting in the command, it said something about not having "hostpolicy.dll" in one of dotnet's folders.

**Comment by OblivionWarp** [comment]
I got it to work! After a huge amount of trial and error, I found that I just needed to install the exact drivers it wanted, and I had been using the wrong ones! It works now!
