### ISSUE TITLE
I have infinite downloading of reloaded hook, how to fix it?

### ISSUE THREAD

**Issue by Sourentr** [Reloaded-Project/Reloaded-II#210]
https://user-images.githubusercontent.com/129459982/229185604-4f934c0b-40d4-47e0-a8d3-a8d4e8501370.mp4

**Comment by Sewer56** [comment]
does this persist across launcher reboot?

**Comment by Sourentr** [comment]
Yep, I tried that and it's still downloading hooks

**Comment by Sewer56** [comment]
Try pasting `r2:https://github.com/Sewer56/Reloaded.SharedLib.Hooks.ReloadedII/releases/download/1.16.0/Reloaded.Hooks.ReloadedII1.16.0.7z` in your browser address bar, might work.

**Comment by Sourentr** [comment]
Unfortunately. it did not help

**Comment by Sewer56** [comment]
Okay try the following:
- Download https://github.com/Sewer56/Reloaded.SharedLib.Hooks.ReloadedII/releases/download/1.16.0/Reloaded.Hooks.ReloadedII1.16.0.7z

- Go to `Mods` folder in Reloaded Folder
- Make a folder called `reloaded.sharedlib.hooks`
- Extract the contents there.

Should look something like this

![image](https://user-images.githubusercontent.com/6697380/229218691-0fd5b6a2-6547-41b0-9d51-5ff554cb70bd.png)

**Comment by Sourentr** [comment]
Thank you, now it works
