### ISSUE TITLE
Persona 3 stuttering

### ISSUE THREAD

**Issue by peakey94** [Reloaded-Project/Reloaded-II#214]
Hi guys,

I just installed reloaded II with a few mods on persona 3. But I get micro stuttering even without having mods on.

Is there any solution?

Thanks in advance

**Comment by Sewer56** [comment]
It's being worked on; known issue if at least 1 file is linked via the [CriFs.V2.Hook](https://github.com/Sewer56/CriFs.V2.Hook.ReloadedII) mod. 

Fixing this however requires the release of another, very complex mod and I've been working on that for a long time. just that my backlog has been so big in terms of own projects, that things on that front are progressing slowly.
