### ISSUE TITLE
Bug: Unable to configure Mod when the Mod targets Interface 2.4.0

### ISSUE THREAD

**Issue by jroweboy** [Reloaded-Project/Reloaded-II#217]
**Describe the Bug**
Now that the Interface 2.4.0 nuget package is published, I started targeting my mods against the new Interface version, but i cannot configure them from the Launcher because the latest launcher Interface.dll version is still only as v2.3.0 (despite have the code for 2.4.0 inside it)

**To Reproduce**
Steps to reproduce the behaviour:
1. Download reloaded II
2. Make a new project using the latest template that targets Reloaded.Mod.Interfaces v2.4.0
3. Attempt to configure the mod
4. Configure button is greyed out even though the mod is configurable.

**Expected Behaviour**

Unable to configure the mod (loading the application with the mods enabled still works)

**Screenshots**

Unable to Configure Mod
![Reloaded-II_68zN44J0cK](https://user-images.githubusercontent.com/952515/230986221-ce83d92a-1d81-43c2-98a0-8cc69d77e6ef.png)

ILSpy shows that the version is listed as 2.3.0 in the assembly, but it also has the new Control parameters
![ILSpy_Oo1E01H3Dn](https://user-images.githubusercontent.com/952515/230986319-e206fd88-1bf1-4c06-8aad-924de1ef2d24.png)

**Additional Context**

I think it can be fixed by just releasing a bug fix version for Reloaded, but I can understand if you wanna hold off on that too.

**Comment by Sewer56** [comment]
Forgot when, but was fixed.
