### ISSUE TITLE
Help: Please help me with trying to play sonic heroes but cant keeps saying reloaded failed 

### ISSUE THREAD

**Issue by Slayer2712** [Reloaded-Project/Reloaded-II#220]
**Did you install the Prerequisites?**
You can see them right beside the download button on each official download. 
You'll need all of them as stated.

**As seen on GitHub**:
![image](https://user-images.githubusercontent.com/6697380/90259427-e71e8900-de41-11ea-87aa-0ff27cf5e486.png)

**As seen on GameBanana**:
![image](https://user-images.githubusercontent.com/6697380/90259465-f8679580-de41-11ea-9ef9-08eb3e9c4a2e.png)

**Describe the Issue**
A clear and concise description of what you would like help with.

**Screenshots**

**Additional Resources**
If the issue is related to any external resource e.g. specific version of a mod or pack, consider stating the version or linking the resource in question. Preferably though, mod specific issues should go in their own GitHub repositories as I in most cases would not be able to help.
![Screenshot_2](https://user-images.githubusercontent.com/130836720/232209700-01af8578-8c27-4d84-bafd-ffecfaa6e50e.png)
im not sure what this means so if someone can help me that would be a great help i used to have it working a couple of years back but had to do a system reset on my pc so i forgot how i had it working again if possible please tell me what to do to fix it

**Comment by Sewer56** [comment]
Check your `Mods` folder in the `Reloaded-II` folder.
Delete `reloaded.sharedlib.hooks`; and restart the launcher.

See what happens.

If this does not succeed; try pasting `r2:https://github.com/Sewer56/Reloaded.SharedLib.Hooks.ReloadedII/releases/download/1.16.0/Reloaded.Hooks.ReloadedII1.16.0.7z` into your browser. Do the download and then start the game.

**Comment by Slayer2712** [comment]
wow that first thing you suggested i think fixed it i didn't get an error code that time so thanks a bunch now i just need to look for some mods to make the game look better and in full screen if possible but thanks for helping me with the current issue

**Comment by Sewer56** [comment]
No sweat, have fun.
You probably just had a bad download.

**Comment by Slayer2712** [comment]
hey i have another question how do i get the game to run in fullscreen and how can i play it with a ps4 controller. 
![Screenshot_5](https://user-images.githubusercontent.com/130836720/232228475-86b5a57f-2bd9-4cc6-845a-8e42a2a5cd20.png)
![Screenshot_4](https://user-images.githubusercontent.com/130836720/232228485-8827471f-5a80-42b5-ad9f-cc2dff5b144b.png)
if you can help me with this i think that will be all i need

**Comment by Sewer56** [comment]
You can change the resolution in `SH Essentials: Graphics` if you configure that mod.
There's a fullscreen toggle in there; make sure resolution matches your monitor.

As for controller, get `Custom Mapping for Controller Hook` and bind your controller via `Configure Mod`.
Combine that with `Post Process for Controller Hook` to set up deadzones.

**Comment by Slayer2712** [comment]
ok now i see a couple of them with names similar to you which 1 do i download i see a sewer56 then sewer56lol are you the same person or is someone taking your name?
![Screenshot_6](https://user-images.githubusercontent.com/130836720/232229149-2e3ef8e0-ca39-42a9-81fa-bbbd3308c424.png)

**Comment by Sewer56** [comment]
I am the same person; just have a different name on GameBanana

**Comment by Slayer2712** [comment]
ah ok now this is gonna sound like a silly question here but how do i find this out as you said make sure resolution matches your monitor i tried entering this which is what i think is right but i got this as a result 
![Screenshot_7](https://user-images.githubusercontent.com/130836720/232229684-fbab221f-04c7-4e80-9280-511352e5d30d.png)
![Screenshot_9](https://user-images.githubusercontent.com/130836720/232229690-130ff41f-d999-425a-9f15-0129910398c5.png)
![Screenshot_8](https://user-images.githubusercontent.com/130836720/232229709-f146f27e-e02c-4103-b8c1-0f04df1f7faf.png)
so yeah i did something wrong

**Comment by Sewer56** [comment]
You swapped the Height and Width fields.

**Comment by Slayer2712** [comment]
oh so i entered it backwards lol well great to know now is there a mod for in game dialogue to maybe make it like the ps2 commands?
![Screenshot_15](https://user-images.githubusercontent.com/130836720/232230440-5d471440-427b-4331-b83b-4c0558ce0072.png)
also was the camera control in game always inverted i haven't played it in ages so i forget how stuff was in this game?

**Comment by Sewer56** [comment]
Quite honestly; I don't remember. But if you need to swap the stick or trigger directions; those settings are in the `Post Process` mod.

**Comment by Slayer2712** [comment]
ah ok thanks now in what are the best mods to use that you know or think will make sonic heroes better? also does the discord presence mod work?

**Comment by Sewer56** [comment]
Should work fine. As for picks; I have no preference; go out there and look around :p

**Comment by Slayer2712** [comment]
alright well again thanks for all your help
