### ISSUE TITLE
Help: P5R does not inject mods whenever trying to start 

### ISSUE THREAD

**Issue by crunchyrollroll** [Reloaded-Project/Reloaded-II#227]
Whenever I attempt to launch P5R (or any other game that I have modded and try to launch with mods enabled) It doesn't work and says "Failed to DLL Inject into application process." please let me know if you can help.

![image](https://user-images.githubusercontent.com/132961399/236964852-bcc0f8a4-7893-4cff-abab-5bf91fcce591.png)

**Comment by markie32099** [comment]
i have the same problem with sonic heroes

**Comment by Sewer56** [comment]
Seems issue is with bootstrapper, but I have no idea what. Maybe Antivirus.

When I sent @markie32099 a completely unmodified bootstrapper (no lines of code changed), it worked on their machine. But the one from the latest release didn't work. It's very bizarre.

**Comment by Sewer56** [comment]
Was probably caused by Defender False Flagging `Kernel32AddressDumper.exe`.
(I have to report this as false positive almost every release)
