### ISSUE TITLE
Help: I'm having issues with downloading reloaded II

### ISSUE THREAD

**Issue by LAH08** [Reloaded-Project/Reloaded-II#228]
I follow the instructions but whenever I run the setup.exe it downloads and opens the app but it doesn't create a folder/app so I watched a video saw the person put there folder with setup.exe on there desktop thought that was the issue as I was doing it in the downloads folder it still didn't work and then I tried putting setup.exe directly on my desktop and it still doesn't work I don't know whats causing the issue/what I'm doing wrong

**Comment by Sewer56** [comment]
It should install to the desktop under `Reloaded-II` folder, no matter where `Setup.exe` is located.
If you can't find it there; try manually installing https://github.com/Reloaded-Project/Reloaded-II/releases/download/1.24.1/Release.zip

Extract latest release (linked above) to desktop.

**Comment by LAH08** [comment]
thank you
