### ISSUE TITLE
Reloaded II - Reloaded II does not perform explicit game profile save before launching game. 

### ISSUE THREAD

**Issue by susoheit** [Reloaded-Project/Reloaded-II#23]
reloaded ii doesn't load the mods I've enable until I close the game and launch it a second time, i.e. i'll enable a mod, launch the game, exit the game and launch it again to be able to register the changes I've made, not the biggest problem but I'd rather it didn't happen

**Comment by Sewer56** [comment]
Note: User specific bug that started occurring after some time. Will look into it once I am free.

**Comment by Sewer56** [comment]
Added explicit save just in case in c4d1518bff696beb0ca52bbccd7ac57778cc6b07
