### ISSUE TITLE
Help: I want keep getting "Reloaded config has not been found" when using asi on steam

### ISSUE THREAD

**Issue by GearToward** [Reloaded-Project/Reloaded-II#233]
### I'm using Fedora Linux 38
I'm trying to use mods for Persona 3 Portable and I managed to inject the asi in my p3p folder but when I run the game in steam, I get an error of "Reloaded Config has not been found.".

I have added WINEDLLOVERRIDES="dinput8=n,b" %command% to my launch options and I have installed the required installers from the wiki but I still to have this problem when launching the game. 

This is really all I have to say but I would appreciate if anyone could help me. I've been struggling for about 7 hours on this so I just decided to ask on the official github.

**Comment by Sewer56** [comment]
Can you screenshot the exact error? Am curious.

**Comment by GearToward** [comment]
> Can you screenshot the exact error? Am curious. (There's two errors that can fit this bill)

I'm currently trying to see how I can run steam on the terminal so i can show the error I'm having

**Comment by Sewer56** [comment]
It's okay, if you can paraphrase it word for word, that would work as an alternative.

**Comment by GearToward** [comment]
> It's okay, if you can paraphrase it word for word, that would work as an alternative.

I couldn't find a way to check out the error but I would like if there is anything to do to try out.

**Comment by Sewer56** [comment]
Okay, there's 2 errors that can fit under this banner.

1. Reloaded Bootstrapper can't find launcher config, and thus can't locate the mod loader.

This might happen if you are running Proton. Try running the Reloaded launcher in your game's wineprefix (use `protontricks` or similar.

2. Path of game doesn't match where the game itself thinks it is located in.

This one could be solved by launching launcher in your game's wineprefix (same as step 1. above), then going to `Edit Application` and setting a new path.

**Comment by GearToward** [comment]
Idk how I fixed it but i ended up switching to using protontricks for the installing deps and everything. Didnt work until i switched my compatability settings on my game. Then it started to load up along my game. Thanks for the help
