### ISSUE TITLE
Bug: Persona 5 royal stuttering in areas when used with reloaded II

### ISSUE THREAD

**Issue by Ch0i10** [Reloaded-Project/Reloaded-II#238]
title says everything.

I tried launching the game without reloaded II and it works smooth with no stutters, then when i enabled the mods again it stutters

**Comment by Ch0i10** [comment]
i also use the gamepass version of the game

**Comment by dreamsyntax** [comment]
This is a known issue until Persona virtual filesystem is complete.

**Comment by Ch0i10** [comment]
> This is a known issue until Persona virtual filesystem is complete.

is there anyway to fix it tho?

**Comment by Sewer56** [comment]
Not for a long time; a lot of code needs porting over to another programming language.
And some pre-requisites done before even that can be started.

**Comment by Sewer56** [comment]
Was fixed around August IIRC
