### ISSUE TITLE
Reloaded II won't install at all

### ISSUE THREAD

**Issue by somepersondontask** [Reloaded-Project/Reloaded-II#239]
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/80771873/f007d057-4781-4b76-ad6a-5b1ff2c0d3c6)

Attempted to run setup.exe of the latest release. It reaches 15% then displays this error message. Dunno what I'm doing wrong.

**Comment by Sewer56** [comment]
Your operating system's .NET installation might be broken.

Anyway, try extracting manually.
You might need to install some dependencies following prompts, but you should be okay.

https://github.com/Reloaded-Project/Reloaded-II/releases/download/1.24.1/Release.zip
