### ISSUE TITLE
Help: Please help me with Crashes on game load with Steam Deck

### ISSUE THREAD

**Issue by mc6415** [Reloaded-Project/Reloaded-II#240]
**Did you install the Prerequisites?**
All the Prerequisites are installed

**As seen on GitHub**:
![image](https://user-images.githubusercontent.com/6697380/90259427-e71e8900-de41-11ea-87aa-0ff27cf5e486.png)

**As seen on GameBanana**:
![image](https://user-images.githubusercontent.com/6697380/90259465-f8679580-de41-11ea-9ef9-08eb3e9c4a2e.png)

**Describe the Issue**
I've been following this guide: https://www.reddit.com/r/SteamDeck/comments/1353snk/updated_persona_4_golden_community_enhancement/ to get this up and running on the Steam Deck, one thing I encountered here was when I was installing the prerequisites I had to do so from the explorer, if I right clicked and opened them with Proton Tricks they would say they installed and then promptly say they weren't installed when opening Reloaded. 

I've followed all of the steps and got as far as setting the executable path, I've made a drive in winecfg for this so it's just D:/P4G.exe but I've also tried the path with Z:/home/deck/.local etc. 

Now when I have launched the application the command prompt shows up as expected and the game window opens up briefly, after a bit of time it just auto closes and it's as if nothing happened. Scanning through the logs I can't see any errors either so not entirely sure what's going on here

I've attached a copy of the log in case this helps at all.
[2023-07-03_23.11.50__P4G.txt](https://github.com/Reloaded-Project/Reloaded-II/files/11948723/2023-07-03_23.11.50__P4G.txt)

**Comment by PenguinSolider** [comment]
I'm having basically the same issue for p5r on my steam deck. Running p5r mods through reloaded 2 through wine. "Launch application" opens command prompt starts running perfectly fine and then opens game for not even 2 seconds before everything just closes. Followed this guide (https://gamebanana.com/tuts/15409) basically to a T twice and got the same result both times. Second time I tried having "Persona Essentials" as my only mod and it closed the game just the same. What's weird is even with the auto inject ASI Loader launch through steam, the game just launches without mods, even with the launch exception in place.
