### ISSUE TITLE
Help: Failed to Load Reloaded Hooks Shared Lib Mod

### ISSUE THREAD

**Issue by pgofay** [Reloaded-Project/Reloaded-II#243]
Hello, I reinstalled Reloaded II, with it working fine before, and now am unable to get it to load:

![image](https://github.com/Reloaded-Project/Reloaded-II/assets/117420774/1c2cae45-a6ea-4f6c-8438-5a265c4546ff)

I have attempted running and reinstalled the launcher several times, have tried installing it manually, and have the required dependencies installed.

**Comment by Sayvilay** [comment]
actually have this exact same problem right now you solved it yet?

**Comment by Sewer56** [comment]
Paste into your browser `r2:https://github.com/Sewer56/Reloaded.SharedLib.Hooks.ReloadedII/releases/download/1.16.0/Reloaded.Hooks.ReloadedII1.16.0.7z`, and you should be good.

Although the fact the dependency wasn't automatically fetched when it's mirrored across 2 sources is slightly concerning.

**Comment by Sayvilay** [comment]
can you pass some guide here I'm pretty sure I did something wrong, cause I did exactly as you say and it still not working.

**Comment by Sewer56** [comment]
Apologies, seems I forgot to reply:

When you open the link in a browser, you should get a quick download and a confirmation window that looks like this:

![Reloaded-II_00mxNNy4ae](https://github.com/Reloaded-Project/Reloaded-II/assets/6697380/c2e47647-7716-4aec-9403-c37407f226ea)

If this doesn't resolve your issue, look inside the `Mods` folder of Reloaded-II, there should be a folder called `reloaded.sharedlib.hooks` that is non-empty. If such a folder does not exist, and you cannot find `Reloaded Hooks Shared Lib` under the `Manage Mods` (gear) tab, try a manual download & extract.

You can find instructions for that under `Reloaded-II Tutorial` in the main page of the tab.

**Comment by Sayvilay** [comment]
I can't even open the main page normally the popup will always prevent me from doing anything so using Reloaded II are out of question for me.

**Comment by Sewer56** [comment]
Which main page specifically? Could you please elaborate? I might be a bit lost

**Comment by Sayvilay** [comment]
tbh I'm more lost then you right now, maybe let make it more clear so first off the mian page I prefered to is Reloaded II program itself if that's not what you meant then it's on me, second I manage to get a look at the tutorial so if I understand correctly what I have to do is download Reloaded Hooks Shared Lib using the link you gave us manualy and extract it to Mods folder in Reloaded II files right? but the problem is I have no Idea where it is the download file just disapear somehow.

**Comment by Sewer56** [comment]
Usually if you paste `r2:https://github.com/Sewer56/Reloaded.SharedLib.Hooks.ReloadedII/releases/download/1.16.0/Reloaded.Hooks.ReloadedII1.16.0.7z` you would get a dialog box to 'open with Reloaded-II' in your browser, after which it you accept it would be automatically downloaded and installed (showing the above confirmation message box).

> you would get a dialog box to 'open with Reloaded-II' in your browser
Note: I've found this to be buggy in Vivaldi web browser in the past but it should work fine in all regular browser's.

In the case that you can't use the link for whatever reason, you can try removing the `r2:` prefix, getting the link `https://github.com/Sewer56/Reloaded.SharedLib.Hooks.ReloadedII/releases/download/1.16.0/Reloaded.Hooks.ReloadedII1.16.0.7z`, which you can then install using the tutorial inside the app. (Download manually in browser and extract per shown video guide)

**Comment by Sayvilay** [comment]
Alright I got it after removed the r2 so now just extract it normally to the Reloaded-II/Mods right?

**Comment by Sewer56** [comment]
You might need to make a folder (as shown in the clip) if one doesn't already exist. But yeah, extract into a subfolder.

**Comment by Sayvilay** [comment]
anything work? or do I have to name something specific.

**Comment by Sewer56** [comment]
Any folder name works. Ideally `reloaded.sharedlib.hooks` though to match its unique identifier.

**Comment by Sewer56** [comment]
Just extract the files in there. If there's a `MosConfig.json`, you're good.

I'm really confused why it could never auto download it though.

**Comment by Sayvilay** [comment]
there is one but I try open it and the popup still keep showing up.

**Comment by Sewer56** [comment]
Is it the exact same error? Can you take a screenshot? Maybe the text changed

**Comment by Sayvilay** [comment]
The exact same one

**Comment by Sewer56** [comment]
Hmm, tries to download it anyway. Is it stuck in a download loop or something?

**Comment by Sayvilay** [comment]
yeah it take about a second every loop and I can't really do anything while it happenning.

**Comment by Sewer56** [comment]
Weird, since you downloaded it manually. Can you screenshot the `Mods` folder maybe? And inside the `Sharedlib.Hooks` folder too.

-------

Normally when this happens, I tell users to use the `r2` link but that clearly didn't work here.

**Comment by Sayvilay** [comment]
<img width="1280" alt="Screenshot 2023-08-01 221547" src="https://github.com/Reloaded-Project/Reloaded-II/assets/55591230/309c6c8d-896d-4da6-9fd8-916a2d870424">
<img width="753" alt="2023-08-01" src="https://github.com/Reloaded-Project/Reloaded-II/assets/55591230/137635db-6330-4437-8483-d972da1328e2">
<img width="753" alt="2023-08-01 (1)" src="https://github.com/Reloaded-Project/Reloaded-II/assets/55591230/e90671e4-7f39-41c3-ad23-52ef74c1b0f0">

**Comment by Sewer56** [comment]
This is weird, the files are there and yet it's still not working right? 

Hmm, try moving Reloaded outside of OneDrive, it has helped some people I'm the past.

**Comment by Sayvilay** [comment]
maybe becuase it in the desktop

**Comment by Sayvilay** [comment]
I think it's work I moved it from OneDrive and it stopped.
