### ISSUE TITLE
Documentation: How to download "one click installer" is not Documented

### ISSUE THREAD

**Issue by ceeeKay** [Reloaded-Project/Reloaded-II#247]
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/1403534/e53718e6-8c90-4e08-a277-0e85c59a8050)

This looks great on the list of features, but as far as I can tell the website gives no indication of how to get to said installer.

The "Quick Start" made no mention of downloading, it picked up starting from having installed already.

Reality appeared to be to go to github -> releases -> latest -> guess that setup.exe was what I wanted.

Obviously I can follow this process, but a giant green "Download setup.exe for latest one-click installer" button linking to https://github.com/Reloaded-Project/Reloaded-II/releases/latest could be helpful.

**Comment by Sewer56** [comment]
Would the following be sufficient?

- Hyperlink in the HTML box [pictured above].
- Hyperlink in Quick Start guide.
- Link on top of index page & project's README.MD

If you have ideas for any other places; let me know.

**Comment by ceeeKay** [comment]
Any/all of those would be great! Seems like a few spots to cover the various ways people may find it would be helpful to get them downloading.

**Comment by Sewer56** [comment]
Took a while, but it is done.
