### ISSUE TITLE
Newest update is blocked by Norton Security

### ISSUE THREAD

**Issue by Gillenwage** [Reloaded-Project/Reloaded-II#248]
I tried installing the newest update, but it was blocked by Norton's data protector, and after installing it, it completely deleted Reloaded II along with all the mods I had installed and gives me an error when I try and reinstall it, please try and fix this ASAP, I had over 600 hours in one of my modded game.

**Comment by Sewer56** [comment]
There's nothing I can do about a third party security product.

Best you can do is submit a false positive from within the user interface of your antivirus software.

**Comment by Gillenwage** [comment]
There's clearly an issue, since it worked fine for the last two months, plus why am I getting this error when I try and reinstall it?\
![Error](https://github.com/Reloaded-Project/Reloaded-II/assets/142771689/5ca0328d-c01c-4637-a77e-95cf08e5c80c)

**Comment by Sewer56** [comment]
GitHub limits users to 60 requests/hour per IP address.
Chances are that was used up checking for updates.

You can manually download [Release.zip](https://github.com/Reloaded-Project/Reloaded-II/releases/download/1.24.3/Release.zip) and extract it to a folder of your choice if required.

Usually security products don't fully remove stuff outright, so there's also possibility your old stuff is in quarantine in your AV software.

**Comment by jgalamba** [comment]
Windows Defender is also flagging the latest release.  It says it's a Trojan and offers no option not to remove the files.

**Comment by Sewer56** [comment]
There's no difference between 1.24.3 and 1.25, just an upgrade from .NET 7 to .NET 8.

This stuff is hard to deal with :(

Just report a false positive
