### ISSUE TITLE
Help: Output upon Publishing creates ".json.br" file.

### ISSUE THREAD

**Issue by fivetail** [Reloaded-Project/Reloaded-II#250]
Thanks for the awesome tool.

Exported files upon Publishing from within Reloaded II contain a (working) .7z file and a `.json.br` file.

![Capture](https://github.com/Reloaded-Project/Reloaded-II/assets/9046677/f0f7deab-574c-460d-b309-669172d5b6f7)

Following the Tutorial instructions, I've tried to upload this to GameBanana to enable update support, but it doesn't recognize the file and won't take it. Editing the file extension to remove the `.br` portion creates a JSON full of gibberish.

Please let me know if this is on my end and I've done something wrong, I'm quite new to this. Thank you in advance!

**Comment by Sewer56** [comment]
When publishing, change the Publish target from `Default` to `Gamebanana`.

Should do the trick.

GB has some additional caveats like limits on allowed characters in Filenames and only supporting certain file types/extensions, so a special set of rules needs to be applied specifically for it.

**Comment by fivetail** [comment]
Ah, I missed that option at the top. Worked like a charm! Thank you for the help.
