### ISSUE TITLE
Bug: Persona 5 Royal on Steam Deck not launching with mods.

### ISSUE THREAD

**Issue by bluzrok46** [Reloaded-Project/Reloaded-II#251]
When I have the mods linked up (that is with the DLL override launch options), the game just refuses to load past the first loading screen (right before the disclaimers). I tried launching it in desktop mode, same issue. Game won't launch when I launch it via Reloaded II either. I dunno if its because my version is outdated or what. I can't even update to the latest release; every time I try to update via Reloaded II's prompt, it just closes after it's done downloading.

**Comment by Sewer56** [comment]
Ask in Persona Modding https://discord.gg/naoto , this kind of scenario is pretty new to me.
