### ISSUE TITLE
I am having trouble downloading Reloaded, as my computer detects it as a trojan and is not allowing it to be installed. 

### ISSUE THREAD

**Issue by PhantomWillow** [Reloaded-Project/Reloaded-II#255]
Every time I've tried to download Reloaded, it detects it as a virus, and forbids installation. 

![Screenshot 2023-09-17 020623](https://github.com/Reloaded-Project/Reloaded-II/assets/145256474/81481e55-2f1f-4287-9a1b-82d29c88628f)

![Screenshot 2023-09-17 020719](https://github.com/Reloaded-Project/Reloaded-II/assets/145256474/e99f2531-b900-4200-ad84-e86f0a8862a9)

No matter what I try, I run into this same issue. As of the time I am writing this, I have found no one else with this issue, leaving me stuck.

**Comment by Sewer56** [comment]
It just is what it is.

Report a false positive in your antivirus software and go on with your day; it's unfortunate, but this tends to happen after updates, until the AV vendors' whitelists are updated.

If you have issues getting past the initial install, add a temporary exclusion for your `Desktop` folder in your Antivirus. Reloaded installs to `Desktop/Reloaded-II`.
