### ISSUE TITLE
I have two issues.

### ISSUE THREAD

**Issue by Al-AmeenAdewunmi** [Reloaded-Project/Reloaded-II#256]
**Did you install the Prerequisites?**
Yes.

**Describe the Issue**
1. It keeps telling me to install .NET when I've already done it, although that's probably a known issue.
2. Sonic Heroes won't launch with mods for some reason, even though it can launch without them. There's no window pop-up like there's supposed to be either, so I don't know what's going on. Does it have something to do with my mod list?

**Screenshots**
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/53586162/e2bf9088-11a4-4a7b-8168-9724c7543c1b)
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/53586162/19fe279d-e7b2-4331-9daf-b3c35ffa5fea)
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/53586162/0dfdb482-fb01-4c7c-9e79-104dd169f167)

**Comment by Sewer56** [comment]
Grab the .NET x86 Runtime manually:

- <https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-8.0.0-rc.1-windows-x86-installer>

The Microsoft Servers haven't updated their latest reported version over at <https://dotnetcli.azureedge.net/dotnet/WindowsDesktop/8.0/latest.version> , this is the price of bleeding edge, I suppose :p

**Comment by Al-AmeenAdewunmi** [comment]
Wow, that was.....literally all it took. Whoops.

**Comment by Sewer56** [comment]
Yeah, it's not your fault. It's just something outside of my control
