### ISSUE TITLE
Persona 3 portable (steam) mods not loading 

### ISSUE THREAD

**Issue by sillybillygirl** [Reloaded-Project/Reloaded-II#257]
I cannot get persona 3 portable to load any mods even if i just turn on persona essentials and am constantly running into the same 3 error messages as shown in the picture
I went through the prerequisite installer and did all that and find myself genuinely unsure of how to resolve this issue 
<img width="774" alt="Screenshot 2023-09-17 181802" src="https://github.com/Reloaded-Project/Reloaded-II/assets/145302734/71248164-419f-4ada-b917-b032e2e94b85">

**Comment by Sewer56** [comment]
Try extracting the latest Reloaded release over your existing install, replacing the files:

https://github.com/Reloaded-Project/Reloaded-II/releases/download/1.25.0/Release.zip

This works for some people to resolve it. I have no idea why; sometimes it's antivirus interference with the installer/during installation, but sometimes no AV logs are produced and this seemingly just happens.
