### ISSUE TITLE
Failure to install on Windows 7 [Unsupported OS by Runtime]

### ISSUE THREAD

**Issue by HyperGui** [Reloaded-Project/Reloaded-II#259]
Hi, I tried both installing it through the Setup.exe and manually with Release.zip. In both cases, I get an errror and can't open the application.

I already reinstalled the prerequisites and even got as far as reinstalling every .NET runtime I was able since 1.1.

I'm getting the following errors:

Release.zip:
![Release Error](https://github.com/Reloaded-Project/Reloaded-II/assets/147348501/490179ae-211c-40f0-a96e-4d907724692d)

Setup.exe:
![Setup Error](https://github.com/Reloaded-Project/Reloaded-II/assets/147348501/fb74a32d-574c-4517-acc2-94b39b173bc6)

I'm currently using Windows 7 x86

Thanks in advance.

**Comment by Sewer56** [comment]
Based on the error message, it's dying somewhere in the code that initializes the JPEG XL codec used for downloading packs.

In any case, Windows 7 is out of support for 3 years now, and .NET stopped supporting it with .NET 7. The fact it still boots at all, is kind of a miracle in its own way.

You might have some luck with the last version https://github.com/Reloaded-Project/Reloaded-II/releases/download/1.24.3/Release.zip , but I myself don't intend on doing anything as supporting Win7 is out of my control. The literal .NET runtime already dropped support for it 2 years ago, so there's not really much I can do about it.
