### ISSUE TITLE
Reloaded II - Unify Project Templates

### ISSUE THREAD

**Issue by Sewer56** [Reloaded-Project/Reloaded-II#26]
Specifically:
- Add Powershell scripts for releasing mod. (Build and package ZIP)
- Add Powershell scripts for building NuGet package.
- Enable R2R Support
- Include Commonly Used Libraries
- Update from netstandard2.1 to netcoreapp3.0

**Comment by Sewer56** [comment]
Implemented as of 37196cf2153265a21a981f3dce088b05a3bfcf47

**Comment by GamerBoy563** [comment]
![image](https://github.com/user-attachments/assets/75493d66-692c-48b5-b0e2-f72262d15242)
i got this

**Comment by Sewer56** [comment]
> ![image](https://private-user-images.githubusercontent.com/50081336/354828425-75493d66-692c-48b5-b0e2-f72262d15242.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3MDMxMDIsIm5iZiI6MTcyMjcwMjgwMiwicGF0aCI6Ii81MDA4MTMzNi8zNTQ4Mjg0MjUtNzU0OTNkNjYtNjkyYy00OGI1LWIwZTItZjcyMjYyZDE1MjQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDE2MzMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhYTNiYTMyZmRlODExZTljMDI1MzlkNzBjNGM5YTQ4ZGMzMzFmMDJmMDE0MWVhYjgwNzgwOWJmYWY5Mzk5NjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WCYo9huOn7LMusMx7IiaNl993fZPJLw5gqBwhMMEkqc) i got this

Paste this into your browser `r2:https://gamebanana.com/mmdl/1018363`.
