### ISSUE TITLE
When started, Reloaded II shared lib is infinitely downloading

### ISSUE THREAD

**Issue by NeonGooRoo** [Reloaded-Project/Reloaded-II#260]
When I open the Modloader I have a window appearing and disappearing every second and the only way to stop it is to turn off the internet.

App is unusable because this thing appears and interrupts any activity.
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/123720895/9375e1a8-214e-486c-bd42-4fdd752dd498)

**Comment by NeonGooRoo** [comment]
Ok, I downloaded this file manually, then some other ones, but now it wants to download these 4 things and I don't know where to find them. Please help. Why doesn't the download just work?
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/123720895/b4e4ee97-e8fb-4340-afca-f4a0b4fe46db)

**Comment by Sewer56** [comment]
Do you maybe have your Reloaded folder inside OneDrive? I know that had caused some issues for people in the past.

**Comment by Sewer56** [comment]
Closing while keeping:
- https://github.com/Reloaded-Project/Reloaded-II/issues/226

Open
