### ISSUE TITLE
Bug: <Linux P5R: Unable to initialize steam api>

### ISSUE THREAD

**Issue by gabdfreitas** [Reloaded-Project/Reloaded-II#261]
Running EndeavourOS
Trying to launch P5R through reloaded ii gives me this error:
![Screenshot_20231015_205858](https://github.com/Reloaded-Project/Reloaded-II/assets/82598113/1d17296a-167b-47df-8eb9-38c335eaac80)
Setup everything throught the official linux guide, deployed asi loader, added "WINEDLLOVERRIDES="version=n,b" %command%" to launch args.

**Comment by Sewer56** [comment]
Did you launch from Steam directly after installing ASI Loader?

[Note: I can't currently replicate as I am away from home, with no Linux machine at hand]

**Comment by gabdfreitas** [comment]
ooh, i was launching from reloaded ii itself, i tried deploying again and launching it through steam now and mods dont work

**Comment by Sewer56** [comment]
You mentioned adding `"WINEDLLOVERRIDES="version=n,b" %command%"`.

Can you doublecheck the filename used by the deployed ASI Loader? Normally it tells you after deployment.

Your current command ensures `version.dll` is loaded from game folder, but you might want to use something like `dinput8=n,b` instead.

**Comment by gabdfreitas** [comment]
using "dinput8=n,b" gave me this error instead: 
![Screenshot_20231016_193550](https://github.com/Reloaded-Project/Reloaded-II/assets/82598113/d7d6f586-28a8-49d7-9e87-56d885baaf81)
the filename tho, it gave me this:
![Screenshot_20231016_193504](https://github.com/Reloaded-Project/Reloaded-II/assets/82598113/8c885f27-2a99-43e7-986e-8ab1e58db6da)

**Comment by Sewer56** [comment]
The situation for this kinda sucks, and it will probably continue to suck until I can get a native Linux launcher going (it will take a while, but I am planning and going for it). In any case, [see the docs for this](https://reloaded-project.github.io/Reloaded-II/LinuxSetupGuide/#proton), you need to set up a symlink when running from Proton. Yeah, it's a bit tedious for now :(

**Comment by gabdfreitas** [comment]
Its alright tho, thank you for the support! ill try setting up the symlink again, it was giving me some errors before.
