### ISSUE TITLE
I can't install reloaded

### ISSUE THREAD

**Issue by YuIzanagi** [Reloaded-Project/Reloaded-II#265]
**Describe the Issue**
I am struggling to redownload reloaded again after I couldn't launch the app again so I tried downloading it and It gives me this.

**Screenshots**
![Screenshot 2023-11-12 160714](https://github.com/Reloaded-Project/Reloaded-II/assets/150630450/ea2ba757-0711-4db4-8574-e4b45f950ced)

**Additional Resources**
If the issue is related to any external resource e.g. specific version of a mod or pack, consider stating the version or linking the resource in question. Preferably though, mod-specific issues should go in their own GitHub repositories as I in most cases would not be able to help.

**Comment by Sewer56** [comment]
GitHub limits itself to 60 requests per hour for guests, and your household/place probably exceeded it.

You can install manually by downloading the current [release.zip](https://github.com/Reloaded-Project/Reloaded-II/releases/download/1.25.1/Release.zip) and extracting it to a folder. In your case, try extracting it over the old install.

**Comment by YuIzanagi** [comment]
Thank you this solved it
