### ISSUE TITLE
P5R not launching at all

### ISSUE THREAD

**Issue by jumpydolly** [Reloaded-Project/Reloaded-II#267]
So I downloaded P5R and Reloaded II, followed a guide on gamebanana since I’m using my steam deck! Everything works as planned until I try to open p5r on steam and it launches, opens reloaded ii on the side, and then it doesn’t launch at all. Nothing happens. Taking out a file of my mods folder called, I believe, reloadedii.memory.sigscan (I have to check again but I hope this is enough) opens up the game but the mods are nowhere to be found. Putting it back in the folder warrants the same issue, that it doesn’t launch at all. If it helps I’m on my steam deck, and I deployed the asi loader so I can launch it properly. I hope this is enough info, I usually try to fix things myself but I am lost!

**Comment by Sewer56** [comment]
Ask in [Persona Modding](https://discord.gg/naoto), and ping me when you get there.

There's a bunch of Deck users in there; Deck apparently has some specific minor differences from a regular Linux setup. I've never owned a Deck so I can't confirm/deny.

In any case, when you get there, can you grab a log of your last run? You should be able to find it in `~/.local/share/Steam/steamapps/compatdata/601219/pfx/drive_c/users/steamuser/Application Data/Reloaded-Mod-Loader-II/Logs`. 

If you have your Steam game installed in another storage location, replace `~/.local/share/Steam/steamapps` with path to your `steamapps` folder.
