### ISSUE TITLE
Bug: HELP ME

### ISSUE THREAD

**Issue by JermiahJ8901** [Reloaded-Project/Reloaded-II#268]
![IMG_20231203_153331953_HDR](https://github.com/Reloaded-Project/Reloaded-II/assets/152817612/418d20ab-4b38-41c2-ad68-2fa91780356a)
**Describe the Bug**
Trying to start the application for sonic heroes but this happens I tried all of the injection methods and still didn't work 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Reloaded 2
2. Click on The sonic heroes icon
3. Scroll down to Launch Application

**Expected Behaviour**
To start the application of sonic heroes and for it to start loading my mods.

**Screenshots**
![IMG_20231203_153331953_HDR](https://github.com/Reloaded-Project/Reloaded-II/assets/152817612/d4668f51-d0b9-4f04-a0ed-1158bde9bcf0)

**Additional Context**
I tried the other injection methods and it still didn't work I just wanna have fun.

**Comment by JermiahJ8901** [comment]
Its saying error in installing reloaded

**Comment by Sewer56** [comment]
Extract the files over the existing version installed to your desktop

**Comment by JermiahJ8901** [comment]
OK next

**Comment by Sewer56** [comment]
Merge them

**Comment by JermiahJ8901** [comment]
Merge what

**Comment by JermiahJ8901** [comment]
I'm seriously about to cry this is not working and I just wanna play my favorite sonic game but to mod it

**Comment by Sewer56** [comment]
Worst case scenario, hit `Deploy ASI Loader` under `Edit Application` and launch via TSonic_win.exe after configuring mods as needed

**Comment by Sewer56** [comment]
Probably means DLL required by bootstrapper is missing.

Try installing [Visual C++ Redist (x86)](https://aka.ms/vs/17/release/vc_redist.x86.exe). Maybe it was installed on your machine, then uninstalled in a non-clean way, and the Reloaded installer thought it was already installed, thus it did not install it again.

**Comment by Sewer56** [comment]
Game is 32-bit, do you need the 32-bit components.

**Comment by JermiahJ8901** [comment]
Thank you
