### ISSUE TITLE
Request: Please Add A Prompt When Deleting Something

### ISSUE THREAD

**Issue by LuigiIsCanonicallyTheAntiChrist** [Reloaded-Project/Reloaded-II#269]
I was working on a mod and was just about done but accidentally clicked "Delete" instead of "Edit" in the Manage Mods section and it deleted the whole thing, not even to the recycling bin, just completely gone. Please add an "Are you sure you want to delete this?" prompt or something because i don't want others to potentially lose hours of work from a misclick.

**Comment by Sewer56** [comment]
I'll make sure to add that into R3
