### ISSUE TITLE
I downloaded and installed .NET 8.00, and I still get the "You don't have this" pop up.

### ISSUE THREAD

**Issue by ChrisFratz** [Reloaded-Project/Reloaded-II#270]
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/28227666/9834440f-0100-42b6-b6df-6ade1cc1ef29)
IDK what I'm doing wrong. I try to Launch Nights into Dreams, and I get this.
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/28227666/59470823-d8e5-4022-8c30-fe76006d8c0c)

**Comment by Sewer56** [comment]
Are you stuck in a loop where even if you install the missing runtime, you get the prompt?

**Comment by christhefox** [comment]
Yes. Even though it's installed, and I even rebooted my PC, I still get the prompt.

**Comment by Sewer56** [comment]
That's kinda weird. Can you try running any other 32-bit program? I'm curious if it's game specific or not. The runtime detection is failing in any case.

**Comment by christhefox** [comment]
I don't know if I have anything else that uses .NET 8... Hmm...

**Comment by Sewer56** [comment]
Well, I was thinking of adding a 32-bit game to Reloaded, see what happens if you try launching that

**Comment by christhefox** [comment]
So I tried adding in Halo Custom Edition, and nothing happened. No error, and it didn't launch the game. I was hitting the launch button in Reloaded

**Comment by Sewer56** [comment]
I'd check your Antivirus logs, add an exclusion and extract a [fresh copy of Reloaded](https://github.com/Reloaded-Project/Reloaded-II/releases/download/1.25.1/Release.zip) over your existing one, see what happens

**Comment by christhefox** [comment]
It only caught the release zip, and I allowed it. It's not yelling at me about reloaded itself. And I'm still getting the same issue.

**Comment by Sewer56** [comment]
Curious: What are the contents of `Program Files (x86)/dotnet/shared/Microsoft.WindowsDesktop.App/` ?

**Comment by christhefox** [comment]
I ran the installer, and now it put the 8.00 folder in here. WTF?
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/28227666/91e73f7b-1cc0-4f2f-9c70-3fc78cb6ebec)

**Comment by christhefox** [comment]
And it's STILL telling me to get this
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/28227666/8bfd9f9e-bdc0-4729-9364-777ccac6e54d)

**Comment by christhefox** [comment]
I OGT IT TO WORK I launched Reloaded32 and it works.

**Comment by Sewer56** [comment]
> I ran the installer, and now it put the 8.00 folder in here. WTF? ![image](https://private-user-images.githubusercontent.com/28227666/288951787-91e73f7b-1cc0-4f2f-9c70-3fc78cb6ebec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMDYwOTksIm5iZiI6MTcwMjAwNTc5OSwicGF0aCI6Ii8yODIyNzY2Ni8yODg5NTE3ODctOTFlNzNmN2ItMWNjMC00ZjJmLTljNzAtM2ZjNzhjYjZlYmVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDAzMjMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0Y2I0ZDk0OGU3ZmI1MzI5YTFjMmU5ZDZiMDVmNGYwNjgwYjViZDNmOGI0M2NmMzdkNjUxZDY1NzhhMTY2ZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ov21DTL6tV6-oly5S60zvzoMVbsZFq_1n0_Q3XHS8nA)

I can only guess the installer wasn't working before, somehow.
Also note there are x86 and x64 runtimes.

For Reloaded32 and 32-bit games you only need x86 runtime.
For 64-bit games, you need the other one.
