### ISSUE TITLE
Trojan:Win32 /Znyomn

### ISSUE THREAD

**Issue by Luna24009** [Reloaded-Project/Reloaded-II#271]
Sorry to bother you with this, like the title said this Trojan is in the Mod loader. Is it safe to install the mod loader ? Really Scared of Trojan and Viruses so i just wanna be on the safe side ! 
Is the Trojan a way to inject the files in the game ? 
Ty in advance for your time and answer !

**Comment by Sewer56** [comment]
It's pretty standard for mod loaders to be falsely detected by Antivirus Software due to their nature of injecting arbitrary code into games. I won't worry about it, just report a false positive.

**Comment by Luna24009** [comment]
Ty some much for the fast reply ! <3 Then im gonna install it ! :D Was just scared as i saw an File which was called Trojan ! xD Better safe than Sorry ! <3
