### ISSUE TITLE
Release.zip is flagged as Trojan

### ISSUE THREAD

**Issue by princevael** [Reloaded-Project/Reloaded-II#272]
**Describe the Bug**

I know it is most likely a false flag, but windows security keeps flagging Release.zip every time I try to open it.

**To Reproduce**

1. Downloaded Release.zip directly from official GitHub page
2. Tried to Unzip Release.zip
3. Microsoft Defender flags it as a “Severe Trojan”
4. Tried Reinstalling and it has the same issue

**Expected Behaviour**
Again, I know this most likely a false flag since it has happened before with Reloaded. Just wanted to confirm it was a false flag and wondering if there is a way to do a false flag report. 

Thanks :)

**Comment by Sewer56** [comment]
Yeah, it's a recent false flag. Not much you can really do other than reporting a false positive, it happens :(

I'm surprised I managed to go longer than half a year without a false positive, it used to be constant.
