### ISSUE TITLE
Windows Defender detects Trojan Win32/Znyonm in latest version

### ISSUE THREAD

**Issue by PlanetaRob** [Reloaded-Project/Reloaded-II#273]
A while ago I was trying to download the latest version and it was automatically deleted when downloading it.
When checking Windows Defender it indicated that there was a Trojan in the file called Znyonm.
Is this a false positive? Is it really safe?

**Comment by Sewer56** [comment]
https://github.com/Reloaded-Project/Reloaded-II/issues/272

https://github.com/Reloaded-Project/Reloaded-II/issues/271

Happens around once a year, nothing I can do about it. Report as false positive and go about your day.
