### ISSUE TITLE
Help: Can't Download due to Windows Defender

### ISSUE THREAD

**Issue by cyndaquilishere** [Reloaded-Project/Reloaded-II#274]
Hello, I don't know if someone else has reported this, but Windows Defender keeps flagging Release.zip.
It appears as if it has a trojan called "znyonm".
Now, I don't know if it's just Windows Defender being weird or if anything has gone wrong, but i'm trying to be careful, since I accidentally got viruses earlier this year and had a hard time removing them.

**Comment by Sewer56** [comment]
https://github.com/Reloaded-Project/Reloaded-II/issues/273
https://github.com/Reloaded-Project/Reloaded-II/issues/272
https://github.com/Reloaded-Project/Reloaded-II/issues/271

Happens around once a year, nothing I can do about it. Whitelist it, report it as a false positive on the Microsoft website and go about your day.
