### ISSUE TITLE
Bug: .NET Core 8.0.0 x86 requirement download link in 64-bit launcher leads to x64 version

### ISSUE THREAD

**Issue by MadmanEpic** [Reloaded-Project/Reloaded-II#275]
**Describe the Bug**
The download link to the x86 version of the .NET Core dependency in the dependency warning popup in the 64-bit version of the loader interface incorrectly leads to the x64 version of .NET Core (which can be easy to miss and very confusing if you aren't paying attention).

**To Reproduce**
1. Launch Reloaded-II.exe without the x86 version of .NET Core 8.0.0 installed.
2. Click the download link.

**Screenshots**
![NVIDIA_Share_2023-12-28_10-35-05](https://github.com/Reloaded-Project/Reloaded-II/assets/51183135/2f4ae393-01d1-49a2-bdba-47d254b9b669)

**Comment by Sewer56** [comment]
Ah, the pain.

**Comment by Sewer56** [comment]
Was a 3rd party issue, been since fixed.
