### ISSUE TITLE
Help: Cannot use the setup tool, and I cannot extract Release.zip

### ISSUE THREAD

**Issue by BeastMode4TM** [Reloaded-Project/Reloaded-II#276]
Hello! For some reason, Windows will *not* let me open the Release.zip file, and when I run Setup.exe, it stops at around 15%, and I get this error (first image). Is there any way to resolve this? Thanks! 

(Second image is the error I get with winrar, but Windows itself also says the same thing when I double click the zip file)
 
<img width="301" alt="Screenshot 2023-12-28 114820" src="https://github.com/Reloaded-Project/Reloaded-II/assets/105402464/d65a90e0-ecde-41bb-a220-abb5bd80c269">

<img width="503" alt="Screenshot 2023-12-28 115115" src="https://github.com/Reloaded-Project/Reloaded-II/assets/105402464/875ee7df-7b80-41ec-9abc-f502b0db7cd3">

**Comment by BeastMode4TM** [comment]
I also unlocked the zip file under properties because it did that automatically, but it did nothing :/

**Comment by Sewer56** [comment]
Your Antivirus blocked the Reloaded.zip

It's been getting false flagged lately, add an exclusion if you need.
