### ISSUE TITLE
Help: Reloaded will close randomly

### ISSUE THREAD

**Issue by kzzmentos** [Reloaded-Project/Reloaded-II#277]
Each time I get an hour into P3P both the game and the Reloaded application will close randomly. There will be no crash report or error each time it closes and nothing in my config folder suggests it's an issue because of my mods. I have already made sure I have installed the required prerequisites and am currently on the latest version of Reloaded.
I plan to re-install the application to see if that fixes anything but for now, I am unsure what is causing this problem.

**Comment by AnimatedSwine37** [comment]
[Localization Fixes](https://gamebanana.com/mods/438386) had a recent update (1.3.0) that fixed a bug that would cause the game to crash when loading into a dungeon, perhaps that's what you're experiencing?

If it's not happening when in dungeons (or that update doesn't fix it) then I'm not sure. You said there were no crash reports, where did you check for them? There may be one (a .dmp file) in `crashdat\bd\reports` in P3P's install folder, if there is then could you send it?  

Some more information that'd be useful:
- What OS are you using (Windows or Linux)
- What mods are you using
- When does the crash happen? Is it literally every hour or just roughly every hour, is it in some particular place during gameplay, etc

**Comment by kzzmentos** [comment]
The OS I'm using is Windows 11 Home. My system is currently up to date.
The application would close when I am in dungeon. I'm not sure if there's any other triggers causing the crash as it mostly happened after I finished a boss fight or when I'll just be running around not attacking any enemies. I've only estimate an hour through Steam's tracked playtime.

It could be Localization Fixes, but I'm unsure if I had that mod enabled during my play-through? Most of the mods I do have enabled are ones I just installed yesterday and should be on their latest versions. Here is the full list:
{
  "EnabledMods": [
    "p3ppc.cutscenesrestored.rudiger__gb",
    "p3ppc.qol.autoheal",
    "p3ppc.mudkipfixes.cleanerbustups",
    "p3ppc.configclarity",
    "p3ppc.qol.earlycompendium",
    "p3ppc.expShare",
    "p3p.aoa.kotonetweak",
    "p3ppc.guaranteedItemDrops",
    "p4gpc.inaba",
    "p3ppc.kenjifix",
    "p3ppc.junepeislinkfix",
    "p3ppc.ui.usefuldescriptions",
    "p3ppc.qol.returnheal",
    "p3ppc.visibleRankupReady",
    "p3ppc.akihikoAOA",
    "p3ppc.manualSkillInheritance",
    "p3pc.skillfusionspells",
    "p3p.events.sapphicmodclassic",
    "p3ppc.socialStatTracker"
  ]
}

Regarding the crash report, I have misspoken. I wrongly assumed it was in Reloaded's files. I've attached the most recent file below. Please let me know if you're able to access it. (still new to github ;;) I have a few other crash reports regarding this issue that I'm happy to share through a zip file if needed!
[cc937b93-057f-4c18-ae7c-8700dddce03d.dmp](https://github.com/Reloaded-Project/Reloaded-II/files/13797601/cc937b93-057f-4c18-ae7c-8700dddce03d.dmp)

I'm sorry if there were any confusions in my post, this is my first time using Reloaded. I appreciate your help! :)

**Comment by AnimatedSwine37** [comment]
Thanks for the info, based on the crash dump and you saying it's only happening in dungeons I'm fairly certain it's the same problem as what was happening with Localization Fixes.

From the list of mods you sent you I don't think any of them would be the cause, hopefully that means you did actually have localization fixes on. Could you check if your version of localization fixes is 1.3.0, the update did only come out yesterday so maybe you downloaded it just before then.

If you find that you still crash with the updated localization fixes (or with it not enabled) then I'll look into the problem further (hopefully it doesn't come to that)

**Comment by kzzmentos** [comment]
Just now did another playtest and unfortunately, the crashed again :( 
I've made sure this time that the Localization Fixes mod was not enabled this time and it is on 1.3.0. Here's the newest crash report:
[609643d5-166c-4c3e-a98d-e980722f4e04.dmp](https://github.com/Reloaded-Project/Reloaded-II/files/13797764/609643d5-166c-4c3e-a98d-e980722f4e04.dmp)
Still re-occurring in Tartarus dungeon; this time now crashes around <20 minutes into playtime. Not sure what else to do ;;

**Comment by AnimatedSwine37** [comment]
Rip, could you search for `dng_init` in your Reloaded mods folder (just using file explorer) to see if you have any mods that edit it as `dng_init.pac` is the file that I believe causes the crashes.

If there aren't any that edit it then you could try turning mods off one (or a few) at a time until the crashes stop. It'll be a bit of a pain but it's the only other idea I have currently.

**Comment by kzzmentos** [comment]
You were right! 
Looked through the files and found out that Auto Heal was causing the issues. I've disabled the mod and no more crashes occurred after.
Thank you again for helping. Your time and patience were greatly appreciated. Have a good rest of your day! :)
