### ISSUE TITLE
Beautiful, too flashy

### ISSUE THREAD

**Issue by maxxslatt** [Reloaded-Project/Reloaded-II#278]
Y'all's application looks really good. I like it a lot. But it is a mod manager, it doesn't need to all the animations. It really is making it too slow and freezy. But I love the work this community has done so thank you.

**Comment by Sewer56** [comment]
Animations are a property of the launcher theme.
If you want to remove the animations, try editing `Theme/Default/Settings.xaml`. 

Inside is a section labeled `<!-- Window: Animation -->`. 
You can set the durations to 0 in order to instantly complete the animations.
