### ISSUE TITLE
Help: Please help me with this!

### ISSUE THREAD

**Issue by Rayisi1** [Reloaded-Project/Reloaded-II#279]
![Capture](https://github.com/Reloaded-Project/Reloaded-II/assets/155607882/4cd7d0f4-8c41-4612-b896-f6b43cd948a3)
Does anyone know how I would be able to fix this issue? I would be incredibly grateful and I have tried everything I could think of to fix it (I have no experience with this sort of thing) I have tried restarting my pc and reinstalling reloaded and all of the mods. Also i should mention that the game still works fine, just that none of the mods are working

**Comment by Sewer56** [comment]
CC @AnimatedSwine37 

Probably best to check against user's input mods and debug

**Comment by Rayisi1** [comment]
i have found the issue and it was with one specific mod @Sewer56 Thank you so much for the idea!

**Comment by Sewer56** [comment]
Please do state which mod was the culprit, it might help in the future. It's unknown whether it's an already known issue, or a new issue.
