### ISSUE TITLE
the type initializer for 'Reloaded.Mod.Launcher.Utility.BasicDlllnjector threw an exception

### ISSUE THREAD

**Issue by MarioSonicBusserA** [Reloaded-Project/Reloaded-II#28]
every time i tried to launch Sonic Heroes on Reloaded II
![Screenshot_60](https://user-images.githubusercontent.com/40992017/84752183-0a80a100-af83-11ea-9427-2e3998cb6641.png)
these last 2 are from the Other Instances Inject button 
![Screenshot_61](https://user-images.githubusercontent.com/40992017/84752187-0bb1ce00-af83-11ea-99d2-d8542a4e72c8.png)
![Screenshot_62](https://user-images.githubusercontent.com/40992017/84752190-0c4a6480-af83-11ea-9c27-87353b5d8a64.png)

no idea why this is happening

**Comment by Sewer56** [comment]
I've only been getting reports of this really, really lately (past 3 days).
As far as I can tell, something broke on Microsoft's end on how it handles Memory Mapped files in the Core Runtime. 

Here's what you should do:
- Update Windows, if you think yours might be out of date.

Otherwise...
- Try downgrading from .NET Core 3.1.5 to 3.1.2.

This seems to have worked for the people so far

**Comment by Sewer56** [comment]
Experimental .NET 5 Version is also now available: 
https://twitter.com/TheSewer56/status/1273030654310178816

If the above doesn't work, feel free to try this version.

**Comment by MarioSonicBusserA** [comment]
Wow i only needed to do was install both links in the reply you put along with that tweet
![Screenshot_63](https://user-images.githubusercontent.com/40992017/84838943-6853ce00-b001-11ea-90ad-b068678858c1.png)
![Screenshot_64](https://user-images.githubusercontent.com/40992017/84838951-6be75500-b001-11ea-87f8-e1911e5dc9d0.png)
![Screenshot_65](https://user-images.githubusercontent.com/40992017/84838954-6d188200-b001-11ea-8eaa-c07f2cf37013.png)

Good job dude

**Comment by Sewer56** [comment]
Thanks, I'll probably push this version out to end users in around 3 weeks.
Main reason is that I only very recently added a changelog to the mod loader update dialog.

If people update from an older version (before the changelog was added), the loader will stop working for those people after the update as they would need to install the runtime. This would be a no-go 😢. With a changelog I can add a **BOLD MESSAGE** informing users to update the runtime before applying the loader update.

I also don't want to inconvenience the users too much as they would need to update *AGAIN* after that when Core 5 goes out of preview.
