### ISSUE TITLE
Request: Portable config location

### ISSUE THREAD

**Issue by user18081972** [Reloaded-Project/Reloaded-II#280]
**Is your feature request related to a problem? Please describe.**
When reinstalling the OS or whatever I have to fetch the reloaded folder from Roaming directory, which i would rather not. I would like to keep all the settings in the program directory.

**Describe the solution you'd like**
allow for storing the config files that are now in appdata\roaming, in the same folder as Reloaded2
This along with the relative file paths to the game executable, can make a game with Reloaded2 mods entirely portable.

**Comment by Sewer56** [comment]
Sorry that I never replied here before, I feel kinda bad about it.

R2 is in maintenance mode, so there aren't any plans for new functionality, while I work on the successor. 

That said, you don't actually need to copy your `Roaming` folder across to get portable functionality (that folder only has your logs and some preferences e.g. launcher language). The main functionality (all of your mods, mod configs, game configs) you can in fact [carry with you in a portable fashion](https://reloaded-project.github.io/Reloaded-II/ExperimentalFeatures/#portable-mode) 👈 docs link. It's not perfect, but it's already been possible to put R2 inside a game folder, use relative paths to games and carry R2 with your game.

True portability is a more difficult challenge however, for more technical reasons. I'll give it a try in the successor.
