### ISSUE TITLE
Bug: Game doesn't open for a reason I don't understand

### ISSUE THREAD

**Issue by AeonCDG** [Reloaded-Project/Reloaded-II#281]
![image_2024-01-07_220914267](https://github.com/Reloaded-Project/Reloaded-II/assets/148015618/faddb3bf-30e9-47ca-bd7d-41f4b24efe96)

I get this on launch, I have no idea what any of this means, and any attempts to try to fix it have not worked. I do not know how I did this, but it only doesn't happen if I have no mods enabled, including the "emulators" or whatever that seem to auto-install if you don't have them

The game doesn't even open if I close it, I just get a bunch of red text
[2024-01-08 05.05.52 ~ P5R.txt](https://github.com/Reloaded-Project/Reloaded-II/files/13856447/2024-01-08.05.05.52.P5R.txt)
This is the log it gave me afterwards

Please help me understand how I could possibly fix this

**Comment by Sewer56** [comment]
CC. @AnimatedSwine37 

Probably a known case. Likely caused by some specific mod combination in user mod setup.

Same as https://github.com/Reloaded-Project/Reloaded-II/issues/279 , but culprit is unknown here.

**Comment by AeonCDG** [comment]
god that's annoying, so I am probably going to have to turn on each mod individually and run it to see if it works, eh?

**Comment by AnimatedSwine37** [comment]
Yeah, disabling them until you find what's broken would be the way to go.

I really should do something so it throws a more useful error...

**Comment by AeonCDG** [comment]
Mod that broke it was "Ultimate Skills in Persona 5 Royal" I tried turning off other mods that most likely edited similar files, but it broke it anyway. So I guess it's just that that mod sucks, and it has nothing to do with reloaded.

Or at least that's all the info about this for now. The mod, however, is only 20days old so it's highly likely it just has a major compatibility problem
