### ISSUE TITLE
Help: Error in Installing Reloaded

### ISSUE THREAD

**Issue by kriemhild3ds** [Reloaded-Project/Reloaded-II#284]
Tried installing manually and ith setup.exe
Either I cant run the mods or I cant run the install

Other times it worked ith 0 issues

please help and thanks !

![image](https://github.com/Reloaded-Project/Reloaded-II/assets/58643706/edbfd4bc-e14f-4d23-842c-16b24711860a)

**Comment by Sewer56** [comment]
You got rate limited by GitHub (GitHub has a limit of 60 requests per hour per IP address). Not much I can do here.

If the situation doesn't resolve itself after an hour, you can install manually by
- Extracting [Release.zip](https://github.com/Reloaded-Project/Reloaded-II/releases/download/1.25.3/Release.zip)
- [.NET 8 x64 Runtime for Launcher & 64-bit Games](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-8.0.1-windows-x64-installer)
- [.NET 8 x86 Runtime for 32-bit Games](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-8.0.1-windows-x86-installer)

Feel free to reopen this if issues persist.

**Comment by kriemhild3ds** [comment]
still having this issue! no with any game, tried a lot of things

**Comment by Sewer56** [comment]
What do you see? The installer was updated recently and doesn't use the GitHub API anymore, so you shouldn't be able to get this error at least.
