### ISSUE TITLE
failed to acquire address of GetProcAdress x86 when trying to boot up sonic heroes

### ISSUE THREAD

**Issue by GeorgeDOC2003** [Reloaded-Project/Reloaded-II#285]
Trying to run sonic heroes, I get this error
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/105425647/c330e2b8-507d-4c6a-b921-f50e914fd118)

x86 NET code is indeed installed, this happens regardless of what mods are loaded. The application itself works fine, only when being launched through reloaded II is this an issue.

![image](https://github.com/Reloaded-Project/Reloaded-II/assets/105425647/5080c669-a15e-4c5c-8167-1c98988aa50d)

the only other instance of this issue i could find was with someone who accidentally assigned the wrong .exe, which isn't the case here.

I'm using the version of sonic heroes from myabandonware.com

**Comment by Sewer56** [comment]
Sometimes this message can show if Antivirus software (notably defender) doesn't like `Kernel32AddressDumper.ex,e` which is required for DLL Injection, to inject custom code into the game.

Extract the latest release.zip (https://github.com/Reloaded-Project/Reloaded-II/releases/download/1.25.3/Release.zip) over your existing Reloaded install and check your AV software's logs. You may need to whitelist the file/folder before extracting
