### ISSUE TITLE
Game not being injected

### ISSUE THREAD

**Issue by theovanua** [Reloaded-Project/Reloaded-II#287]
![error](https://github.com/Reloaded-Project/Reloaded-II/assets/143624519/7f915029-9335-4bfe-9ce9-12fa847e3fbf)

I'm having this issue with Granblue Fantasy Relink using the x32 version of Reloaded, the mods are not injected and the game runs as normal. Even when I dont install any mods this error still appears when trying to run the game.

 The game is installed in Program Files x86 however when I use the x64 version of Reloaded the mods are indeed injected but the game doesnt run and the command prompt closes.

**Comment by Sewer56** [comment]
CC @WistfulHopes (<= The right person to help you debug game specific issues)

In any case, that does sound right, 32-bit Reloaded can't inject into 64-bit process. Only 64-bit process can inject to 64-bit process, so this is expected.

Sounds like you're running into a game/mod specific issue. Consider posting a log.
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/6697380/e7607f4d-1465-4dc9-8722-5f1a2c757ce3)

You can find inside the folder marked with red arrow. Run the game and upload the latest log file.

**Comment by theovanua** [comment]
Thanks for the speedy response! :) Here's the log file attached

[2024-02-15 02.09.39 ~ granblue_fantasy_relink.txt](https://github.com/Reloaded-Project/Reloaded-II/files/14290549/2024-02-15.02.09.39.granblue_fantasy_relink.txt)

**Comment by Sewer56** [comment]
I won't know the cause personally, so you'd still have to wait for the mod author(s).
If it's a case of outdated game, you may be out of luck, you'll have to see.

btw, if you like the game, buy it :wink:

**Comment by Sewer56** [comment]
This was probably caused by a false Antivirus positive on `Kernel32AddressDumper.exe`.
Fairly positive about this one.
