### ISSUE TITLE
[3rd Party Mod Issue] Help:'Object reference not set to an instance of an object'

### ISSUE THREAD

**Issue by HikawaYUnn** [Reloaded-Project/Reloaded-II#290]
I was able to run normally before, but after updating some mods there was an error. I'm not sure if some mod is causing the error?
![QQ图片20240216122458](https://github.com/Reloaded-Project/Reloaded-II/assets/145822939/20f04d4e-9a6c-456f-bc52-3b06277b781f)
Here is my log:
[2024-02-16 04.34.51 ~ P5R.txt](https://github.com/Reloaded-Project/Reloaded-II/files/14307199/2024-02-16.04.34.51.P5R.txt)
I don't know what actually caused the error so I'm trying to post issue here. I'd appreciate it if someone could help me.

**Comment by Sewer56** [comment]
Seems to be mod specific. Not sure if the cause is the input (`.bf`) files in other mods or the mod itself (BF Emulator).

I'd say @AnimatedSwine37 knows a bit more (so do wait there), but chances are, you can in the meantime at least narrow it down to which mod causes it.

**Comment by AnimatedSwine37** [comment]
I'm trying to recreate this for myself but I couldn't find the `p5rpc.misc.maleromanceconftext` mod that you have anywhere. Could you send a link to it?

Using just the female protagonist mod and JP voiceover the game loaded fine for me.

**Comment by HikawaYUnn** [comment]
This is it: https://gamebanana.com/mods/482718

On the contrary, I found that it would only fail to start with the female protagonist mod turned on.
I tried reinstalling and restarting with only the female protagonist mod and the base mod on but got the same error. (But it works fine with only the base mod on)
But it was working fine before so that's weird. This seems to be an uncommon case ...... or maybe I missing some essential file?
Anyway, thanks for your time!

**Comment by Sewer56** [comment]
Is there any update on this?

**Comment by AnimatedSwine37** [comment]
Ah I forgot about this, I'm sorry. 

I did have the mod that I mentioned in the last comment from me already, I just didn't realise it because of the id.

I think I've seen issues with that female protagonist mod on Persona modding so I'll have a look to see if it's the same.

**Comment by AnimatedSwine37** [comment]
@HikawaYUnn sorry for the extremely long delay but apparently this is a problem with the unhardcoded romances mod.

Have a look at [this gb post](https://gamebanana.com/posts/11443939) for info but basically try updating that mod and if it doesn't work delete the bf files the post mentions.

Hopefully cornflakes fixes that mod eventually if it isn't already fixed.

**Comment by HikawaYUnn** [comment]
sorry for the long delay. Today the mod ran successfully after I tried to remove the bf file from the error report. I don't know how this affects the mod but that should be the cause of the problem. I'll put the bf file that should be deleted when the error occurs here, maybe who have the same problem as me can refer to it.
![RDQR5M1Z)LZWM)}4TWUONNQ](https://github.com/Reloaded-Project/Reloaded-II/assets/145822939/3949c3e1-1690-47c6-bddc-e3b3ccc7058f)
Thanks for all your hard work on Reloaded!
