### ISSUE TITLE
Help: Please help me with mods P5R

### ISSUE THREAD

**Issue by Koridian12** [Reloaded-Project/Reloaded-II#291]
So I just started to mod P5R, it works with essentials but then when I add some more mods, it starts making an infinite loop of downloading dependencies, constantly closing in and out.

**Comment by Sewer56** [comment]
Move your Reloaded folder outside of OneDrive if it's in a OneDrive folder. That might help.

**Comment by Koridian12** [comment]
> Move your Reloaded folder outside of OneDrive if it's in a OneDrive folder. That might help.

It is not in a one drive folder from what I can see, unless the desktop counts as a onedrive folder however doesnt seem to be the case as I also disabled onedrive saving

**Comment by Sewer56** [comment]
Can you tell me which dependencies it downloads on loop? I should be able to at least give you the manual download links for them. Should show in window that briefly appears.

It's very unusual behaviour, in any case.

**Comment by Koridian12** [comment]
> Can you tell me which dependencies it downloads on loop? I should be able to at least give you the manual download links for them. Should show in window that briefly appears.
> 
> It's very unusual behaviour, in any case.

So based on what I see it doesnt show any dependencies because it just opens a download tabs, closes out, opens again etc etc. But usually it happens when CRI filehook and awb emulator appear in my p5r mods list, which usually happens when I run the game with mods

**Comment by Sewer56** [comment]
Closing as 'stale', reopen this if needed.
