### ISSUE TITLE
[Strange Anomaly in SteamHook App Restart Bypass / Can't Decode an Instruction]

### ISSUE THREAD

**Issue by ChuaMarcusGitHub** [Reloaded-Project/Reloaded-II#292]
Title.

not exactly sure of the trigger.
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/102853254/ed0f6a23-9489-4017-bbdf-76fd4c85dd29)

**Comment by Sewer56** [comment]
Note: I'm not 100% sure if this is still valid since I updated the disassembler backend, and I don't have the game.

**Comment by Sewer56** [comment]
Duplicate of:
- https://github.com/Reloaded-Project/Reloaded-II/issues/308
And since fixed.
