### ISSUE TITLE
1.25.7 being flagged by Windows Defender

### ISSUE THREAD

**Issue by ralinchan** [Reloaded-Project/Reloaded-II#293]
The current release (1.25.7) in setup,exe form is instantly flagged by Windows Defender for "Trojan:Win32/Wacatac.B!ml"

The release.zip version results in Kernel32AddressDumper.dll being flagged as "Trojan:Win32/Wacatac.H!ml"

**Comment by Sewer56** [comment]
I'm aware, this tends to happen every other update (unfortunately).

I reported false positive on the same day I rolled out the update, anticipating this would be the case ahead of time. They've been submitted via the Microsoft portal yesteday https://www.microsoft.com/en-us/wdsi/filesubmission/ , hopefully they get unflagged in a timely manner.
