### ISSUE TITLE
Reloaded 2 application and Setup simply won't launch

### ISSUE THREAD

**Issue by SeTzer0o** [Reloaded-Project/Reloaded-II#295]
Tryed running both the application and the setup exe but if i try to run it nothing happens, no error or anything

Appreciate the help

**Comment by Sewer56** [comment]
Literally nothing happens?

If you manually extract Release.zip https://github.com/Reloaded-Project/Reloaded-II/releases/download/1.25.7/Release.zip , and try to run it, would you see anything?

(Should be a message asking you to install a 'runtime', if you do)

**Comment by SeTzer0o** [comment]
No nothing is happening. No message, no error.

**Comment by Sewer56** [comment]
That's actually, very very strange.

Never seen something like this before. You are running `Reloaded-II.exe`, right? (And running Win10 or newer)

----

Anyway here's an idea.

Can you provide an Event Viewer log? 

Try running the application, then...

- Open `Event Viewer`
- Go to `Windows Logs` -> `Application`
- See if you can find `Error` (red) with some message in the event that relates to `Reloaded-II.exe` or `.NET Runtime`.

**Comment by SeTzer0o** [comment]
Yes i'm clicking the Reloaded-II.exe

Event viewer doesn't say anything about Reloaded or .net runtime

**Comment by Sewer56** [comment]
Wow, that's, certainly unusual.

I'm not even sure what to do. `Reloaded-II.exe` is just a copy of `apphost.exe` from the .NET Runtime.

Here's something to try, right click while holding shift in some empty space in your Reloaded folder. Then `open with command prompt'. And type `dotnet Reloaded-II.dll`, and press Enter.

See what you get in command prompt

**Comment by SeTzer0o** [comment]
Ok with the command it opened the launcher for some reason. Ty for your quick help

**Comment by Sewer56** [comment]
The behaviour you experienced is still very strange though, normally you'd get a dialog box with an error.

But I'm glad it made things work in some capacity.
