### ISSUE TITLE
Unauthorized operation

### ISSUE THREAD

**Issue by antijeruel** [Reloaded-Project/Reloaded-II#296]
getting this error when running the app

![wa](https://github.com/Reloaded-Project/Reloaded-II/assets/160424398/1056ff16-a4d3-4d77-a3d1-54b054eae1bb)

**Comment by Sewer56** [comment]
I have no idea why but your Windows account doesn't allow you to modify the registry, even though the registry entry is account (user) specific and not machine wide.

Try running as admin, see what happens.

**Comment by antijeruel** [comment]
tried running as admin same issue

**Comment by Sewer56** [comment]
I could make a version that doesn't register a 1 click protocol, but this is pretty strange nonetheless.

Are you sure you're not being blocked by Antivirus software or something?

**Comment by antijeruel** [comment]
sorry about that. Yes it was being blocked by antivirus
