### ISSUE TITLE
Failed to DLL Inject

### ISSUE THREAD

**Issue by antijeruel** [Reloaded-Project/Reloaded-II#297]
getting this error when launching relink from Reload
![aw](https://github.com/Reloaded-Project/Reloaded-II/assets/160424398/763a7943-9914-4122-b5b4-a5f7feaa6939)

**Comment by Sewer56** [comment]
Related to your last issue.

Defender has been false flagging `Kernel32AddressDumper.exe` in recent releases.

Whitelist the R2 folder (or that file) and extract a new one in its place https://github.com/Reloaded-Project/Reloaded-II/releases/download/1.25.7/Release.zip

**Comment by antijeruel** [comment]
thank you worked now
