### ISSUE TITLE
Bug: Unable to find Unreal Engine version number (trying to launch P4G 64-bit)

### ISSUE THREAD

**Issue by AlternisDim20** [Reloaded-Project/Reloaded-II#298]
**Describe the Bug**
When I try to launch Persona 4 Golden (64-bit - fresh install), an error box pops up and the game loads without mods.

The error box should be attached as an image, and a JSON file of the mods I'm using should also be attached (along with screenshots of Reloaded-II).

I don't know why this is happening - why it can't find the "version number" or anything.

![P4G Error](https://github.com/Reloaded-Project/Reloaded-II/assets/84822371/44a7ef46-83ea-40d5-8371-b8bae1462f25)
[P4G Mod List.json](https://github.com/Reloaded-Project/Reloaded-II/files/14325859/P4G.Mod.List.json)
![P4G Reloaded2 1](https://github.com/Reloaded-Project/Reloaded-II/assets/84822371/76373043-7e29-443a-a143-a3f8ec8bd1d9)
![P4G Reloaded2 2](https://github.com/Reloaded-Project/Reloaded-II/assets/84822371/ea7127a2-7d10-4d5c-9e3a-970089350b33)

**Comment by Sewer56** [comment]
Persona 4 Golden does not run on Unreal Engine. You shouldn't be running Unreal Essentials.
