### ISSUE TITLE
the reloaded is a glitching the video with help to make this clear/make sense what i just said

### ISSUE THREAD

**Issue by ReplicaWasD** [Reloaded-Project/Reloaded-II#299]
i dont know how it occur but it prolly due to downloading issue im not sure about it and it was affecting my computer for some reason it was glitching hella wild and i try to reinstall reloaded but still didnt work and couldnt load mods in p4g or p5r

https://github.com/Reloaded-Project/Reloaded-II/assets/160472393/0c962735-8e05-4236-a14c-92653c3103cb

**Comment by Sewer56** [comment]
The Dependency Download Loop is fairly rare, I've tried to fix it in the past, but without being able to reproduce it, I never could.

I might make it stop after a retry on exactly the same set of dependencies, and tell the user how to install the mods manually. Only issue is my health right now is slightly limiting to be making any significant changes. (I'm trying to reduce my screen time)

**Comment by ReplicaWasD** [comment]
i see thank you

**Comment by Sewer56** [comment]
If you upload your `Mods` folder though, I should be able to grab them for you.

**Comment by ReplicaWasD** [comment]
alright than ill do that
wait up

**Comment by ReplicaWasD** [comment]
damn i cant upload alot should i just slide off some mods to give it to you?

**Comment by Sewer56** [comment]
Whatever is minimum amount of mods needed to reproduce the issue for you.

**Comment by ReplicaWasD** [comment]
ight

**Comment by ReplicaWasD** [comment]
[Mods.zip](https://github.com/Reloaded-Project/Reloaded-II/files/14337168/Mods.zip)
not alot tho

**Comment by Sewer56** [comment]
[Mods.zip](https://github.com/Reloaded-Project/Reloaded-II/files/14337212/Mods.zip)

This should have what you were missing. Still kind of strange that it's borked, though.

**Comment by Sewer56** [comment]
Close this if it works for you.

I'll instead keep:
- https://github.com/Reloaded-Project/Reloaded-II/issues/226

Open. This happens very rarely, but I know it does for some people. Reasons still unknown.

**Comment by ReplicaWasD** [comment]
damn even with your help it still glitching

**Comment by ReplicaWasD** [comment]
> [Mods.zip](https://github.com/Reloaded-Project/Reloaded-II/files/14337212/Mods.zip)
> 
> This should have what you were missing. Still kind of strange that it's borked, though.

damn even with your help it still glitching

**Comment by Sewer56** [comment]
That should have been all dependencies missing from the mod list you gave me. Did you try installing something else and run into this again?

**Comment by ReplicaWasD** [comment]
yes?

**Comment by Sewer56** [comment]
yes?

**Comment by ReplicaWasD** [comment]
> That should have been all dependencies missing from the mod list you gave me. Did you try installing something else and run into this again?

i did reinstall some mods in the mod folder because the zip file was unable to go in github because 25mb limit so i remove some mods to fit the limit

**Comment by Sewer56** [comment]
Give me around a day or two.
The least I could do is have a dialog for these rare cases where something's stuck on loop. Hopefully I could get that done by Thursday/Friday. Depends on my health.

After this I'd like to try debug this with you. Having someone who experiences this issue first hand would be invaluable towards trying to actually fix it.

**Comment by ReplicaWasD** [comment]
> Give me around a day or two. The least I could do is have a dialog for these rare cases where something's stuck on loop. Hopefully I could get that done by Thursday/Friday. Depends on my health.
> 
> After this I'd like to try debug this with you. Having someone who experiences this issue first hand would be invaluable towards trying to actually fix it. Because this is a rare issue.

alright than ill see you in two day

**Comment by ReplicaWasD** [comment]
> Give me around a day or two. The least I could do is have a dialog for these rare cases where something's stuck on loop. Hopefully I could get that done by Thursday/Friday. Depends on my health.
> 
> After this I'd like to try debug this with you. Having someone who experiences this issue first hand would be invaluable towards trying to actually fix it. Because this is a rare issue.

now its not letting me open reloaded 2 (i reinstall it)

**Comment by Sewer56** [comment]
(I haven't forgotten, just been extremely busy fixing showstopper issues like false Defender flags, it's been taking longer than expected).

In any case, I added a loop detector in one of these hotfixes, does that at least work for you?
