### ISSUE TITLE
Error when launching

### ISSUE THREAD

**Issue by DingusAnonymous** [Reloaded-Project/Reloaded-II#30]
When I launch Persona 4 Golden, I get the message "The type initializer for 'Reloaded.Mod.Launcher.Utility.BasicDllInjector' threw an exception."

Image with log:
![Screenshot_8](https://user-images.githubusercontent.com/67342827/85457877-c99b1480-b5a0-11ea-8aa2-decedec6e689.png)

I've installed all prerequisites and restarted my computer several times.

**Comment by Sewer56** [comment]
Fixed by installing Core x86 or https://github.com/Reloaded-Project/Reloaded-II/issues/30 ?
Opening post wasn't updated after issue close.

**Comment by DingusAnonymous** [comment]
Yeah, I'd installed x64 instead of x86. It works good now, despite my saves being gone

**Comment by Sewer56** [comment]
(PS. You should install both as outlined by the prerequisites)
