### ISSUE TITLE
1.24.3 and updated plugins !?

### ISSUE THREAD

**Issue by Klemci** [Reloaded-Project/Reloaded-II#301]
Since i want to keep using NETCore 7, i keep older build for now...
... if plugins update, will it work perfectly or can i find manually downloadable plugins appropriate versions ?

This files got updated, when i skipped 1.25.8 popup since my RKLD was on offline PC earlier !:

1.2.10>.13
`\Mods\Reloaded.Memory.SigScan.ReloadedII\ModConfig.json
\Mods\Reloaded.Memory.SigScan.ReloadedII\Reloaded.Memory.dll
\Mods\Reloaded.Memory.SigScan.ReloadedII\Reloaded.Memory.Sigscan.Definitions.dll
\Mods\Reloaded.Memory.SigScan.ReloadedII\Reloaded.Memory.Sigscan.dll
\Mods\Reloaded.Memory.SigScan.ReloadedII\Reloaded.Memory.SigScan.ReloadedII.deps.json
\Mods\Reloaded.Memory.SigScan.ReloadedII\Reloaded.Memory.SigScan.ReloadedII.dll
\Mods\Reloaded.Memory.SigScan.ReloadedII\Reloaded.Memory.SigScan.ReloadedII.Interfaces.dll

1.16.0>.1
\Mods\reloaded.sharedlib.hooks\ModConfig.json
\Mods\reloaded.sharedlib.hooks\x64\Iced.dll
\Mods\reloaded.sharedlib.hooks\x64\Reloaded.Assembler.dll
\Mods\reloaded.sharedlib.hooks\x64\Reloaded.Hooks.Definitions.dll
\Mods\reloaded.sharedlib.hooks\x64\Reloaded.Hooks.dll
\Mods\reloaded.sharedlib.hooks\x64\Reloaded.Hooks.ReloadedII.deps.json
\Mods\reloaded.sharedlib.hooks\x64\Reloaded.Hooks.ReloadedII.dll
\Mods\reloaded.sharedlib.hooks\x64\Reloaded.Hooks.ReloadedII.Interfaces.dll
\Mods\reloaded.sharedlib.hooks\x64\Reloaded.Memory.Buffers.dll
\Mods\reloaded.sharedlib.hooks\x64\Reloaded.Memory.dll
\Mods\reloaded.sharedlib.hooks\x64\Reloaded.Mod.Interfaces.dll
\Mods\reloaded.sharedlib.hooks\x86\Iced.dll
\Mods\reloaded.sharedlib.hooks\x86\Reloaded.Assembler.dll
\Mods\reloaded.sharedlib.hooks\x86\Reloaded.Hooks.Definitions.dll
\Mods\reloaded.sharedlib.hooks\x86\Reloaded.Hooks.dll
\Mods\reloaded.sharedlib.hooks\x86\Reloaded.Hooks.ReloadedII.deps.json
\Mods\reloaded.sharedlib.hooks\x86\Reloaded.Hooks.ReloadedII.dll
\Mods\reloaded.sharedlib.hooks\x86\Reloaded.Hooks.ReloadedII.Interfaces.dll
\Mods\reloaded.sharedlib.hooks\x86\Reloaded.Memory.Buffers.dll
\Mods\reloaded.sharedlib.hooks\x86\Reloaded.Memory.dll
\Mods\reloaded.sharedlib.hooks\x86\Reloaded.Mod.Interfaces.dll

2.1.3>2.2.0
\Mods\reloaded.universal.fileemulationframework\FileEmulationFramework.deps.json
\Mods\reloaded.universal.fileemulationframework\FileEmulationFramework.dll
\Mods\reloaded.universal.fileemulationframework\FileEmulationFramework.Interfaces.dll
\Mods\reloaded.universal.fileemulationframework\FileEmulationFramework.Lib.dll
\Mods\reloaded.universal.fileemulationframework\ModConfig.json
\Mods\reloaded.universal.fileemulationframework\Reloaded.Hooks.Definitions.dll
\Mods\reloaded.universal.fileemulationframework\Reloaded.Memory.dll`

**Comment by Sewer56** [comment]
Most code mods are on GitHub and have a 'releases' page, like Reloaded itself
https://github.com/Reloaded-Project/Reloaded-II/releases

For example: https://github.com/Sewer56/Reloaded.SharedLib.Hooks.ReloadedII/releases

You can check which version of .NET a mod was built against by reading the `.runtimeconfig.json`. Almost if not all mods are still built with 7 or older, so nothing to worry about there. The launcher you can probably force to run on 7 (via `.runtimeconfig.json`) change since I don't remember using anything 8 specific.
