### ISSUE TITLE
Bug: cant start application .net core error

### ISSUE THREAD

**Issue by realfire23** [Reloaded-Project/Reloaded-II#302]
<img width="536" alt="image" src="https://github.com/Reloaded-Project/Reloaded-II/assets/26832574/e3b82dfc-6953-4178-b2dd-ba4b1a759254">

.net core is installed

**Comment by Sewer56** [comment]
You probably got a false positive from Windows Defender/Your Antivirus and it removed/quarantined `Kernel32AddressDumper.exe`.

Extract a [fresh copy](https://github.com/Reloaded-Project/Reloaded-II/releases/latest/download/Release.zip) over your existing Reloaded install
