### ISSUE TITLE
1.25.8 gets flagged by antivirus

### ISSUE THREAD

**Issue by xBowlOfSoupx** [Reloaded-Project/Reloaded-II#303]
Is this a mistake? Ive been screwed by this sort of thing before so Im very apprehensive towards this sort of thing

Trojan:Win32/Wacatac.B!ml

**Comment by Sewer56** [comment]
Recently it's been happening on almost every release with `Kernel32AddressDumper.exe` , for some very strange reason. 

It only has been getting flagged lately, historically it used not to get flagged (even though none of the code changed).

In any case, I've reported false positive as usual, but sometimes it takes a few days for the file to be whitelisted.
