### ISSUE TITLE
[Reloaded.Assembler Can't see FASM.DLL Despite being in User's Folder?? What???]

### ISSUE THREAD

**Issue by AzureAragami** [Reloaded-Project/Reloaded-II#305]
**Describe the Bug**
FASM error shows up whenever I try to launch application.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run setup.exe as an admin for the first time.
2. Add any game.
I have tested with Persona 3 Reload and Persona 5 Royal, both Steam version.
* In case of P3R was pre requisite installer was also used per instructions on link below.
4. Install any mod.
5. Order the mods per the recommendations.
P3R https://gamebanana.com/tuts/17156
P5R https://gamebanana.com/tuts/15399
6. Click on "Launch Application".
7. See error.

**Additional Details**
I had this error 2 days ago and it was randomly fixed by running setup.exe again after deleting the files. 
Today for some reason the reloaded-II folder was gone, I believe somehow Windows Defender deleted it without consulting me, so I redownloaded and followed the steps but now the error does not disappear no matter what.
I added the folder with the reloaded-II files to the whitelist just in case but no luck, so it could be something else.

**Expected Behaviour**
Game should launch with mods, not receiving error.

**Screenshots**
<img width="1089" alt="image" src="https://github.com/Reloaded-Project/Reloaded-II/assets/49356527/7cba19ff-3778-489c-8b88-ae80796507f8">

**Logs**
[2024-02-20 23.41.15 ~ P3R.txt](https://github.com/Reloaded-Project/Reloaded-II/files/14352562/2024-02-20.23.41.15.P3R.txt)

**Comment by AzureAragami** [comment]
> Chances are that for some reason folder `reloaded.sharedlib.hooks` in `Reloaded-II/Mods` is missing file (`FASMX64.DLL`). Delete `reloaded.sharedlib.hooks` , let the launcher re-download it, and see if it fixes your issue.

Tried just now but same error.

I went back to check inside the folder and it does have the file there.
<img width="584" alt="image" src="https://github.com/Reloaded-Project/Reloaded-II/assets/49356527/8309dedd-2da1-4910-9863-0f334c9c7dac">

**Comment by Sewer56** [comment]
You sure it's the exact same error?
Kind of weird; usually that file doesn't get blacklisted by antiviruses, so it's a bit weird to see it inaccessible.

**Comment by AzureAragami** [comment]
> You sure it's the exact same error? Kind of weird; usually that file doesn't get blacklisted by antiviruses, so it's a bit weird to see it inaccessible.

my bad I should have uploaded the screenshot and logs with more details, to me it looks like the same error.

[2024-02-21 00.35.01 ~ P3R.txt](https://github.com/Reloaded-Project/Reloaded-II/files/14352556/2024-02-21.00.35.01.P3R.txt)



<img width="1063" alt="image" src="https://github.com/Reloaded-Project/Reloaded-II/assets/49356527/36f23e78-f9a1-4c3e-9d30-eaf40e42cfbf">

**Comment by Sewer56** [comment]
That's kind of weird.
The way it works is it takes the path to `Reloaded.Assembler.dll`, removes the directory part and appends `FASMX64.DLL`.

It then checks if that path exists on disk.
This path clearly exists in the screenshot, so something really weird is happening.

Are there maybe 2 copies of this mod? I'm not really sure how a situation like this could end up happening.

**Comment by AzureAragami** [comment]
> That's kind of weird. The way it works is it takes the path to `Reloaded.Assembler.dll`, removes the directory part and appends `FASMX64.DLL`.
> 
> It then checks if that path exists on disk. This path clearly exists in the screenshot, so something really weird is happening.
> 
> Are there maybe 2 copies of this mod? I'm not really sure how a situation like this could end up happening.

Sorry, of which mod?

If you refer to "Reloaded.Assembler.dll" then there is only one on x64 folder and x86 folder respectively (refer to screenshot above).

Originally I had the reload-II folder on my D:/ drive instead of the default C:/ drive, so I tested just now to move things to C:/ drive instead, again excluding the whole folder on Windows Defender, but the error persists.

**Comment by Sewer56** [comment]
`reloaded.sharedlib.hooks`, think it has same DLL name, am not on my machine right now.

**Comment by AzureAragami** [comment]
> `reloaded.sharedlib.hooks`, think it has same DLL name, am not on my machine right now.
> 
> Worst case scenario, I can try compiling custom Reloaded.Assembler with extra logging, see what happens when I get back to PC.

It does seem to exist twice but on different sub directories:
1: Reloaded-II/Mods
2: Reloaded-II/User/Mods

<img width="815" alt="image" src="https://github.com/Reloaded-Project/Reloaded-II/assets/49356527/983cbdc7-3a38-4122-a513-b29d41fbfbde">

**Comment by Sewer56** [comment]
The `User` folder just has the config.

I'm more curious is perhaps somehow the code is seeing a weird DLL path for Reloaded.Assembler.dll, gimme a bit. When I get to my PC I'll make a custom version.

**Comment by AzureAragami** [comment]
> The `User` folder just has the config.
> 
> I'm more curious is perhaps somehow the code is seeing a weird DLL path for Reloaded.Assembler.dll, gimme a bit. When I get to my PC I'll make a custom version.

I appreciate it!, do let me know what info would be most useful for you when I run that custom version.

**Comment by Sewer56** [comment]
Sorry for the delays, that's kind of been unexpected. I'm still working on some showstopping issues :(

**Comment by AzureAragami** [comment]
> Sorry for the delays, that's kind of been unexpected. I'm still working on some showstopping issues :( I haven't forgotten

no worries take your time! I appreciate the follow up though thats very nice of you :)

**Comment by Sewer56** [comment]
I am free now though !

**Comment by Sewer56** [comment]
If you got some time, I can probably build a custom version with some extra logging, I'm kinda curious myself what's going on

**Comment by AzureAragami** [comment]
> If you got some time, I can probably build a custom version with some extra logging, I'm kinda curious myself what's going on

I got some time sure!

**Comment by Sewer56** [comment]
[Reloaded.Assembler.dll.zip](https://github.com/Reloaded-Project/Reloaded-II/files/14471441/Reloaded.Assembler.dll.zip)

Can you throw this into the folder you linked here?

<img alt="image" width="584" src="https://private-user-images.githubusercontent.com/49356527/306451712-8309dedd-2da1-4910-9863-0f334c9c7dac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0MzIyNzMsIm5iZiI6MTcwOTQzMTk3MywicGF0aCI6Ii80OTM1NjUyNy8zMDY0NTE3MTItODMwOWRlZGQtMmRhMS00OTEwLTk4NjMtMGYzMzRjOWM3ZGFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDAyMTI1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlYzMzNmQxMjJmNzc0YWYxMzE0MjVhNTdkNjczMDNlNmJjODg5NTRmZTFmZmMyOGFiZDRjZjJlM2MxYzdhNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7Cx4HPi0h0iSxMqlrCKBzJor2ecUwW4ZkzPZbhHqcL0">

It should log some extra info inside your console.

**Comment by AzureAragami** [comment]
the screenshot appears broken for some reason, i placed it on D:\Games\#Mods\Persona\Reloaded-II


[2024-03-03 02.55.15 ~ P3R.txt](https://github.com/Reloaded-Project/Reloaded-II/files/14471511/2024-03-03.02.55.15.P3R.txt)

If this is not the right folder let me know, sorry about that.

**Comment by Sewer56** [comment]
Ah. sorry. This DLL doesn't interact with the logger, so the text it prints won't be in the log.
Are you able to grab a screenshot of the Reloaded console window with the error present?

**Comment by AzureAragami** [comment]
done
<img width="689" alt="image" src="https://github.com/Reloaded-Project/Reloaded-II/assets/49356527/1220237c-9e3c-44c6-a904-95c99cd5c65b">

**Comment by Sewer56** [comment]
Is there anything in the console above the error message itself?
I added a bunch of debug printouts (e.g. `FASM86 DLL found in assembly directory`). Hopefully they print.

**Comment by AzureAragami** [comment]
> Is there anything in the console above the error message itself? I added a bunch of debug printouts (e.g. `FASM86 DLL found in assembly directory`). Hopefully they print.

<img width="690" alt="image" src="https://github.com/Reloaded-Project/Reloaded-II/assets/49356527/3226e75c-6a1f-4fc7-95ef-e1bfd302078a">

**Comment by Sewer56** [comment]
I'm guessing it writes before the console window even opens, so nothing appears.
I modified this to add the log inside the error itself. See what you get.

[Reloaded.Assembler.dll.zip](https://github.com/Reloaded-Project/Reloaded-II/files/14471534/Reloaded.Assembler.dll.zip)

**Comment by AzureAragami** [comment]
placed it but the logs seem the same to me? hopefully im wrong.

I placed it here: D:\Games\#Mods\Persona\Reloaded-II where the Reloaded-II.exe is

**Comment by Sewer56** [comment]
> placed it but the logs seem the same to me? hopefully im wrong.
> 
> I placed it here: D:\Games#Mods\Persona\Reloaded-II where the Reloaded-II.exe is

Ah no, it's `Reloaded-II/Mods/reloaded.sharedlib.hooks/x64` folder. That was why I reposted your screenshot from earlier, as you've already been in that folder.

**Comment by AzureAragami** [comment]
> > placed it but the logs seem the same to me? hopefully im wrong.
> > I placed it here: D:\Games#Mods\Persona\Reloaded-II where the Reloaded-II.exe is
> 
> Ah no, it's `Reloaded-II/Mods/reloaded.sharedlib.hooks/x64` folder. That was why I reposted your screenshot from earlier, as you've already been in that folder.

yeah sorry the screenshot showed as broken as i mentioned on the other comment haha

<img width="983" alt="image" src="https://github.com/Reloaded-Project/Reloaded-II/assets/49356527/7e5947eb-3883-4458-b92f-7dd12413f758">

**Comment by Sewer56** [comment]
Ah, wait, seems I built wrong version of Reloaded.Assembler.
I thought Hooks was using an up to date version, but that may not have been the case.

[Reloaded.Assembler.dll.zip](https://github.com/Reloaded-Project/Reloaded-II/files/14471642/Reloaded.Assembler.dll.zip)

Try this one

**Comment by AzureAragami** [comment]
> Ah, wait, seems I built wrong version of Reloaded.Assembler. I thought Hooks was using an up to date version, but that may not have been the case.
> 
> [Reloaded.Assembler.dll.zip](https://github.com/Reloaded-Project/Reloaded-II/files/14471642/Reloaded.Assembler.dll.zip)
> 
> Try this one

done
<img width="961" alt="image" src="https://github.com/Reloaded-Project/Reloaded-II/assets/49356527/a310f82e-dbe4-4b40-abb1-8458e58e3d58">

**Comment by Sewer56** [comment]
Strange it is failing to link against `2.0.0` of `Reloaded.Memory.Buffers`. The version of `Reloaded.Assembler` I uploaded should be linked against this.

Here's an idea, delete the entire `reloaded.sharedlib.hooks` mod (the whole folder). See what happens when it redownloads.
Then nab another screenshot with the DLL I placed if you still have errors.

**Comment by AzureAragami** [comment]
deleted it but when i clicked Launch it didnt seem to redownload? perhaps it did it too fast.

<img width="991" alt="image" src="https://github.com/Reloaded-Project/Reloaded-II/assets/49356527/c0314a2e-d76e-4e0d-9903-3c63f9d8f9b1">

**Comment by Sewer56** [comment]
That's ok, it's intended to auto redownload if missing. Lemme reboot to Windows and test build before I upload it here.

**Comment by Sewer56** [comment]
[Reloaded.Assembler.zip](https://github.com/Reloaded-Project/Reloaded-II/files/14471690/Reloaded.Assembler.zip)

Okay, try this one in x64 folder. I tested on my machine, I hope it succeeds in throwing the correct error

**Comment by AzureAragami** [comment]
sorry for the delay.

<img width="969" alt="image" src="https://github.com/Reloaded-Project/Reloaded-II/assets/49356527/b3afe297-1ff2-4c22-af84-d1cf71b44809">

**Comment by Sewer56** [comment]
Well, this explains a lot. I wonder why it thinks `D:\Games` is the probing location for this DLL.
Is your Steam Library on a Network drive maybe? (I see `Z` letter) Can you confirm that?

This might work after this patch, 
[Reloaded.Assembler.zip](https://github.com/Reloaded-Project/Reloaded-II/files/14471780/Reloaded.Assembler.zip)

**Comment by AzureAragami** [comment]
> Well, this explains a lot. I wonder why it thinks `D:\Games` is the probing location for this DLL. Is your Steam Library on a Network drive maybe? (I see `Z` letter) Can you confirm that?
> 
> This might work after this patch, [Reloaded.Assembler.zip](https://github.com/Reloaded-Project/Reloaded-II/files/14471780/Reloaded.Assembler.zip)

My steam is installed on the C drive, Persona is installed on a Z drive.
The letters were simply renamed into those, not sure what you mean by a Network drive sorry.


With that said, now the mods worked perfectly with that latest .dll file

**Comment by Sewer56** [comment]
Hmm, strange.
Well, enjoy for now, I'll roll a patch for this. In the meantime, feel free to play with what you have.

**Comment by AzureAragami** [comment]
> Hmm, strange. Well, enjoy for now, I'll roll a patch for this. In the meantime, feel free to play with what you have.
> 
> I'll close this once the patch is rolled out to end users.

sounds good thanks a ton!
