### ISSUE TITLE
Bug: <appears as trojan when unpacking with nano zip to windows defender> 

### ISSUE THREAD

**Issue by Arkcon10** [Reloaded-Project/Reloaded-II#307]
Bug in title. appears to windows defender as a trojan when unpacking with nanozip the latest release.

**Comment by Sewer56** [comment]
I've had to deal with about 40 reports of false positives in the last week. I've reported them as false detections, but it happens every release, and all I can do is wait and pray the files eventually get whitelisted.

I'm rewriting the bit of code that is getting falsely flagged so it hopefully doesn't get flagged again (in my spare time after work). I shouldn't have to do this, but it seems I have no other choice.

Either please whitelist the folder/file, or wait patiently please.
