### ISSUE TITLE
Help: Please help me with Installing/Running Reloaded!

### ISSUE THREAD

**Issue by hamperhamper** [Reloaded-Project/Reloaded-II#311]
![the error](https://github.com/Reloaded-Project/Reloaded-II/assets/160782913/a620283b-5056-47a8-b132-d37cdbae5742)

This is what's going on, and any time I try to redownload the newest version, it's marked as a Virus. It had worked prior (about half a year ago) when I was playing P5R. And since P3R is here, i wanted to use this app again.

Idk what's going on, am I doing osmething wrong? :( ?

**Comment by Sewer56** [comment]
Falsely detected by your antivirus.

Temporarily disable then add to your exclusions. In the meantime, I'm working on it.

Sorry for short response, I've been dealing with multiple of these an hour.

**Comment by Sewer56** [comment]
No sweat, and most importantly.
Make sure to have fun 👍
