### ISSUE TITLE
Pop-ups are going crazy, and I can't do anything.

### ISSUE THREAD

**Issue by hypnosis0930** [Reloaded-Project/Reloaded-II#314]
![bug](https://github.com/Reloaded-Project/Reloaded-II/assets/160973526/8057ebbc-93e4-49a5-bff7-33cdaa901267)

**Comment by desertkona** [comment]
Hello are you using for Relink too? what mod do you use?
You need this mandatory mod for Relink 
https://github.com/WistfulHopes/gbfrelink.utility.manager + you need to order it to number 1

**Comment by Sewer56** [comment]
That was probably the mod that was stuck in download loop.
It wasn't packaged right at the time, I asked the mod author and we hopefully got that fixed.

Around 5 mins after this post anyway.

**Comment by ThieviusRax** [comment]
This is still an issue.

I'm also experiencing pop-ups like crazy and I had to reinstall reloaded all over again to get them to stop.  Then when I tried adding all my mods back the pop-ups came back

**Comment by Sewer56** [comment]
In 1.25.9, I added a 'loop detector' as last resort.
I couldn't investigate at the underlying issue this week, but hopefully I'll be able to do so soon.

**Comment by Sewer56** [comment]
I'll close this in favour of earlier report of this:
- https://github.com/Reloaded-Project/Reloaded-II/issues/226

Please do post if the 'loop detector' doesn't detect endless download attempts.

**Comment by hypnosis0930** [comment]
Thank you for your help. After reinstalling all these things several times, it seems to be all right.
