### ISSUE TITLE
unable to extract the file

### ISSUE THREAD

**Issue by nuclearplutonium** [Reloaded-Project/Reloaded-II#317]
won't let me extract it.
hits me with the 
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/161105977/23a703cc-cac0-4fcd-b978-08f0531d4e58)

**Comment by Sewer56** [comment]
Chances are you may be blocked by Antivirus software, or similar. The release zip(s) should be correct i.e. (specification compliant).

Try 7-zip anyway though, just in case.

**Comment by nuclearplutonium** [comment]
ive been using winrar
