### ISSUE TITLE
setup exe detected as virus when downloaded

### ISSUE THREAD

**Issue by Suruuuu** [Reloaded-Project/Reloaded-II#320]
Hi, I've recently downloaded this program again after a year or so and now I'm getting a malware warning, when the last time I downloaded this back then nothing happened, is the application compromised? or is this a false positive?

![Captura de pantalla 2024-02-25 183445](https://github.com/Reloaded-Project/Reloaded-II/assets/86446513/f29b46c5-112d-47db-a876-d6bb56cf2d08)

![Captura de pantalla 2024-02-25 183409](https://github.com/Reloaded-Project/Reloaded-II/assets/86446513/1b482f2f-8b22-40a3-9b5e-5ce9d082f34f)

**Comment by Sewer56** [comment]
It's probably a false positive, another one to report, I guess.

**Comment by Suruuuu** [comment]
> It's probably a false positive, another one to report, I guess.

so should I carry on to modding P5R? if it's a false positive and it doesn't actually contain malware it's fine.

**Comment by Sewer56** [comment]
Yeah you should be fine.

**Comment by Suruuuu** [comment]
Alright good, thanks for your time and effort.
