### ISSUE TITLE
[Granblue Relink: User is stuck after loader successfully loads in its entirety]

### ISSUE THREAD

**Issue by basterzero** [Reloaded-Project/Reloaded-II#323]
I've been stuck in this window for a long time, what should I do to fix it?
![Screenshot (724)](https://github.com/Reloaded-Project/Reloaded-II/assets/161289858/c2d8f820-133b-4b13-8267-9e596a8f93e9)

**Comment by Reflection4Real** [comment]
I also have the same problem

**Comment by Sewer56** [comment]
Would you be able to provide more information about your system?
I bought this game but have trouble replicating this. 

This is also strange, in that I've never seen the modloader fully initialize before, but the end user be stuck.

Things that come to mind:
- Anything that can overlay/read/alter game visuals (e.g. ReShade, Special K, Video Capture Software)
  - This includes anything that renders ontop of the game such as 'Nahimic Audio Driver' which comes preinstalled on some prebuilt/OEM machines.
  
etc. Anything that would be useful in trying to replicate your setup.

**Comment by basterzero** [comment]
What information do you need to help? I'll go get it.

**Comment by Sewer56** [comment]
Anything that 

> Would you be able to provide more information about your system? I bought this game but have trouble replicating this.
> 
> This is also strange, in that I've never seen the modloader fully initialize before, but the end user be stuck.
> 
> Things that come to mind:
> 
>     * Anything that can overlay/read/alter game visuals (e.g. ReShade, Special K, Video Capture Software)
>       
>       * This includes anything that renders ontop of the game such as 'Nahimic Audio Driver' which comes preinstalled on some prebuilt/OEM machines.
> 
> 
> etc. Anything that would be useful in trying to replicate your setup.

Anything that falls under the above @basterzero

**Comment by TianTan2024** [comment]
im having the same problem now.
I was able to use reloaded before and it has the same problem now.
I did not add any new mods and it will only startup when all my mods turned off(but the mods are still on).
This might happen because I updated the reloaded app, or maybe I forced quit once.

**Comment by Keinechanw** [comment]
im having the same problem now.
I was able to use reloaded before and it has the same problem now.
I did not add any new mods and it will only startup when all my mods turned off(but the mods are still on).
This might happen because I updated the reloaded app, or maybe I forced quit once.

**Comment by basterzero** [comment]
I forgot about this one. What is it?
![Screenshot (729)](https://github.com/Reloaded-Project/Reloaded-II/assets/161289858/53f6200b-ff52-4de9-a00a-00f34d176060)

**Comment by Sewer56** [comment]
Normally this is printed while loading a code mod.
Hmm, actually. Wait, is something trying to be loaded after Steam DRM Bypass?

What's your enabled mod list?

**Comment by Keinechanw** [comment]
Enabled mod list doesnt matter. Game won't start even if I only enable the GBFR mod manager.

**Comment by Sewer56** [comment]
> Enabled mod list doesnt matter. Game won't start even if I only enable the GBFR mod manager.

My concern was maybe there was a deadlock in the mod itself, causing it to get stuck on boot; since I only print when mods actually finish loading.

Does it happen without any mods enabled at all?

**Comment by Keinechanw** [comment]
It won't happen without any mod. However, all my mods are loaded even I disabled all of them.

**Comment by Sewer56** [comment]
Is the problem specific to GBFR ModManager mod then?

Try loading something generic like 'Reloaded File Monitor', I presume that works OK?

**Comment by Keinechanw** [comment]
it works OK

**Comment by Sewer56** [comment]
I'll look in ModManager mod source code then, to see if anything stands out. Gimme a while.

**Comment by Sewer56** [comment]
Hmm, weird, gimme a while, I'll be back later. Will build some debug versions of mods.

**Comment by Keinechanw** [comment]
Oh Btw the open folder function is not working for me now(it worked before), so I assume something is wrong with my reloaded

**Comment by basterzero** [comment]
I have reloaded the monitor file. What happens is that when it reaches this screen, it bounces back to the program. 
![Screenshot (732)](https://github.com/Reloaded-Project/Reloaded-II/assets/161289858/c9824e45-b2bd-4ea8-b48e-bf9dc4dd444a)
And I tried to remove GBFR Manager, it appears that it can run the game normally, but it cannot run the mods.

**Comment by basterzero** [comment]
Yes, exactly what you say.

**Comment by KurochaK** [comment]
Unfortunately, I just run into the same problem and I wonder if there is already a solution now.
![screenshot1](https://github.com/Reloaded-Project/Reloaded-II/assets/166246402/950063ed-ca93-47a2-9638-87e3b446e9ae)
I successfully run the game with mods in it at first but failed on the second attempt.
I am just stuck in this window and it cannot run the game again.
I can manually start the game with these mods in it even if I disabled all of them, which is just the same situation as above.
I'm not very good at English, and I'm sorry if I can't describe this situation clearly.

**Comment by Sewer56** [comment]
I could probably try debugging it myself but I'd suggest asking the current project maintainer ( @Nenkai ) in case this is a common situation.

It seems that utility manager is stuck deadlocked on boot.

**Comment by Nenkai** [comment]
I've seen this problem very rarely from various people, but never personally
I'm not sure. There should be enough error messages during and after initialization, which aren't being fired at all

Maybe it _is_ stuck during the loader's logic somewhere, but I wouldn't know where without an exact setup to reproduce

**Comment by Sewer56** [comment]
> I've seen this problem very rarely from various people, but never personally I'm not sure. There should be enough error messages during and after initialization, which aren't being fired at all
> 
> Maybe it _is_ stuck during the loader's logic somewhere, but I wouldn't know where without an exact setup to reproduce

I'd usually try doing the following:

- Check for any async code (check for anything that waits).
- Check for any silent exceptions tied to async code.

If nothing else, just add log lines all over the place and grab someone who's affected by the issue. Should make things easier.

**Comment by Nenkai** [comment]
Apologies for the _very_ delayed reply,

As far as I know we are not using any async code here but i've added further logging in the newest version to at least know whether the loader's entrypoint is even being hit - every errornous phase should've already been logged before this though, maybe third party lib code deadlocking, hard to tell.

Thanks for the suggestions!

**Comment by Vinzelles** [comment]
I am facing the same issue but with a slight difference.
When I click "Launch Application" through the Reload program panel, it will stuck here forever.

![image](https://github.com/Reloaded-Project/Reloaded-II/assets/67829622/5834df6b-63fb-4021-8148-7f75c6258929)

But if I start the game directly from steam, the Reload terminal will appear and finish the loading stage without any exception, and then every mod works normally.

**Comment by Sewer56** [comment]
[Should I try to reproduce and fix this myself?]

**Comment by Nenkai** [comment]
[This](https://github.com/WistfulHopes/gbfrelink.utility.manager/blob/a8daf145bf29b0db923750e2a6660c824bd1be25/gbfrelink.utility.manager/Mod.cs#L69) is not being printed, so the mod's entrypoint is not being hit.

You'll have an hard time trying to reproduce it, however it seems that this deadlock only appears on OS'es using different text encodings? Most of the people having this issue have been from China.
Perhaps it is related, but I am not sure.

**Comment by Sewer56** [comment]
It's strange. .NET itself uses UTF-16, and I've had success before running mods out of paths that have non-ANSI characters. Heck, in their log the hooks library seems to have loaded just fine.

The actual entry point is `StartEx` https://github.com/WistfulHopes/gbfrelink.utility.manager/blob/a8daf145bf29b0db923750e2a6660c824bd1be25/gbfrelink.utility.manager/Template/Startup.cs#L53 , maybe we can try logging something inside there?

Just log on every major step.

**Comment by Sewer56** [comment]
![granblue_fantasy_relink_g3BDMdL4hv](https://github.com/Reloaded-Project/Reloaded-II/assets/6697380/027d51a0-4939-41f3-858a-cf5165a93b25)

I tried to get something to happen by moving everything into folders using non-ANSI paths and using a non-ANSI locale, but I couldn't reproduce it.

**Comment by Nenkai** [comment]
The latest version of the manager now has a log at StartEx. If anyone who still has this issue could report if that's it's at least printed, it'd be appreciated

For the past few weeks I haven't seen anyone reporting issues at all at least.

**Comment by nukieberry** [comment]
> The latest version of the manager now has a log at StartEx. If anyone who still has this issue could report if that's it's at least printed, it'd be appreciated
> 
> For the past few weeks I haven't seen anyone reporting issues at all at least.

I'm still having the same issue. It stuck after showing following message.
[GBFRelinkManager] StartEx
[Reloaded] Loading: Granblue Fantasy Relink Mod Manager
[Reloaded] - AppId   : gbfrelink.utility.manager
[Reloaded] - Location: D:\Reloaded\Mods\gbfrelink.utility.manager\ModConfig.json
Where is the log file you mentioned?

**Comment by Sewer56** [comment]
@nukieberry by 'log' they meant a print out to the log file. It's the one you see at the top of your log snippet.

**Comment by Sewer56** [comment]
In any case. This doesn't seem to make any sense. Between this printout and what should be the next one, only the config file should be accessed. It's really strange that a deadlock happens here; I've never seen that happen before.

**Comment by nukieberry** [comment]
It worked fine after game version 1.3.1. Deadlock happened when I upgraded Reloaded from 1.27.8 to 1.27.10 and add a few new mods. Same as people mentioned above, the game can only boot up when all mods are crossed out in Reloaded, and it still has the old mods taking effect whatsoever. I'm trying a clean reinstallation now.

**Comment by Sewer56** [comment]
> Deadlock happened when I upgraded Reloaded from 1.27.8 to 1.27.10

There's no changes in the loader between those versions. It's a bugfix in launcher and improved accessibility in launcher for people with impaired eyesight.

> and it still has the old mods taking effect whatsoever.

I've actually brought this up to @WistfulHopes in the past. You really shouldn't be modifying any game files from Reloaded mods, it's a big no-no.

Instead hook NtCreateFile to redirect the file to your own, or hook whatever part of game code opens the file. either-or.

-----

If anything I'm confused why the log stopped there. The mod isn't doing anything substantial other than loading a config file. Yet, it freezes up.

**Comment by Sewer56** [comment]
[gbfrelink.utility.manager.zip](https://github.com/user-attachments/files/15826031/gbfrelink.utility.manager.zip)
@nukieberry 

I built a copy with some more print statements myself.
Curious what it prints.

**Comment by nukieberry** [comment]
> [gbfrelink.utility.manager.zip](https://github.com/user-attachments/files/15826031/gbfrelink.utility.manager.zip) @nukieberry
> 
> I built a copy with some more print statements myself. Curious what it prints.

I didn't manually modify any files in Reloaded or game folder. But hold on, relevant or not, I did drag a newer version of a mod into Reloaded. Two entries with same name appeared in the mod list for a while until I restarted Reloaded.
I shall try this build once installation completed.

**Comment by nukieberry** [comment]
> > [gbfrelink.utility.manager.zip](https://github.com/user-attachments/files/15826031/gbfrelink.utility.manager.zip) @nukieberry
> > I built a copy with some more print statements myself. Curious what it prints.
> 
> I didn't manually modify any files in Reloaded or game folder. But hold on, relevant or not, I did drag a newer version of a mod into Reloaded. Two entries with same name appeared in the mod list for a while until I restarted Reloaded. I shall try this build once installation completed.

![image](https://github.com/Reloaded-Project/Reloaded-II/assets/55907281/fe646803-71c8-49d9-8c71-a67b80889289)

Clean reinstallation of game and Reloaded. Added back the mods. Click Launch to get the mod manager. Replaced files in Mods/gbfrelink.utility.manager/. Launch Application clicked again. This is what I get at this point.

**Comment by Sewer56** [comment]
By all accounts it's probably softlocking trying to read config file. Wow, I've never really seen that before.

I'm probably gonna fall asleep by the time I next touch my PC, so I'll ping @Nenkai in case they feel like debugging.

If not, I'll try debugging this hopefully when I wake up.

**Comment by Sewer56** [comment]
@nukieberry 

Here, see what this logs.
[gbfrelink.utility.manager.zip](https://github.com/user-attachments/files/15829631/gbfrelink.utility.manager.zip)

(I couldn't sleep 😅)

**Comment by nukieberry** [comment]
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/55907281/442cb5ef-07b0-428f-b629-fa70c4081af8)

**Comment by Sewer56** [comment]
[gbfrelink.utility.manager.zip](https://github.com/user-attachments/files/15829732/gbfrelink.utility.manager.zip)

@nukieberry I wonder if it's getting stuck reading config somehow.
Here, try this one; I put log statements pretty much everywhere else at this point.

**Comment by nukieberry** [comment]
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/55907281/05d50c30-4952-411e-b2ee-b86cf7bf89e1)

**Comment by Sewer56** [comment]
If I disable config live update, does it then work?

[gbfrelink.utility.manager.zip](https://github.com/user-attachments/files/15829878/gbfrelink.utility.manager.zip)

Normally this shouldn't lock up, I'm not sure why it gets deadlocked, as I've never seen that happen before.

According to log, no other code is running in the background; unless you have some ASI Loader plugin sitting in your game folder unaccounted for.

**Comment by nukieberry** [comment]
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/55907281/6774afaf-7022-4604-811c-582dd721624f)

**Comment by Sewer56** [comment]
I somehow get the feeling that yours is being prevented from reading any files whatsoever.
I'm not really sure what to say about that, other than maybe trying to run as Admin and checking antivirus logs out of curiosity.

None of this seems to be making much sense, it just locks up trying to access any file on disk seemingly.

**Comment by nukieberry** [comment]
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/55907281/64b049b4-a495-4fb1-9041-8de56c8634da)
I've double checked it is running as admin. However this message pops up on the first run after a reboot. But it doesn't seem to block anything. The folder itself is not read-only either. Weird.

**Comment by Sewer56** [comment]
I've got no idea myself honestly, it's just strange.
It's not even to do with being read-only. It's even being prevented from reading in the first place.

As if blocked by some kernel module, like an anticheat, an antivirus, or something of the kind.

**Comment by nukieberry** [comment]
If I'm not confused, it can at lease read AppConfig.json, otherwise the mod list should be empty. But not for files in Mods folder. Can you test what specific file, or all files, it cannot access?

**Comment by Sewer56** [comment]
The weird part is the mod started loading, so the loader itself can access files just fine. After all, it needs to load and parse all of the `ModConfig.json` files.

But the moment Relink Mod Manager tries to touch any file, everything works.

I'd be curious to see what happened if you loaded another completely unrelated mod though, something non-game specific, for example `Reloaded File Monitor`.

**Comment by nukieberry** [comment]
Adding an exclusion in Windows Security didn't help. Can I have a link for this unrelated mod? Should I just put it in GBFR and disable all other mods?

**Comment by Sewer56** [comment]
You can find it via search inside the launcher. Should be pretty easy. No links needed.

**Comment by nukieberry** [comment]
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/55907281/347023fe-a896-4f52-b357-68c51e03ebfd)
:(

**Comment by Sewer56** [comment]
Huh, Redirector somehow loaded just fine on the other hand. But monitor, a mod that only prints events from redirector locked up? That really does not make any sense, wow.

Does this happen with all games? If you add something like notepad, and use monitor in it, does that work?

**Comment by nukieberry** [comment]
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/55907281/44d3aaaf-aa5e-4402-9d6a-b84444b82262)
For some reason there are two entries. Clicking any of them will result in the lower one highlighted.
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/55907281/432fa737-6d3c-4fe8-9889-214dbaf992be)
Notepad launched just fine. Does it mean the problem is in the game executable?

**Comment by Sewer56** [comment]
It's something weird going on specifically with the game most likely, but I don't really have an idea what.

I'd consider running things as minimal as possible, disable all overlays, etc. reset game folder to clean, and see if that fixes it. Then if that works, you could start re-enabling things again and seeing where it goes.

For a quick game folder reset, I'd probably just delete all files that aren't the main `data` archive, and then verify files in Steam to get the others back.

**Comment by nukieberry** [comment]
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/55907281/05ce45ff-2de7-4cd6-91ab-205b8f56bb58)
A clean game client still stuck. But as a workaround, setting up ASI Loader worked.
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/55907281/91bbca16-dd1f-4e7f-bcf3-b7476ae28efc)

**Comment by Sewer56** [comment]
That's kinda interesting.

I've been getting strange reports of DLL Injection causing unexpected issues lately, I wonder what's up with that.

But hey, if it works, it works!

**Comment by nukieberry** [comment]
Thanks for all contributions and support. Good luck on future fixes. :)

**Comment by dropDBToRun** [comment]
If you need a VPN/accelerator for gaming like I do, try launching the game with Reloaded first, then enable the accelerator – it should work properly that way.But I'm not sure if this method only works with the specific accelerator I'm using.Although you can use ASI loaders, I still encounter this particular issue.#374
![Image](https://github.com/user-attachments/assets/e0a28df3-b331-4e1b-9bb7-08f6fcd4b38f)

![Image](https://github.com/user-attachments/assets/b9ec1f2c-51f0-4ee5-a5e7-011de6b64ef3)
