### ISSUE TITLE
Can't launch game with mods

### ISSUE THREAD

**Issue by Pirate1Frog** [Reloaded-Project/Reloaded-II#328]
When i launch the application from reloaded 2 i get 2 errors and the game launches without the mods

After updating reloaded 2 today and even if i try to roll back to an older version i see the 2 errors.

Normally the reloaded 2 opens the console that loads the mods and then the game opens normally

I have tried redownloading reloaded 2 both the older and newest version but the errors persist and they only started after i updated reloaded 2. I have tried the instructions on the unknown error window but i still can't launch the game with mods.

The errors i get are:
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/162321838/3dc8ec0d-5f4a-4b9d-9726-ff9faee05ccf)
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/162321838/b282a8c2-e3e6-409c-9adb-c30a554595e5)

**Comment by Sewer56** [comment]
Try removing the 'Cache' folder inside Persona Essentials.
I think the index for the cache got borked.
