### ISSUE TITLE
.NET Runtime Download file error

### ISSUE THREAD

**Issue by zlqd123** [Reloaded-Project/Reloaded-II#331]
When starting the program, the application prompts and guides the download .NET runtime 8.0.2 x86, but the prompt still pops up when restarting the application after installation is complete.
If downloading and installing .NET **Desktop** Runtime x86, this prompt will not pop up when starting the application.

Moreover, the download link used for guidance is too slow and not as fast as the official Microsoft link.

**Comment by Sewer56** [comment]
> Moreover, the download link used for guidance is too slow and not as fast as the official Microsoft link.

The code for getting the download link is here:
- https://github.com/Sewer56/NetCoreInstallChecker/blob/901e09680e8b8e2ac929190b4c5f5c74064c4b5a/NetCoreInstallChecker/NetCoreInstallChecker/FrameworkDownloader.cs#L95

This code is based on the official Microsoft [dotnet-install](https://github.com/dotnet/install-scripts/blob/main/src/dotnet-install.ps1) powershell script, which uses an API hosted on Azure. You can find the same logic in the original PowerShell script [here](https://github.com/dotnet/install-scripts/blob/8b3dcd913824ec6ba098fa91d324b5babe428404/src/dotnet-install.ps1#L615).

If you experienced any issues with speed, chances are, it's on Microsoft's part.
In any case, I'm curious, was it serving you the wrong runtime? I think the link Reloaded gave you is probably still in your browser history.

**Comment by Sewer56** [comment]
(Closing as 'stale' and/or invalid)
