### ISSUE TITLE
Documentation: <X> net9

### ISSUE THREAD

**Issue by Klemci** [Reloaded-Project/Reloaded-II#333]
**Is your request related to a feature? Please describe.**
I just ask myself...
e.g. 
- **X** feature is not well documented.
- That's the app i seen the most quickly switch to new netCore versions, since 3.1 (that i know about)
- x64

**Describe the solution you'd like**
So, seeing the [net9 preview](https://dotnet.microsoft.com/en-us/download/dotnet/9.0), i'm thinkeg about : when RLD-II will use the newest binaries ?.. and MS, will they update versions again often ?

**Additional context**
Thanks for the answer.

**Comment by Sewer56** [comment]
I forgot to respond to this.

The answer is, on Release Candidate 1 (RC1). These usually release around 2 months before the full runtime release, with future updates only containing bug fixes. Shipping Previews to end users is a bit risky, Reloaded does some low level things that either aren't officially supported or are very uncommonly used per se. I've had bugs and changes appear in the past in Previews which caused things to break. 

For instance, if I recall correctly, one situation was that when .NET 5 was in Preview, the update from Preview 8 to RC1 (IIRC) broke running the WPF Launcher UI as single EXE, so I had to undo that change before shipping. If an end user happened to install RC1 and run that build, it won't work, even though Preview 8 had no issues there.

I usually test Reloaded on previews from time to time, so there usually isn't a delay when it comes to shipping.

The only potential delay for shipping .NET 9 is if [FileEmulationFramework](https://github.com/Sewer56/FileEmulationFramework) breaks. Some games rely on this extensively, but it's also a ticking timebomb as hooking OS functions from .NET has become unsafe to do, and certain hooks may break on any major .NET runtime update (e.g. .NET 8 to .NET 9). In that case, I'd remain on 8 until FileEmulationFramework is ported to Rust.
