### ISSUE TITLE
Unable to add XGP games

### ISSUE THREAD

**Issue by THECODE-MASTER** [Reloaded-Project/Reloaded-II#334]
I just had one simple question, according to the latest release what i understand from it is that u can now directly add game pass games to reloaded 2 without dumping them but when i tried to do it for persona 3 reload it told me that it failed to open the file. So how can i add xgp games to reloaded 2 or do i still have to dump them?

**Comment by Sewer56** [comment]
Record your screen of adding a GamePass game, I'm curious to see what you get.

It should work out of the box without needing to dump or do anything at all, but as this is a multi-step process that relies on external code (and is thus very error prone), some bugs may still exist.

**Comment by THECODE-MASTER** [comment]
https://filebin.net/4djqwgjgwde4mmbb

**Comment by Sewer56** [comment]
Ah, pain.
Gimme till Friday, I'll make some test versions then.

**Comment by THECODE-MASTER** [comment]
I think Im being stupid. I was trying to just directly select the exe file in the xbox games folder. I thought that was what I needed to do. What is the procedure exactly to add an XGP game

**Comment by Sewer56** [comment]
That is exactly the procedure. You got a silent error though, so it's unclear why things are failing. 

As I don't do logging in the launcher, and cleanup during that operation; it's hard to tell what went wrong, so I'll need to make some test builds with test messages.

**Comment by THECODE-MASTER** [comment]
I got an error before when trying to update the application path. But i think it was basically the drm protection talking.
Sending a screen recording: https://filebin.net/4djqwgjgwde4mmbb/Recording_2024-03-13_114907.mp4

**Comment by Sewer56** [comment]
Yeah, that happens due to the copy protection preventing reads. Unfortunately.

**Comment by THECODE-MASTER** [comment]
I get it, debugging is one of the hardest things in the world and that's when you are only dealing with your code. You are dealing with intentionally hard to crack anti-piracy protection and working against code you haven't even seen fully.

**Comment by THECODE-MASTER** [comment]
> Yeah, that happens due to the copy protection preventing reads. Unfortunately.

Were you able to come up with a solution?

**Comment by Sewer56** [comment]
No. For now, I've been resting this weekend.
It's been a really, really, really long time since I've had a rest.

**Comment by THECODE-MASTER** [comment]
Ok np

**Comment by Sewer56** [comment]
I changed the approach for this a bit in 1.26.1, I'm curious if it resolves the issue on your end.

**Comment by THECODE-MASTER** [comment]
Ok I will check

**Comment by Sewer56** [comment]
Note: 1.26.1 is still building (I didn't expect a reply so soon).
Give it ~10 mins to release.

**Comment by THECODE-MASTER** [comment]
Ya no problem, I just got an email so that’s why the reply was quick

**Comment by THECODE-MASTER** [comment]
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/63726176/96faa844-df31-4c41-906d-4b22f1492f58)
This file is present in all of your releases

**Comment by THECODE-MASTER** [comment]
Can you confirm if this file is legit

**Comment by Sewer56** [comment]
It's a dummy program I wrote for 1.26.0

https://github.com/Sewer56/replace-files-with-itself

It just copies and renames files https://github.com/Sewer56/replace-files-with-itself/blob/main/src/main.rs nothing else. No idea why it would get false flagged by an antivirus.

**Comment by THECODE-MASTER** [comment]
Its because of the name, it sounds like a worm which replaces all files in the system with itself

**Comment by Sewer56** [comment]
I suppose that might be true, haha. Though in this context it's replacing a file with the same file.

**Comment by THECODE-MASTER** [comment]
My windows system won't even let it run, i think what might have happened in the old release would have been that windows might have secretly qurantined it and when i tried to add a file the app would have gotten stuck in the process as it wouldnt have been able to find the file, cause ig there might be no timeout for the process freezing reloaded 2

**Comment by Sewer56** [comment]
I imagine that was very possibly the case if you're getting a false positive now, yeah. A false positive on previous version.

**Comment by THECODE-MASTER** [comment]
Maybe name it gameconexecuter.exe, anyway it WORKED

**Comment by Sewer56** [comment]
👌
