### ISSUE TITLE
Help: How to fully uninstall Reloaded - II <X>

### ISSUE THREAD

**Issue by Fvngus** [Reloaded-Project/Reloaded-II#335]
Hi, i uninstalled the program but my games is still stuck with Reloaded version. how do i revert my game back to normal? Thanks

![image_2024-03-12_221942569](https://github.com/Reloaded-Project/Reloaded-II/assets/163150803/d7bc3637-4ea8-4296-b08c-932de6741689)

**Comment by Sewer56** [comment]
Given the frequency of questions asking 'how to uninstall' is roughly as common as 'Steam broke my controller and I can't use it anywhere else', I guess for now, I'll revert the change in 1.26.0 that auto deploys stub.
