### ISSUE TITLE
[User Has issues running on a NAS, hasn't responded yet]

### ISSUE THREAD

**Issue by KyleStilkey** [Reloaded-Project/Reloaded-II#337]
It looks like this doesn't support network paths very well. I see a few years ago a small change was to change how pathing for drives was worked but maybe it wasn't pushed or was reverted back?

I am testing with SH3 and when I run it locally on my drive no problems, when I go to use this with a network drive (like a NAS) it fails to load.

I can go in and edit the pathing manually from the UNC\192.168.1.147\Retail-Games\KONAMI\SILENT HILL 3 to W:\KONAMI\SILENT HILL 3 and it works kinda.

Once I go to start a new game it crashes and looking into the logs I can see it's
 still trying to override using the UNC\ path style which I think is causing issues, testing again locally the game will load a new game no problem at all.

I will provide the crash logs too. [Crash.zip](https://github.com/Reloaded-Project/Reloaded-II/files/14576918/Crash.zip)

https://github.com/Reloaded-Project/Reloaded-II/issues/56

Here is the previous issue I saw on the Github for reference.

**Comment by Sewer56** [comment]
Can you give me the following info:
- When you update path to game in launcher (`Edit Application` -> `Update`), which location do you get?
- Reupload the logs.

GitHub is having issues right now (unfortunately), and the last log upload got borked.

In the past the issue with NAS was symlinks, Reloaded used EXE path to determine which profile to select. Unfortunately in some NAS setups, the user could select one path in the launcher, but the OS actually just made that a symlink to some hidden location. So back then I added symlink resolving to fix that.

I did touch that code in the last update a bit, but only to remove GamePass/MS Store config parsing, so shouldn't have changed in that end. I also added matching profile by EXE name if path couldn't be resolved as last resort, so things hopefully should have improved there.

Anyway curious to see what the error is.

**Comment by KyleStilkey** [comment]
> Can you give me the following info:
> 
> * When you update path to game in launcher (`Edit Application` -> `Update`), which location do you get?
> * Reupload the logs.
> 
> GitHub is having issues right now (unfortunately), and the last log upload got borked.
> 
> In the past the issue with NAS was symlinks, Reloaded used EXE path to determine which profile to select. Unfortunately in some NAS setups, the user could select one path in the launcher, but the OS actually just made that a symlink to some hidden location. So back then I added symlink resolving to fix that.
> 
> I did touch that code in the last update a bit, but only to remove GamePass/MS Store config parsing, so shouldn't have changed in that end. I also added matching profile by EXE name if path couldn't be resolved as last resort, so things hopefully should have improved there.
> 
> Anyway curious to see what the error is.

I was able to download the zipped file without issues here, check again see if any issues but I will look into my system soon again once I have a moment to.

When I add the exe it puts this as the path UNC\192.168.1.147\Retail-Games\KONAMI\SILENT HILL 3 when it should be W:\KONAMI\SILENT HILL 3\

**Comment by Sewer56** [comment]
Please reopen this issue if necessary.
