### ISSUE TITLE
Help: Issue with running Reloaded on Persona 5 Royal

### ISSUE THREAD

**Issue by twicemiku** [Reloaded-Project/Reloaded-II#339]
I only installed [this mod](https://gamebanana.com/mods/430624) and it worked the first time I ran the app. This happened on my second time running it with Reloaded, when I opened it through the Steam web shortcut instead of the Reloaded app's launch application.

**Screenshots**
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/163434930/18ee1efa-1033-4994-8831-e620344dbfc5)
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/163434930/4046b5d3-fffa-47ef-9d65-a83b7953f736)
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/163434930/a6062879-b307-46fe-bde3-cfd2e812adb9)

**Comment by Sewer56** [comment]
Hold my beer, I'll make a test build in a few hours, and we'll see what's up. Strange behaviour.

**Comment by twicemiku** [comment]
I finally have it working after 3 reinstalls of reloaded. I don't know what was happening but it's been running every boot so far, though I haven't launched it with the web shortcut yet.

**Comment by Sewer56** [comment]
Am I fine to close this?

**Comment by twicemiku** [comment]
Oh, sure. I haven't had problems anymore so far.
