### ISSUE TITLE
[More Info Needed] Loader Config Corruption

### ISSUE THREAD

**Issue by SputnikMan123** [Reloaded-Project/Reloaded-II#34]
Every time I open up Reloaded, this weird error keeps opening up. I don't know exactly why this keeps on happening. I've downloaded all the prerequisites and ran it as an admin. Here's a screenshot of the error below:

![image](https://user-images.githubusercontent.com/68884141/88612520-4148dd00-d040-11ea-8af4-31dcb45d3fc9.png)

**Comment by Sewer56** [comment]
This means that your loader config is somehow corrupted.
Not really sure how that could happen, but since the initial release a year ago, this is only the 3rd time I've seen so far.

You should be ok if you delete `%appdata%/Reloaded-Mod-Loader-II/ReloadedII.json`

**Comment by Sewer56** [comment]
There's a workaround for this issue in the latest version (releasing this week?); albeit it will reset the loader config.
It's still unknown what causes this.

**Comment by Sewer56** [comment]
After longer than a year and nobody knowing how to reliably reproduce this but, this is finally fixed with 24d33f4033e65de08350b266b5bc7f5cb3ae2267 .
