### ISSUE TITLE
mods not loading in P3R

### ISSUE THREAD

**Issue by nonsmarts** [Reloaded-Project/Reloaded-II#340]
I saved a mod set created in reloaded 2 to the win64 folder (where it automatically takes you when you click "save mod set" but when I launch the game it gives me an error screen about reloaded 2 being unable to find dependencies for the mods. Anyone know what might be wrong?

**Comment by Sewer56** [comment]
Post the error, or a screenshot of it. I'll get you sorted.

**Comment by nonsmarts** [comment]
> Post the error, or a screenshot of it. I'll get you sorted.

Sorry about the late reply but here it is
![IMG_20240319_163733488_HDR](https://github.com/Reloaded-Project/Reloaded-II/assets/163785143/4a7ab461-96c9-41f3-8df9-75120ec50b94)

**Comment by Sewer56** [comment]
Paste this into your browser

`r2:https://gamebanana.com/mmdl/1153141`

And you should be good

**Comment by nonsmarts** [comment]
What folder should I put it in?

**Comment by nonsmarts** [comment]
> Paste this into your browser
> 
> `r2:https://gamebanana.com/mmdl/1153141`
> 
> And you should be good

What folder does it go in?

**Comment by Sewer56** [comment]
It should give you a dialog to open with Reloaded-II in your browser.
If you accept, it will auto download and install the mod.

**Comment by nonsmarts** [comment]
> It should give you a dialog to open with Reloaded-II in your browser. If you accept, it will auto download and install the mod.

I've tried using the link multiple times and it keeps opening a download window and eventually telling me the download is complete but then whenever I open up reloaded I keep getting notifications that I have missing dependencies and when I try to start p3r it gives me the same error

**Comment by Sewer56** [comment]
Can you post your current log? Maybe you're missing some other things.

**Comment by nonsmarts** [comment]
> Can you post your current log? Maybe that was resolved and now you're missing some other things.

![Annotation 2024-03-20 205845](https://github.com/Reloaded-Project/Reloaded-II/assets/163785143/a0b789b5-aa2a-485b-9c59-06ede3a3a608)

**Comment by Sewer56** [comment]
Here, use this

`r2:https://gamebanana.com/mmdl/1153141`

And you should be good.

**Comment by nonsmarts** [comment]
> Here, use this
> 
> `r2:https://gamebanana.com/mmdl/1153141`
> 
> And you should be good.

that worked perfectly.  thanks
