### ISSUE TITLE
About uninstallation of mods in persona 5 royal

### ISSUE THREAD

**Issue by ThoughtfulChild** [Reloaded-Project/Reloaded-II#342]
To uninstall mods, do you just delete the reloaded 2 folder and Reloaded.Mod.Bootstrapper.asi and your game goes back to normal? or do the mods modify the game's folder? i want to start a fresh new playthough and i want to make sure there arent any mods

**Comment by Sewer56** [comment]
Mods shouldn't modify the game folder. There's only 1 mod that I know which currently does, and it's the 'Manager' mod for Granblue.

Therefore, just deleting the ASI file should be sufficient to get an unmodded experience.

**Comment by ThoughtfulChild** [comment]
got it, thanks!

**Comment by Sewer56** [comment]
Historically Reloaded won't touch the game folder at all, but with 1.26.0, the default is to use ASI Loader. 

This is just to garner feedback from end users, and may be reverted in the future.

For now, the purpose of this experiment is to gauge whether `I want my mods to run when I boot from Steam` vs `I want to uninstall the loader` will be the more common support request.

Historically there have been people who can't use their controllers outside of Steam whatsoever (unfortunately), so the experiment is there to gauge whether the tradeoff of `harder uninstall` vs `can't use controller` is worthwhile keeping.
