### ISSUE TITLE
Unable to find dependencies P5R (Persona Essentials active)

### ISSUE THREAD

**Issue by DerKlassiker91** [Reloaded-Project/Reloaded-II#343]
When I try to launch the game I get an error.

![image](https://github.com/Reloaded-Project/Reloaded-II/assets/142808775/7f47ba84-7de2-4682-972a-0d63b62eae4e)

![image](https://github.com/Reloaded-Project/Reloaded-II/assets/142808775/315b1b1c-c1e7-41b2-92f4-2b822db0b9bb)

These are the only mods that are active:

![image](https://github.com/Reloaded-Project/Reloaded-II/assets/142808775/b8fec72f-e51a-439d-ad3d-741eb71e3144)

If I deactivate "Persona Essentials" it works fine. Tried to reinstall Reloaded II and downloaded the Release Zip but it keeps throwing that error.
Any help would be appreciated.

**Comment by Sewer56** [comment]
Did the issue resolve itself for you? I'm guessing it was maybe GitHub rate limits.

**Comment by DerKlassiker91** [comment]
Yes. Seems like it was a problem with leftover ReShade files. I deleted the whole P5R folder and reinstalled it and it works now.

**Comment by Sewer56** [comment]
No, this was a missing dependencies problem.
More likely, your IP address exhausted the 60/hour API calls GitHub allows, and it couldn't download the dependencies on the first time.

And somehow you couldn't connect with my server which acts as backup.

**Comment by DerKlassiker91** [comment]
Ah. Ok. I see. Then it was just a wierd coincident that deleting and reinstalling seemd to fix ist. Good to know if something like this happens again. Thanks for the help ^^
