### ISSUE TITLE
Can't load P5R through Reloaded II

### ISSUE THREAD

**Issue by lolDayus** [Reloaded-Project/Reloaded-II#344]
Basically I've had this work before but had to redo my entire installation and now no matter what I do I get the following when I try to run my modded P5R through Reloaded II. I've tried reinstalling the game, Reloaded, the mods etc. but there always seems to be some issue with this BF Emulator for File Emulation Framework

![image](https://github.com/Reloaded-Project/Reloaded-II/assets/103860125/ed079af9-a07e-4ac2-a621-70d46ab7ffea)

**Comment by Sewer56** [comment]
Try a clean install:

`r2:https://github.com/Sewer56/FileEmulationFramework/releases/download/2.7.0/BF.File.Emulator1.1.2.7z`
`r2:https://github.com/Sewer56/Reloaded.SharedLib.Hooks.ReloadedII/releases/download/1.16.1/Reloaded.Hooks.ReloadedII1.16.1.7z`

Paste these into your browser and accept the prompt to download with the launcher.

**Comment by lolDayus** [comment]
ok yeah I think that fixed it, thanks
