### ISSUE TITLE
Help: Getting "Failed to Load Reloaded-II" in Persona 3 Reload

### ISSUE THREAD

**Issue by Antichthon47** [Reloaded-Project/Reloaded-II#349]
I get the following error when trying to run P3R via Reloaded. I've installed all the dependencies with the Persona Prerequisite installer. I had the mods working a few days back, but it stopped working after I reinstalled the game and Reloaded-II. All the mod versions are up to date. I'm running the GamePass version.

![image](https://github.com/Reloaded-Project/Reloaded-II/assets/100145522/f9d396a7-ff7f-4ace-9d57-4522dc214c69)

The latest log is attached below: 

[2024-03-25 09.02.33 ~ P3R.txt](https://github.com/Reloaded-Project/Reloaded-II/files/14741273/2024-03-25.09.02.33.P3R.txt)

These are how the mods look: 
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/100145522/6acd0ff6-4a49-4f44-a7ff-d7cf890291f3)

**Comment by Sewer56** [comment]
The really weird part about this whole situation is:

- Game is x64
- Mod is x64 only

Yet somehow Windows throws an error as if there was a mismatch

**Comment by Antichthon47** [comment]
> The really weird part about this whole situation is:
> 
> - Game is x64
> - Mod is x64 only
> 
> Yet somehow Windows throws an error as if there was a mismatch

Yep. You're right. I thought maybe it was something with the dependencies and reinstalled them as well, but no avail.

**Comment by Antichthon47** [comment]
I wiped the Windows and installed Windows 10 x64. Also reinstalled game and Reloaded-II, but mods are still not working. Am met with 'stuff won't work'

[2024-03-26 05.05.44 ~ P3R.txt](https://github.com/Reloaded-Project/Reloaded-II/files/14752760/2024-03-26.05.05.44.P3R.txt)

**Comment by Antichthon47** [comment]
> I wiped the Windows and installed Windows 10 x64. Also reinstalled game and Reloaded-II, but mods are still not working. Am met with 'stuff won't work'
> 
> [2024-03-26 05.05.44 ~ P3R.txt](https://github.com/Reloaded-Project/Reloaded-II/files/14752760/2024-03-26.05.05.44.P3R.txt)
> 

It was just the permissions. After fixing the permissions, still get the same error.

**Comment by Sewer56** [comment]
This is strange. 

Can you post your mod list and the very latest error? I'm curious if it'd happen on my machine.

**Comment by Sewer56** [comment]
@Antichthon47 bump

**Comment by Sewer56** [comment]
Closing as 'stale'
