### ISSUE TITLE
Won't Run/Open at all after installing dependencies 

### ISSUE THREAD

**Issue by SmoothEnigma** [Reloaded-Project/Reloaded-II#35]
I've installed, Uninstalled, and Reinstalled all dependencies multiple times, restarting my computer each time and trying running both with and without admin privileges and it just doesn't open at all. As far as I can see when looking at task manager the program isn't even crashing cause it isn't opening in the first place. I'm desperate for advice. I've seen others online post this issue elsewhere and no responses besides "make sure you've installed all the dependencies" has been given, which as I've made clear I have certainly done.

**Comment by SmoothEnigma** [comment]
Went and installed  .NET SDK (64 Bit) which isn't listed in the requirements but that fixed the issue if anyone else runs into this problem

**Comment by Sewer56** [comment]
I forgot to respond, big oopsie.
Still worth asking, where did you download the program from? All official download pages include hyperlinks directly to each requirement needed and they have been placed as close to the actual download button as the sites allow.

Normally you'd need x64 Desktop Runtime and x86 Desktop Runtime.
x64 is required for launcher and 64-bit games while x86 is required for 32-bit games.

**Comment by SmoothEnigma** [comment]
https://dotnet.microsoft.com/download/dotnet-core/3.1  here

**Comment by Sewer56** [comment]
@SmoothEnigma  I actually meant Reloaded since every download page has direct hyperlinks to all required dependencies.

**Comment by SmoothEnigma** [comment]
https://github.com/Reloaded-Project/Reloaded-II/releases/tag/1.6.1  at the
bottom of the page below the bugfixes in the assets section download
release.zip

**Comment by Sewer56** [comment]
Hmm, I checked with a clean virtual machine; installing the linked dependencies (hyperlinks) on a clean windows 8.1 install does seem to work fine. Maybe you just missed the hyperlinks? Weird.
