### ISSUE TITLE
Persona 3 Reload fails to start, with no error present in logs 

### ISSUE THREAD

**Issue by Sparkles2025** [Reloaded-Project/Reloaded-II#351]
I recently installed the GamePass version of Persona 3 Reload, simply because I wanted to mod it. Everything was running perfectly, and then I stopped playing for about 3 days (3/27/23 was when everything was last used). Today, after my Reloaded-II updated to 1.27.1, P3R won't open. The command window pops up as normal, and nothing seems amiss, but eventually it closes itself and no processes remain open, no error pop-up. The logs from these shut downs show no errors or anything, and all just stop after loading my last mod. I've tried whatever I thought could work, but nothing I did made a change.

This is my most recent attempt's log:
[2024-03-31 01.17.37 ~ P3R.txt](https://github.com/Reloaded-Project/Reloaded-II/files/14813767/2024-03-31.01.17.37.P3R.txt)

My mods are set up as such:
![First image](https://github.com/Reloaded-Project/Reloaded-II/assets/165530321/ffc63871-c65a-4190-aeed-5fd1246e14a9)
![Second image](https://github.com/Reloaded-Project/Reloaded-II/assets/165530321/58266f46-01f9-496a-84f2-ec85fcf109e0)

This is my first experience with modding, so if I happened to make some simple mistake, I apologize. Thanks!

**Comment by Sewer56** [comment]
Don't sweat it.

> The command window pops up as normal, and nothing seems amiss

Can you record the screen? Maybe there's something useful in the log in the window before it dies.

**Comment by Sparkles2025** [comment]
If you need me to take another and full-screen the command window, I can do that as well.
https://github.com/Reloaded-Project/Reloaded-II/assets/165530321/89ea766b-f838-4643-973b-80fc91bda4ab

Seeing the video, there does seem to be some errors before the window shuts down... Unsure what I would do about them

**Comment by Sewer56** [comment]
This game got an update this week, which led to one or two code mods breaking.

![20240331_03h07m07s](https://github.com/Reloaded-Project/Reloaded-II/assets/6697380/5d94e361-5611-420a-9fc7-7f0a5087da6c)

Unfortunately the log doesn't capture it, but the footage has an error printout.
Some memory address in some mod is wrong.

I'd suggest hitting `Save Mod Set`, and then turning off mods one by one until you find the culprit. Then report it to the mod author.

**Comment by Sparkles2025** [comment]
Culprit located! Thankfully, it was a minor mod that simply added music to the config menu. Thanks for your help!

**Comment by Sewer56** [comment]
Make sure to let the mod author know 👍.

**Comment by Sparkles2025** [comment]
Handled!
