### ISSUE TITLE
Help:  There is a fatal error when launching a game from reload II

### ISSUE THREAD

**Issue by Ppat69** [Reloaded-Project/Reloaded-II#355]
MMMMMMMMMMMMMMMMMMdo`        hMMM+ +MMMh
                                        MMMMMMMMMMMMMMMMMMMMh       `MMMM` dMMM/
                                        MMMM-          `yMMMN       +MMMh .MMMN`
                                        MMMM-          `sMMMN       dMMM/ sMMMy
                                        MMMM- .sMMMMMMMMMMMMd      -MMMN  NMMM:
                                        MMMM-   `sNMMMMMMMdo`      sMMMy :MMMm
                                        MMMM-     `oNMMMMy-        NMMM- yMMMo
                                        MMMM-       `oNMMMMh-     :MMMm `MMMM.
                                        MMMM-         `+mMMMMh:   yMMMo /MMMd
                                        MMMM-            /mMMMMd:`MMMM. dMMM+

                                                  1.27.1 // .NET 8.0.3

[Reloaded] Create Loader | Time: 27ms
[Reloaded] Loading 1 Mod(s).
[Reloaded]
[Reloaded] Loading: Reloaded II Shared Lib: Reloaded.Hooks
[Reloaded] - AppId   : reloaded.sharedlib.hooks
[Reloaded] - Location: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\reloaded.sharedlib.hooks\ModConfig.json
[Reloaded] - LoadTime: 5ms
[Reloaded] Loaded via: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Loader\x64\Bootstrapper\Reloaded.Mod.Loader.Bootstrapper.dll
[Reloaded] Current Process Location: D:\Steam\steamapps\common\P3R\P3R\Binaries\Win64\P3R.exe
[Reloaded] Loading 20 Mod(s).
[Reloaded]
[Reloaded] Loading: BGME Framework API
[Reloaded] - AppId   : BGME.Framework.API
[Reloaded] - Location: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\BGME.Framework.API\ModConfig.json
[Reloaded] - LoadTime: 13ms
[Reloaded]
[Reloaded] Loading: BGME Battle Themes
[Reloaded] - AppId   : BGME.BattleThemes
[Reloaded] - Location: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\BGME.BattleThemes\ModConfig.json
[BGME Framework API] [INF] Music script added.
[Reloaded] - LoadTime: 64ms
[Reloaded]
[Reloaded] Loading: Library: Reloaded.Memory.Sigscan for Reloaded II
[Reloaded] - AppId   : Reloaded.Memory.SigScan.ReloadedII
[Reloaded] - Location: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\Reloaded.Memory.SigScan.ReloadedII\ModConfig.json
[Reloaded] - LoadTime: 4ms
[Reloaded]
[Reloaded] Loading: Shared Scans
[Reloaded] - AppId   : SharedScans.Reloaded
[Reloaded] - Location: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\SharedScans.Reloaded\ModConfig.json
[Reloaded] - LoadTime: 7ms
[Reloaded]
[Reloaded] Loading: Ryo Framework
[Reloaded] - AppId   : Ryo.Reloaded
[Reloaded] - Location: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\Ryo.Reloaded\ModConfig.json
[Reloaded] - LoadTime: 17ms
[Reloaded]
[Reloaded] Loading: BGME Framework for P3R
[Reloaded] - AppId   : BGME.Framework.P3R
[Reloaded] - Location: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\BGME.Framework.P3R\ModConfig.json
[R-II SteamHook] SteamAPI_RestartAppIfNecessary hooked successfully.
[R-II SteamHook] SteamAPI_IsSteamRunning hooked successfully.
[R-II SteamHook] Found Steam Library Entry with Id 2161700. Dropping steam_appid.txt.
[Reloaded] Setting Up Hooks (Async) | Time: 134ms
[BGME Framework] [INF] Music loaded.
[Reloaded] - LoadTime: 79ms
[Reloaded]
[Reloaded] Loading: File Emulation Framework: Base Mod
[Reloaded] - AppId   : reloaded.universal.fileemulationframework
[Reloaded] - Location: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\reloaded.universal.fileemulationframework\ModConfig.json
Starting FileEmulationFramework
[Reloaded] - LoadTime: 30ms
[Reloaded]
[Reloaded] Loading: IO Store Emulator
[Reloaded] - AppId   : UTOC.Stream.Emulator
[Reloaded] - Location: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\UTOC.Stream.Emulator\ModConfig.json
[Reloaded] - LoadTime: 9ms
[Reloaded]
[Reloaded] Loading: Unreal Essentials
[Reloaded] - AppId   : UnrealEssentials
[Reloaded] - Location: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\UnrealEssentials\ModConfig.json
Starting UTOC.Stream.Emulator
[Reloaded] - LoadTime: 17ms
[Reloaded]
[Reloaded] Loading: Colorful Cut-ins
[Reloaded] - AppId   : p3rpc.ui.colorfulcutins
[Reloaded] - Location: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\colorful_cut-ins1_1_2_6896d\ModConfig.json
[Unreal Essentials] Loading files from C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\colorful_cut-ins1_1_2_6896d\idk
Setting root directory P3R to Game
[Unreal Essentials] Loading files from C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\colorful_cut-ins1_1_2_6896d\morbius\Regular Akihiko
Setting root directory P3R to Game
[Unreal Essentials] Loading files from C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\colorful_cut-ins1_1_2_6896d\morbius\Regular Koromaru
Setting root directory P3R to Game
[Reloaded] - LoadTime: 15ms
[Reloaded]
Setting root directory P3R to Game
[Reloaded] Loading: Easier Academics Social Stat
[Reloaded] - AppId   : p3rpc.balanceacademicsch
[Reloaded] - Location: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\easyacademicscharm100\ModConfig.json
[Unreal Essentials] Loading files from C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\easyacademicscharm100\UnrealEssentials
[Reloaded] - LoadTime: 1ms
[Reloaded]
Setting root directory P3R to Game
[Reloaded] Loading: Extended Outfits
[Reloaded] - AppId   : p3r.skins.extendedoutfits
[Reloaded] - Location: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\p3r.skins.extendedoutfits\ModConfig.json
[Unreal Essentials] Loading files from C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\p3r.skins.extendedoutfits\UnrealEssentials
[Reloaded] - LoadTime: 3ms
[Reloaded]
[Reloaded] Loading: Unreal Objects Emitter
[Reloaded] - AppId   : Unreal.ObjectsEmitter.Reloaded
[Reloaded] - Location: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\Unreal.ObjectsEmitter.Reloaded\ModConfig.json
[Reloaded] - LoadTime: 19ms
[Reloaded]
[Reloaded] Loading: Unreal Atlus Script
[Reloaded] - AppId   : Unreal.AtlusScript.Reloaded
[Reloaded] - Location: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\Unreal.AtlusScript.Reloaded\ModConfig.json
[Reloaded] - LoadTime: 129ms
[Reloaded]
[Reloaded] Loading: Costume Framework for P3R
[Reloaded] - AppId   : P3R.CostumeFramework
[Reloaded] - Location: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\P3R.CostumeFramework\ModConfig.json
[Reloaded] - LoadTime: 24ms
[Reloaded]
[Reloaded] Loading: Just-A-Phase Outfit Mod
[Reloaded] - AppId   : P3R.JustAPhaseOutfitMod
[Reloaded] - Location: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\just-a-phase_outfit_mod1_0_2\ModConfig.json
[Ryo (P3R)] [INF] Adding folder: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\just-a-phase_outfit_mod1_0_2\bgme\p3r
[Ryo (P3R)] [INF] Assigned Cue: 4000 || ACB: bgm
File: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\just-a-phase_outfit_mod1_0_2\bgme\p3r\4000.hca
[Ryo (P3R)] [INF] Assigned Cue: 4001 || ACB: bgm
File: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\just-a-phase_outfit_mod1_0_2\bgme\p3r\4001.hca
[Ryo (P3R)] [INF] Assigned Cue: 4002 || ACB: bgm
File: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\just-a-phase_outfit_mod1_0_2\bgme\p3r\4002.hca
[Ryo (P3R)] [INF] Assigned Cue: 4003 || ACB: bgm
File: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\just-a-phase_outfit_mod1_0_2\bgme\p3r\4003.hca
[Ryo (P3R)] [INF] Assigned Cue: 4004 || ACB: bgm
File: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\just-a-phase_outfit_mod1_0_2\bgme\p3r\4004.hca
[Ryo (P3R)] [INF] Assigned Cue: 4005 || ACB: bgm
File: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\just-a-phase_outfit_mod1_0_2\bgme\p3r\4005.hca
[Ryo (P3R)] [INF] Assigned Cue: 4006 || ACB: bgm
File: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\just-a-phase_outfit_mod1_0_2\bgme\p3r\4006.hca
[Ryo (P3R)] [INF] Assigned Cue: 4007 || ACB: bgm
File: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\just-a-phase_outfit_mod1_0_2\bgme\p3r\4007.hca
[Ryo (P3R)] [INF] Assigned Cue: 4008 || ACB: bgm
File: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\just-a-phase_outfit_mod1_0_2\bgme\p3r\4008.hca
[Ryo (P3R)] [INF] Assigned Cue: 4009 || ACB: bgm
File: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\just-a-phase_outfit_mod1_0_2\bgme\p3r\4009.hca
[Ryo (P3R)] [INF] Assigned Cue: 4010 || ACB: bgm
File: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\just-a-phase_outfit_mod1_0_2\bgme\p3r\4010.hca
[Ryo (P3R)] [INF] Assigned Cue: 4011 || ACB: bgm
File: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\just-a-phase_outfit_mod1_0_2\bgme\p3r\4011.hca
[Ryo (P3R)] [INF] Assigned Cue: 4012 || ACB: bgm
File: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\just-a-phase_outfit_mod1_0_2\bgme\p3r\4012.hca
[Ryo (P3R)] [INF] Assigned Cue: 4013 || ACB: bgm
File: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\just-a-phase_outfit_mod1_0_2\bgme\p3r\4013.hca
[Ryo (P3R)] [INF] Assigned Cue: 4014 || ACB: bgm
File: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\just-a-phase_outfit_mod1_0_2\bgme\p3r\4014.hca
[Ryo (P3R)] [INF] Assigned Cue: 4015 || ACB: bgm
File: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\just-a-phase_outfit_mod1_0_2\bgme\p3r\4015.hca
[BGME Framework API] [INF] Music script added.
[Unreal Essentials] Loading files from C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\just-a-phase_outfit_mod1_0_2\UnrealEssentials
Setting root directory P3R to Game
[Reloaded] [LoaderAPI] Warning: GetController<IReloadedHooks> returned null.
[Unreal Essentials] Loading files from C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\just-a-phase_outfit_mod1_0_2\Options\Menu-Swap\Swap
Setting root directory P3R to Game
[P3R.CostumeFramework] [INF] Costume created: Player || Costume ID: 1000 || Folder: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\just-a-phase_outfit_mod1_0_2\UnrealEssentials\P3R\Content\Costumes\Player\JustAPhaseOutfit
[P3R.CostumeFramework] [INF] Costume created: Yukari || Costume ID: 1001 || Folder: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\just-a-phase_outfit_mod1_0_2\UnrealEssentials\P3R\Content\Costumes\Yukari\JustAPhaseOutfit
[P3R.CostumeFramework] [INF] Costume created: Stupei || Costume ID: 1002 || Folder: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\just-a-phase_outfit_mod1_0_2\UnrealEssentials\P3R\Content\Costumes\Stupei\JustAPhaseOutfit
[P3R.CostumeFramework] [INF] Costume created: Akihiko || Costume ID: 1003 || Folder: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\just-a-phase_outfit_mod1_0_2\UnrealEssentials\P3R\Content\Costumes\Akihiko\JustAPhaseOutfit
[P3R.CostumeFramework] [INF] Costume created: Mitsuru || Costume ID: 1004 || Folder: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\just-a-phase_outfit_mod1_0_2\UnrealEssentials\P3R\Content\Costumes\Mitsuru\JustAPhaseOutfit
[P3R.CostumeFramework] [INF] Costume created: Fuuka || Costume ID: 1005 || Folder: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\just-a-phase_outfit_mod1_0_2\UnrealEssentials\P3R\Content\Costumes\Fuuka\JustAPhaseOutfit
[P3R.CostumeFramework] [INF] Costume created: Aigis || Costume ID: 1006 || Folder: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\just-a-phase_outfit_mod1_0_2\UnrealEssentials\P3R\Content\Costumes\Aigis\JustAPhaseOutfit
[P3R.CostumeFramework] [INF] Costume created: Ken || Costume ID: 1007 || Folder: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\just-a-phase_outfit_mod1_0_2\UnrealEssentials\P3R\Content\Costumes\Ken\JustAPhaseOutfit
[P3R.CostumeFramework] [INF] Costume created: Koromaru || Costume ID: 1008 || Folder: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\just-a-phase_outfit_mod1_0_2\UnrealEssentials\P3R\Content\Costumes\Koromaru\JustAPhaseOutfit
[P3R.CostumeFramework] [INF] Costume created: Shinjiro || Costume ID: 1009 || Folder: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\just-a-phase_outfit_mod1_0_2\UnrealEssentials\P3R\Content\Costumes\Shinjiro\JustAPhaseOutfit
[Reloaded] - LoadTime: 110ms
[Reloaded]
[Reloaded] Loading: Social Stat Tracker
[Reloaded] - AppId   : p3rpc.socialStatTracker
[Reloaded] - Location: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\p3rpc.socialStatTracker\ModConfig.json
[Reloaded] - LoadTime: 8ms
[Reloaded]
[Reloaded] Loading: Inaba Exe Patcher
[Reloaded] - AppId   : p4gpc.inaba
[Reloaded] - Location: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\p4gpc.inaba\ModConfig.json
[Reloaded] - LoadTime: 3ms
[Reloaded]
[Reloaded] Loading: Social Link + Hangouts Cheat Sheet
[Reloaded] - AppId   : p3rpc.misc.sociallinkcheatsheet
[Reloaded] - Location: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\social_link__hangouts_cheat_sheet1_3_2\ModConfig.json
[Unreal Essentials] Loading files from C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\social_link__hangouts_cheat_sheet1_3_2\UnrealEssentials
Setting root directory P3R to Game
[Reloaded] - LoadTime: 57ms
[Reloaded]
[Reloaded] Loading: Persona 3 Reload Essentials
[Reloaded] - AppId   : p3rpc.essentials
[Reloaded] - Location: C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\p3rpc.essentials\ModConfig.json
[Reloaded] - LoadTime: 7ms
[SharedScans] [INF] criAtomExPlayer_SetCueName found at: 143A0C68C
[SharedScans] [INF] Scan for "criAtomExPlayer_SetCueName" given to 2 listener(s).
[SharedScans] [INF] criAtomExPlayer_Start found at: 143A0CF34
[SharedScans] [INF] Scan for "criAtomExPlayer_Start" given to 1 listener(s).
[SharedScans] [INF] criManaPlayer_SetFile found at: 157B1D6D0
[SharedScans] [INF] Scan for "criManaPlayer_SetFile" given to 1 listener(s).
[Ryo (P3R)] [INF] criAtomExPlayer_Create found at: 143A0AF4C
[Ryo (P3R)] [INF] criAtomExPlayer_SetFormat found at: 143A0C930
[Ryo (P3R)] [INF] criAtomExPlayer_SetSamplingRate found at: 157997E78
[Ryo (P3R)] [INF] criAtomExPlayer_SetNumChannels found at: 157996670
[Ryo (P3R)] [INF] criAtomExPlayer_SetVolume found at: 143A0CF0C
[Ryo (P3R)] [INF] criAtomExPlayer_SetCategoryById found at: 143A0C55C
[Ryo (P3R)] [INF] criAtomExPlayer_SetData found at: 157993528
[Ryo (P3R)] [INF] criAtomExCategory_SetVolumeById found at: 143A09CD8
[Ryo (P3R)] [INF] criAtomExPlayer_UpdateAll found at: 143A0D638
[Ryo (P3R)] [INF] criAtomExPlayer_LimitLoopCount found at: 143A0BDE0
[Ryo (P3R)] [INF] criAtomExPlayer_GetStatus found at: 143A0B998
[Ryo (P3R)] [INF] criAtomExPlayer_Stop found at: 143A0D338
[Ryo (P3R)] [INF] criAtomExPlayer_SetAisacControlByName found at: 143A0C04C
[Ryo (P3R)] [INF] USoundAtomCueSheet_AsyncLoadCueSheetTask found at: 140D05A60
[Ryo (P3R)] [INF] GetCategoryVolumeByIndex found at: 143A08A08
[Ryo (P3R)] [INF] GetCategoryIndexFromId found at: 143A200BC
[BGME Framework] [INF] RequestSound found at: 1493A5670
[BGME Framework] [INF] Encounter BGM Hook found at: 1410175B4
[BGME Framework] [INF] UBtlCoreComponent_FadeoutBGM found at: 14100A6F0
[UtocEmulator] Found OpenContainer at 0x1416A8D20
[UE.Obj.Emitter] [INF] FGlobalNamePool found at: 1417D0F89
[UE.Obj.Emitter] [INF] FName Constructor found at: 1417C43B0
[UE.Obj.Emitter] [INF] FMemory_Malloc found at: 1416D5AF0
[UE.Obj.Emitter] [INF] FUN_142f283d0 found at: 143031260
[UE.Obj.Emitter] [INF] UObject Function_14197ffb0 (Called after initalized and ready) found at: 14196D290
[P3R.CostumeFramework] [INF] GET_PARTY found at: 1411E1D80
[P3R.CostumeFramework] [INF] UAppCharacterComp_Update found at: 1410301E0
[P3R.CostumeFramework] [INF] GET_ITEM_NUM found at: 14BAC29F0
[P3R Essentials] Found SetupWindow at 0x141A190C0
[P3R Essentials] Found Intro Skip at 0x1414EED80
[P3R Essentials] Found Caution Skip at 0x1414EE7B0
################################################################################
                  ASSET COLLECTOR: Collected files from 8 mods
================================================================================
C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\colorful_cut-ins1_1_2_6896d\idk
12 directories added
9 added files (9222 KB)
0 replaced files (0 KB)
================================================================================
C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\colorful_cut-ins1_1_2_6896d\morbius\Regular Akihiko
12 directories added
1 added files (1024 KB)
0 replaced files (0 KB)
================================================================================
C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\colorful_cut-ins1_1_2_6896d\morbius\Regular Koromaru
12 directories added
1 added files (1024 KB)
0 replaced files (0 KB)
================================================================================
C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\easyacademicscharm100\UnrealEssentials
5 directories added
1 added files (0 KB)
0 replaced files (0 KB)
================================================================================
C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\p3r.skins.extendedoutfits\UnrealEssentials
19 directories added
3 added files (48 KB)
0 replaced files (0 KB)
================================================================================
C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\just-a-phase_outfit_mod1_0_2\UnrealEssentials
23 directories added
334 added files (302870 KB)
0 replaced files (0 KB)
================================================================================
C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\just-a-phase_outfit_mod1_0_2\Options\Menu-Swap\Swap
7 directories added
3 added files (4199 KB)
0 replaced files (0 KB)
================================================================================
C:\Users\portp\OneDrive\Asztali gép\Reloaded-II\Mods\social_link__hangouts_cheat_sheet1_3_2\UnrealEssentials
238 directories added
230 added files (1105 KB)
0 replaced files (0 KB)
================================================================================
Fatal error. System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
Fatal error while logging another fatal error.
Fatal error while logging another fatal error.

**Comment by Sewer56** [comment]
This involves a lot of components I'm not personally familiar with.
Open an issue in the Persona Modding Discord instead 

https://discord.com/invite/naoto

Game got recently updated, maybe it's an out of date code mods. I won't know though.
