### ISSUE TITLE
Anerror occured while trying to load Reloaded-II '0x00' is an invalid start of a value

### ISSUE THREAD

**Issue by daneobyrd** [Reloaded-Project/Reloaded-II#36]
I continue to get this error pop-up saying Reloaded-II has failed to load. I have un/reinstalled all dependencies from the correct links multiple times but this continues to happen. I am choosing to run the program as an administrator as well.

This is extremely frustrating as I just want to use a few mods for Persona 4 Golden on Steam.
<img width="698" alt="oof" src="https://user-images.githubusercontent.com/38336138/89718846-1b98cd80-d988-11ea-9af4-491e20477df0.PNG">

**Comment by Sewer56** [comment]
See: #34 
It's unknown what causes this and extremely rare.
Can add a workaround but I personally would like to know what causes it too.

Can you maybe retrace any steps? Launcher ever crash? etc.
Please continue conversation in the other issue.
