### ISSUE TITLE
Help: Cannot run Reloaded II.exe

### ISSUE THREAD

**Issue by shadowserf** [Reloaded-Project/Reloaded-II#361]
I ran the program just fine on my external harddrive before I wanted to move the program to my internal drive. Now I cannot open the ReloadedII.exe app file despite running the setup.exe twice. Whenever I click on the shortcut or open the app directly from the folder, I will get the blue windows loading circle, but nothing opens up. I have also checked task manager to make sure it was running in the background. I am unsure of how to fix this issue and unfortunately I am not able to go back to the external harddrive. Any assistance would be appreciated!

**Comment by Sewer56** [comment]
- Go to Reloaded folder.
- Shift+Click somewhere in empty space.
- Open in CMD (or PowerShell)
- Run command `dotner Reloaded-II.dll`

Screenshot the output.

[Sorry for concise post, I should be sleeping]

**Comment by shadowserf** [comment]
Perfectly fine if you need sleep. I'm no good with the whole running commands in powershell. Nothing happens when I shift click within the reloaded folder. Is there supposed to be a pop-up?

**Comment by Sewer56** [comment]
Ah, shift+right click, my bad.

**Comment by shadowserf** [comment]
Hopefully that helps? I tried getting all of the message in a single snip.

**Comment by Sewer56** [comment]
Try deleting the `ReloadedII.json` file in `%appdata%/Reloaded-Mod-Loader-II`.

Paste that folder path into address bar of explorer.

**Comment by shadowserf** [comment]
Hey, feel free to take your time. My external is busted, so I was really just seeing if it was possible y'know? Also, I managed to find 2 JSON files through pasting that folder path. There is a deps.json and a runtimeconfig.json. Either of these the one I need to delete?

**Comment by shadowserf** [comment]
Nah, wait a sec. I see it. Just go ahead and get rid of the ReloadedII.json then. Got it.

**Comment by shadowserf** [comment]
I think we should be good. I got the thing to open up anyway.

**Comment by shadowserf** [comment]
Yep. We're all good here. Hey, thanks for the help seriously. I honestly didn't think making an account would get me anywhere lol. I'll be sure to give you a sponsor by Friday after I get paid. Something monthly maybe. You deserve it y'know. Anyway, keep up the good work!

**Comment by Sewer56** [comment]
Yup, certainly a bug for me to fix though.

I've just been fixing bugs left and right, while I work on planning the successor over at https://reloaded-project.github.io/Reloaded-III/

(WIP documentation)

**Comment by Sewer56** [comment]
Although I'm not entirely sure of the underlying issue (I poked around the code to try guess), I did go out of the way to make sure that in the future, you get a user friendly error message today. So hopefully that helps avoid the issue in the future.
