### ISSUE TITLE
Getting Error when trying to launch P3R

### ISSUE THREAD

**Issue by NormalAleister2** [Reloaded-Project/Reloaded-II#362]
I am getting an error message every time I try to open a modded Persona 3 Reload. I have uninstalled and reinstalled Reloaded II and I get the same message. Is there a way to fix this? 

![image](https://github.com/Reloaded-Project/Reloaded-II/assets/153869482/56127fab-0edb-4545-8015-1e35688f790b)

thanks

**Comment by NormalAleister2** [comment]
I am able to start a game normally through steam. The game version is whatever the latest one is.

**Comment by Sewer56** [comment]
What a strange situation. I'm thinking right now, but can't come up with a reason as to why the game would die during startup before even running any code, as seen in the initial post.

**Comment by NormalAleister2** [comment]
I could try and redo the prerequisite installer that you have to download

**Comment by NormalAleister2** [comment]
Ok I just reinstalled everything and it works now
