### ISSUE TITLE
Error When Trying to Select an Application

### ISSUE THREAD

**Issue by KakoLykos** [Reloaded-Project/Reloaded-II#364]
When I run Reloaded II to try to patch Persona 3 Portable, I keep getting this error pop-up
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/167529097/453fc883-6232-4b9b-ab14-7ea03fd3a8ab)
Meanwhile, as this screenshot shows, the file path in question very much exists
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/167529097/8e9f5245-0523-4565-b267-04b3a77e167c)
Any help on this matter would be greatly appreciated.

**Comment by KakoLykos** [comment]
Nevermind, I'm just dumb. After sitting around for a while, I finally thought to run the app as administrator and suddenly my problems vanished.

**Comment by Sewer56** [comment]
I just woke up.

I think the caveat here is you out Reloaded in a place that requires Admin access to execute files from. So when not running as Admin, it couldn't do that.

(Note: Reloaded is usually installed in some directory owned by the current user)
