### ISSUE TITLE
Reloaded II opens Sonic Heroes fine but the mods don't show.

### ISSUE THREAD

**Issue by ZionJames97** [Reloaded-Project/Reloaded-II#366]
The Game runs off Reloaded II but it acts if though I didn't install the mods.

**Comment by Sewer56** [comment]
Can you provide a log file?

Or even a screenshot of the 'Console' window that pops up when the game starts.

**Comment by ZionJames97** [comment]
![21 4 24](https://github.com/Reloaded-Project/Reloaded-II/assets/93690938/82c49d30-62d7-4716-a948-741b3f561b0d)

**Comment by Sewer56** [comment]
Two things:

1. It's not recommended to put Reloaded in your game folder. Though I guess it's a bit too late for that.

2. Whoever made the mods you're running forgot to set a dependency on `reloaded.universal.redirector` a.k.a. (Reloaded File Redirector). This error is on the mod authors' side.
