### ISSUE TITLE
Help: Please help me with finishing to install Reload

### ISSUE THREAD

**Issue by RaccoonBoyy** [Reloaded-Project/Reloaded-II#371]
I'm trying to install Reloaded as the title says. I'm almost done with it i practically am but there's a pop up that keep appearing when I do.
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/168737284/a5149b34-89e8-48f5-b8a9-940274757666)

I've done what it says and downloaded the net core yet it still pops this up. Is this particularly needed or can I simply skip it?

**Comment by Sewer56** [comment]
Have you installed an ancient version by chance?
I'm not really sure why it'd request .NET 5.

Try the latest [Setup.exe](https://github.com/Reloaded-Project/Reloaded-II/releases/download/1.27.5/Setup.exe)

**Comment by RaccoonBoyy** [comment]
> Have you installed an ancient version by chance? I'm not really sure why it'd request .NET 5.
> 
> Try the latest [Setup.exe](https://github.com/Reloaded-Project/Reloaded-II/releases/download/1.27.5/Setup.ex

**Comment by Sewer56** [comment]
There's an x86 install and x64 one, you need to download and install both.

Normally the setup automatically installs them for you though.

Where the confusion came from, is the fact that it asked for .NET 5 specifically. Reloaded hasn't been using .NET 5 for around 2 years now, so I was thinking you maybe had some very old download.

**Comment by RaccoonBoyy** [comment]
Alright though apologies for so many questions since this is my first time doing anything related to the Reloaded software but how can I change the .NET version from 5 to the newest one?

**Comment by Sewer56** [comment]
They install side by side. If you install 8, you'll have both 8 and 5.

**Comment by RaccoonBoyy** [comment]
Alright I will try this ^^ I'm pretty sure i have downloaded some wrong files but thank you!

**Comment by RaccoonBoyy** [comment]
I came to update on the issue, The reason it showed 5.0 was because i downloaded an older 5.0 file for the application. I uninstalled the 5.0 to see what'd happen and it showed this issue which was the one i was having from the start even before the one I posted about.

![image](https://github.com/Reloaded-Project/Reloaded-II/assets/168737284/c1444f80-29fe-444b-94b4-16dd3c14edf7)

Could someone help with this issue as well?

**Comment by Sewer56** [comment]
I'm not really sure why you couldn't use Setup.exe

> Have you installed an ancient version by chance? I'm not really sure why it'd request .NET 5.
> 
> Try the latest [Setup.exe](https://github.com/Reloaded-Project/Reloaded-II/releases/download/1.27.5/Setup.exe)

Anyway, if you want to manual install, get the two runtimes listed here

https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-8.0.4-windows-x64-installer
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-8.0.4-windows-x86-installer

If you clicked `yes`, it would have installed the first of the 2, and the launcher would have installed the other for you.

**Comment by RaccoonBoyy** [comment]
It worked! Thank you so much :D

**Comment by Sewer56** [comment]
No worries, have fun.
