### ISSUE TITLE
[Reloaded-II Should have a Retry Policy in case of Unreliable Servers]

### ISSUE THREAD

**Issue by orah28** [Reloaded-Project/Reloaded-II#372]
**Describe the Bug**
I seem to get a 503 error when trying to update mods. Here is the screenshots of the error
![Screenshot 2024-05-03 195907](https://github.com/Reloaded-Project/Reloaded-II/assets/109697346/f8511f59-081a-4919-8ad0-457c57fa62ca)
![Screenshot 2024-05-03 200038](https://github.com/Reloaded-Project/Reloaded-II/assets/109697346/8265d6a8-9842-4d94-9707-efbe78bb89ac)

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Reloaded
2. Wait for update pop up to appear and press update
3. the update bar gets up to 50%
4. The error appears and the whole app crashes

**Expected Behaviour**
I would like my mods to update

**Comment by Sewer56** [comment]
Not much I can do here, other than maybe trying to add a retry policy so it tries more than once.

Some people experience this when downloading from GameBanana, been more common in the past 2 months; and it's just down to their servers being a bit unreliable sometimes.

**Comment by Sewer56** [comment]
GameBanana download servers were having an issue. Here's a quote from tom (site owner):

![image](https://github.com/Reloaded-Project/Reloaded-II/assets/6697380/ae75d802-fe6b-4e2e-a140-f1b9173e121c)

In 1.27.6 , I added a retry policy, just in case to help alleviate these issues if possible in the rare case a download randomly fails; but that's just a preventative measure in case of temporary 'blips'.
https://github.com/Reloaded-Project/Reloaded-II/discussions/369
