### ISSUE TITLE
Help: An error occured while trying to load Reloaded-l. 'Linux' is not a valid version string. 

### ISSUE THREAD

**Issue by Lukienlong** [Reloaded-Project/Reloaded-II#373]
![2024-05-04 160239](https://github.com/Reloaded-Project/Reloaded-II/assets/91059751/4f38af5a-1400-4cd7-9e6e-df276b0ee967)

**Comment by Sewer56** [comment]
Wow, this is an error I've never seen before 
Just what even is happening here?

Did you screenshot this from Windows or Linux?

If it's Linux, what happens if you `export DOTNET_ROOT='""` before launching in Wine? (Maybe it's mixing up the .NET install location)

**Comment by Lukienlong** [comment]
No, I'm using the Windows system. I'm also puzzled as to why 'Linux' would come up.

**Comment by Sewer56** [comment]
I need a bit of a nap, so might only fully get around this tomorrow.

Can you give a listing of folders you have at 
`Program Files/dotnet/shared` and `Program Files (x86)/dotnet/shared`?

Normally there's just a bunch of folders with the version as the folder name. Yours might have something extra though. I wonder if there's some edge case the runtime version finder doesn't handle.

**Comment by Lukienlong** [comment]
C:/Program Files/dotnet/shared

**Comment by Lukienlong** [comment]
C:/Program Files/dotnet/shared
![2024-05-04 172246](https://github.com/Reloaded-Project/Reloaded-II/assets/91059751/212f76ee-0861-4d70-b54c-f8431a68fadd)
PS C:\Program Files\dotnet\shared> tree
卷 系统 的文件夹 PATH 列表
卷序列号为 09E6-4F4D
C:.
├─Libraries
│  ├─basic.reference.assemblies.net60
│  │  └─1.2.4
│  │      └─lib
│  │          └─netstandard2.0
│  ├─CsvHelper
│  │  └─2.0.0.0
│  ├─FNA
│  │  └─1.0.0
│  ├─hjson
│  │  └─3.0.0
│  │      └─lib
│  │          └─netstandard1.3
│  ├─humanizer.core
│  │  └─2.2.0
│  │      └─lib
│  │          └─netstandard1.0
│  ├─Ionic.Zip.Reduced
│  │  └─1.9.1.8
│  ├─log4net
│  │  └─2.0.8.0
│  ├─microsoft.bcl.asyncinterfaces
│  │  └─6.0.0
│  │      └─lib
│  │          └─netstandard2.1
│  ├─microsoft.build.locator
│  │  └─1.6.10
│  │      └─lib
│  │          └─net6.0
│  ├─microsoft.codeanalysis.common
│  │  └─4.2.0
│  │      └─lib
│  │          └─netcoreapp3.1
│  │              ├─cs
│  │              ├─de
│  │              ├─es
│  │              ├─fr
│  │              ├─it
│  │              ├─ja
│  │              ├─ko
│  │              ├─pl
│  │              ├─pt-BR
│  │              ├─ru
│  │              ├─tr
│  │              ├─zh-Hans
│  │              └─zh-Hant
│  ├─microsoft.codeanalysis.csharp
│  │  └─4.2.0
│  │      └─lib
│  │          └─netcoreapp3.1
│  │              ├─cs
│  │              ├─de
│  │              ├─es
│  │              ├─fr
│  │              ├─it
│  │              ├─ja
│  │              ├─ko
│  │              ├─pl
│  │              ├─pt-BR
│  │              ├─ru
│  │              ├─tr
│  │              ├─zh-Hans
│  │              └─zh-Hant
│  ├─microsoft.codeanalysis.csharp.workspaces
│  │  └─4.2.0
│  │      └─lib
│  │          └─netcoreapp3.1
│  │              ├─cs
│  │              ├─de
│  │              ├─es
│  │              ├─fr
│  │              ├─it
│  │              ├─ja
│  │              ├─ko
│  │              ├─pl
│  │              ├─pt-BR
│  │              ├─ru
│  │              ├─tr
│  │              ├─zh-Hans
│  │              └─zh-Hant
│  ├─microsoft.codeanalysis.flowanalysis.utilities
│  │  └─2.9.6
│  │      └─lib
│  │          └─netstandard1.3
│  ├─microsoft.codeanalysis.workspaces.common
│  │  └─4.2.0
│  │      └─lib
│  │          └─netcoreapp3.1
│  │              ├─cs
│  │              ├─de
│  │              ├─es
│  │              ├─fr
│  │              ├─it
│  │              ├─ja
│  │              ├─ko
│  │              ├─pl
│  │              ├─pt-BR
│  │              ├─ru
│  │              ├─tr
│  │              ├─zh-Hans
│  │              └─zh-Hant
│  ├─microsoft.codeanalysis.workspaces.msbuild
│  │  └─4.2.0
│  │      └─lib
│  │          └─netcoreapp3.1
│  │              ├─cs
│  │              ├─de
│  │              ├─es
│  │              ├─fr
│  │              ├─it
│  │              ├─ja
│  │              ├─ko
│  │              ├─pl
│  │              ├─pt-BR
│  │              ├─ru
│  │              ├─tr
│  │              ├─zh-Hans
│  │              └─zh-Hant
│  ├─microsoft.win32.systemevents
│  │  └─6.0.0
│  │      ├─lib
│  │      │  └─net6.0
│  │      └─runtimes
│  │          └─win
│  │              └─lib
│  │                  └─net6.0
│  ├─mono.cecil
│  │  └─0.11.5
│  │      └─lib
│  │          └─netstandard2.0
│  ├─monomod.backports
│  │  └─1.1.0
│  │      └─lib
│  │          └─net6.0
│  ├─monomod.core
│  │  └─1.1.0
│  │      └─lib
│  │          └─net6.0
│  ├─monomod.ilhelpers
│  │  └─1.0.1
│  │      └─lib
│  │          └─net6.0
│  ├─monomod.runtimedetour
│  │  └─25.1.0
│  │      └─lib
│  │          └─net6.0
│  ├─monomod.utils
│  │  └─25.0.4
│  │      └─lib
│  │          └─net6.0
│  ├─MP3Sharp
│  │  └─1.0.0.0
│  ├─Native
│  │  ├─Linux
│  │  ├─OSX
│  │  └─Windows
│  ├─Newtonsoft.Json
│  │  └─12.0.0.0
│  ├─NVorbis
│  │  └─0.10.0.3
│  ├─RailSDK.Net
│  │  └─1.0.0.0
│  ├─ReLogic
│  │  └─1.0.0
│  ├─steamworks.net
│  │  └─20.1.0
│  │      ├─lib
│  │      │  └─netstandard2.1
│  │      └─runtimes
│  │          ├─linux-x64
│  │          │  └─lib
│  │          │      └─netstandard2.1
│  │          ├─linux-x86
│  │          │  └─lib
│  │          │      └─netstandard2.1
│  │          ├─osx-x64
│  │          │  └─lib
│  │          │      └─netstandard2.1
│  │          ├─osx-x86
│  │          │  └─lib
│  │          │      └─netstandard2.1
│  │          ├─win-x64
│  │          │  └─lib
│  │          │      └─netstandard2.1
│  │          └─win-x86
│  │              └─lib
│  │                  └─netstandard2.1
│  ├─SteelSeriesEngineWrapper
│  │  └─1.0.0.0
│  ├─system.codedom
│  │  └─6.0.0
│  │      └─lib
│  │          └─net6.0
│  ├─system.composition.attributedmodel
│  │  └─6.0.0
│  │      └─lib
│  │          └─net6.0
│  ├─system.composition.convention
│  │  └─6.0.0
│  │      └─lib
│  │          └─net6.0
│  ├─system.composition.hosting
│  │  └─6.0.0
│  │      └─lib
│  │          └─net6.0
│  ├─system.composition.runtime
│  │  └─6.0.0
│  │      └─lib
│  │          └─net6.0
│  ├─system.composition.typedparts
│  │  └─6.0.0
│  │      └─lib
│  │          └─net6.0
│  ├─system.configuration.configurationmanager
│  │  └─6.0.0
│  │      └─lib
│  │          └─net6.0
│  ├─system.diagnostics.performancecounter
│  │  └─6.0.0
│  │      ├─lib
│  │      │  └─net6.0
│  │      └─runtimes
│  │          └─win
│  │              └─lib
│  │                  └─net6.0
│  ├─system.drawing.common
│  │  └─6.0.0
│  │      ├─lib
│  │      │  └─net6.0
│  │      └─runtimes
│  │          ├─unix
│  │          │  └─lib
│  │          │      └─net6.0
│  │          └─win
│  │              └─lib
│  │                  └─net6.0
│  ├─system.io.pipelines
│  │  └─6.0.1
│  │      └─lib
│  │          └─net6.0
│  ├─system.reflection.metadataloadcontext
│  │  └─6.0.0
│  │      └─lib
│  │          └─net6.0
│  ├─system.security.cryptography.protecteddata
│  │  └─6.0.0
│  │      ├─lib
│  │      │  └─net6.0
│  │      └─runtimes
│  │          └─win
│  │              └─lib
│  │                  └─net6.0
│  ├─system.security.permissions
│  │  └─6.0.0
│  │      └─lib
│  │          └─net6.0
│  ├─system.windows.extensions
│  │  └─6.0.0
│  │      ├─lib
│  │      │  └─net6.0
│  │      └─runtimes
│  │          └─win
│  │              └─lib
│  │                  └─net6.0
│  ├─TerrariaHooks
│  │  └─0.0.0.0
│  ├─tModPorter
│  │  └─1.0.0
│  └─utf.unknown
│      └─2.5.0
│          └─lib
│              └─netcoreapp3.0
├─Microsoft.AspNetCore.App
│  ├─6.0.27
│  ├─6.0.29
│  ├─7.0.18
│  └─8.0.4
├─Microsoft.NETCore.App
│  ├─3.1.32
│  ├─6.0.27
│  ├─6.0.29
│  ├─7.0.18
│  └─8.0.4
└─Microsoft.WindowsDesktop.App
    ├─6.0.27
    │  ├─cs
    │  ├─de
    │  ├─es
    │  ├─fr
    │  ├─it
    │  ├─ja
    │  ├─ko
    │  ├─pl
    │  ├─pt-BR
    │  ├─ru
    │  ├─tr
    │  ├─zh-Hans
    │  └─zh-Hant
    ├─6.0.29
    │  ├─cs
    │  ├─de
    │  ├─es
    │  ├─fr
    │  ├─it
    │  ├─ja
    │  ├─ko
    │  ├─pl
    │  ├─pt-BR
    │  ├─ru
    │  ├─tr
    │  ├─zh-Hans
    │  └─zh-Hant
    ├─7.0.18
    │  ├─cs
    │  ├─de
    │  ├─es
    │  ├─fr
    │  ├─it
    │  ├─ja
    │  ├─ko
    │  ├─pl
    │  ├─pt-BR
    │  ├─ru
    │  ├─tr
    │  ├─zh-Hans
    │  └─zh-Hant
    └─8.0.4
        ├─cs
        ├─de
        ├─es
        ├─fr
        ├─it
        ├─ja
        ├─ko
        ├─pl
        ├─pt-BR
        ├─ru
        ├─tr
        ├─zh-Hans
        └─zh-Hant

**Comment by Lukienlong** [comment]
C:/Program Files (x86)/dotnet/shared
![Uploading 2024-05-04 173049.png…]()

**Comment by Lukienlong** [comment]
C:/Program Files (x86)/dotnet/shared
![2024-05-04 173049](https://github.com/Reloaded-Project/Reloaded-II/assets/91059751/47751cf9-2124-49eb-8432-db03bbe4a1b3)

**Comment by Sewer56** [comment]
I added a safeguard in 1.27.7 against unintended files in the `dotnet/shared` folder.

I'm not really sure why you have non-runtime files there, I presume it's dropped there by `tModLoader` (or some plugin of it) based on the contents, intentionally or accidentally, but I can't be really sure.

Should hopefully be live in 10 mins

**Comment by Lukienlong** [comment]
Just as you said, Reloaded runs smoothly after I removed the non-runtime files. These files must have been moved to this location unintentionally by me. Thank you very much for your help.
