### ISSUE TITLE
Bug: Reloaded 2 (1.23) doesn't want to open on steam deck through protontricks

### ISSUE THREAD

**Issue by rebelsandrenegades** [Reloaded-Project/Reloaded-II#375]
**Describe the Bug**
I had no issues with using Reloaded II for P4G (the 1.23 release since that seems to be the only one that works properly) and all of a sudden it refuses to open and when it does it crashes and then I have to ctrl - esc and close the exe. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Reloaded-II.exe
2. Click on it and open protontricks.
3. Scroll down to the Persona 4 Golden prefix and click on that.
4. See error - sometimes Reloaded 2 opens sometimes it doesn't, other times it tries to open the tutorial but otherwise nothing seems to load and always crashes.

**Comment by Sewer56** [comment]
Can you screenshot the error?

**Comment by rebelsandrenegades** [comment]
![2024-05-07_19-20](https://github.com/Reloaded-Project/Reloaded-II/assets/169218534/9ca03700-ff83-47f6-a3be-1d401b315a83)
This is where it gets stuck sometimes. Other times it just refuses to open. I have all the runtimes downloaded and installed through proton tricks.

**Comment by Sewer56** [comment]
I've linked this to someone who does Deck stuff.

It's a strange issue I haven't seen before; and the fact it softlocks without an error is especially strange. Very non-trivial to debug, especially as I don't do logging.

I wonder if it's something tied to the first start sequence. If you skip the tutorial, does that still happen?
You can skip it by overwriting `Z:\Users\steamuser\AppData\Roaming\Reloaded-Mod-Loader-II\ReloadedII.json` inside your WINEPREFIX (wine/proton sandbox).

The native path for that is probably `/home/<YOUR_USERNAME>/.local/share/Steam/steamapps/compatdata/1113000/pfx/users/steamuser/AppData/Roaming/Reloaded-Mod-Loader-II/ReloadedII.json` (or something very close to that).

If you set `"FirstLaunch": true,` in the config, it should skip the tutorial. Curious how that will change things.

**Comment by Sewer56** [comment]
@rebelsandrenegades 
Ah, one thing does come to mind.

In 1.25 the .NET version upgraded from 7 to 8.
Maybe that doesn't play right with your Proton version.

If you're running some older Proton version, try 9.0 or Proton Experimental.

**Comment by rebelsandrenegades** [comment]
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/169218534/ce4d664d-326a-448b-887a-b585f9388159)
So I opened the files and it seems it's already set to true. Forgive me, I'm not the most well versed with working with linux. But yeah it worked just fine until a couple days ago and now when I try loading reloaded-II.exe it crashes immediately. I tried different releases and they all operate the same way. I wish there was a cache or something I could clear. I already cleared the steam download cache.

**Comment by Sewer56** [comment]
There is a cache in `\AppData\Local\Reloaded-Mod-Loader-II` but it's only for stuff downloaded from the web.
You can try clearing it, but it's unlikely to make a difference.

Also oopsie, I meant `"FirstLaunch": false,`. I forgot this defaults to `true`.
Do try a newer Proton version if possible though.

**Comment by rebelsandrenegades** [comment]
Omg changing the game from proton experimental to 9.0 somehow worked?????? 

Thank you so much! I would have never thought of that.

**Comment by Sewer56** [comment]
Haha, All's Well that Ends Well, Right?

Just be careful when launching the game, if you switch your Wine/Proton version too often and launch the game, the Denuvo Copy Protection system will boot you out for 24 hours. Seen this happen a few times with Deck users.

**Comment by rebelsandrenegades** [comment]
issue resolved:
Changed proton from experimental to 9.0!
