### ISSUE TITLE
Bug(Probably): 2 Trojans, why?

### ISSUE THREAD

**Issue by SummerPain** [Reloaded-Project/Reloaded-II#376]
Installer has two trojans (1 and 2)

Release.zip has one (1)

So i basically should force my AV to not do machine-learning-detection of these 2 - it is not good i think.

I saw somewhere problem with wacatac trojan with !ml on some python framework, but this one is completely different so i wonder what is the deal.

Screenshots:
(1): ![изображение_2024-05-08_151219108](https://github.com/Reloaded-Project/Reloaded-II/assets/70639614/8f7b57c4-f3da-4e16-9e32-58fadff0e346)
(2): ![изображение_2024-05-08_151233553](https://github.com/Reloaded-Project/Reloaded-II/assets/70639614/8e016c3a-8300-4645-9944-22f87dbc3621)

**Comment by Sewer56** [comment]
`!ml` are machine learning detections, yeah.

I unfortunately have to deal with them every other month. The only alternative is I buy a expensive code signing certificate, thus participating in the extortion cycle.

When I make releases, I often boot into Windows (I don't use Windows on a daily basis) and scan the binaries with Defender, so I can then submit them as false positives when they get flagged. I'm not sure why there's a flag, I actually did one of these test scans yesterday.
