### ISSUE TITLE
Bug: Tutorial Window Not Interactable [SteamOS]

### ISSUE THREAD

**Issue by MrCamel999** [Reloaded-Project/Reloaded-II#378]
**Describe the Bug**
The tutorial window will not properly allow interactions upon first launch under the P5R Protontricks prefix on SteamOS.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to whatever directory you have Reloaded-II.exe in
2. Click on the executable
3. Scroll down to P5R

**Expected Behaviour**
The tutorial window should be able to be interactable so I can skip it.

**Screenshots**
YouTube link for unlisted video showing the problem since github complains about file size: https://youtu.be/H6WuPGo9aCM?si=cS7ah8IiosOTIfwH

**Additional Context**
I think it might work if it somehow runs under X11? I don't know how to make that happen on SteamOS though, since the sign out button on KDE sends you back to gaming mode, not the KDE session manager. Also, it seemingly worked fine for me when I set up P3R, so I'm not sure what changed to cause this issue (and yes, I installed all 6 required dependencies to the correct prefix, that isn't the issue). I tried installing an older version of Reloaded-II to see if it was some sort of recent update, but that didn't work.

**Comment by MrCamel999** [comment]
Sorry, it's already in X11 it seems. I don't know how to try it on Wayland to see if that fixes it somehow. Point is still the same though.

**Comment by Sewer56** [comment]
I've seen a report like this before. It may be related to running on Proton 9.X vs Proton Experimental.
I think something got borked on the Proton side.

Since all the windowing logic etc. is in WPF, I'm not really sure if there's much I can do about issues experienced on Wine forks. I've been working on a successor for Reloaded-II which is natively cross platform for around a year now, but I expect it'll probably take me another 2 years.

**Comment by MrCamel999** [comment]
Gotcha, thanks for the info. I know I'm running P5R and P3R via Proton Experimental, I'll try switching to a different Proton version and see if that helps. Thanks again for the info!

**Comment by MrCamel999** [comment]
Switching from Experimental to 9.0-1 worked PERFECTLY. Thanks a crap ton!!!
