### ISSUE TITLE
Can't play P4G with PS4 controller while using Reloaded

### ISSUE THREAD

**Issue by sleepymanakete** [Reloaded-Project/Reloaded-II#38]
Hi!
I'm having a problem where if I use reloaded to launch P4G, the game will only detect mouse and keyboard inputs. Is there a way to make it use my PS4 controller? Having no mods still cause this issue.

**Comment by Sewer56** [comment]
Don't have P4G but I'm guessing when you launch from Steam, it emulates an XInput (Xbox) controller using the Steam Input Wrapper. 

In this case, you have a few options:
- Emulate an Xbox Controller outside of Steam by using a wrapper (e.g. DS4Windows seems to be the popular one).
- Create a shortcut in Reloaded-II, and add the shortcut to Steam.
![image](https://user-images.githubusercontent.com/6697380/90083094-8855f400-dd09-11ea-9e6b-494f6977c327.png)
Note: You will need to copy the target manually as for some reason Steam doesn't do this for you.

- Load Reloaded through an external universal loader that uses DLL Hijacking ([Documentation](https://github.com/Reloaded-Project/Reloaded-II/blob/master/Docs/InjectionMethods.md#dll-loader-introduction)). This will cause the game to always load the mod loader regardless of where it's launched from. Reloaded can now automate this process for you if you click this button: 
![image](https://user-images.githubusercontent.com/6697380/90083348-28138200-dd0a-11ea-8343-6a29d8c2535d.png)




Hope it helps.

**Comment by sleepymanakete** [comment]
I will try those, thank you!

**Comment by sleepymanakete** [comment]
The last option worked, thank you again!
