### ISSUE TITLE
Help: Game (Sonic Heroes) doesn't start. 

### ISSUE THREAD

**Issue by RunningintheRain** [Reloaded-Project/Reloaded-II#380]
**Pre-requisites**

All listed Pre-requisites have been installed and are working. (Although did have some initial issues of .Net Framework not wanting to let me start Reloaded II despite being downloaded already.)

**Issue**

Upon pressing "Launch Application" using the MyAbandonware ISO of Sonic Heroes, no application opens, nor does any sort of error message appear, the only notable change is a message appearing within the "Processes" section of Reloaded II, in which a "[SYS] Id: (4-5 random numbers)" will generate, and nothing else.

----------------------------------------------------------------------------------

Fixes already attempted:
- Full re-install of both Reloaded II and Sonic Heroes (on multiple occasions)
- Temp Disabling Anti-Virus to see if it was conflicting
- Setting Reloaded II to run as Admin, and both Sonic Heroes and Reloaded II to run as Admin.
  + When Reloaded II is not opened as Administrator, pressing "Launch Application" returns the following window pop-up.
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/170029676/e2a1fd1d-3f48-4c32-aff1-d1927f4c9a62)
- Disabling any and all mods/enabling "essential" mods, etc.
- Attempting to use ReShade + d3d8to9 tools as modern Nvidia drivers don't support DirectX 8 anymore.

----------------------------------------------------------------------------------

**Screenshots**

After Pressing "Launch Application"
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/170029676/1a96b07f-f535-4cb4-85dd-9c5750d1d55d)

No other windows, consoles or other changes of any kind after "Launch Application" is pressed, other than a brief loading circle appearing on the mouse, lasting for about 2-5 seconds.

----------------------------------------------------------------------------------

**Additional Resources**

Mods to hopefully get working with game (in descending order):
  - CRI FileSystem Hook (1.1.10, Sewer56)
  - SH Essentials: Graphics (1.4.3, Sewer56)
  - SH Essentials: Widescreen Revamp (1.0.1, Raphael Drew Boltman)
  - TONERR: The ONe Expandonger Reloaded Reloaded (1.2.2, Sewer56)
  
Mods have been shuffled in the load order as an attempted fix already.

----------------------------------------------------------------------------------

Upon start-up of Reloaded II, the following message appears

![image](https://github.com/Reloaded-Project/Reloaded-II/assets/170029676/2c85c754-4673-443b-92dd-3276db77180f)

.Net Core 8.0.0 x86 has been downloaded and installed already (with several re-installs too in case it was causing the issue), after closing this window, Reloaded II opens as normal with no other issues.

----------------------------------------------------------------------------------

Relevant PC Info:
  OS: Windows 11 Home x64
  Graphics Card: Nvidia GeForce GTX 1650 Laptop Graphics
      Installed Driver: GeForce Game Ready Driver; Version 546.29

----------------------------------------------------------------------------------

Just for a lil bit of extra information: The Sonic Heroes Launcher itself loads perfectly fine, however also runs into the same launch issue of nothing happening. Occasionally when using this method (roughly every 1/5 attempts), Windows Compatibility Troubleshooter will start, however the tool is doesn't seem to detect any issues that need fixing.

Honestly here as a last-ditch effort, as I am not sure if this is a game issue, Reloaded II issue, Nvidia issue or simply a Windows version incompatibility, but figured it might be worth asking as from the looks of things, this GitHub repository also has a lot of experience with Sonic Heroes in the past.

**Comment by Sewer56** [comment]
Can you:

- Screenshot the game folder.
- The contents of `dotnet --list-runtimes` when typed in cmd.
    - If that doesn't work, the contents of `Program Files(x86)/dotnet/shared/Microsoft.WindowsDesktop.App` 
    
This sounds fairly odd.

By the way, the error says `You need to run Reloaded as Admin` in human friendly terms. However, this should not normally be necessary, unless the game is specifically set to require admin in the `Properties` window when right clicking the EXE.

**Comment by RunningintheRain** [comment]
Wasn't expecting such a fast response, so apologies if I'm not entirely prepared.

Game Folder: (Currently without d3d8to9 due to having just reinstalled it.
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/170029676/8d5c1047-b126-4b74-b296-76b5500de773)

Cmd contents after inputing dotnet --list-runtimes:
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/170029676/b9a631d7-3a64-43d2-935f-33d8506f0311)

Tsonic_win.exe is not set to not admin in Properties, just double checked just in case.

**Comment by Sewer56** [comment]
Ah, I'm not exactly sure why Reloaded is showing you have the runtime missing, but you should be okay here.

The issue is that you got the unmodified US release of the game. This includes the original `SafeDisc` copy protected `TSonic_Win.exe`.

Due to a security vulnerability in the `SafeDisc` kernel driver, that driver was blacklisted and cannot be ran on modern versions of Windows (alongside like 500-1000 other games) without some very difficult steps. And even if you can, you should not force enable the driver, because the privilege escalation vulnerability is pretty severe.

Get the cracked (NoCD) version of the game, and you should be okay.
This is actually what SEGA did themselves when they released the 'Sonic PC Collection' 😉

**Comment by RunningintheRain** [comment]
Alrighty, that would indeed explain my issue. Any clue where I might be able to find the cracked version safely? Most sources I've found link to a 404 page now.

**Comment by Sewer56** [comment]
The ads may be a bit unusual on this ancient site, but this should work https://gamecopyworld.com/games/pc_sonic_heroes.shtml#Sonic%20Heroes%20v1.0%20[ENGLISH]%20Fixed%20EXE

**Comment by RunningintheRain** [comment]
Managed to get it installed, ads were for sure...unusual. 

Cleared out the folder and moved the new Tsonic_win.exe which is indeed 5,012kb, reset the file path within Reloaded II but still have the same issue of nothing happening when launching through Reloaded.

Also, yep! I've currently got my old Sonic Heroes disks right next to me haha.

**Comment by Sewer56** [comment]
Curious, can you open a command prompt at `C:/Program Files (x86)/dotnet` and try `dotnet --list-runtimes` ?
There's actually a separate x86 version of `dotnet` in there. I'm curious if the actual Microsoft binary can find the 32-bit version.

**Comment by RunningintheRain** [comment]
I think you're on to something! Seems it's only finding the 3.1.2 version of x86

![image](https://github.com/Reloaded-Project/Reloaded-II/assets/170029676/071302f8-5b4d-4904-a72f-e870b52ecdb8)

**Comment by Sewer56** [comment]
Can you post the URL that the download button sends you to when you click it from Reloaded? I wonder if it's sending you to the wrong place. It uses the same logic as the official Microsoft install scripts for unattended installs, but I've had it point to the wrong place before.

It should download same file as this https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-8.0.5-windows-x86-installer

**Comment by RunningintheRain** [comment]
Download link from Reloaded II downloads the same file you sent through, as well as a second file named "dotnet-runtime-8.0.5-win-x86.exe"

**Comment by Sewer56** [comment]
You should only need `windowsdesktop-runtime-8.0.5-win-x86.exe`, hopefully that works.

**Comment by RunningintheRain** [comment]
Seems like that fixed something! 

Not only did Reloaded II not have a pop-up on launch, but upon pressing "Launch Application" with Sonic Heroes, the Reloaded II console opened. 

However, seems like something has gone wrong again, as the bottom of the console reads "[Reloaded] Crashed. Generating Crash Dump. Might take a while." along with a ghost Sonic Heroes window and a pop-up 

![image](https://github.com/Reloaded-Project/Reloaded-II/assets/170029676/0408ec26-3490-4690-9fa5-2255a4091628)

**Comment by Sewer56** [comment]
That's an address I've never seen.
[Tsonic_win.EXE.zip](https://github.com/Reloaded-Project/Reloaded-II/files/15339719/Tsonic_win.EXE.zip)

Try my EXE as a sanity test.

**Comment by RunningintheRain** [comment]
Switched the EXEs out, same crash address.

Also just tested both with all mods disabled, same thing.

![image](https://github.com/Reloaded-Project/Reloaded-II/assets/170029676/3555eca1-2de5-4914-9e26-5c1d52b9abef)

**Comment by Sewer56** [comment]
Message me on Discord (sewer56). I'll send you a link to my game copy as a sanity test. Am not home ATM and I'd rather not post a full game on GitHub.

**Comment by Sewer56** [comment]
So after almost 2 hours of debugging, we got... nowhere.
For some reason with ASI Loader, stuff runs fine; but without it, the game just dies.

Some Notes:

- Intel Iris Xe Driver gets loaded, even when Nvidia is set to main Adapter
- Game folder completely clean
- No external overlays etc. no unexpected modules
- D3D9On12 is loaded for some reason. Maybe due to intel drivers.

***It works with DLL Hijacking (i.e. ASI Loader) only.*** DLL Injection into suspended process of any capacity does not work. I have no idea why at this point. It's not the injector, the loader runs fine, the game somehow crashes in the PRS Decompression function.

My only possible idea is Intel is hooking stuff, and they fail for some reason; because no DLL looks out of place other than the Intel stuff in the module list. But that's a very crazy idea.
