### ISSUE TITLE
Help: Please help me with it. After I follow the tutorial and install some mods, I stated it. but it goes wrong like this

### ISSUE THREAD

**Issue by KRINCE223** [Reloaded-Project/Reloaded-II#381]
**Did you install the Prerequisites?**
You can see them right beside the download button on each official download. 
You'll need all of them as stated.

**As seen on GitHub**:
![image](https://user-images.githubusercontent.com/6697380/90259427-e71e8900-de41-11ea-87aa-0ff27cf5e486.png)

**As seen on GameBanana**:
![image](https://user-images.githubusercontent.com/6697380/90259465-f8679580-de41-11ea-9ef9-08eb3e9c4a2e.png)

**Describe the Issue**
A clear and concise description of what you would like help with.

**Screenshots**

**Additional Resources**
If the issue is related to any external resource e.g. specific version of a mod or pack, consider stating the version or linking the resource in question. Preferably though, mod specific issues should go in their own GitHub repositories as I in most cases would not be able to help.

**Comment by KRINCE223** [comment]
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/170155212/e1e35c39-05a0-41a6-be07-f972d9135450)

**Comment by Sewer56** [comment]
As a sanity test, I suggest going to the mod folder of Persona Essentials. (Highlight it in launcher and click `Open Mod Folder`). Then delete the `Cache` folder.

And also delete Bf emulator in case it itself is borked. You can do that by deleting it from inside the launcher or deleting the folder `reloaded.universal.fileemulationframework.bf` from Reloaded-II's mods folder. It'll redownload automatically.

**Comment by KRINCE223** [comment]
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/170155212/d17c8dcb-5550-4048-860e-c2c705bf3004)
I tried, but it seems that it stilll can't be fixed by that.

**Comment by Sewer56** [comment]
Have you tried individually disabling/enabling mods? Maybe something is using an older format, I'm not exactly sure myself.

From the error I can only guess something is missing in a mod somewhere.

**Comment by KRINCE223** [comment]
Oh, I see . One of my mods is definitely not fit for it. I'm sorry that I haven't think about that. Thank for your help.
