### ISSUE TITLE
Hello, I require help with "received an uxepected EOF"

### ISSUE THREAD

**Issue by KyF4** [Reloaded-Project/Reloaded-II#384]
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/102164484/b767b9c1-f11c-4fea-9064-66d7f500c75b)

I received this problem trying to update the mods i have for Persona 5 Royal. It is the female protagonist mod. I've scoured the internet for help but none seems similar to my current problem. I've tried reinstalling it and it wouldnt go away. If all roads leads to a dead end i might try manually place the files myself (As of writing this the files are painfully slowly downloading XD, I am patient but if this issue can be helped then it would be nice)

Appreciate all the help and effort, 
Thanks

**Comment by Sewer56** [comment]
According to the error, it started downloading but then the server wasn't returning any data.

Most likely it's an issue on the other end; I'm not sure if there's much I can do about it, but if you have the mod name and current version, I can at least check if the mod author configured things correctly.

**Comment by KyF4** [comment]
The mods names are:
P5R Female Protagonist by Chlorophylls version 1.20.7
P5R Female Protagonist - English Voiceover version 1.0.7

**Comment by KyF4** [comment]
> According to the error, it started downloading but then the server wasn't returning any data.
> 
> Most likely it's an issue on the other end; I'm not sure if there's much I can do about it, but if you have the mod name and current version, I can at least check if the mod author configured things correctly.

Ah well. thats unfortunate then. i'll try my luck with manual installation. Cheers for the answer though.

**Comment by Sewer56** [comment]
Closing because user opened another issue 
#386
