### ISSUE TITLE
Help: Hello again. I was wondering how to manually install the mod into Reloaded II. 

### ISSUE THREAD

**Issue by KyF4** [Reloaded-Project/Reloaded-II#386]
Due to EOF errors I decided to try out installing the mods manually through chrome. However, from the tutorials i've seen. dragging the file into Reloaded II mod menu doesn't seem to work in my pc (am i missing something?) and putting the files directly into the mod folders didn't work either. 

a step by step solution would be marvelous. Thanks.

**Comment by KyF4** [comment]
Hello. Dragging the file into the titlebar worked. Thanks a lot mate!

**Comment by Sewer56** [comment]
No worries. There's some controls on the window where drag-drop doesn't work due to their own logic. I've never gotten around to patching all of them up, but in around 90% of the space it works fine.,
