### ISSUE TITLE
Help: Can't get Reloaded-II to start

### ISSUE THREAD

**Issue by NerdyKingpin** [Reloaded-Project/Reloaded-II#388]
I installed all 4 prerequisite programs and it won't open. This is my first time ever using it and I'm trying to use the P4G community pack. I made sure that nothing was where it shouldn't be and it's still not working.

I don't know if there's any additional thing I need to download or if a program on my laptop is blocking it somehow, but either way the program isn't running for me but my friends can use it fine and I don't know why.

**Comment by Sewer56** [comment]
Try this:

- Open `Event Viewer`
- Go to `Windows Logs` -> `Application`
- Find latest `Error` (red) with `.NET Runtime` as Source.
- Copy-paste the error text, or screenshot it.

![image](https://github.com/Reloaded-Project/Reloaded-II/assets/6697380/bcaffc18-8216-435b-8c2f-5e94011e8624)

**Comment by NerdyKingpin** [comment]
I just tried to run the program again and then look at event viewer but nothing popped up. It's like I never tried to open it.
![Screenshot 2024-05-25 191349](https://github.com/Reloaded-Project/Reloaded-II/assets/170820649/5cb2b80e-4899-4c79-9a84-14e539212e41)
![Screenshot 2024-05-25 191408](https://github.com/Reloaded-Project/Reloaded-II/assets/170820649/ffbb5d34-bb04-4cbf-ae59-25aa97c22b9d)
![Screenshot 2024-05-25 191626](https://github.com/Reloaded-Project/Reloaded-II/assets/170820649/fe1e3b5f-7d59-41e7-991c-1c6aea2f663f)

**Comment by Sewer56** [comment]
Ah which program are you running? CEP's installer? Or `Reloaded-II.exe`?

**Comment by NerdyKingpin** [comment]
Reloaded-II.exe

**Comment by NerdyKingpin** [comment]
No error at all. I get the blue circle loading thing by my mouse but then nothing happens.

**Comment by Sewer56** [comment]
Can you go to where Reloaded-II.exe, click the address bar and type `cmd`? Then press enter, this should get you a command prompt.

I'm the prompt, type `dotnet Reloaded-II.dll` and hit enter, then see what happens. Maybe that'll get us an error message.

**Comment by NerdyKingpin** [comment]
I did that and Reloaded booted up and is now showing me the tutorial

**Comment by Sewer56** [comment]
The exe should be doing pretty much the exact same thing as this command. Maybe an external program, like an antivirus blacklisted it then. Strange.

But yeah, that's it working.

**Comment by NerdyKingpin** [comment]
Hopefully I won't have to do that every time, but thank you!
