### ISSUE TITLE
Bug: A crash happens when I try to assign a preview image to a mod

### ISSUE THREAD

**Issue by esqwrf** [Reloaded-Project/Reloaded-II#389]
Reloaded II crashes when I try to assign a preview image to a mod that doesn't have one. Replacing an existing preview works fine.

**Comment by esqwrf** [comment]
UPD: in both cases everything works fine if the target image is located anywhere outside of the target mod folder.

**Comment by Sewer56** [comment]
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/6697380/529dbdc0-31d5-4621-8b79-a295613cb8c4)

Is it a file in use issue like this?

**Comment by Sewer56** [comment]
I'll fix it in a bit, I've been bamboozled by NTFS3 driver again. (I need to run Disk Repair to boot into Windows)

It's 2024 and you can't have a decent cross platform no compromises filesystem a-aaaaaa.
