### ISSUE TITLE
Reloaded II not booting Sonic Heroes 

### ISSUE THREAD

**Issue by KiwiiiShine** [Reloaded-Project/Reloaded-II#39]
When trying to launch Sonic Heroes PC it just won't boot up, throwing an exception before closing itself, I ran the app as admin and checked if Sonic Heroes worked and they are no issues, here's the error that keeps popping up 

![image](https://user-images.githubusercontent.com/61021879/90216442-e00d6180-ddd4-11ea-8b15-81f7bcaa6bfa.png)

**Comment by Sewer56** [comment]
![image](https://user-images.githubusercontent.com/6697380/90259427-e71e8900-de41-11ea-87aa-0ff27cf5e486.png)
![image](https://user-images.githubusercontent.com/6697380/90259465-f8679580-de41-11ea-9ef9-08eb3e9c4a2e.png)
