### ISSUE TITLE
Help: Did I just install the app too many times? <X>

### ISSUE THREAD

**Issue by HowCanYouSitThereAndEatPizza** [Reloaded-Project/Reloaded-II#391]
I've been trying to install the audio enhancement pack for Silent Hill 3 using Reloaded 2. The audio mod wasn't showing up in my applications on Reloaded 2, so I have uninstalled and re-installed Reloaded 2 several times to try to get the mod to work. But now I can't download Reloaded 2 itself. Is it saying that I've downloaded it too many times? I'm confused. See the error message below. 

![Reloaded 2 Error Message](https://github.com/Reloaded-Project/Reloaded-II/assets/171900604/863d3a7f-5600-4566-80d6-38d45786b798)

**Comment by Sewer56** [comment]
GitHub was seeing too many requests from your IP address (it limits them to 60/hour) and blocked you until the next hour starts.

The installer these days avoids that, so you probably just got a very old installer.
Anyway, grab a newer installer https://github.com/Reloaded-Project/Reloaded-II/releases/download/1.27.9/Setup.exe and you should be fine.

Reopen this issue if you run into any further problems.
