### ISSUE TITLE
Help: Please help me to resolve this problem with P3R 

### ISSUE THREAD

**Issue by thorgal45** [Reloaded-Project/Reloaded-II#392]
I've installed all the prerequisites and the program seems to run well, but every time I tell it where P3R.exe is, i have this : 
![Bug](https://github.com/Reloaded-Project/Reloaded-II/assets/172197543/1e224380-243a-42a0-956a-4c06366ae3c8)
 
as a result, most of the mods I've tested don't work (the game launches but without the expected modifications), I used the mod Is it working ? to check and it doesn't do anything, on the other hand, the Memento mori mod for exemple seems to work with the modified parts in English and the rest in french, since I play in the french version, and unfortunately the Master Quest mod I wanted does nothing
I should add that my Steam installation is not in program files x64 but directly at the root of C:
Could someone help me understand what I did wrong? Thank you!

**Comment by Sewer56** [comment]
You're best off asking in [Persona Modding](https://discord.com/invite/naoto), not many people watch the main loader bug tracker.

Could just be the game using different assets for different languages, could be something else. I wouldn't know personally.

**Comment by thorgal45** [comment]
Thanks, I'll do that.
