### ISSUE TITLE
The entire program has been deleted from my pc for seemingly no reason.

### ISSUE THREAD

**Issue by wangamoses** [Reloaded-Project/Reloaded-II#395]
i have no idea why, but reloaded ii has been entirely deleted from my pc, along with any files connected to it. The shortcut i used to open it is still there, but it shows this when i try to open it.
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/172990850/f3cda273-2aed-44eb-a3de-dbd85c8e3c15)
It asks me to find the file so i can open the shortcut, but i obviously can't because it doesn't exist anymore.
Additionally, i tried to redownload it but it showed this message.
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/172990850/26f5c445-c5d9-442c-aeca-b52770ff0f3d)
No idea what this means whatsoever.
Any help with any of this would be very appreciated.

**Comment by wangamoses** [comment]
Ok now the whole thing has completely broken and shows this when i try to run the shortcut.
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/172990850/09d8e6b4-c56c-4185-9aeb-78d1f4e85a13)
Im fucking pissed off because i was playing Persona 5 royal and had like 45 hours and now all that time is gone completely down the fucking drain

**Comment by Sewer56** [comment]
I suggest checking your Antivirus logs.

Chances are it silently nuked the whole thing and didn't tell you about it; a classic Windows move.

**Comment by Sewer56** [comment]
Also note that running Setup again will delete anything in existing install folder.

It's probably too late, but extracting Release.zip directly over an existing folder is best way to restore files
https://github.com/Reloaded-Project/Reloaded-II/releases/download/1.27.11/Release.zip

**Comment by wangamoses** [comment]
> I suggest checking your Antivirus logs.
> 
> Chances are it silently nuked the whole thing and didn't tell you about it; a classic Windows move.

How exactly would i do this?

**Comment by wangamoses** [comment]
To be honest, im pretty sure trying to recover my files may be a lot cause, but there is still the issue of being unable to reinstall the program, is there any way to fix this?

**Comment by Sewer56** [comment]
Extracting the files from Release.zip manually to a folder should do the job. That's really just doimg what the installer would, before it was stopped by some external program.

**Comment by Sewer56** [comment]
> > I suggest checking your Antivirus logs.
> > Chances are it silently nuked the whole thing and didn't tell you about it; a classic Windows move.
> 
> How exactly would i do this?

It depends on the software you're using.

If it's plain Defender, it's be in 'Windows Security' menu, otherwise it's probably either hidden somewhere in a 'scan' or 'settings' tab depending on the AV you have installed.

**Comment by wangamoses** [comment]
Thanks a lot for your help, it seems to have worked although it didnt say anything in the antivirus logs, so im still not quite sure why it got deleted in the first place, but as long as i can get back to p5r im fine
