### ISSUE TITLE
Help: accidentally closed the tab and i cant find it

### ISSUE THREAD

**Issue by crucifixo** [Reloaded-Project/Reloaded-II#396]
yes i know this is very stupid but i accidentally closed the tab and cannot find the exe to open it back up again. i tried searching with keywords on my computer but i get nothing. is what i need to open under a different name?

thanks!

**Comment by Sewer56** [comment]
`Reloaded-II/Reloaded-II.exe` on your desktop

**Comment by crucifixo** [comment]
i already tried that, i got nothin :/

**Comment by Sewer56** [comment]
What does 'I got nothing' mean here?
Can you not find the file?
Does nothing show up when you run it?

etc.

**Comment by crucifixo** [comment]
no i just searched on my computer for this in my files and nothing came up even though i have a game that ive played off of it for a long time (sorry)

**Comment by Sewer56** [comment]
Other possibility is you either:

- Made it a portable install
- Moved it to another location

A system-wide search for `Reloaded.Mod.Loader.dll` should find the loader. From there you can navigate a few folders up.
