### ISSUE TITLE
Help: Can't launch on CachyOS/Linux

### ISSUE THREAD

**Issue by potaterfry** [Reloaded-Project/Reloaded-II#398]
I'm trying to mod P5R on Linux. I've tried both steps on the tutorial guide on gamebanana, as well as the Linux installation guide on the Reloaded website, but both seem to only result in the Reloaded-II window being stuck on the "Reloaded-II Tutorial" tab and nothing loads in.

All dependencies have been installed already on the P5R prefix as well so not sure what I can do to fix this.

![Screenshot_20240621_142808](https://github.com/Reloaded-Project/Reloaded-II/assets/173441590/e3759301-23aa-49dc-9dda-030e561da047)

**Comment by Sewer56** [comment]
I could never reproduce this personally, so it may just be a difference in installed packages. Or related to video decoding in step 2.

If you navigate to `/home/$USER/.wine/drive_c/users/$USER/AppData/Roaming/Reloaded-Mod-Loader-II` (or your equivalent if using Proton or a non-default WINEPREFIX) and set `"FirstLaunch": false` in the config file, it should hopefully skip the dialog.

**Comment by Sewer56** [comment]
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/6697380/f2f83a82-7f18-414e-b004-92c9c8eae9bd)

For reference, that is `DOTNET_ROOT= wine Reloaded-II.exe` and

```
➜  Reloaded-II pacman -Qs wine
local/wine 9.11-1
    A compatibility layer for running Windows programs
local/wine-gecko 2.47.4-1
    Wine's built-in replacement for Microsoft's Internet Explorer
local/wine-mono 9.1.0-1
    Wine's built-in replacement for Microsoft's .NET Framework
```

**Comment by potaterfry** [comment]
Managed to get it to run but it seems to be constantly crashing on my end after a few minutes

**Comment by Sewer56** [comment]
I don't really know what to suggest for the time being; unfortunately.
I'm working on a linux native successor, but it may take another 1.5-2 years or so; it's a lot of work.

**Comment by potaterfry** [comment]
I'll just be waiting on that one then! No worries as I can just always use the Windows version which works perfectly. Thank you for your work!

**Comment by NaruIzanagi** [comment]
> I'm trying to mod P5R on Linux. I've tried both steps on the tutorial guide on gamebanana, as well as the Linux installation guide on the Reloaded website, but both seem to only result in the Reloaded-II window being stuck on the "Reloaded-II Tutorial" tab and nothing loads in.
> 
> All dependencies have been installed already on the P5R prefix as well so not sure what I can do to fix this.
> 
> ![Screenshot_20240621_142808](https://private-user-images.githubusercontent.com/173441590/341664959-e3759301-23aa-49dc-9dda-030e561da047.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyOTY3ODYsIm5iZiI6MTcxOTI5NjQ4NiwicGF0aCI6Ii8xNzM0NDE1OTAvMzQxNjY0OTU5LWUzNzU5MzAxLTIzYWEtNDlkYy05ZGRhLTAzMGU1NjFkYTA0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNVQwNjIxMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NDZjYzJmOGVmZGQ2NWQ5NzExZDBlZTljYmZhMjE3YjhmYjk5MjNiM2Q2MDkyODRlMWI2NDFkZGQ3ZjM1OTQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BaM0Veinf3X355OWgi837_k1iIZDm2lKbpGt1PZUuWI)

I literally made an Account to May Post a solution. I had the exact same Problem. Even on previously working installs.
In case you are using Proton 9.0 or above (including Experimental) you need to downgrade to 8.0. I have Set my game to Proton 8.0.5, ran the vanilla game once and then proceeded with reloaded. It works now with the Launch method found on gamebanana without the asi Loader.

**Comment by potaterfry** [comment]
> > I'm trying to mod P5R on Linux. I've tried both steps on the tutorial guide on gamebanana, as well as the Linux installation guide on the Reloaded website, but both seem to only result in the Reloaded-II window being stuck on the "Reloaded-II Tutorial" tab and nothing loads in.
> > All dependencies have been installed already on the P5R prefix as well so not sure what I can do to fix this.
> > ![Screenshot_20240621_142808](https://private-user-images.githubusercontent.com/173441590/341664959-e3759301-23aa-49dc-9dda-030e561da047.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyOTY3ODYsIm5iZiI6MTcxOTI5NjQ4NiwicGF0aCI6Ii8xNzM0NDE1OTAvMzQxNjY0OTU5LWUzNzU5MzAxLTIzYWEtNDlkYy05ZGRhLTAzMGU1NjFkYTA0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNVQwNjIxMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NDZjYzJmOGVmZGQ2NWQ5NzExZDBlZTljYmZhMjE3YjhmYjk5MjNiM2Q2MDkyODRlMWI2NDFkZGQ3ZjM1OTQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BaM0Veinf3X355OWgi837_k1iIZDm2lKbpGt1PZUuWI)
> 
> I literally made an Account to May Post a solution. I had the exact same Problem. Even on previously working installs. In case you are using Proton 9.0 or above (including Experimental) you need to downgrade to 8.0. I have Set my game to Proton 8.0.5, ran the vanilla game once and then proceeded with reloaded. It works now with the Launch method found on gamebanana without the asi Loader.

Holy cow this actually fixed things for me. Thank you so much!
