### ISSUE TITLE
Reloaded II won't open

### ISSUE THREAD

**Issue by NinjaUkulele** [Reloaded-Project/Reloaded-II#40]
I've seen this happen two other times, but it looks like there have been different reasons as far as I can tell. Simply put, Reloader II won't open even though I've downloaded the prerequisites, and my computer doesn't seem to accept `dotnet Reloaded-II.dll` as a command

**Comment by Sewer56** [comment]
Can you provide a screenshot?

**Comment by NinjaUkulele** [comment]
![cmdprmpt](https://user-images.githubusercontent.com/69883024/90586306-b618be00-e18b-11ea-96cb-7740e1a6f3f9.png)

**Comment by Sewer56** [comment]
Huh weird. Take a look in `Add/Remove Programs`
A core install should look something like: 
![image](https://user-images.githubusercontent.com/6697380/90586366-f5b4c980-e1ce-11ea-9cf5-fc03e2e2421d.png)

Although in your case it will most likely say "Runtime" or "Desktop Runtime" instead of "SDK".

**Comment by NinjaUkulele** [comment]
![image](https://user-images.githubusercontent.com/69883024/90587367-0b55cf00-e18e-11ea-81be-6a55dadf740e.png)
unless i'm being the Big Dumb, would these be what you mean? they're what I downloaded via the links in the prerequisites part

**Comment by Sewer56** [comment]
Huh weird, very weird. Do try a reinstall. At the very least, typing `dotnet` in the command prompt should yield some results after a clean Core install.

Maybe try rebooting after installing Core, but normally you shouldn't need to.

**Comment by NinjaUkulele** [comment]
![image](https://user-images.githubusercontent.com/69883024/90587770-09404000-e18f-11ea-8e59-1d1aed33bcad.png)
i reinstalled them, and it would seem they're still Weird, but at least the command got a better response
![image](https://user-images.githubusercontent.com/69883024/90587845-3260d080-e18f-11ea-8d47-0ce47d254419.png)

**Comment by Sewer56** [comment]
Oh, it does pick up now.
By the way, you made a typo hehehe.

The launcher should work now, if it doesn't, try opening the command prompt or PowerShell in the mod loader launcher folder (Shift + Right Click, Open with Powershell) and running `dotnet Reloaded-II.dll` as you tried here.

**Comment by NinjaUkulele** [comment]
it works! thanks for the help and pointing out a typo that I cANT FIND- _~~oh wait yes I can~~_
