### ISSUE TITLE
How do I run the program so the Reloaded-II UI appears?

### ISSUE THREAD

**Issue by noni-mizu** [Reloaded-Project/Reloaded-II#405]
**Describe the Issue**
I'm simply trying to run the program but there is no .exe file.
I'm NOT a modder, just a user looking to use mods for Persona 3 Reload. This app is required before I can start adding mods to my game. But there is no basic instruction on how to run the program. Please add this to the documentation for Users. Thanks.

**Comment by Sewer56** [comment]
After you run downloaded [Setup.exe](https://github.com/Reloaded-Project/Reloaded-II/releases/download/1.27.11/Setup.exe), it should install to `Reloaded-II` on your desktop.

Inside there is `Reloaded-II.exe`

**Comment by noni-mizu** [comment]
> After you run downloaded [Setup.exe](https://github.com/Reloaded-Project/Reloaded-II/releases/download/1.27.11/Setup.exe), it should install to `Reloaded-II` on your desktop.
> 
> Inside there is `Reloaded-II.exe`

Thanks so much! Where did this setup.exe file come from? And why isn't it included on the README file? Regardless, thanks a lot!
