### ISSUE TITLE
Bug: i always stuck at 84% in installing the reloaded-II

### ISSUE THREAD

**Issue by 7miw** [Reloaded-Project/Reloaded-II#407]
it always stuck on 84% , and when i close the installation, i cant even delete the failed folder, and when i tried to install again, it still stuck at 84%

please HELP !!

**Comment by Sewer56** [comment]
I replied at 
- https://github.com/Reloaded-Project/Reloaded-II/issues/51#issuecomment-2241589118

**Comment by Sewer56** [comment]
Fixed in issue linked above.
