### ISSUE TITLE
Bug: <Won't install Happens> when <whenever I try >

### ISSUE THREAD

**Issue by Yuloves-uyu** [Reloaded-Project/Reloaded-II#408]
![Bug report](https://github.com/user-attachments/assets/c8ec0c18-c1e9-4597-901c-44dd837cc8ec)

My download gets stuck at 15% and my game keeps crashing whenever I get in. Can someone please help me. Im new to this and have no idea whats going on.

**Comment by Sewer56** [comment]
@Yuloves-uyu The setup is not meant to be ran multiple times as that will incur data loss.

In any case, close your game, delete your Reloaded folder, and only then run setup.
