### ISSUE TITLE
[User Is Missing Write Privileges to Program Files] Bug: Access to the path 'Reloaded-II mod path' is denied 

### ISSUE THREAD

**Issue by Mootje527** [Reloaded-Project/Reloaded-II#410]
When downloading a mod for Persona 5 Royal from the 'Download Mods' category, it shows this small console with the crash info and completely crashes. When restarting Reloaded-II again it will crash again with the same error (see attached video). 

https://github.com/user-attachments/assets/57da2d6c-a268-4249-a91e-a80765a38428

1. Go to 'Reloaded-II'
2. Click on 'Download Mods'
3. Pick any of the mods. (Some work and some don't, no idea why)
4. Download and wait for it to complete. 
5. It will show the error (if not, choose another mod like the nojiggle mod of Persona 5 Royal)

I have no idea what happened here and would appreciate any help.

![image](https://github.com/user-attachments/assets/bcbae033-7b5b-4ef8-9f42-34f396aba64c)

**Comment by Sewer56** [comment]
@Mootje527 You moved your Reloaded folder to Program Files.

Applications not running as admin do not have full write access to Program Files, and therefore Windows is prohibiting you from creating a folder.

Either move to a directory which is writeable for you or (less recommended) run as admin.

**Comment by Mootje527** [comment]
Okay, thank you very much, but its still weird how some mods will write while some don't. But I'll do it and check again. Thanks again
