### ISSUE TITLE
Download Looped when downloading Ryo and BGME

### ISSUE THREAD

**Issue by HyperPixel7** [Reloaded-Project/Reloaded-II#412]
**Describe the Bug**
Download Looped when I was downloading the BGME and Ryo Framework

**Expected Behaviour**
For it to download

**Screenshots**
If applicable, add screenshots to help explain your problem. ![20240813_134401](https://github.com/user-attachments/assets/6546db0a-a71d-49c5-9191-c1b8c55fac6c)

**Comment by Sewer56** [comment]
https://gamebanana.com/mmdl/1252116
https://gamebanana.com/dl/1249322

Download these and drag + drop them onto the Reloaded Window.
(Or install manually)
