### ISSUE TITLE
Linux Bug: "Unable to initialize SteamAPI"

### ISSUE THREAD

**Issue by MrHappyHam** [Reloaded-Project/Reloaded-II#414]
When launching the game (Persona 3 Reload) through Reloaded-II on Linux, it starts booting up and loading mods, but then throws an error in the form of a pop-up, saying "Unable to initialize SteamAPI. Please make sure Steam is running and you are logged in to an account entitled to the game."
Of note, I am experiencing this issue on two different devices. I installed it manually on a machine running Manjaro after I had trouble with Setup.exe. That seems to have worked well, per the Linux Setup Guide.
I then also tried setting it up on a laptop running Garuda Linux, and did not experience issues with Setup.exe and was able to get it installed promptly. Both of these devices experience this issue. This also seems to happen whether or not I've added any mods.

Steps to reproduce the behaviour:
1. Follow the [setup guide](https://reloaded-project.github.io/Reloaded-II/LinuxSetupGuide/) on a Arch-based distribution.
2. After following the steps to make it work with Proton, launch the game through Reloaded-II.

Here is the Wine console output. It doesn't seem to throw any errors in and of itself.

> [SharedScans] [INF] FMemory_Free found at: 14141BBD4
[SharedScans] [INF] Scan for "FMemory_Free" given to 1 listener(s).
[SharedScans] [INF] UGlobalWork_GetUUIResources found at: 14124D113
[SharedScans] [INF] Scan for "UGlobalWork_GetUUIResources" given to 1 listener(s
).
[SharedScans] [INF] GetUGlobalWork found at: 1411C4A90
[SharedScans] [INF] Scan for "GetUGlobalWork" given to 1 listener(s).
[SharedScans] [INF] FAppCalculationItem_Lerp found at: 14127E3B0
[SharedScans] [INF] Scan for "FAppCalculationItem_Lerp" given to 1 listener(s).
[SharedScans] [INF] FUObjectArray found at: 1419D5710
[SharedScans] [INF] Scan for "FUObjectArray" given to 1 listener(s).
[SharedScans] [INF] FGlobalNamePool found at: 1417D2BE9
[SharedScans] [INF] Scan for "FGlobalNamePool" given to 1 listener(s).
[SharedScans] [INF] StaticConstructObject_Internal found at: 1419C69E0
[SharedScans] [INF] Scan for "StaticConstructObject_Internal" given to 1 listene
r(s).
[SharedScans] [INF] GetPrivateStaticClassBody found at: 14185A2D0
[SharedScans] [INF] Scan for "GetPrivateStaticClassBody" given to 1 listener(s).
[SharedScans] [INF] GetSpriteItemMaskInstance found at: 1413E8738
[SharedScans] [INF] Scan for "GetSpriteItemMaskInstance" given to 2 listener(s).
[SharedScans] [INF] UIDraw_SetPresetBlendState found at: 1412FA4F0
[SharedScans] [INF] Scan for "UIDraw_SetPresetBlendState" given to 1 listener(s)
.
[SharedScans] [INF] USprAsset_FUN_141323540 found at: 1413E8801
[SharedScans] [INF] Scan for "USprAsset_FUN_141323540" given to 1 listener(s).
[SharedScans] [INF] UPlgAsset_FUN_14131f0d0 found at: 14131C900
[SharedScans] [INF] Scan for "UPlgAsset_FUN_14131f0d0" given to 1 listener(s).
[SharedScans] [INF] UIDraw_SetBlendState found at: 140CC85D0
[SharedScans] [INF] Scan for "UIDraw_SetBlendState" given to 1 listener(s).
[SharedScans] [INF] DrawComponentMask_FUN_140cb27f0 found at: 14143A4CC
[SharedScans] [INF] Scan for "DrawComponentMask_FUN_140cb27f0" given to 1 listen
er(s).
[SharedScans] [INF] DrawComponentMask_FUN_14bffbdd0 found at: 14C32E220
[SharedScans] [INF] Scan for "DrawComponentMask_FUN_14bffbdd0" given to 1 listen
er(s).
[SharedScans] [INF] DrawComponentMask_FUN_140cc8760 found at: 14141ADEE
[SharedScans] [INF] Scan for "DrawComponentMask_FUN_140cc8760" given to 1 listen
er(s).
[SharedScans] [INF] DrawComponentMask_ActiveDrawTypeId found at: 1411191FF
[SharedScans] [INF] Scan for "DrawComponentMask_ActiveDrawTypeId" given to 1 lis
tener(s).
[SharedScans] [INF] DrawSingleLineText found at: 14143AD2E
[SharedScans] [INF] Scan for "DrawSingleLineText" given to 1 listener(s).
[SharedScans] [INF] AUIDrawBaseActor_DrawPlg found at: 14127E50D
[SharedScans] [INF] Scan for "AUIDrawBaseActor_DrawPlg" given to 1 listener(s).
[SharedScans] [INF] AUIDrawBaseActor_DrawSpr found at: 1413004B0
[SharedScans] [INF] Scan for "AUIDrawBaseActor_DrawSpr" given to 1 listener(s).
[SharedScans] [INF] AUIDrawBaseActor_SetRenderTarget found at: 140CC8BC0
[SharedScans] [INF] Scan for "AUIDrawBaseActor_SetRenderTarget" given to 1 liste
ner(s).
[SharedScans] [INF] AUIDrawBaseActor_DrawRect found at: 1412FD990
[SharedScans] [INF] Scan for "AUIDrawBaseActor_DrawRect" given to 1 listener(s).
[SharedScans] [INF] AUIDrawBaseActor_DrawRectV4 found at: 1412FD5D0
[SharedScans] [INF] Scan for "AUIDrawBaseActor_DrawRectV4" given to 1 listener(s
).
[P3RE Native Types] Found gMalloc at 1456771B0
[SharedScans] [INF] UClass_DeferredRegister found at: 1418560B0
[SharedScans] [INF] Scan for "UClass_DeferredRegister" given to 1 listener(s).
[SharedScans] [INF] UObjectProcessRegistrants found at: 1419CAD40
[SharedScans] [INF] Scan for "UObjectProcessRegistrants" given to 1 listener(s).
[SharedScans] [INF] FName_Ctor found at: 1417C6010
[SharedScans] [INF] Scan for "FName_Ctor" given to 1 listener(s).
[SharedScans] [INF] FUObjectHashTables_Get found at: 1419D3F32
[SharedScans] [INF] Scan for "FUObjectHashTables_Get" given to 1 listener(s).
[Femc Project] Couldn't find location for UMsgProcWindow_Mind::DrawMessageBox us
ing pattern 40 55 57 48 8D AC 24 ?? ?? ?? ?? 48 81 EC 28 02 00 00, trying with a
nother pattern...
[Femc Project] Couldn't find location for UMsgProcWindow_Mind::DrawMessageBoxLef
tSpotBg1 using pattern 4C 8B 87 ?? ?? ?? ?? 48 8D 4D ?? 45 0F 57 C9, trying with
 another pattern...
[Femc Project] Couldn't find location for UMsgProcWindow_Mind::DrawMessageBoxLef
tSpotBg2 using pattern 4C 8B 87 ?? ?? ?? ?? 48 8D 4D ?? 0F 57 DB F3 44 0F 11 4C
24 ?? 49 8B D6, trying with another pattern...
[Femc Project] Couldn't find location for AUIAccessInfoDraw::DrawMinimap using p
attern 4C 8B DC 55 57 49 8D AB ?? ?? ?? ?? 48 81 EC D8 01 00 00 45 0F 29 A3 ?? ?
? ?? ??, trying with another pattern...
################################################################################
                 ASSET COLLECTOR: Collected files from 12 mods
================================================================================
C:\users\USERNAME\Desktop\Reloaded-II\Mods\p3r.skins.extendedoutfits\UnrealEssenti
als
19 directories added
3 added files (49 KB)
0 replaced files (0 KB)
================================================================================
C:\users\USERNAME\Desktop\Reloaded-II\Mods\Femc_Project1.2.1\UnrealEssentials
1725 directories added
3400 added files (1725537 KB)
0 replaced files (0 KB)
================================================================================
C:\users\USERNAME\Desktop\Reloaded-II\Mods\Femc_Project1.2.1\3d\hair\MudkipHair
9 directories added
29 added files (25665 KB)
0 replaced files (0 KB)
================================================================================
C:\users\USERNAME\Desktop\Reloaded-II\Mods\Femc_Project1.2.1\2d\AOA\Ely
7 directories added
4 added files (41301 KB)
0 replaced files (0 KB)
================================================================================
C:\users\USERNAME\Desktop\Reloaded-II\Mods\Femc_Project1.2.1\2d\AOAText\SorryBoutT
hat
7 directories added
1 added files (2032 KB)
0 replaced files (0 KB)
================================================================================
C:\users\USERNAME\Desktop\Reloaded-II\Mods\Femc_Project1.2.1\2d\Bustup\Neptune
7 directories added
5 added files (4613 KB)
0 replaced files (0 KB)
================================================================================
C:\users\USERNAME\Desktop\Reloaded-II\Mods\Femc_Project1.2.1\2d\Shard\Esa
41 directories added
20 added files (29155 KB)
0 replaced files (0 KB)
================================================================================
C:\users\USERNAME\Desktop\Reloaded-II\Mods\Femc_Project1.2.1\2d\LevelUp\Esa
67 directories added
52 added files (71030 KB)
0 replaced files (0 KB)
================================================================================
C:\users\USERNAME\Desktop\Reloaded-II\Mods\Femc_Project1.2.1\2d\Cutin\berrycha
10 directories added
2 added files (2264 KB)
0 replaced files (0 KB)
================================================================================
C:\users\USERNAME\Desktop\Reloaded-II\Mods\Femc_Project1.2.1\Fun Stuff\Funny Anims
og
8 directories added
2 added files (217 KB)
0 replaced files (0 KB)
================================================================================
C:\users\USERNAME\Desktop\Reloaded-II\Mods\Femc_Project1.2.1\Fun Stuff\GregoryHous
eRatPoisonDeliverySystemog
9 directories added
3 added files (1196 KB)
0 replaced files (0 KB)
================================================================================
C:\users\USERNAME\Desktop\Reloaded-II\Mods\Femc_Project1.2.1\3d\Nagitana
8 directories added
77 added files (53868 KB)
0 replaced files (0 KB)
================================================================================
Built table of contents
Built container file
[Unreal Essentials] Loading PAK files from C:\users\USERNAME\Desktop\Reloaded-II\M
ods\UTOC.Stream.Emulator\TargetFiles
[Reloaded] Loading Mods (Total) | Time: 6584ms
[Reloaded] Total Loader Initialization Time: 6730ms

**Comment by Sewer56** [comment]
I'm not really sure if there's anything I can do here. I've never seen this DRM (Copy Protection) error outside of the context of people launching the game with Steam closed on Windows.

Do make sure you're booting from Steam though for Steam titles, it's possible that booting from the R2 launcher might skip some of their initialisation mechanisms required for handling DRM'd content under Wine.

**Comment by MrHappyHam** [comment]
Interesting. I know people have gotten this to work, so it likely is some issues with Wine.

**Comment by Sewer56** [comment]
Just start the game from the Steam client, and it'll probably be alright.

**Comment by MrHappyHam** [comment]
Tried that after running ASI loader and editing launch options. It doesn't seem to work, though it doesn't throw any errors. Should a wine console be launched when doing so?

**Comment by Sewer56** [comment]
Can you screenshot your launch option and game folder?

**Comment by MrHappyHam** [comment]
Pardon the wait.
![Game folder](https://github.com/user-attachments/assets/0eb8d3be-6980-4ad1-8c48-2627983bab5c)

![Launch options](https://github.com/user-attachments/assets/4434c8c3-cd0a-4b38-a23d-d9223d67b933)

![Link between wine prefix and proton game prefix](https://github.com/user-attachments/assets/53f81bc9-c8a1-4bc9-981c-83ac571faad9)

**Comment by Sewer56** [comment]
You need to change the `WINEDLLOVERRIDES` from `version` to `dsound`.
You probably missed that small part of the guide.

**Comment by MrHappyHam** [comment]
Well hey, I did miss that. It seems to work correctly now. Much appreciated. You're the best!

**Comment by Sewer56** [comment]
No worries, have fun :p
