### ISSUE TITLE
Bug: "Error: Access to the path '<path>\steam_appid.txt' is denied" when launching Persona 3 Reloaded

### ISSUE THREAD

**Issue by DaithiFeMCFan** [Reloaded-Project/Reloaded-II#416]
**Describe the Bug**
I am receiving the above error message when attempting to launch my Steam copy of P3R through Reloaded-II. This started happening today, despite the fact that I was able to play the game with no issues earlier this morning and yesterday.

This started when I attempted to install a copy of the FeMC mod, into which I had manually added an additional .uasset file.
This may very well have been the initial cause of failure to launch, but I am still receiving the above error after reinstalling both the game and Reloaded.

So far, I have tried giving Reloaded permission on Windows Defender and running as admin, to no effect.

See screenshot.
![2024-08-19_Fail_to_Launch_No_Mods](https://github.com/user-attachments/assets/d333e9e5-a844-42ef-8630-ad7ce0626536)

**Comment by Sewer56** [comment]
I would just delete the file it says it can't access, and then retry. If it doesn't work, restart machine.

**Comment by DaithiFeMCFan** [comment]
> I would just delete the file it says it can't access, and then retry. If it doesn't work, restart machine.

Thank you very much for your quick reply! This worked!

**Comment by Sewer56** [comment]
No worries, have fun and happy gaming!!
