### ISSUE TITLE
Bug: <Y Happens> when <X>

### ISSUE THREAD

**Issue by Akko003** [Reloaded-Project/Reloaded-II#417]
When i try to install ReloadedII i get an error

I just started the setup.exe

![image](https://github.com/user-attachments/assets/beda108d-51a8-40f6-8899-2999c282898b)

**Comment by Sewer56** [comment]
Use a more up to date setup.exe

https://github.com/Reloaded-Project/Reloaded-II/releases/download/1.27.12/Setup.exe

Where did you get yours?

**Comment by Akko003** [comment]
I used the last in date. I got it from Github. 
![image](https://github.com/user-attachments/assets/053d1999-4837-4839-afcd-6936dccece1c)

**Comment by Sewer56** [comment]
Presumably issue was resolved. If it was not, open another issue or comment here.
