### ISSUE TITLE
[Linux] Reloaded can't find steam library when trying to open up a game

### ISSUE THREAD

**Issue by Lucass003** [Reloaded-Project/Reloaded-II#418]
I get this in the console that appears:
[16:35:46] [Reloaded] Create Loader | Time: 33ms
[16:35:46] [Reloaded] Loading 1 Mod(s).
[16:35:46] [Reloaded] 
[16:35:46] [Reloaded] Loading: Reloaded II Shared Lib: Reloaded.Hooks
[16:35:46] [Reloaded] - AppId   : reloaded.sharedlib.hooks
[16:35:46] [Reloaded] - Location: Z:\home\lucas\Desktop\Games\Reloaded 2\Mods\reloaded.sharedlib.hooks\ModConfig.json
[16:35:46] [Reloaded] - LoadTime: 5ms
[16:35:46] [Reloaded] Loaded via: Z:\home\lucas\Desktop\Games\Reloaded 2\Loader\x64\Bootstrapper\Reloaded.Mod.Loader.Bootstrapper.dll
[16:35:46] [Reloaded] Current Process Location: Z:\home\lucas\.local\share\Steam\steamapps\common\P3R\P3R\Binaries\Win64\P3R.exe
[16:35:46] [Reloaded] Loading Mods (Total) | Time: 10ms
[16:35:46] [R-II SteamHook] SteamAPI_RestartAppIfNecessary hooked successfully.
[16:35:46] [R-II SteamHook] SteamAPI_IsSteamRunning hooked successfully.
[16:35:46] [R-II SteamHook] Failed to scan through Steam games and locate current game. Error: Steam Directory was not found!,    at Indieteur.SAMAPI.SteamAppsManager..ctor()
   at Reloaded.Mod.Loader.Utilities.Steam.SteamHook.DropSteamAppId(Logger logger)
[16:35:46] [Reloaded] Setting Up Hooks (Async) | Time: 174ms
[16:35:46] [Reloaded] Total Loader Initialization Time: 226ms

I also get this pop up
![Screenshot from 2024-08-20 16-34-41](https://github.com/user-attachments/assets/0d15899e-7583-40e6-8d02-76f03b991969)
I'm on Linux Mint 21.2, so did I maybe screw something up in wine?

**Comment by Sewer56** [comment]
@Lucass003 You're being penalized by Steam's copy protection (unfortunately).

Set up R2 using the ASI Loader method and instead start the game via Steam itself.

**Comment by Lucass003** [comment]
> @Lucass003 You're being penalized by Steam's copy protection (unfortunately).
> 
> Set up R2 using the ASI Loader method and instead start the game via Steam itself.

Alrighty. I was trying to to that, but realized the Proton part was done improperly, because I couldn't run the installer (I previously tried to run it to install R2 in general, but went with the manual option, because it didn't work before, and didn't know I'd need it again.

Here's what shows up in the console when trying to run the second comand under the "proton" section of the linux settup guide-
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:xinput:pdo_pnp IRP_MN_QUERY_ID type 5, not implemented!
0084:fixme:xinput:pdo_pnp IRP_MN_QUERY_ID type 5, not implemented!
0084:fixme:xinput:pdo_pnp IRP_MN_QUERY_ID type 5, not implemented!
0084:fixme:xinput:pdo_pnp IRP_MN_QUERY_ID type 5, not implemented!
00e8:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION

Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'ConsoleProgressBar, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'ConsoleProgressBar, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'
  at Reloaded.Mod.Installer.Program.Main (System.String[] args) [0x0002b] in <d04eb840636e439793442e93ff12251e>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'ConsoleProgressBar, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'ConsoleProgressBar, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'

**Comment by Sewer56** [comment]
Weird, never seen it fail to unpack before.

Here, try installing the runtimes manually:

- https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-8.0.8-windows-x64-installer
- https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-8.0.8-windows-x86-installer

Instead of running `Setup.exe` in the [`Proton` section](https://reloaded-project.github.io/Reloaded-II/LinuxSetupGuide/#proton)

**Comment by Lucass003** [comment]
No, still doesn't seem to be loading. I was able to create the symbolic link at least. I'm guessing something with Wine is stopping things from working properly, but I don't know what sadly

**Comment by Sewer56** [comment]
Technically it's possible, Ubuntu, Debian and Mint are notorious for shipping very old versions of Wine. You may have some luck using protontricks to do that installed using proton itself.

**Comment by Lucass003** [comment]
Okay. You know how I might be able to use it to get it working? I have it installed, but I don't really know it well

**Comment by Sewer56** [comment]
You might have some luck with using protontricks. IIRC if you right click an executable you can launch it with 'Protontricks Launcher', and run something in a prefix from there.

**Comment by Lucass003** [comment]
Okay, I tried running R2 through Persona 3 Reload, the game I'm trying to run (assuming that's what you meant?) but I just get this error
![Screenshot from 2024-08-20 23-04-37](https://github.com/user-attachments/assets/ca3a6937-ee06-4908-a1ed-a76fe24f2ac1)
I'm pretty sure it's the thing I had just installed,and when I hit yes on this prompt, nothing changes, even when I try again

**Comment by Lucass003** [comment]
Oh, by the way, I also tried creating a desktop shortcut that would open R2 with P3R automatically, though it instantly crashes, probally because of all the other issues. I mention it so I can put the log here, in case it's any herp

> Unhandled exception: 0xe0434352 in 64-bit code (0x006fffff443c47).
> Register dump:
>  rip:00006fffff443c47 rsp:00007ffffe27df40 rbp:00007ffffe27e2b0 eflags:00000202 (   - --  I   - - - )
>  rax:00007ffffe27dfa0 rbx:00007ffffe27e0d8 rcx:00007ffffe27df60 rdx:0000000000000000
>  rsi:0000000000000001 rdi:0000000000000005  r8:00006ffffc400000  r9:00007ffffe27e0f8 r10:0000000000000001
>  r11:00007ffffe27e008 r12:0000000000000000 r13:00007f93ec40ab10 r14:00000000e0434352 r15:0000000000004000
> Stack dump:
> 0x007ffffe27df40:  00007ffffe27df60 00007b9d4e0da29d
> 0x007ffffe27df50:  00007ffffe2adf00 00006ffffc547ca0
> 0x007ffffe27df60:  00000001e0434352 0000000000000000
> 0x007ffffe27df70:  00006fffff443c47 00006fff00000005
> 0x007ffffe27df80:  ffffffff80131508 0000000000000000
> 0x007ffffe27df90:  0000000000000000 0000000000000000
> 0x007ffffe27dfa0:  00006ffffc400000 00007ffffe27e0e0
> 0x007ffffe27dfb0:  00006ffffc547ca0 00006fff9c9d8b10
> 0x007ffffe27dfc0:  0000000000000001 0000000000000000
> 0x007ffffe27dfd0:  0000000000000000 0000000000000000
> 0x007ffffe27dfe0:  00007fffffa22dd0 00007ffffe27e198
> 0x007ffffe27dff0:  00007fff00000001 00006ffffc4beeaa
> Backtrace:
> =>0 0x006fffff443c47 in kernelbase (+0x13c47) (0x007ffffe27e2b0)
>   1 0x006ffffc4b61ce in coreclr (+0xb61ce) (0x007ffffe27e2b0)
>   2 0x006ffffc4b5349 in coreclr (+0xb5349) (0x007ffffe27e2b0)
> 0x006fffff443c47 kernelbase+0x13c47: add $0xc8, %rsp
> Modules:
> Module  Address                                 Debug info      Name (131 modules, 33 for wow64 not listed)
> PE             100400000-       10135e000       Deferred        presentationframework
> PE             101360000-       101584000       Deferred        windowsbase
> PE             101590000-       1016e8000       Deferred        system.xaml
> PE             1016f0000-       101734000       Deferred        system.io.packaging
> PE             101740000-       10177d000       Deferred        system.private.uri
> PE             101780000-       101fa3000       Deferred        presentationcore
> PE             101fb0000-       102027000       Deferred        directwriteforwarder
> PE             102030000-       102045000       Deferred        system.runtime.interopservices
> PE             102050000-       102055000       Deferred        system.runtime.compilerservices.visualc
> PE             102060000-       102072000       Deferred        system.threading
> PE             102080000-       102097000       Deferred        system.collections.nongeneric
> PE             1020a0000-       1020bb000       Deferred        microsoft.win32.registry
> PE             1020c0000-       1020fd000       Deferred        system.collections
> PE             102100000-       102117000       Deferred        system.collections.specialized
> PE             102120000-       102144000       Deferred        system.memory
> PE             102150000-       102161000       Deferred        system.componentmodel.primitives
> PE             102170000-       102274000       Deferred        system.configuration.configurationmanager
> PE             102280000-       102a1c000       Deferred        system.private.xml
> PE             102a20000-       102a47000       Deferred        system.net.webclient
> PE             102a50000-       102ad2000       Deferred        system.linq
> PE             102ae0000-       102b01000       Deferred        system.diagnostics.tracesource
> PE             102b10000-       102bc3000       Deferred        system.componentmodel.typeconverter
> PE             102bd0000-       102bea000       Deferred        system.windows.extensions
> PE             102bf0000-       102bf5000       Deferred        system.componentmodel
> PE             102c00000-       102c41000       Deferred        system.collections.concurrent
> PE             102c50000-       102c61000       Deferred        system.objectmodel
> PE             102c70000-       102cc2000       Deferred        system.net.requests
> PE             102cd0000-       102d06000       Deferred        system.net.primitives
> PE             102d10000-       102e70000       Deferred        system.windows.controls.ribbon
> PE             102e70000-       102ec0000       Deferred        system.diagnostics.process
> PE             102ec0000-       102f00000       Deferred        presentationframework.classic
> PE             102f00000-       102f09000       Deferred        system.componentmodel.eventbasedasync
> PE             102f10000-       102f5a000       Deferred        uiautomationtypes
> PE             102f60000-       103098000       Deferred        presentationui
> PE             1031a0000-       10330c000       Deferred        system.text.json
> PE             103310000-       103323000       Deferred        system.io.filesystem.watcher
> PE             103930000-       103caf000       Deferred        system.linq.expressions
> PE             103cb0000-       103cce000       Deferred        system.text.encodings.web
> PE             103cd0000-       103cfb000       Deferred        system.security.principal.windows
> PE             103d00000-       103d16000       Deferred        system.security.claims
> PE             103d20000-       103d29000       Deferred        system.diagnostics.stacktrace
> PE             103d30000-       103e3e000       Deferred        system.reflection.metadata
> PE             103e40000-       103f0a000       Deferred        system.collections.immutable
> PE             140000000-       14003b000       Deferred        reloaded-ii
> PE             180000000-       180c8d000       Deferred        system.private.corelib
> PE          6ffff8970000-    6ffff8baa000       Deferred        microsoft.diasymreader.native.amd64
> PE-Wine     6ffff8bc0000-    6ffff8c37000       Deferred        propsys
> PE-Wine     6ffff8c50000-    6ffff94dc000       Deferred        windowscodecs
> PE-Wine     6ffff94f0000-    6ffff972f000       Deferred        wininet
> PE-Wine     6ffff9740000-    6ffff9a56000       Deferred        urlmon
> PE          6ffff9a70000-    6ffff9f28000       Deferred        d3dcompiler_47_cor3
> PE          6ffff9f40000-    6ffffa125000       Deferred        wpfgfx_cor3
> PE          6ffffa140000-    6ffffa26f000       Deferred        presentationnative_cor3
> PE-Wine     6ffffa280000-    6ffffa5a3000       Deferred        dwrite
> PE-Wine     6ffffab50000-    6ffffac14000       Deferred        uxtheme
> PE-Wine     6ffffac30000-    6ffffaf11000       Deferred        dbghelp
> PE-Wine     6ffffaf30000-    6ffffb024000       Deferred        mscoree
> PE-Wine     6ffffb2b0000-    6ffffb2cf000       Deferred        version
> PE-Wine     6ffffb4a0000-    6ffffb51c000       Deferred        imm32
> PE-Wine     6ffffb8d0000-    6ffffb933000       Deferred        mpr
> PE-Wine     6ffffb950000-    6ffffbe4e000       Deferred        oleaut32
> PE-Wine     6ffffbe60000-    6ffffc3eb000       Deferred        ole32
> PE          6ffffc400000-    6ffffc8e8000       Export          coreclr
> PE-Wine     6ffffc900000-    6ffffd693000       Deferred        shell32
> PE-Wine     6ffffd6b0000-    6ffffd937000       Deferred        rpcrt4
> PE-Wine     6ffffd950000-    6ffffd98d000       Deferred        win32u
> PE-Wine     6ffffd9a0000-    6ffffdf73000       Deferred        user32
> PE-Wine     6ffffdf90000-    6ffffe25b000       Deferred        gdi32
> PE-Wine     6ffffe280000-    6ffffe2dd000       Deferred        bcrypt
> PE-Wine     6ffffe2f0000-    6ffffe347000       Deferred        winex11
> PE          6ffffe360000-    6ffffe517000       Deferred        clrjit
> PE-Wine     6ffffe530000-    6ffffe57b000       Deferred        coml2
> PE-Wine     6ffffe590000-    6ffffe726000       Deferred        combase
> PE          6ffffe740000-    6ffffe7a2000       Deferred        hostpolicy
> PE          6ffffe7c0000-    6ffffe817000       Deferred        hostfxr
> PE-Wine     6ffffe830000-    6ffffe880000       Deferred        shcore
> PE-Wine     6ffffe890000-    6ffffe9a1000       Deferred        shlwapi
> PE-Wine     6ffffe9c0000-    6ffffea6d000       Deferred        ws2_32
> PE-Wine     6ffffea80000-    6ffffee7d000       Deferred        ucrtbase
> PE-Wine     6ffffee90000-    6ffffef50000       Deferred        sechost
> PE-Wine     6ffffef60000-    6fffff2c1000       Deferred        msvcrt
> PE-Wine     6fffff2e0000-    6fffff411000       Deferred        advapi32
> PE-Wine     6fffff430000-    6fffffa65000       Dwarf-4         kernelbase
> PE-Wine     6fffffa80000-    6fffffc3d000       Deferred        kernel32
> PE-Wine     6fffffc50000-    6fffffff0000       Deferred        ntdll
> ELF         7f9351c9a000-    7f9351d1c000       Deferred        libgmp.so.10
> ELF         7f9351d1c000-    7f9351d64000       Deferred        libhogweed.so.6
> ELF         7f9351d64000-    7f9351daa000       Deferred        libnettle.so.8
> ELF         7f9351daa000-    7f9351dc2000       Deferred        libtasn1.so.6
> ELF         7f9351dc2000-    7f9351f6c000       Deferred        libunistring.so.2
> ELF         7f9351f6c000-    7f9351f8d000       Deferred        libidn2.so.0
> ELF         7f9351f8d000-    7f93520c8000       Deferred        libp11-kit.so.0
> ELF         7f93520c8000-    7f93522b3000       Deferred        libgnutls.so.30
> ELF         7f9352ab0000-    7f9352ac4000       Deferred        libxi.so.6
> ELF         7f9352ac4000-    7f9352adc000       Deferred        libbsd.so.0
> ELF         7f9352adc000-    7f9352b06000       Deferred        libxcb.so.1
> ELF         7f9352b06000-    7f9352c46000       Deferred        libx11.so.6
> ELF         7f9352c46000-    7f9352c5b000       Deferred        libxext.so.6
> ELF         7f9352c78000-    7f9352d00000       Deferred        winex11.so
> ELF         7f9352d2f000-    7f9352d53000       Deferred        libgcc_s.so.1
> ELF         7f9353083000-    7f9353090000       Deferred        libffi.so.8
> ELF         7f93530a4000-    7f93530b0000       Deferred        bcrypt.so
> ELF         7f93534b2000-    7f93534b8000       Deferred        dwrite.so
> ELF         7f93534b8000-    7f93534c0000       Deferred        libxfixes.so.3
> ELF         7f93534cd000-    7f93534d4000       Deferred        ws2_32.so
> ELF         7f93534d4000-    7f93534e0000       Deferred        libxcursor.so.1
> ELF         7f9353663000-    7f9353670000       Deferred        libxrandr.so.2
> ELF         7f9353873000-    7f9353880000       Deferred        libxrender.so.1
> ELF         7f93e83ab000-    7f93e83b0000       Deferred        libxcomposite.so.1
> ELF         7fd3ec3b3000-    7fd3ec3c0000       Deferred        libmd.so.0
> ELF         7fd3ec541000-    7fd3ec548000       Deferred        libxxf86vm.so.1
> ELF         7fd3ec548000-    7fd3ec550000       Deferred        libxdmcp.so.6
> ELF         7fd3ec55b000-    7fd3ec560000       Deferred        libxinerama.so.1
> ELF         7fd3ec674000-    7fd3ec67a000       Deferred        libxau.so.6
> ELF         7fd3ec73a000-    7fd3ec743000       Deferred        libuuid.so.1
> ELF         7fd3ec743000-    7fd3ec774000       Deferred        libexpat.so.1
> ELF         7fd3ec774000-    7fd3ec7be000       Deferred        libfontconfig.so.1
> ELF         7fd3ec7be000-    7fd3ec7e1000       Deferred        libbrotlicommon.so.1
> ELF         7fd3ec7e1000-    7fd3ec7ef000       Deferred        libbrotlidec.so.1
> ELF         7fd3ec7ef000-    7fd3ec80b000       Deferred        libz.so.1
> ELF         7fd3ec80b000-    7fd3ec846000       Deferred        libpng16.so.16
> ELF         7fd3ec846000-    7fd3ec90e000       Deferred        libfreetype.so.6
> ELF         7fd3ec90e000-    7fd3ec9f5000       Deferred        libm.so.6
> ELF         7fd3ec9f5000-    7fd3ecb93000       Deferred        win32u.so
> ELF         7fd3ed506000-    7fd3ed531000       Deferred        liblzma.so.5
> ELF         7fd3ed531000-    7fd3ed54c000       Deferred        libunwind.so.8
> ELF         7fd3ed54c000-    7fd3ed607000       Export          ntdll.so
> ELF         7fd3ed60a000-    7fd3ed833000       Deferred        libc.so.6
> ELF         7fd3ed852000-    7fd3ed88e000       Deferred        ld-linux-x86-64.so.2
> ELF         7fd3ed88e000-    7fd3ed893000       Deferred        <wine-loader>
> PE          7fffffaf0000-    7fffffafe000       Deferred        system.net.webheadercollection
> Threads:
> process  tid      prio    name (all IDs are in hex)
> 00000038 services.exe
> 	0000003c    0     
> 	00000040    0     wine_rpcrt4_server
> 	0000004c    0     wine_rpcrt4_io
> 	00000078    0     wine_rpcrt4_io
> 	00000084    0     wine_rpcrt4_io
> 	000000b0    0     wine_rpcrt4_io
> 	000000c8    0     wine_rpcrt4_io
> 	000000dc    0     
> 	00000120    0     wine_rpcrt4_io
> 00000044 winedevice.exe
> 	00000048    0     
> 	0000005c    0     
> 	00000060    0     wine_sechost_service
> 	00000064    0     
> 	00000068    0     
> 	0000006c    0     
> 	000000d4    0     
> 	000000d8    0     
> 00000070 winedevice.exe
> 	00000074    0     
> 	0000007c    0     
> 	00000080    0     wine_sechost_service
> 	00000088    0     
> 	0000008c    0     
> 	00000090    0     
> 	00000094    0     
> 	00000098    0     
> 	000000a8    0     
> 	000000ac    0     
> 000000a0 plugplay.exe
> 	000000a4    0     
> 	000000b4    0     
> 	000000b8    0     wine_sechost_service
> 	000000bc    0     wine_rpcrt4_server
> 	00000194    0     wine_threadpool_worker
> 000000c0 svchost.exe
> 	000000c4    0     
> 	000000cc    0     
> 	000000d0    0     wine_sechost_service
> 00000118 rpcss.exe
> 	0000011c    0     
> 	00000124    0     
> 	00000128    0     wine_sechost_service
> 	0000012c    0     wine_rpcrt4_server
> 	00000130    0     wine_rpcrt4_server
> 	000001bc    0     wine_threadpool_worker
> 	000001f4    0     wine_rpcrt4_io
> 000001c0 start.exe
> 	000001c4    0     
> 000001c8 (D) Z:\home\lucas\Desktop\Games\Reloaded 2\Reloaded-II.exe
> 	000001cc    0 <== 
> 	000001d0    0     .NET EventPipe
> 	000001d4    0     .NET Debugger
> 	000001d8    2     .NET Finalizer
> 	000001dc    0     .NET Tiered Compilation Worker
> 	000001f8    0     .NET BGC
> 	000001fc    1     .NET ThreadPool IO
> 	00000200    1     .NET ThreadPool IO
> 	00000204    0     .NET TP Worker
> 	00000208    0     .NET TP Gate
> 	0000020c    0     .NET TP Worker
> 	00000210    0     .NET TP Worker
> 	00000224    0     
> 000001e4 explorer.exe
> 	000001e8    0     
> 	000001ec    0     
> 	000001f0    0     wine_rpcrt4_server
> 0000021c conhost.exe
> 	00000220    0     
> System information:
>     Wine build: wine-9.0
>     Platform: x86_64 (guest: i386)
>     Version: Windows 7
>     Host system: Linux
>     Host version: 5.15.0-118-generic
>

**Comment by Sewer56** [comment]
> Okay, I tried running R2 through Persona 3 Reload, the game I'm trying to run (assuming that's what you meant?) but I just get this error ![Screenshot from 2024-08-20 23-04-37](https://private-user-images.githubusercontent.com/131922887/359732708-ca3a6937-ee06-4908-a1ed-a76fe24f2ac1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNDMxMjgsIm5iZiI6MTcyNDI0MjgyOCwicGF0aCI6Ii8xMzE5MjI4ODcvMzU5NzMyNzA4LWNhM2E2OTM3LWVlMDYtNDkwOC1hMWVkLWE3NmZlMjRmMmFjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQxMjIwMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YWE1MGFiOTRiMzM1OWY1MTgxNTUxZTgwMzcxOTNlNmExZGVkODMxZThlMDc2NmQ4NGMxZTYzNGY0ZjUzZTczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lrnQILkEM62puNy4AQ_4N-fd6RR7Bvw8B2xDofDOvg4) I'm pretty sure it's the thing I had just installed,and when I hit yes on this prompt, nothing changes, even when I try again

That's why I suggested running the installers manually here https://github.com/Reloaded-Project/Reloaded-II/issues/418#issuecomment-2299820094

If you reacted to the prompt, chances are you installed them in regular Wine when you need to install it into the WINEPREFIX used by your game's proton instance. (i.e. via Protontricks Launcher)

**Comment by Lucass003** [comment]
Okay, it looks like I got it! I just had to use protron tricks to use P3R's prefix and set the non-reloaded dll's library override there! Thank you so much!
