### ISSUE TITLE
getting mods to work again

### ISSUE THREAD

**Issue by nonsmarts** [Reloaded-Project/Reloaded-II#419]
A while back when I was having a different problem with P3R, someone told me to"Delete your Reloaded.Mod.Bootstrapper.asi in game folder" and I did.  It later turned out that the problem had nothing to do with Reloaded-II but rather my PC.  I got my PC fixed but now I can run any mods, presumably because I deleted the aforementioned folder.  How would I go about restoring it?

**Comment by Sewer56** [comment]
@nonsmarts 

That gets placed in your game folder by the 'Deploy ASI Loader' function in Edit Application menu inside Reloaded-II. I think running rhat again would work.

If it doesn't, let me know

**Comment by Sewer56** [comment]
Closing as stale. Please respond or re-open the issue if needed.
