### ISSUE TITLE
Request: UI Improvements and Changes

### ISSUE THREAD

**Issue by Sewer56** [Reloaded-Project/Reloaded-II#42]
# UI Improvements and Changes
This is a random collection of feedback from various users, from waifu to long time community contributors.
This list is being updated as time progresses.

# Shell Sidebar
![image](https://user-images.githubusercontent.com/6697380/90603012-7fc25980-e1f2-11ea-9c7f-fc23caff4e81.png)

## Sorting
- [x] Complete

There is currently no order to how the individual games are displayed, as it is only expected to have users add 3-4 applications at most. However, Reloaded has been getting traction and for the real power users out there, sooner or later this number may expand.

The current display order is alphabetically by `AppId` (normally EXE name), because that is how the list of configs is returned from filesystem, however it may be a good idea to sort items by most commonly used at the top.

To do this, we'll need to add an open tracker into each `AppConfig` for the number of times the application has been launched.
Don't know if we should track application launches (have loader increment the counter) or the amount of times the icon has been clicked in the launcher.

## Recents
- [ ] Complete

The most recently selected items might be displayed either in the default screen of the application or in the default/settings/info menu.

## More Useful Links
- [x] Reloaded Discord (currently in the works)
- [x] Author's Social Media
- [x] Github
- [x] Donation Page? (I've accepted $0 + a copy of Nekopara in my life as of time of writing)

# Add Application
![Reloaded-II_ZrtbmLTdpQ](https://user-images.githubusercontent.com/6697380/90601532-44269000-e1f0-11ea-8e9e-51e8ba6f3772.png)

## UX: Change Icon
- [x] Complete

You can currently change the game logo by clicking the one extracted from the EXE, however not all users seem to know this.
It might be a good idea to add an explicit button for this or reduce the tooltip delay.

## Rename Menu
- [x] Complete

As suggested by @shadowth117 , the `Add Application` menu is by nature misleading, since it can also edit applications.
It should ideally be called `Add/Edit Application`.

## Move Advanced Options
- [ ] Complete

For convenience the advanced options such as the Auto-Inject toggle should preferably be moved into the application sidebar instead of being in the `Add/Edit Application` menu to enhance discoverability.

As end users do not read tooltips, toggling Auto Inject option should probably produce a warning dialog telling the user the information currently present in the tooltip.

Might be good to have a way to at least remove the bootstrapper ASI file as a way to "undo" the ASI Loader deployment.

# Application Menu
![image](https://user-images.githubusercontent.com/6697380/90606893-5e646c00-e1f8-11ea-93cc-32dcec539152.png)

## Categorise Items
- [x] Complete

**Example:**
![image](https://user-images.githubusercontent.com/6697380/90607597-56f19280-e1f9-11ea-8ae7-5b69e7282934.png)

# Create Mod
- [x] Complete

![image](https://user-images.githubusercontent.com/6697380/90694353-63650200-e270-11ea-8230-104a5d69ac8f.png)

The list of dependencies should preferably have fixed height (like mod list) and 
be searchable, much like the `Manage Dependencies` menu.

![image](https://user-images.githubusercontent.com/6697380/90694413-7e377680-e270-11ea-8e93-4e377e040dfa.png)

# Contribute

If you have your own UI ideas, fire them away here.
Here's a list of what would be considered [Essential Items](https://github.com/Reloaded-Project/Reloaded-II/issues/42#issuecomment-678332723), anything else is up to your interpretation.

**Comment by Arggg** [comment]
Damn Sewer I didn't know you were so good at mspaint

**Comment by Arggg** [comment]
The main thing would be to reduce words though, ideally without a loss of information; tool tips could be in conjunction with icons / images. Really would be good to get a list of things the common user would want to access (that may be hidden away or not clear)

**Comment by Arggg** [comment]
> The main thing would be to reduce words though, ideally without a loss of information; tool tips could be in conjunction with icons / images. Really would be good to get a list of things the common user would want to access (that may be hidden away or not clear)

Images may be hard to use with everything though (please excuse me using this to work out github w)
Changes like this will take quite a bit of brainstorming and you really want a clear understanding of whats expected of the final product. I'd really appreciate help in that area, because I don't know all of Rii's features. 
(Also, putting this idea here before I forget: under INSTANCES (You might need to find a more familiar word for the user) I'd try to use colour to and possibly SYS or RII to differ between the instances. )

**Comment by Sewer56** [comment]
> (You might need to find a more familiar word for the user)

Since they'd all be grouped together, the right word would be _Processes_, which I think any user who would want to go there would probably understand.

**Comment by HyperPolygon64** [comment]
Thought I'd throw some ideas into this and provide a cleaner alternative based on a work-in-progress screenshot. Similar to Discord, the game header will use a darker background to separate it from the other headers, which will be above the lines, rather than underneath.

This screenshot has been manipulated, not edited directly into the UI itself.

![image](https://user-images.githubusercontent.com/34012267/91662540-11777400-eadb-11ea-9322-ba19dc773420.png)

**Comment by Sewer56** [comment]
Actual in launcher screenshot
![Reloaded-II_EpY2vU4Fee](https://user-images.githubusercontent.com/6697380/91799664-70460600-ec1f-11ea-9777-af2dd02a2a1e.png)

**Comment by Sewer56** [comment]
This issue seems finalized for 1.7.0 as of dbdb665422df723de82e935f6bba7e7c587f8400
