### ISSUE TITLE
I don't understand what's wrong with my mod manager

### ISSUE THREAD

**Issue by Yoitsadum** [Reloaded-Project/Reloaded-II#421]
So I've been using Reloaded II for around a week to play Persona 3 Reload and everything was fine until i decided to switch my game from my external hard drive to my internal ssd.
![Screenshot 2024-08-22 233459](https://github.com/user-attachments/assets/8232861a-dd7c-47fd-9b3f-b3fde903cbcb)
I get this error message and don't quite understand it and if I'm being honest I'm too inept to know what to do myself so if anyone could help I would greatly appreciate that. Thanks in advance.

**Comment by Sewer56** [comment]
Go to `Edit Application` menu and click the `Update` button to set a new path.

In a box below that you'll also want to update the working directory, just copy the path to the EXE and remove the file name.

**Comment by Yoitsadum** [comment]
I tried that and the exact same popup comes up.

**Comment by Sewer56** [comment]
Take a screenshot of 'Edit Application' menu

**Comment by Yoitsadum** [comment]
![Screenshot 2024-08-23 000516](https://github.com/user-attachments/assets/22dfac68-a6ee-4d97-b2e0-56fd08d1fe26)

**Comment by Sewer56** [comment]
In the box on the bottom, remove `P3R.exe` and you should be good.

**Comment by Yoitsadum** [comment]
![Screenshot 2024-08-23 001231](https://github.com/user-attachments/assets/5667cd38-db7d-4121-92e9-1381109ed15b)
I got a new error, I don't really understand this one.

**Comment by Sewer56** [comment]
Delete `mods/reloaded.universal.fileemulationframework` folder, your download might be borked for some strange reason. Or Antivirus didn't like it.

Launcher will redownload it as needed.

**Comment by Yoitsadum** [comment]
What should I do if that doesn't work?

**Comment by Sewer56** [comment]
I forgot which exact mod causes this error, but it is one of the mods not being correctly downloaded.

There isn't a checksum verify in Reloaded-II, only in the successor, unfortunately.

It might be `reloaded.sharedlib.hooks`, it's one of your mods; probably one that begins with `reloaded.`

**Comment by Yoitsadum** [comment]
It worked, thanks for your time and effort.
