### ISSUE TITLE
The Gay Joker Mod on Persona 5 Royal

### ISSUE THREAD

**Issue by PhantomThieves8** [Reloaded-Project/Reloaded-II#422]
I am new to modding, and I am trying to download the Gay Joker Mod and with that the Persona 5 Essentials and Unhardcoded Romance for Persona 5 Royal. For some reason, every time I try to run the game it says there is a fatal error. I have deleted and redownloaded Reloaded and all of the mods multiple times, but that has not worked. Even if I don't use the Unhardcoded Romance mod, there is still an error. Can you please help me? I bought the game solely for the purpose of these mods, but I honestly have no idea what I am doing.

**Comment by Sewer56** [comment]
@AnimatedSwine37 would know something about this. (<= currently unfortunately asleep)

I know these mods have previously been quoted as problematic, not sure if due to dependencies or otherwise.

**Comment by Sewer56** [comment]
You may have a quicker time asking in Persona Modding Discord Server though https://discord.gg/naoto

**Comment by PhantomThieves8** [comment]
Man you answered quick. I really appreciate that. Ok I will try asking there. I have been asking around but I don't really have the best connections so I am just stuck. I know you all are very busy, but I would appreciate if you could stay in touch while I try to get this sorted out. I am so worried I am going to mess something up but so far everything has been working well except for when I try to run the game. Thanks again for answering man!
