### ISSUE TITLE
Bug: Reload-2 Not downloading??

### ISSUE THREAD

**Issue by RaccoonBoyy** [Reloaded-Project/Reloaded-II#423]
I put in a form a few months ago about installing. I made a mistake and downloaded an older version. After someone helped me It worked for a bit but it then shut down. i decided to quit for a couple months and tried to uninstall and reinstall everything to mod Persona 3 Reload. But when i tried to set it up again it gave me this
![Screenshot 2024-09-03 045330](https://github.com/user-attachments/assets/fb58b954-fdea-47a3-a1fc-f490034e75b4)

Can someone help me out on what to do and ensure it actually works this time so i can load mods? (please)

**Comment by Sewer56** [comment]
I think you might just have a borked download @RaccoonBoyy .

Try grabbing Release.zip https://github.com/Reloaded-Project/Reloaded-II/releases/download/1.27.12/Release.zip and extracting all files to the Reloaded install location, overwriting them in the process.

**Comment by RaccoonBoyy** [comment]
It worked! Thank you :)
