### ISSUE TITLE
Help: Mod stopped working after p5r 1.04 september 6 update

### ISSUE THREAD

**Issue by babuubaja** [Reloaded-Project/Reloaded-II#425]
P5R essentials skip intro mod stopped working after p5r 1.04 september 6 update

![Screenshot 2024-09-06 211544](https://github.com/user-attachments/assets/a68bb9e6-86a7-4669-a9be-8fa6e57fe477)

[log.txt](https://github.com/user-attachments/files/16909259/log.txt)

**Comment by Sewer56** [comment]
This issue belongs in https://github.com/Sewer56/p5rpc.modloader , please reopen there.

In any case, community is already aware. Just that the more breaking things are being fixed first.
