### ISSUE TITLE
P5R crashing when I open the game's menu

### ISSUE THREAD

**Issue by lucid-waking** [Reloaded-Project/Reloaded-II#426]
I just downloaded the update and now P5R consistently crashes whenever I open the menu to save. I attached my last log for reference.
I'm a little new to using reloaded ii, so I don't know if "[15:24:56] [P5R Library] Unable to main loop, won't be able to call flow functions :(" and "[15:24:56] [P5R Library] Unable to find sequence info, sequence stuff won't work :(" in the log has anything to do with this? I've already tried uninstalling and reinstalling reloaded ii and my mods. Thanks in advance for help!
[2024-09-06 19.24.48 ~ P5R.txt](https://github.com/user-attachments/files/16912306/2024-09-06.19.24.48.P5R.txt)

**Comment by Sewer56** [comment]
They changed the compiler, so the code came out different and many mods broke. It's unfortunate; but expected.

**Comment by lucid-waking** [comment]
Thanks so much!
