### ISSUE TITLE
Persona 5 Royal / P5R Update Broke Mods #2

### ISSUE THREAD

**Issue by iL03t** [Reloaded-Project/Reloaded-II#427]
![error](https://github.com/user-attachments/assets/4218e24d-4007-44d3-8878-263ee31695e1)

Was working fine yesterday. Today it did this. Could anyone help me out?

**Comment by iL03t** [comment]
Same mods for the last 4 days have been installed. Nothing was changed or edited. Assuming maybe a mod is bad but not sure.

**Comment by Sewer56** [comment]
Rebooting your machine and/or downgrading your game https://github.com/Reloaded-Project/Reloaded-II/issues/426#issuecomment-2334703382 may help.

**Comment by iL03t** [comment]
> Rebooting your machine and/or downgrading your game [#426 (comment)](https://github.com/Reloaded-Project/Reloaded-II/issues/426#issuecomment-2334703382) may help.

**Comment by iL03t** [comment]
> Rebooting your machine and/or downgrading your game [#426 (comment)](https://github.com/Reloaded-Project/Reloaded-II/issues/426#issuecomment-2334703382) may help.

Thank you very much!! Not very smart with this stuff so when something like this happens. I get frustrated!!! Really do appreciate your help!!!

**Comment by Sewer56** [comment]
No worries ^-^
