### ISSUE TITLE
P5R won't open the Costume Framework mod active.

### ISSUE THREAD

**Issue by Potatopi13** [Reloaded-Project/Reloaded-II#428]
When I try to open Persona 5 Royal via the Reloaded II launcher while the Costume Framework mod is open, the game will consistently crash at the first loading screen.

1) Download the Costume Frameworks mod
2) Open the game

Every other time I used the Costume Frameworks mod before today, the game opened just fine and allowed me to do anything I wanted with the costume mods. FeMC mod worked fine, any extra costumes worked fine. It's not today, and I don't know what changed.

![image](https://github.com/user-attachments/assets/aede5a6f-1f8c-450e-ae96-47ca85126d93)

![image](https://github.com/user-attachments/assets/91d90674-b6bb-4f66-95b1-fa00c4e225e8)

As shown above, the game will consistently crash just as the spotlights move away from the logo. Turning the mod off fixes this issue. Any recommendations?

**Comment by Sewer56** [comment]
Until mods are updated, I would suggest downgrading the game; here's some backups of the previous version's exe file:

https://pastebin.com/UMNcQkYg

Drop into existing game folder.

**Comment by Sewer56** [comment]
Relevant mod was updated to support latest game version.
