### ISSUE TITLE
Norton Antivirus flagged it, once again, as harmful

### ISSUE THREAD

**Issue by MagpieSyndrome** [Reloaded-Project/Reloaded-II#430]
I've been using it fine for weeks now. After the most recent security update, Norton has not only decided to stop the game launch/injection process (I excluded the alert to tell it to stop), it then went ahead and decided to entirely delete Reloaded II. I hate Norton, but it's what my household decided to pay for. I'm trying to figure out how to completely disable Norton in the meantime, but I thought you should know this is currently an issue in case you have any way to get this to stop on your end. I'm so incredibly pissed off right now.
![Stupid shit](https://github.com/user-attachments/assets/afd9af37-ab92-4d57-b5af-966c1ea0b8b8)

**Comment by Sewer56** [comment]
It just unfortunately happens with AV providers from time to time. Best thing you can do is report a false positive.
