### ISSUE TITLE
i just try team super in sonice heroes

### ISSUE THREAD

**Issue by yosef208iad** [Reloaded-Project/Reloaded-II#433]
![Screenshot 2024-09-15 204616](https://github.com/user-attachments/assets/e13fea39-b5ac-49af-865f-3fb0f2a25315)

**Comment by Sewer56** [comment]
`r2:https://github.com/Reloaded-Project/reloaded.universal.redirector/releases/download/1.2.9/Reloaded.Universal.Redirector1.2.9.7z`

`r2:https://github.com/Sewer56/AfsFsRedir.ReloadedII/releases/download/1.0.9/Reloaded.Utils.AfsRedirector1.0.9.7z`

`r2:https://github.com/Sewer56/TONERR.ReloadedII/releases/download/1.2.2/sonicheroes.utils.toner1.2.2.7z`

`r2:https://github.com/Sewer56/Reloaded.SharedLib.Hooks.ReloadedII/releases/download/1.16.1/Reloaded.Hooks.ReloadedII1.16.1.7z`

Paste these into your browser to download them manually. Should solve your issue.

**Comment by Sewer56** [comment]
User responded in another thread (forgot which); issue had likely to do with file path; base game does not support unicode file paths well.
