### ISSUE TITLE
It's something I need to look into; this behaviour is extremely, extremely rare but there are edge cases where people's downloads infinitely loop during dependency resolution process, or the built in downloader doesn't extract at all. Not sure if it's Antivirus interference, FileSystem issue, Cloud Storage/OneDrive or whatever else it could be; but it is pretty rare.

### ISSUE THREAD

**Issue by yosef208iad** [Reloaded-Project/Reloaded-II#434]
It's something I need to look into; this behaviour is extremely, extremely rare but there are edge cases where people's downloads infinitely loop during dependency resolution process, or the built in downloader doesn't extract at all. Not sure if it's Antivirus interference, FileSystem issue, Cloud Storage/OneDrive or whatever else it could be; but it is pretty rare.

In the meantime, feel free to post this link into your browser address bar: `r2:https://github.com/Sewer56/Reloaded.SharedLib.Hooks.ReloadedII/releases/download/1.16.0/Reloaded.Hooks.ReloadedII1.16.0.7z`

Should fix the issue for you. Usually the plain link downloader inside R2 still works fine.

_Originally posted by @Sewer56 in https://github.com/Reloaded-Project/Reloaded-II/issues/226#issuecomment-1534941463_

**Comment by yosef208iad** [comment]
pls tell me how to solve it
![Screenshot 2024-09-15 204616](https://github.com/user-attachments/assets/d00e630a-c263-4368-8688-49a861689cf6)

**Comment by Sewer56** [comment]
I already replied in:

- https://github.com/Reloaded-Project/Reloaded-II/issues/433
