### ISSUE TITLE
Reloaded won't recognize SMT5 Vengeance EXE after update

### ISSUE THREAD

**Issue by delijoe79** [Reloaded-Project/Reloaded-II#435]
Basically when I try to add the SMT5V exe in reloaded it says it doesn't recognize the exe and I can't download or manage any mods.

**Comment by Sewer56** [comment]
Download/Manage mods should work just fine; even if EXE has mismatched.
Can you make a quick screen recording if it's actually borked? I'm curious.

**Comment by Sewer56** [comment]
@delijoe79 You should also be adding `smt5v-win64-shipping.exe` , the other EXE is a launcher, and is not what you want. Reloaded would have told you this when you tried adding the game.

**Comment by Sewer56** [comment]
Closing as stale. Re-open this if needed.
