### ISSUE TITLE
Bug: Drag and drop 7zip broken when application is ran trough setup.exe

### ISSUE THREAD

**Issue by ThomasAunvik** [Reloaded-Project/Reloaded-II#436]
**Describe the Bug**

When at first starting the application trough the setup.exe, the application is kept in elevated admin levels, drag and drop features are unavailable. This can be confusing where instructions can be plainly written as (when working normally):

- Install Reloaded-II
- Drag and drop 7z into Reloaded-II

As a new user, when running the setup.exe, you would wonder "why doesn't this work, am i doing something wrong?"

**To Reproduce**
Steps to reproduce the behaviour:
1. Run `setup.exe`
2. Admin UAC Popup
3. Application autolaunches
4. Try dragging a mod

For example, i tried to install this mod: https://www.nexusmods.com/finalfantasy16/mods/3

**Expected Behaviour**
To either launch the application in non-elevated mode, or not launch it at all and let the user manually open it?

**Additional wishes**

- [x] Installer should have a better install location, or allow selecting a location, if it installs on the desktop, why even elevate it, might aswell install it in programfiles too.
- [x] Installer sometimes fails to install when a file already exist:  (try running the setup.exe multiple times?) (and the existing application uninstalls itself?)
![image](https://github.com/user-attachments/assets/3478efaa-f914-47fc-8dc0-11cb3ebda7b8)
- [x] If the installer fails with the message above, can happen different stages, the installation botches and requires an another run of the setup.exe .

- As a first time user, i had no easy way of figuring out from the documentation where the mods folder were, didn't knew it was installed on my C:/Users/username/Desktop/Reloaded-II by default, and there was no button to open the mods folder.
- Example: Context menu in the mods list shows up when there is no mods with "Open Folder" button, but no window opens.

- [x] #247 would be a nice help too. As i've had to dig to this github to find the download link, after searching it in the docs thinking "surely there is a download link here somewhere". Which is kind of ironic considering there is a "quick start" guide.

**Comment by Sewer56** [comment]
I'll see if this can be launched non-elevated; but no guarantees outside of that.
I'm the only dev behind R2, sans the very rare pull request; and I'm working on a successor.

**Comment by Sewer56** [comment]
Finding time to maintain this is difficult, albeit; I've been so overworked the past 1.5 years with 'hobby' stuff, that I even broke down lately.

**Comment by Sewer56** [comment]
> if it installs on the desktop, why even elevate it

There's multiple reasons, but it mainly comes down to silent installation of .NET Runtime (x86 and x64).

The mod loader itself requires the runtimes, both x86 and x64 depending on game; and there's no easy way to start CoreCLR with a runtime in custom location. I will do that in R3 in the future though; there's no public API for it, but I have learned how to do that since by looking at some runtime code.

The other reason is with the launcher itself. Making a self contained binary means shipping it for a specific architecture. When I tried dropping 32-bit support in the past; some person from a place like Latin America would eventually ask if there's a 32-bit version of the program. (This happened twice)

So in order to keep things simple (for end users), I went with an installer that ships both 32-bit and 64-bit; and AnyCPU DLLs. That unfortunately however means no true static build.

**Comment by Sewer56** [comment]
Anyway, made some quick fixes; whatever I could get done before going to sleep.
Will update the docs stuff tomorrow; it's 7:30am.

**Comment by angrynewraze** [comment]
Drag and drop is broken regardless of running it through the setup.exe or the exe in the releases.zip file after extracting the zip file.

**Comment by Sewer56** [comment]
@angrynewraze It could just be down to where you're trying to drop to. Try dropping on the titlebar.

Certain UI components like the mods list seem to obstruct the window's drop handler, even if they're not set to allow drop. It's probably fixable, but I haven't looked too much into it. I've been trying to focus on the more major bugs as they crop up.

While I'm focusing on Reloaded3 (will take around another 2 years or so), I'm just fixing up more major issues for the most part. Unfortunately as a solo dev it's hard to delegate issues to others.

**Comment by angrynewraze** [comment]
I just tried dragging it to the title bar and it worked. Dragging and dropping to the square box doesn't work though

**Comment by Sewer56** [comment]
Figured, it's not perfect; haha.

**Comment by Sewer56** [comment]
Will handle:

- https://github.com/Reloaded-Project/Reloaded-II/issues/247

In the next hour. In the meantime, I spent 2 days streamlining setup on Linux a bit.
Provided you have `protontricks` installed, you can set things up just as easily as on Windows now.
