### ISSUE TITLE
Bug: Missing Distirubutables when trying to launch reloaded II

### ISSUE THREAD

**Issue by HyperPixel7** [Reloaded-Project/Reloaded-II#437]
What happened:
I followed this tutorial right here: (https://gamebanana.com/tuts/17166#H1_16) and some wacky things happened.

What Actually Happens: 
When launching Persona 3 Reload with Protontricks, I'm greeted with a message stating it's missing the Visual C++ x86 and x64, which I've installed several times, trying to launch it through steam, I'm missing a .NET redistributeable, which I've also tried installing several times.

Any help would be appreciated![1000105534.jpg](https://github.com/user-attachments/assets/1ee58c6e-cc1f-4a4b-bb4a-50484c55417d)

![1000105533.jpg](https://github.com/user-attachments/assets/885951ed-6982-4b6e-8cdb-18fd9062ee9f)

**Comment by Sewer56** [comment]
> When launching Persona 3 Reload with Protontricks, I'm greeted with a message stating it's missing the Visual C++ x86 and x64, which I've installed several times

You can usually ignore this message.
The game itself would use Visual C++, so it'd get installed into the Proton WINEPREFIX managed by Steam by the time you run the game.

> trying to launch it through steam, I'm missing a .NET redistributeable

---------

I suspect you may have chosen a different WINEPREFIX when following the guide at step 2

![image](https://github.com/user-attachments/assets/6a51b991-eb66-4994-acd7-2c3203046388)

Make sure you boot the game first; so it shows up in the Protontricks menu; then launch the runtime installers with Protontricks.

**Comment by Sewer56** [comment]
For anyone more familiar with terminal that may read this. There is a slightly faster way to install dependencies.

As a quick shortcut, you can try downloading [Setup.exe](<https://github.com/Reloaded-Project/Reloaded-II/releases/latest/download/Setup.exe>); and running it from the CLI.

```bash
# install .net framework (required for setup.exe)
protontricks 2161700 dotnet48

# install dependencies using the setup.exe helper.
protontricks-launch --appid 2161700 "Setup.exe" --dependenciesOnly
```

**Comment by HyperPixel7** [comment]
I think I lack basic reading comprehension or what you said didn't work, I made sure everything was on the P3RE wine configurations, and I'm still getting this error

**Comment by HyperPixel7** [comment]
If anyone sees this
Also install direcctories for reloaded 2
