### ISSUE TITLE
P5R Crash when entering battle

### ISSUE THREAD

**Issue by kokasco** [Reloaded-Project/Reloaded-II#438]
The bug seems to occur whenever I try to ambush an enemy, or get surprise attacked (essentially going into battle).
The game crashes, and so does Reloaded II.
I'm not sure what is causing this, I downgraded to a previous version of P5R, but I dont know what going on. What mod could be conflicting this? 

![e2](https://github.com/user-attachments/assets/0f88ab43-3528-4cf7-9bd1-6a76d26cd133)
![e1](https://github.com/user-attachments/assets/cbc29a9f-67fd-491d-8fd2-eef1f122de36)

**Comment by Sewer56** [comment]
You're best off asking in the [Persona Modding](https://discord.gg/naoto) Discord Server.
Some of the mods here got updated for the newest version of the game recently; you may be running a mix of updated and un-updated mods.
