### ISSUE TITLE
Crashing upon launching Reloaded II for P4G

### ISSUE THREAD

**Issue by stefannguyenn1** [Reloaded-Project/Reloaded-II#443]
**Describe the Bug**
Reloaded II gives an error when trying to run Persona 4 Golden. The game is able to run but without any mods loaded it appears. I recently just updated to version 1.27.14 while on .NET framework 8.0.4.

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch and run P4G via Reloaded II. 
2. Error message is given, log is created in system. 
3. P4G is able to launch without any mods. 

**Additional Context**
I have not run Reloaded II for about two months. I recently just updated to 1.27.14 and have not gotten this error in the past. Any help would be greatly appreciated!
![r3](https://github.com/user-attachments/assets/fdbe6f53-a036-4a59-8968-3274f1cb576b)
![r2](https://github.com/user-attachments/assets/6e4347a6-0258-49f0-a1f6-3a3aaf2511a9)
![r1](https://github.com/user-attachments/assets/f71e1c31-0a8f-4476-80b1-d446fff7901d)

**Comment by stefannguyenn1** [comment]
Apologies for the redundancy,
I resolved this issue by disabling two music pack mods and suddenly Reloaded II now works as expected. In case anyone else has this issue, it was caused by the Music Enhancement pack by Pixelguin, and the Anime Music Pack by Brawler & Friends. 
Once again, sorry about the confusion.

**Comment by Sewer56** [comment]
@stefannguyenn1 `r2:https://github.com/T-PoseRatkechi/Ryo/releases/download/2.2.2/Ryo.Reloaded2.2.2.7z`

Pasting this into your browser should do the trick.
The dependency failed to download due to GameBanana site outages, and author didn't enable update support via other sources.

**Comment by stefannguyenn1** [comment]
@Sewer56 
Thank you so much! After adding this my music mods now work again like before.
