### ISSUE TITLE
Bug: An error occurs when installing Reloaded II with Setup-Linux.exe

### ISSUE THREAD

**Issue by athnnn** [Reloaded-Project/Reloaded-II#444]
**Describe the Bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Download 'Setup-Linux.exe'
2. Open the file and installing Reloaded-II with protontricks using new prefix
3. Wait for it to finish installing

**Expected Behaviour**
Reloaded II installed
**Screenshots**
![image](https://github.com/user-attachments/assets/371253d1-5eef-4e96-8f1e-98fcf976dd3b)

**Additional Context**
![image](https://github.com/user-attachments/assets/225e2477-5276-4020-b261-fe658593fe16)
the shortcut that was made also gives an error
![image](https://github.com/user-attachments/assets/883f9b1c-8d0e-4805-b136-19a55d9e3b8c)

**Comment by Sewer56** [comment]
This was closed, what's the specific reason?
Did you install another way? Or did the bug resolve itself?

**Comment by athnnn** [comment]
> This was closed, what's the specific reason? Did you install another way? Or did the bug resolve itself?

I didn't read through enough and didn't realise I was using flatpak version of protontricks. But i am also having issues right now because only 32bit will run and then it gives a big error and most buttons in the app will crash it but I will upload the logs and stuff tomorrow because im not on my pc right now
