### ISSUE TITLE
Bug: persona 3 reload game, trying to use theurgy will crash the game.

### ISSUE THREAD

**Issue by afat123** [Reloaded-Project/Reloaded-II#445]
**Describe the Bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected Behaviour**

**Screenshots**

**Additional Context**

**Comment by Sewer56** [comment]
Consider Asking in [Persona Modding](https://discord.gg/naoto).
Do provide more details, such as which mods you are running once you get there.

**Comment by afat123** [comment]
> Consider Asking in [Persona Modding](https://discord.gg/naoto). Do provide more details, such as which mods you are running once you get there.

ok. will go there.
