### ISSUE TITLE
Bug: Reloaded won't run the P5R exe file, runs into an error of missing dependecies 

### ISSUE THREAD

**Issue by bueno04** [Reloaded-Project/Reloaded-II#447]
Hi there! In this example, I tried running some mods on P5R, but the error bellow is showing continuosly. I tried to run the wonder over joker mod, and the expansive compedium mod. In both cases, it still doesn't work. Persona essentials and both frameworks are installed (bgm and costume), but it still says its missing the dependencies, which I have no clue where to find. Am i doing something wrong? Thanks in advance!

![image](https://github.com/user-attachments/assets/633b0055-ca37-4475-92c6-e9a9ce9c1741)

**Comment by Sewer56** [comment]
`r2:https://github.com/T-PoseRatkechi/BGME/releases/download/3.4.4/BGME.Framework.API1.0.1.7z`

`r2:https://github.com/T-PoseRatkechi/BGME/releases/download/3.4.4/BGME.Framework3.0.1.7z`

`r2:https://github.com/AnimatedSwine37/p5rpc.lib/releases/download/1.0.5/p5rpc.lib1.0.5.7z`

Paste these manually into your browser to start downloads for the missing components and you should be good.

It just failed to auto download needed dependencies on your end.

**Comment by bueno04** [comment]
Thanks for the files! Installed successfully, but the error still shows up, maybe there's more dependencie that didn't auto download? 
![image](https://github.com/user-attachments/assets/78920c54-42e3-4aa0-8b63-34a87b3a7618)

**Comment by Sewer56** [comment]
Yeah, you can grab them from here:

`r2:https://github.com/RyoTune/Ryo/releases/download/2.4.1/Ryo.Reloaded2.4.1.7z`

`r2:https://github.com/RyoTune/SharedScans/releases/download/1.1.1/SharedScans.Reloaded1.1.1.7z`

These should be the right ones, hopefully.

**Comment by bueno04** [comment]
It worked! Thank you so much for your support!

**Comment by Sewer56** [comment]
No worries :p
