### ISSUE TITLE
Help: Please help me with this error

### ISSUE THREAD

**Issue by SoulNpL** [Reloaded-Project/Reloaded-II#448]
Hi, I followed the tutorial and installed the Reloaded-II and tried to Launch the application before any installed any mod but got this error pop up.

![Screenshot 2024-09-22 103629](https://github.com/user-attachments/assets/4ae51f21-cf65-4da0-b9ab-88c8d9c28e6f)

Any help would be greatly appreciated!

**Comment by Sewer56** [comment]
CC @nenkai

**Comment by Sewer56** [comment]
While I'm waiting from someone more knowledgeable with the game, can you upload the console logs?
Go to `View Log Files` from the main/settings screen of Reloaded, and upload the most recent log please.

**Comment by SoulNpL** [comment]
Hi Sewer,

Thanks for looking into this. Here it is.
[2024-09-22 00.02.58 ~ ffxvi.txt](https://github.com/user-attachments/files/17091766/2024-09-22.00.02.58.ffxvi.txt)

**Comment by Sewer56** [comment]
Yeah, in this case you'll want to wait for @nenkai (who probably just fell asleep). The game just came out, and I'm not involved on that end, so I don't know any of the game specific details.

I imagine it probably runs fine with all mods disabled; in which case it's a mod issue.

**Comment by SoulNpL** [comment]
And this is after I did a clean install/uninstall and retried Reloaded-II.

[2024-09-22 17.35.58 ~ ffxvi.txt](https://github.com/user-attachments/files/17091775/2024-09-22.17.35.58.ffxvi.txt)

**Comment by Sewer56** [comment]
> And this is after I did a clean install/uninstall and retried Reloaded-II.
> 
> [2024-09-22 17.35.58 ~ ffxvi.txt](https://github.com/user-attachments/files/17091775/2024-09-22.17.35.58.ffxvi.txt)

Wait, does this still crash?

If it does, can you reset your game folder to as vanilla state as possible? I'm curious if there's anything else going on.

**Comment by Nenkai** [comment]
(They've already asked & been responded to on nexus so i'm not sure why an issue was raised here)

Either way I don't have a single clue, actually. This error box comes directly from the game - if it's without mods, there shouldn't be any tampering going on at all (loader will clear the state on start). This is the first time I've seen something like this so far. Their last log doesn't show the FF16 loader logs.

Their latest nexus post mentions they've been running without mods, only FFXVIFix and Reshade.

Maybe a conflict of sorts, either way, verify your game data, try without any of these other addons first, and try booting without anything at all, and then with the loader.

**Comment by SoulNpL** [comment]
> (They've already asked & been responded to on nexus so i'm not sure why an issue was raised here)
> 
> Either way I don't have a single clue, actually. This error box comes directly from the game - if it's without mods, there shouldn't be any tampering going on at all (loader will clear the state on start). This is the first time I've seen something like this so far. Their last log doesn't show the FF16 loader logs.
> 
> Their latest nexus post mentions they've been running without mods, only FFXVIFix and Reshade (with the loader).
> 
> Maybe a conflict of sorts, either way, verify your game data, try without any of these other addons first, and try booting without anything at all, and then with the loader.

Thanks @Nenkai, I put a post here because I was not sure if this was Reloaded-II issue or mod issue and it seems inappropriate if I ask for your help if it was not your mod's problem in the beginning. I do apologise for any inconvenience it may cause.

I will try your suggested method and let you know if it is resolved.

Thanks

**Comment by SoulNpL** [comment]
Yup, found the issue.

The Reloaded-II. Must be incompatible with FFXVIFix, When I have FFXVIFix installed, I have this on the log

_[Reloaded] Create Loader | Time: 51ms
[Reloaded] Loading 1 Mod(s).
Updating Config w/ HasExports & CanUnload.
[Reloaded]
[Reloaded] Loading: Reloaded II Shared Lib: Reloaded.Hooks
[Reloaded] - AppId   : reloaded.sharedlib.hooks
[Reloaded] - Location: C:\Users\phlua\OneDrive\Desktop\Reloaded-II\Mods\reloaded.sharedlib.hooks\ModConfig.json
[Reloaded] - LoadTime: 25ms
[Reloaded] Loaded via: C:\Users\phlua\OneDrive\Desktop\Reloaded-II\Loader\x64\Bootstrapper\Reloaded.Mod.Loader.Bootstrapper.dll
[Reloaded] Current Process Location: E:\Games\steamapps\common\FINAL FANTASY XVI\ffxvi.exe
[Reloaded] Loading Mods (Total) | Time: 10ms
[R-II SteamHook] SteamAPI_RestartAppIfNecessary hooked successfully.
[R-II SteamHook] SteamAPI_IsSteamRunning hooked successfully.
[R-II SteamHook] Found Steam Library Entry with Id 2515020. Dropping steam_appid.txt.
[Reloaded] Setting Up Hooks (Async) | Time: 145ms
[Reloaded] Total Loader Initialization Time: 233ms
Setting breakpad minidump AppID = 2515020
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198069485685 [API loaded no]
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198069485685 [API loaded no]
File 'e:/games/steamapps/common/final fantasy xvi/sl.interposer.dll' is signed by NVIDIA and the signature was verified.
#
# FAITH Exception
#
# code: 0xc0000005
# message: πâªπâ╝πé╢πâ╝πâóπâ╝πâëπâçπâ╝πé┐σ«ƒΦíîΘÿ▓µ¡ó∩╝êDEP∩╝ëΘüòσÅìπÇé
#
# registers:
# Rax: 00007ffedb0e1e20  Rbx: 00000050e51a8d48
# Rcx: 0000000140000000  Rdx: 0000000000000800
# Rsi: 0000000000001894  Rdi: 00000001413ec830
# Rbp: 000000000014fcf0  Rsp: 000000000014f2b8
# R8 : 00000001413ec830  R9 : 000000000014fae0
# R10: 00007ffe0f2d0000  R11: 0000000000000246
# R12: 0000000000000040  R13: 0000000000000000
# R14: 000000000014fb50  R15: 00000000ffffffff
# Rip: 0000000000000000  EFlags: 00010202
# SegGs: 0000002b  SegFs: 00000053
# SegEs: 0000002b  SegDs: 0000002b
# SegCs: 00000033  SegSs: 0000002b

Uninstalled FFXVIFix and the Reloaded-II worked.

Is there anyway we can make this compatible with FFXVIFix since it is such a great mod that can fix Ultrawide issue for me.

Thanks.

**Comment by Sewer56** [comment]
That's highly unusual. Lyall's other mods work just fine with R2.

--------

I mentioned this the other day, however, when it comes to the loader itself. Reloaded's loader only modifies the process in the following way:

- Hooks ExitProcess 
    - This ensures logs are complete if user closes the game normally.
- Hooks UnhandledExceptionFilter
    - This lets us create a crash dump if the process (for example) encounters an Access Violation or other hard crash.

- If Steam Stub DRM (.bind PE section) is present, delays injection until game is decrypted in memory.
    - By hooking common library entry points in [DelayInjectHooks.json](<https://github.com/Reloaded-Project/Reloaded-II/blob/master/source/Reloaded.Mod.Loader/DelayInjectHooks.json>) and then safely unhooking.

Unless some mod touches the same code, there shouldn't be possibility of a conflict.

**Comment by Sewer56** [comment]
[ffxvifix.zip](https://github.com/user-attachments/files/17091870/ffxvifix.zip)

I didn't test this (don't have game), but out of curiosity do see what happens if you load ffxvifix through Reloaded itself.
This should (probably) do the trick. I just packaged it up as an R2 mod.

**Comment by Sewer56** [comment]
In the past, I've made a PR such that upstream automatically generates Reloaded-II packages, with update support: https://github.com/Lyall/P3RFix/pull/39 , for one of their other projects. Would be easy to migrate here.

**Comment by SoulNpL** [comment]
> [ffxvifix.zip](https://github.com/user-attachments/files/17091870/ffxvifix.zip)
> 
> I didn't test this (don't have game), but out of curiosity do see what happens if you load ffxvifix through Reloaded itself. This should (probably) do the trick. I just packaged it up as an R2 mod.

Thank Sewer, I downloaded your file but could not drop it to Reloaded. I drag and drop but the mod did not show up on the mod list.

Thanks

**Comment by Sewer56** [comment]
@SoulNpL 
I don't own the game, so I may have gotten the name wrong. I just copied what I saw on SteamDB and estimated the AppID field from that.

Go to the `Manage Mods` menu (one with 3 cogs) and you can enable the mod from there.

**Comment by SoulNpL** [comment]
Hi @Sewer56 & @Nenkai ,

I finally got it worked. The cause of this is the file "dinput8.dll". After rename it to something else like "version.dll", it works.
