### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by 12Alfo** [Reloaded-Project/Reloaded-II#450]
![Screenshot 2024-09-25 041934](https://github.com/user-attachments/assets/965a94db-33a6-4341-b6f5-d63dca662a39)
I want to mod my persona 5 royal :(
I kept on reinstalling because it said i was in a installation bug loop and i couldnt install the persona essentials mod

**Comment by Sewer56** [comment]
> i was in a installation bug loop and i couldnt install the persona essentials mod

Please instead post the image of that dialog.

**Comment by 12Alfo** [comment]
I didn’t take a screenshot of that dialog and i can’t open it now since i
can’t even install reloaded anymore

**Comment by 12Alfo** [comment]
> > i was in a installation bug loop and i couldnt install the persona essentials mod
> 
> Please instead post the image of that dialog.

May I ask is the issue for me not being able to download reloaded now because I'm timed out due to multiple installation attempts?

**Comment by Sewer56** [comment]
I think you're using an old installer, and are being rate limited by GitHub.

Try a newer [Setup.exe](https://github.com/Reloaded-Project/Reloaded-II/releases/download/1.27.14/Setup.exe).  Alternatively just extract [Release.zip](https://github.com/Reloaded-Project/Reloaded-II/releases/download/1.27.14/Release.zip) to a new folder.

**Comment by 12Alfo** [comment]
> I think you're using an old installer, and are being rate limited by GitHub. They impose a 60 per hour limit per IP.
> 
> Try a newer [Setup.exe](https://github.com/Reloaded-Project/Reloaded-II/releases/download/1.27.14/Setup.exe), IIRC it doesn't use GitHub API anymore. Alternatively just extract [Release.zip](https://github.com/Reloaded-Project/Reloaded-II/releases/download/1.27.14/Release.zip) to a new folder.

Alright im on it now its installing again ill let you know if i run into the issue when downloading the mod itself

**Comment by 12Alfo** [comment]
![Uploading Screenshot 2024-09-25 042930.png…]()

**Comment by Sewer56** [comment]
You pressed 'Send' before the image got uploaded.

**Comment by 12Alfo** [comment]
> You pressed 'Send' before the image got uploaded.

Yup, My bad xd

**Comment by Sewer56** [comment]
`r2:https://github.com/Sewer56/Reloaded.SharedLib.Hooks.ReloadedII/releases/download/1.16.1/Reloaded.Hooks.ReloadedII1.16.1.7z`

Pasting this should resolve that specific download.
Though it's weird the program would fail to download something from 3 sources. Maybe it can't access the internet on your end for whatever reason.

**Comment by 12Alfo** [comment]
> `r2:https://github.com/Sewer56/Reloaded.SharedLib.Hooks.ReloadedII/releases/download/1.16.1/Reloaded.Hooks.ReloadedII1.16.1.7z`

Where should I paste this into sorry for asking im not too familiar with modding only done it once on a sonic game

**Comment by 12Alfo** [comment]
![Screenshot 2024-09-25 042930](https://github.com/user-attachments/assets/b55e7abd-aa79-44ea-b44d-9b45f131de2d)

This is the issue i get whenever I try to download the essential mod

**Comment by Sewer56** [comment]
Ah, it's a browser link. That will send it to Reloaded.

**Comment by 12Alfo** [comment]
![Screenshot 2024-09-25 044109](https://github.com/user-attachments/assets/d9fa57c0-7143-42b5-af23-a09056e7eb45)

Ive pasted it, is this still suppose to pop up?

**Comment by Sewer56** [comment]
Could your copy of Reloaded-II maybe somehow be blocked from accessing the Internet?

See if `Download Mods` menu (top left) shows you anything.

**Comment by 12Alfo** [comment]
![image](https://github.com/user-attachments/assets/933c362e-6b46-49e6-8f93-09421536f2eb)

Mods are appearing so I assume its alright

**Comment by 12Alfo** [comment]
Could anti virus be an issue to this?

**Comment by Sewer56** [comment]
Then you're probably fine.

Normally pasting a link to browser like `r2:https://github.com/Sewer56/Reloaded.SharedLib.Hooks.ReloadedII/releases/download/1.16.1/Reloaded.Hooks.ReloadedII1.16.1.7z` would open a download window in Reloaded; which downloads the mod.

If you try to download some mod from the Download Mods menu, does stuff work?

**Comment by 12Alfo** [comment]
> Then you're probably fine.
> 
> Normally pasting a link to browser like `r2:https://github.com/Sewer56/Reloaded.SharedLib.Hooks.ReloadedII/releases/download/1.16.1/Reloaded.Hooks.ReloadedII1.16.1.7z` would open a download window in Reloaded; which downloads the mod.
> 
> If you try to download some mod from the Download Mods menu, does stuff work?

When I download from the mods menu it gives me the unknown error page I posted earlier above

**Comment by Sewer56** [comment]
Really weird that downloading dependencies just doesn't work here.
Anyway, I guess for now just post the error dialog, I'll give you the links for whatever you're missing as needed.

**Comment by 12Alfo** [comment]
> Really weird that downloading dependencies just doesn't work here. Anyway, I guess for now just post the error dialog, I'll give you the links for whatever you're missing as needed.

Alright thanks I can send u a whole video of the process
I will get back to u tomorrow as its 5am for me and I need to head to bed xd

**Comment by Sewer56** [comment]
No worries :p

**Comment by 12Alfo** [comment]
> No worries :p


https://github.com/user-attachments/assets/86796a06-36a1-4e4e-a543-ea25789d8810

videos too big ill send it in 2 parts

**Comment by 12Alfo** [comment]
https://github.com/user-attachments/assets/3077ce36-e51b-4b15-83dd-98677d363940

Part 2

**Comment by 12Alfo** [comment]
Thanks for the assistance in this issue btw I really do appreciate your time and effort into helping me solve this :p

**Comment by Sewer56** [comment]
Oh, the extractor is borked.
What's the file path to your desktop? I wonder if it's a special character.

**Comment by 12Alfo** [comment]
> Oh, the extractor is borked. What's the file path to your desktop? I wonder if it's a special character.

![image](https://github.com/user-attachments/assets/50aad5d3-d553-4aea-b9c2-5a076ccdace9)

Its in my downloads

**Comment by Sewer56** [comment]
To Desktop. Reloaded-II installs to your Desktop, I wonder what the full path there is.

e.g. `C:\users\<username>\Desktop\Reloaded-II`.
If your files are in `OneDrive`, or if your username contains special characters, you may have luck if you move Reloaded to another folder.

**Comment by 12Alfo** [comment]
> To Desktop. Reloaded-II installs to your Desktop, I wonder what the full path there is.
> 
> e.g. `C:\users\<username>\Desktop\Reloaded-II`. If your files are in `OneDrive`, or if your username contains special characters, you may have luck if you move Reloaded to another folder.

![image](https://github.com/user-attachments/assets/92d55f8c-a706-4e7e-8cd5-a45b40ef492e)

Is this what your asking for?

**Comment by 12Alfo** [comment]
![image](https://github.com/user-attachments/assets/df59273b-ac4c-4ac7-84d1-f3ed23582c12)

Maybe this is what you meant by special characters?

**Comment by 12Alfo** [comment]
> ![image](https://private-user-images.githubusercontent.com/55656194/370470704-df59273b-ac4c-4ac7-84d1-f3ed23582c12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyMTI0ODUsIm5iZiI6MTcyNzIxMjE4NSwicGF0aCI6Ii81NTY1NjE5NC8zNzA0NzA3MDQtZGY1OTI3M2ItYWM0Yy00YWM3LTg0ZDEtZjNlZDIzNTgyYzEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDIxMDk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlN2Q0NThmMWRlMGQ5NWU0OTRkNDA1Y2QxY2UxODM5MDBkMzE5MDk0NzJiMGM0NDI5Y2Q5YTg0MTM1MmU3MDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TidInRuZSqvOmYzdeOucUS7Z6JADmsSoOA8vOdow_b8)
> 
> Maybe this is what you meant by special characters?

If so how do i change it

**Comment by Sewer56** [comment]
Ah, your desktop folder is in Chinese. This is probably the issue.
Reloaded itself works fine, but 7z.dll used for extraction does not; and some games don't like it.

Just move your `Reloaded-II` folder from `Desktop/Reloaded-II` to a location without special characters. No need to use installer.

**Comment by 12Alfo** [comment]
![image](https://github.com/user-attachments/assets/93e3e815-34ca-4de7-abca-388aa6d7ac6d)

OMG IT FINALLY WORK
THANKS SO MUCH
I truly appreciate this a lot thanks bro

**Comment by 12Alfo** [comment]
> No worries, have fun :p

Tipped you $1 for the help I really do appreicate this from the bottom of my heart

**Comment by Sewer56** [comment]
Awwww, I'm flattered.
I'll try to patch up the installer so it doesn't install into problematic directories in the future.
