### ISSUE TITLE
P4g mods do not work using reloaded.

### ISSUE THREAD

**Issue by HydroZenon** [Reloaded-Project/Reloaded-II#451]
![Screenshot (371)](https://github.com/user-attachments/assets/9eaaa501-621b-4441-9ac1-d8679d7c9a06)
I did the tutorial, I linked the .exe file to p4g... And ow and behold this happens. Help me Please!

**Comment by Sewer56** [comment]
Verify your game files (in Steam).

I've seen this error happen before (in Inner Exception) when someone had a borked download/corrupted of the game.
