### ISSUE TITLE
Bug: reloaded 2 is having issues with loading framework

### ISSUE THREAD

**Issue by Voidseption** [Reloaded-Project/Reloaded-II#452]
![Screenshot 2024-09-26 213819](https://github.com/user-attachments/assets/32c8ddff-1408-4bae-bed2-91e72e8290e4)

To put it simply, I was able to find and download every mod dependency for my mods. I have the process nailed down pretty well, until i get this error and I am confused on how it works. I looked around and still confused. Is there anything I am missing or is it a bug and i need to work around it?

**Comment by Sewer56** [comment]
One of these mods' downloaded files may be borked:

- `reloaded.universal.fileemulationframework.awb`
- `crifs.v2.hook`

Usually deleting the folder and letting the launcher automatically re-download it does the trick.

**Comment by Voidseption** [comment]
![Screenshot 2024-09-26 215133](https://github.com/user-attachments/assets/6d1c873d-f360-4a09-9092-1caa0a4e378e)
and the rabbit hole gets deeper, i am assuming something is missing this time?

**Comment by Sewer56** [comment]
To my awareness, that mod (coloured chat icon BG) wasn't updated for the latest version of the game.

**Comment by Voidseption** [comment]
i don't have that mod installed though, any reason it is giving me an error for something i don't even have?

**Comment by Sewer56** [comment]
It's likely a dependency of a mod you have enabled. Either direct or transitive.

**Comment by Voidseption** [comment]
i got the errors to disappear (finally), now comes a new bug. The game is refusing to load, just shows me the "take your time" on the bottom right and game closes.

**Comment by Sewer56** [comment]
Usually you're best off trying with a minimal mod setup and enabling mods one by one until stuff works.

**Comment by Voidseption** [comment]
Turns out it is none of the mods, it is one of the frameworks which are auto enabled. I tried to launch without any mods and yeah game just closes again.

**Comment by Voidseption** [comment]
oh i figured it out, it is the mod called "Expansive Persona Compendium"
