### ISSUE TITLE
Menu crashing game after opening

### ISSUE THREAD

**Issue by Voidseption** [Reloaded-Project/Reloaded-II#454]
I am modding persona 5 royal using reloaded 2. I am not sure which mod could be causing this. I try to open the menu in persona 5 royal and as soon as i scroll down or up through the options, the game just crashes. To my knowledge, none of the mods i have installed should be messing with the menu.

**Comment by Sewer56** [comment]
You're best off asking in [Persona Modding](https://discord.gg/naoto)

**Comment by Sewer56** [comment]
As a general rule of thumb, I'd just disable mods one by one till stuff works.
Or if you want to be more efficient, disable half the mods each time.

Moment it fixes itself, you know a mod in the half you didn't disable is at fault.

**Comment by Sewer56** [comment]
Closing as mod specific
