### ISSUE TITLE
Bug: <no have option> when <drop in>

### ISSUE THREAD

**Issue by ioritree** [Reloaded-Project/Reloaded-II#455]
**Describe the Bug**
no any new option after drag files ([1.27.14))

Steps to reproduce the behaviour:
1. Go to 'drag a files to Reloaded-II '
2. no any new disable/enable option after drag files
3. mods files can see files have been add

![Honeycam 2024-09-29 11-13-36](https://github.com/user-attachments/assets/a1873b67-8620-4c0f-a629-0f244edc5329)

**Comment by ioritree** [comment]
> Either your ffxvi instance has the wrong AppId or the mod is misconfigured most likely.
> 
> Compare the `AppId` field in the `Apps/ffxvi.exe/App.json` file inside Reloaded folder. (It should have a path similar to this). Hopefully `AppId` is `"ffxvi.exe"`. If it is not, change it to `"ffxvi.exe"`.
> 
> Otherwise mod is misconfigured. Open the `ModConfig.json` file inside mod folder. If `SupportedAppId` field doesn't have `[ "ffxvi.exe" ]`, or similar, make it so.
> 
> If the mod was misconfigured, let the mod author know.

thank you ,add demo.exe then work good !

**Comment by SagarChandra07** [comment]
download
https://bit.ly/47P0Nvo
Archive password: changeme
If you don't have the c compliator, install it.(gcc or clang)
