### ISSUE TITLE
Bug: Reloaded-II crashes when clicking on a mod with numerous configuration options in SteamOS or Linux

### ISSUE THREAD

**Issue by RVRZERO** [Reloaded-Project/Reloaded-II#457]
**Describe the Bug**
Reloaded-II crashes immediately when highlighting my mod which is DLC Manager in SteamOS or Linux, I suspect, it is because of the numerous configuration options which are 49.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Reloaded-II
2. Click on DLC Manager
3. Reloaded-II Crashes

**Expected Behaviour**
It shouldn't crash.

**Additional Context**
This was reported by many users but not tested by me, you could look at the comments at the Gamebanana page: https://gamebanana.com/mods/523026

**Comment by Sewer56** [comment]
I just woke up, I'll have a look in a short while.

**Comment by Sewer56** [comment]
@RVRZERO The issue is with your image format. You used AVIF but named the image `.png`. Wine and older versions of Windows (pre Windows 10 2019 H1) don't have a built-in AVIF decoder.

**Comment by RVRZERO** [comment]
@Sewer56 Hi! Thanks for the fast response! I am going to update the picture soon since it is the cause. If it not hard, I suggest you add some line of code that gives a warning if it detects a format that is not supported by Wine. Thank you for your hard work!

**Comment by Sewer56** [comment]
> I suggest you add some line of code that gives a warning if it detects a format that is not supported by Wine

I can add an arbitrary check that arbitrarily limits the supported file formats in the whole application but then it would be rather arbitrary. Under the hood, loading the actual images is done outside of my own code. I could do it; but it's a very rare problem.
