### ISSUE TITLE
Help: Can't find game location using Protontricks

### ISSUE THREAD

**Issue by Keldium** [Reloaded-Project/Reloaded-II#458]
Hi ! I ran Reloaded II using Protontricks with Persona 5 Royal but I can't find the place where the exe of my game is, and none of the shown disk actually have the correct folders of my home... I've been on this for more than 3 hours, can someone help me, please ? Sorry for my bad english !
![IMG_20241007_220654](https://github.com/user-attachments/assets/03083bce-0cb0-457e-8ab6-897899596b06)
![IMG_20241007_220722](https://github.com/user-attachments/assets/ac81b620-87f2-463e-b255-debe5ebf1e98)

**Comment by Sewer56** [comment]
(I was napping, but I think they found it)
