### ISSUE TITLE
Can't open folder to add mods or drag mods folder into Reloaded II

### ISSUE THREAD

**Issue by SpxllTheTee** [Reloaded-Project/Reloaded-II#461]
I just finished setting up the installer but I can't drag the mod into the installer or open the folder.

**Comment by Sewer56** [comment]
If you're working with .zip files, try dragging mods onto the titlebar.

**Comment by SpxllTheTee** [comment]
I'm also stuck in a download loop and it shows up a huge error window when i tried dragging my mods into there

**Comment by Sewer56** [comment]
It's unusual for this to fail

```
r2:https://github.com/Sewer56/Reloaded.SharedLib.Hooks.ReloadedII/releases/download/1.16.1/Reloaded.Hooks.ReloadedII1.16.1.7z
```

Copying this to your web browser's address bar should manually trigger a download.

However doublecheck the path to `Reloaded-II.exe`; if it has special characters, you may find you have issues extracting mods and/or running mods with some games; since the mods get loaded from the Reloaded folder and some games don't handle that well.

**Comment by SpxllTheTee** [comment]
![image](https://github.com/user-attachments/assets/0152ae3f-bc9b-4bac-9029-3c3d16f38bcf)
it still pops up

**Comment by Sewer56** [comment]
Then follow the rest of the post please; check the file path to Reloaded.

**Comment by SpxllTheTee** [comment]
![image](https://github.com/user-attachments/assets/704691b2-a92d-4f5e-8356-c0725f740b8d)
is it correct

**Comment by Sewer56** [comment]
I said

> However doublecheck the path to `Reloaded-II.exe`

By this I mean the location of the Reloaded program itself;. I do not mean the place where the game is installed.

**Comment by SpxllTheTee** [comment]
It's in my D drive

**Comment by Sewer56** [comment]
That's not very helpful.
What is the path to `Reloaded-II.exe` ?

**Comment by SpxllTheTee** [comment]
can you guide me to it i'm also kinda confused

**Comment by Sewer56** [comment]
How do you launch Reloaded? Is it through a shortcut on your desktop?
If that is the case, right click the shortcut and hit `properties`. There should be a file path to the EXE file stated there.

**Comment by SpxllTheTee** [comment]
it's in my onedrive i don't know why

**Comment by Sewer56** [comment]
A full path would be more useful. In any case, I'll assume either file path or OneDrive could be a problem.
Try moving the folder out from `OneDrive` to a location like `C:/Reloaded-II`, maybe that will help.

**Comment by SpxllTheTee** [comment]
I closed it and I tried moving it and it's still OneDrive

**Comment by Sewer56** [comment]
Well; I do not know what else to say. Sorry.
What do you see? Is Windows preventing you from moving it?
Do you maybe need to close the program and game; so files are not in use?
I don't know.

**Comment by SpxllTheTee** [comment]
I moved the program to D drive and it's folder and the program's property is still in OneDrive.

**Comment by Sewer56** [comment]
> and the program's property is still in OneDrive.

Shortcuts don't automatically relocate.

Remove the shortcut.
Go to `Reloaded-II.exe` in your D drive; and create a new shortcut from the right click menu.

**Comment by SpxllTheTee** [comment]
Alright done

**Comment by SpxllTheTee** [comment]
what do i do next

**Comment by Sewer56** [comment]
I don't know, I give up for now.

**Comment by SpxllTheTee** [comment]
alright.

**Comment by Sewer56** [comment]
They were able to get this working eventually (in Discord).
