### ISSUE TITLE
Recently unable to open ReloadedII in SteamOS, mods still load in Persona 5.

### ISSUE THREAD

**Issue by kdliu86** [Reloaded-Project/Reloaded-II#462]
I've had mods installed since forever, and have Persona 5 1.03b exe replaced in.  I can't open ReloadedII.exe using Protontricks though, Protontricks tries for a few seconds then exits.

When starting P5R it loads with the mods (and the Reloaded terminal in the background).

Loading Reloaded with protontricks does nothing, so I can't check enable/disable mods.

**Comment by Sewer56** [comment]
Can you run protontricks via the termimal?
I think it was `protontricks --gui` off the top of my head, and get a log file. 

If you run `protontricks --gui  &> out.txt`, you should get a log file named `out.txt`. Then simply try running the exe from protontricks, hopefully there's something useful in there.

**Comment by kdliu86** [comment]
Per @Sewer56 recommendations from chat:

1. Copy apps, mods, user folders to the desktop reloadedii-p5r folder.
2. Delete the "old" reloadedii.exe installation folder.
3. Rerun setup-linux.exe with the P5R prefix.

**Comment by Sewer56** [comment]
(Just re-running launcher with old launcher folder gone would have fixed the JSON)
