### ISSUE TITLE
Help: [WINE]Can't run Silent Hill 3 via ASI loader

### ISSUE THREAD

**Issue by Erwin-Iosef** [Reloaded-Project/Reloaded-II#463]
**Did you install the Prerequisites?**
Yes. x86 and x64 of 8.0.10 .NET
Using wine-cachyos(proton-9.0)

**Describe the Issue**
Trying to run sh3.exe via ASI deploy crashes the game. Mods used are Silent Hill 3 Audio Enhancement pack.
Address Error is 0
Fault Module is blank

**Additional Resources**
[2024-10-11 06.14.56 ~ sh3.txt](https://github.com/user-attachments/files/17338690/2024-10-11.06.14.56.sh3.txt)
[info.json](https://github.com/user-attachments/files/17338692/info.json)
[dump.txt](https://github.com/user-attachments/files/17338697/dump.txt)
I uploaded the dump file as .txt since I couldn't upload it with it's usual extension.

**Comment by Sewer56** [comment]
Does the unmodified game run fine? [I think you could easily test by removing WINEDLLOVERRIDES temporarily]
The error's a bit unusual, the game code jumps to an invalid address (0x0), which is very rare.

**Comment by Erwin-Iosef** [comment]
Of course and through the reloaded launcher too.
By the way, I did not expect the fast response, thanks!

**Comment by Sewer56** [comment]
Does it crash at a specific place? Like the intro sequence?
I think I might have a backup of this game somewhere, so I could try it on my own machine; I'm conveniently on the same distro.

**Comment by Erwin-Iosef** [comment]
CachyOS?
Nope, never did crash.

**Comment by Erwin-Iosef** [comment]
I tried reinstalls of ASI deployer obviously.

**Comment by Sewer56** [comment]
![image](https://github.com/user-attachments/assets/110a61f1-e157-4a58-9837-9663e9068220)

![image](https://github.com/user-attachments/assets/41b2671d-405b-4825-a59a-3bb9287d7806)

![image](https://github.com/user-attachments/assets/ee024247-8966-42a5-88a7-27a0961fa1c2)

I can't reproduce.

I tried what I think would be a 'common' setup; so the base game, the common fix mod; a clean install of Reloaded and a clean install of Audio Enhancement Pack.

**Comment by Erwin-Iosef** [comment]
Oh I use gallium nine if that counts.

**Comment by Erwin-Iosef** [comment]
I'll try in a clean wineprefix.

**Comment by Sewer56** [comment]
No worries :p

**Comment by Erwin-Iosef** [comment]
@Sewer56 I'm back, tried with a clean prefix with both the x86 and 64bit .NET installed and the ASI loading starts the game but no mod. But when launched through the Launcher I get this, mod loaded or no: 
![image](https://github.com/user-attachments/assets/1a0c512f-e11f-4e97-8276-379b17914228)

**Comment by Sewer56** [comment]
That's rather unusual; I have no idea.
In my case, when trying to repro, I specifically:

0. Ran the game unmodded to generate new WINEPREFIX
1. Setup the game with `Setup-Linux.exe`; and the game's WINEPREFIX.
2. Dropped files for PC fix mod by Steam006;
3. Started game from Reloaded.

I actually didn't try ASI Loader, but I did modify launch commands to get Steam006's fix to kick in.

**Comment by Erwin-Iosef** [comment]
I just removed the Reloaded folder and retried the Setup Linux thing and the same error occurs.
I think I'll use my old wineprefix but remove gallium nine(I use Arch's 'wine-nine' package which is broken a bit when it comes to disabling wine)

**Comment by Sewer56** [comment]
Hmm... how strange.

**Comment by Erwin-Iosef** [comment]
Okay, I got it, I missed the VCredists(also you ought to update their links, we have a 2015-2022 at the present, while your download button goes to download the 2015-2019 one) , the game runs with launcher with mod running although the graphics have some glitchy fade effect.
ASI loader, runs but no mod. Also both of them run windowed.

**Comment by Sewer56** [comment]
> ASI loader, runs but no mod

Probably need a WINEDLLOVERRIDES entry for whatever the loader's name wound up being

**Comment by Erwin-Iosef** [comment]
I think the problem after all might be Gallium Nine, in hindsight I should have checked it for that at the start.

**Comment by Erwin-Iosef** [comment]
Just checked, nope it wasn't. I even tried through the reinstall through the WINEOVERRIDEDLL command with the d3d9 dlls restored to their wine counterparts.

**Comment by Sewer56** [comment]
What a strange situation; damn. I don't know what to say :sweat_smile:

**Comment by Erwin-Iosef** [comment]
Indeed, the prefix wasn't that old and only contained audio fixes like xaudio and faudio and other codecs installed via winetricks. Maybe something in the old registry I imported too. I'll try posting the winedebug messages if that will help, apart from that, "fixing" the registry will be a major pain in the ass, which I'll do as a last resort.

**Comment by Erwin-Iosef** [comment]
Alright the problem was my registry. Tried the old prefix with the MS dependencies for Reloaded(I think R2 is a cool short name for it btw) with a clean registry with nothing added and launched the game via winedll command. It worked.

**Comment by Erwin-Iosef** [comment]
> n any case, that's how it creates an AFS file the game reads for audio without actually writing to the disk. It's very unusual it works on my end though and not yours; especially since we're on the same distro. Yours is on /media, could it be something with filesystem maybe?
No, I don't think so, I always created a wine drive for each windows partition I had, it's clean.

*wipes sweat off brow*

**Comment by Erwin-Iosef** [comment]
Lesson for anyone reading this in the future, keep your registry simple and halal :moyai:

**Comment by Erwin-Iosef** [comment]
@Sewer56 Thank you so much for your help and input. It really helped.
Marking it as closed if no further objections?

**Comment by Sewer56** [comment]
Feel free :p

**Comment by Erwin-Iosef** [comment]
Thanks man :+1:
