### ISSUE TITLE
[Startup Fails due to Outdated Mod: Coloured Chat Icon BG]

### ISSUE THREAD

**Issue by Mountainbugs** [Reloaded-Project/Reloaded-II#465]
**Describe the Bug**

1. Go to Persona 5 Royal
2. Click on Launch Application
3. See error

This disables all mods when I launch the game. I deleted the colored chat icon mod and this still appears. 

![image](https://github.com/user-attachments/assets/8ca9440e-07d7-40a5-8a8e-6d0a1b076441)

**Comment by Sewer56** [comment]
The 'Coloured Chat Icom BG' and any mods which depend on it, were not updated for the latest version of the game.

**Comment by Mountainbugs** [comment]
Wasn't Sure what that mod would be but it was the creators other mod P5R Unhardcoded Tookit. Thanks for the help!
