### ISSUE TITLE
Bug: Persona 5 Royal frequently fails to launch if "AWB Emulator for File Emulation Framework" is enabled

### ISSUE THREAD

**Issue by MaxHeat** [Reloaded-Project/Reloaded-II#466]
On a fresh install of Persona 5 Royal and Reloaded-II, the game will frequently fail to launch (with the process still open in Task Manager).
An "Unknown Error" window appears with the actual error stating "Failed to obtain port for the Reloaded instance running inside the process".

The game will sometimes successfully launch and when it does everything seems to be working fine.

While testing I've disabled all mods and managed to find the game will fail to launch with "AWB Emulator for File Emulation Framework" being the only mod enabled.

**Comment by Sewer56** [comment]
Try removing the mod; and see what happens after it auto redownloads.

**Comment by MaxHeat** [comment]
After removing it and the software redownloading it, the game manages to launch only one time only. Any other attempt will produce the error.

I've also discovered deleting the mod and auto redownloading it before launching the game will never fail oddly enough.

**Comment by Sewer56** [comment]
Consider checking antivirus logs; maybe it's getting blacklisted for some reason after first run.

**Comment by MaxHeat** [comment]
With the console enabled, this is where everything stops 
![screenshot](https://github.com/user-attachments/assets/30f80b39-7c06-4e56-95a0-4d0919e91a1c)

I usually need to retry launching 9-10 times (without changing anything) to be able to play with mods.

**Comment by Sewer56** [comment]
That's unfortunately normal for the time being (it's an Issue with FileEmulationFramework); and wouldn't be fixed for a while.

It requires a full rewrite.

**Comment by Sewer56** [comment]
Closing this as 'stale', re-open this if it still affects you.
