### ISSUE TITLE
Request: Please Add Support for Multiple Profiles and Mod Folders, One for Each Game

### ISSUE THREAD

**Issue by ChemGuy1611** [Reloaded-Project/Reloaded-II#467]
**Is your feature request related to a problem? Please describe.**
When trying to manage multiple different games with Reloaded, it wants to look for mods in the folder you established for the first game you managed. If you want to use a different folder for subsequent games, there is no way to add a second folder to load mods from.

**Describe the solution you'd like**
Add the ability to have each game that is added to Reloaded load mods from a different folder. In my case, I am using Vortex Mod Manager to install mods to the "Mods" folder next to the reloaded executable. I'm deploying a separate Reloaded executable to each game's installation folder to load mods for that game.

In fact, it would be ideal to have separate profiles for each game, not just the mod folder, so that you could configure Reloaded entirely separately for each individual game. 

This would also help clean up the mods list when managing multiple games. As it is now, when managing several games, you end up seeing all the installed mods listed for each game, which could get cumbersome if a certain game uses many mods.

**Describe alternatives you've considered**
The only way I see to do this now would be to manually edit the mod directory in the config file each time you want to load mods for a different game, which is obviously not feasible.

**Additional context**
This request is specifically in regards to Vortex Mod Manager. I have made a Vortex extension for FFXVI that downloads Reloaded to the game folder and installs mods to the Mods folder there. I am working on another extension for Metaphor: ReFantazio, and ran into the problem described above when trying to setup the second downloaded instance of Reloaded in the MRF game folder. THe config files still refers to folders for FFXVI, and I don't see any way to change this except manually editing the config file, which would obviously break the instance used for FFXVI.

Here's how the ReloadedII.json ends up looking in this case. You can see how it ends up being a mix between the FFXVI (where the "config" folders are, because it was the first place Reloaded was launched from) folders and the new MRF folders (where the executable is being launched from now):

```
  "LoaderPath32": "F:\\Game_Tools\\Metaphor_Tools\\Metaphor ReFantazio TEST GAME FOLDER\\Reloaded\\Loader\\x86\\Reloaded.Mod.Loader.dll",
  "LoaderPath64": "F:\\Game_Tools\\Metaphor_Tools\\Metaphor ReFantazio TEST GAME FOLDER\\Reloaded\\Loader\\x64\\Reloaded.Mod.Loader.dll",
  "LauncherPath": "F:\\Game_Tools\\Metaphor_Tools\\Metaphor ReFantazio TEST GAME FOLDER\\Reloaded\\reloaded-ii.exe",
  "Bootstrapper32Path": "F:\\Game_Tools\\Metaphor_Tools\\Metaphor ReFantazio TEST GAME FOLDER\\Reloaded\\Loader\\x86\\Bootstrapper\\Reloaded.Mod.Loader.Bootstrapper.dll",
  "Bootstrapper64Path": "F:\\Game_Tools\\Metaphor_Tools\\Metaphor ReFantazio TEST GAME FOLDER\\Reloaded\\Loader\\x64\\Bootstrapper\\Reloaded.Mod.Loader.Bootstrapper.dll",
  "ApplicationConfigDirectory": "F:\\SteamLibrary\\steamapps\\common\\FINAL FANTASY XVI DEMO\\Reloaded\\Apps",
  "ModUserConfigDirectory": "F:\\SteamLibrary\\steamapps\\common\\FINAL FANTASY XVI DEMO\\Reloaded\\User\\Mods",
  "MiscConfigDirectory": "F:\\SteamLibrary\\steamapps\\common\\FINAL FANTASY XVI DEMO\\Reloaded\\User\\Misc",
  "PluginConfigDirectory": "F:\\SteamLibrary\\steamapps\\common\\FINAL FANTASY XVI DEMO\\Reloaded\\Plugins",
  "ModConfigDirectory": "F:\\SteamLibrary\\steamapps\\common\\FINAL FANTASY XVI DEMO\\Reloaded\\Mods",
  "EnabledPlugins": [],
  "LanguageFile": "F:\\Game_Tools\\Metaphor_Tools\\Metaphor ReFantazio TEST GAME FOLDER\\Reloaded\\\\Assets\\Languages\\en-GB.xaml",
  "ThemeFile": "F:\\Game_Tools\\Metaphor_Tools\\Metaphor ReFantazio TEST GAME FOLDER\\Reloaded\\\\Theme\\Default.xaml",
  "FirstLaunch": false,
  "ShowConsole": true,
  "LogFileCompressTimeHours": 6,
  "LogFileDeleteHours": 336,
  "CrashDumpDeleteHours": 24,
  "NuGetFeeds": [
    {
      "Name": "Official Repository",
      "URL": "http://packages.sewer56.moe:5000/v3/index.json",
      "Description": "Package repository of Sewer56, the developer of Reloaded. Contains personal and popular community packages."
    }
  ],
  "ForceModPrereleases": false,
  "ReloadedProcessListRefreshInterval": 1000,
  "LoaderSetupTimeout": 30000,
  "LoaderSetupSleeptime": 32,
  "ProcessRefreshInterval": 200,
  "SkipWineLaunchWarning": false,
  "DisableDInput": false
}
```

So, I think what I am asking is for each game profile to allow you to set separately these directories. I suppose the "ApplicationConfigDirectory" would need to be in a centralized location, such as the Roaming AppData folder where the ReloadedII.json is located.

```
"ApplicationConfigDirectory": "F:\\SteamLibrary\\steamapps\\common\\FINAL FANTASY XVI DEMO\\Reloaded\\Apps",
"ModUserConfigDirectory": "F:\\SteamLibrary\\steamapps\\common\\FINAL FANTASY XVI DEMO\\Reloaded\\User\\Mods",
"MiscConfigDirectory": "F:\\SteamLibrary\\steamapps\\common\\FINAL FANTASY XVI DEMO\\Reloaded\\User\\Misc",
"PluginConfigDirectory": "F:\\SteamLibrary\\steamapps\\common\\FINAL FANTASY XVI DEMO\\Reloaded\\Plugins",
"ModConfigDirectory": "F:\\SteamLibrary\\steamapps\\common\\FINAL FANTASY XVI DEMO\\Reloaded\\Mods",
```

**Comment by Sewer56** [comment]
I have no plans on future feature work; only bug fixes. Especially given that I'm the only developer here.

R2 was simply not designed with proper profiles in mind; including full config separation. And unfortunately, I don't have the same level of resources projects like HedgeModManager or ModOrganizer2 have; I do not have a dev team, it's just me after all. This sort of thing is possible with the Reloaded3 spec; but not with Reloaded-II.

In any case:

> so that you could configure Reloaded entirely separately for each individual game.

I think it's possible to achieve what you want [portable mode](https://reloaded-project.github.io/Reloaded-II/ExperimentalFeatures/#portable-mode) by placing a `portable.txt` file next to `Reloaded-II.exe`. This flag ignores the global config file, and reads from folders local to the launcher. Do note that it's a a bit of a hack; R2 wasn't designed with that in mind (I added it postmortem by request); but as long as the correct `Reloaded-II.exe` was launched last before starting the given game, stuff should work fine.

**Comment by ChemGuy1611** [comment]
Thank your for the quick reply. I think the portable.txt hack will help to achieve what I am looking to do for now.

Thanks for your work on this mod loader. You are enabling mods for many games that would not have any mod support otherwise. Hopefully you can find some additional developer help. I would offer mine, but I don't really know C# at all, so I would be rather useless lol.

**Comment by ChemGuy1611** [comment]
Gave it a quick test and the portable.txt seems to do the trick. I can have my extension write that file right next to Reloaded-II.exe and it seems to work just fine. 

Thanks again!
