### ISSUE TITLE
Bug: When Executable and Working Directory don't match

### ISSUE THREAD

**Issue by Blackouto000** [Reloaded-Project/Reloaded-II#468]
I downloaded P5R into another drive, so i changed the executable location, but everytime i launched the game an error was spammed constantly, it was only after changing the working directory to the one on the other drive that it actually worked, decided to report this as a bug because there wasn't an appropiate report type for this (And this technically isn't a bug)

**Comment by Klemci** [comment]
Please tell me how i set RLD **portable**, i don't want two games managed by the same instance, and i just used RLD for a second game by making a new instance (it runs from another folder, so) as i thinked it'd work, and it showed the other game too inthe list, also it finds/searches mods there and not in his new/second directory and not the mods in his new instance !!!

I need to know how to enable **portable mode** to not mix the games, as i always do.

Thanks

**Comment by Sewer56** [comment]
@Klemci Use a relative path in the App.json

https://reloaded-project.github.io/Reloaded-II/ExperimentalFeatures/#relative-pathed-applications

After putting Reloaded ***in a subfolder of the game.***

(DO NOT mix Reloaded-II.exe with existing files, else you will incur data loss on Reloaded update)

**Comment by Sewer56** [comment]
Also closing this because I made WorkingDir auto adjust in code lately already.

**Comment by Klemci** [comment]
Perfect thanks.
