### ISSUE TITLE
[Flatpak: Installer generated shortcuts are broken because protontricks alias doesn't kick in]

### ISSUE THREAD

**Issue by NickOnimura** [Reloaded-Project/Reloaded-II#471]
I have installed Reloaded-II onto Steam Deck via the Linux installer and followed all of the instructions for configuring Protontricks and Flatseal to detect my Sonic Heroes installation. However, clicking on the desktop shortcut does not open the loader and opening the shortcut in the start menu gives the error "Could not find the program 'protontricks-launch'.

I assume this has to do with the echo command entered into the terminal. Are there any other steps I have to take?

**Comment by Sewer56** [comment]
I'm guessing the alias:

```
echo "alias protontricks='flatpak run com.github.Matoking.protontricks'" >> ~/.bashrc
echo "alias protontricks-launch='flatpak run --command=protontricks-launch com.github.Matoking.protontricks'" >> ~/.bashrc
```

Isn't sticking with flatpak.
I'm not exactly sure what can be done here as I'm not a flatpak user myself.

I could try modify the installer itself, but it's hard to run native commands.
I'm currently taking a break, so I can't guarantee any solutions; I rely on others to test some of this stuff.

**Comment by NickOnimura** [comment]
Appreciate the feedback.

**Comment by Sewer56** [comment]
Quick question; would you be able to try something for me?

If you look in your Desktop, you should see a `.desktop` file which contains the shortcut.
If you modify it such that the command is wrapped in `bash -ic`; for example

Before:
`Exec=protontricks-launch --appid 3847140856 "/home/sewer/Desktop/Reloaded-II - Sonic Heroes/Reloaded-II.exe"`

After:
`Exec=bash -ic 'protontricks-launch --appid 3847140856 "/home/sewer/Desktop/Reloaded-II - Sonic Heroes/Reloaded-II.exe"'`

Does the shortcut work?

---------

Misc note: Technically I shouldn't run bash, but the whole installer is a hack anyway. R3 will have proper native support.

**Comment by Sewer56** [comment]
May be fixed in future build with 35e43fbbd17a30afe7a4f02361879bd0282233f4

**Comment by NickOnimura** [comment]
Adding the bash tag to the desktop shortcut did the trick. Reloaded opened without a hitch.

**Comment by Sewer56** [comment]
The newest installer does this out of the box, so I consider the problem fixed.
