### ISSUE TITLE
Bug: Reloaded II does not load MetaphorFix when Deploy ASI Loader and start the game directly from Steam or .exe

### ISSUE THREAD

**Issue by Randy28CR** [Reloaded-Project/Reloaded-II#475]
Hi there!

Thank you so much for you hard work on this tool. It is amazing!

Idk if this is a bug or a sort of incompatibility, but I would like to report the following:

I added MetaphorFix from Lyall to Reloaded II. It works as intended when launched through Reloaded II app.

However, when I deploy de ASI loader in order for the game to load all mods when launching from Steam (specifically Big Picture Mode) or even the .exe file, MetaphorFix does not load.

Is there a way this can be fixed?

I use my PC plugged to my TV and trying to load MetaphorFix through Special K breaks controller support on Big Picture Mode. I would love to be able to load MetaphorFix along the other mods when launching the game directly through Steam Big Picture Mode.

Regards!

**Comment by Sewer56** [comment]
Curious, can you screenshot the game folder?
When you launch the game via the exe directly (no big picture), do you get the logging console?

**Comment by Nenkai** [comment]
Same issue over on the FFXVI side which has been left unanswered - https://github.com/Lyall/FFXVIFix/issues/151

Unless the author is willing to deploy reloaded-compatible packages for every single of their fix projects, this issue will persist across games (and I don't personally have the time to do a PR for every single one of their project even though they all stem from a template).

**Comment by Sewer56** [comment]
@Nenkai they're loading MetaphorFix via Reloaded according to description. MetaphorFix does have 1st party R2 package built in CI. Same with P3RFix

**Comment by Randy28CR** [comment]
Hello @Sewer56!
I will be sharing the screenshot later today once I arrive home. Thank you for having interest on this!

**Comment by Randy28CR** [comment]
Hello @Sewer56 
I opened this when testing the MetaphorFix version 8.0.2.
I was taking the SS to share with you the problem but the I noticed Lyall updated the mod to 8.0.3
I updated the mod and now, idk why, it works as intended!

**Comment by Sewer56** [comment]
If it works, it works :ok_hand:

**Comment by Randy28CR** [comment]
Still, thank you so much for being pending!
Keep the great job!
