### ISSUE TITLE
Enhancement: Detection of OneDrive during Reloaded Install

### ISSUE THREAD

**Issue by dreamsyntax** [Reloaded-Project/Reloaded-II#477]
--- Update: ---
--- Enhancement: Detection of OneDrive during Reloaded Install
Per the below discussion, instead I only will check for OneDrive and defer to the system root of the OS. In most common cases, that would be `C:\` - so Reloaded-II's folder would be `C:\Reloaded-II`

--- Original Issue below: ---
--- Enhancement: Detection of Problematic Locations of Target Game or Reloaded Folder 
Games can fail to load properly if either the target game path OR Reloaded-II's primary folder...
- is located in a path that is synced by OneDrive. By default, logged in Microsoft accounts on Windows 11 try to sync Desktop to OneDrive. As such Reloaded.Mod.Loader.Bootstrapper.dll may reference `C:\Users\someguy\OneDrive\Desktop\Reloaded-II`
- contains special characters (ex: `C:\Users\ͽͽʹ˧˧˧˧˧crqa5 userbruh\Desktop\Reloaded-II\`)
- is on a NAS (ex: `\\192.168.17.52\SharedStorage\Games\MyGoofyGame`)

**Describe the solution you'd like**
- Implement runtime detection and suggested mitigation popups if either a game path or Reloaded-II contains potentially problematic state. Potentially offering to automatically move Reloaded-II's folder.

**Alternatives**
- Move Reloaded-II primary configuration back to AppData; Still does not account for games.
- Warning pops up on game load/launch IFF the target game crashes and the game or reloaded installation is in a 'known problematic path'
---

This may be a bit tricky to account for all cases and not negatively impact any Linux users. I'm not sure if we could reliably detect other cloud providers (such as DropBox) - so rather than a perfect solution, the highest priority imo is accounting for Windows 11 default case of OneDrive and the conflict with Desktop.

I plan to look into implementing a PR for this issue, but it may only partially resolve.

**Comment by Sewer56** [comment]
Unusually detailed ticket, I like those.

> if either a game path 

If a game path itself has special characters, you can probably assume the game handles itself fine.

-------

In any case, Reloaded-II itself has no issues with paths with special characters, aside from extraction with `7z.dll` in case of special characters which may be fixable.

I think the best solution would be simply not installing R2 to OneDrive or a location with special characters. For the latter, path to Desktop will have `OneDrive` in it, for the former, check the character set.

Since the installer runs as admin, you could fallback to `C:/Reloaded-II` in those cases; assuming that a typical user can write to that path. That needs to be checked.

**Comment by dreamsyntax** [comment]
For now the following PR will use a variant of:
https://github.com/Reloaded-Project/Reloaded.Memory/blob/6bab99d723bf6f783d24ed0d489db28ea5d9e075/src/Reloaded.Memory/Internals/Backports/System/Globalization/TextInfo.cs#L139C31-L139C58
for special chars
And explicitly look for "OneDrive" (which even on other language installs, should be called that).

On fail, will fallback to either `C:\Reloaded-II` or `%appdata%\Reloaded-II\program`
I think the best solution would be simply not installing R2 to OneDrive or a location with special characters. For the latter, path to Desktop will have OneDrive in it, for the former, check the character set.

**Comment by Sewer56** [comment]
The user's username can also use special characters; although rare, it is possible.
Because `%appdata%` falls under that, I think you'll need to delegate to `C:\` in any case.

**Comment by Sewer56** [comment]
For games you can ignore it, most people will install games via a game store in practice, which wouldn't usually use a special path.

For games installed outside of stores, I simply hope the user tests an unmodded game first.

**Comment by dreamsyntax** [comment]
Split this issue up into three.

Repurposed this issue to just be about mitigating OneDrive on initial install, but has no bearing on existing users.

Moved two items I think are worthwhile to separate issues:
https://github.com/Reloaded-Project/Reloaded-II/issues/503
https://github.com/Reloaded-Project/Reloaded-II/issues/502
