### ISSUE TITLE
Request: Please Add <PORTABLE FULL>

### ISSUE THREAD

**Issue by Klemci** [Reloaded-Project/Reloaded-II#478]
Portable Instances:

I tried but no luck, it finds the EXE ( "..\\..\\..\\DIR\\EXE.exe" ) but once i launch another instance from another folder it finds the other...
Since there is local & roaming AppData settings it can't work bc each instances share json files !
RLDII adds an Environement Variable for Mods folder, then it can't be set to portable at all.

That's all i can say.

Since i use the last **but** net**8** version, perhaps _since net9_ it changed !?

**Comment by Sewer56** [comment]
True portable mode for R2 is unlikely to happen, as it's in maintenance mode; I'm not working on any new features.

You can soften the blow however by making shortcuts to your individual copies of the program, or shortcuts which boot the game with a given Reloaded copy (1 click in launcher).

The codebase wasn't originally written with portable in mind, for instance, the bootstrapper has no knowledge of how to find Reloaded outside of the shared static `.json` file. Rewriting that logic is a bit more than I'd be willing to invest time into, given I've been working on R2's successor for a long while.

**Comment by Klemci** [comment]
Do i understand correctly **Granblue Fantasy Relink :**

 if i launch it by RLDII with my wanted mods in rldII\mods folder... it writes (and backups) the data.i file then after i don't need RLDII to start the game since it's already patched/modded the file !?

**Comment by Sewer56** [comment]
Bear in mind this is mod specific behaviour.
Usually R2 mods should never edit the game folder.

**Comment by Nenkai** [comment]
I should fix it for GBFR eventually 😅
That would at least bring it to.. 1.

**Comment by Sewer56** [comment]
That's true :p

**Comment by Klemci** [comment]
No logo, Easy Parry, DOF MBlur OFF, Fast Auto Healing - All look to be data mods, i use none ASI.

That's all,

and Special-K for the UI Customs mod btw.

**Comment by Klemci** [comment]
> I should fix it for GBFR eventually 😅 That would at least bring it to.. 1.

In my case i don't need RLDII anymore i'll just use the Mod Manager specific to the game (2024-4) since it does the same :p 

What mods are called injected if not ASI/DLL ??

**Comment by Nenkai** [comment]
> > I should fix it for GBFR eventually 😅 That would at least bring it to.. 1.
> 
> In my case i don't need RLDII anymore i'll just use the Mod Manager specific to the game (2024-4) since it does the same :p
> 
> What mods are called injected if not ASI/DLL ??

In the case of GBFR that will be mainly my mods, but also the Weapon Customization mod.

**Comment by Klemci** [comment]
> > > I should fix it for GBFR eventually 😅 That would at least bring it to.. 1.
> > 
> > 
> > In my case i don't need RLDII anymore i'll just use the Mod Manager specific to the game (2024-4) since it does the same :p
> > What mods are called injected if not ASI/DLL ??
> 
> In the case of GBFR that will be mainly my mods, but also the Weapon Customization mod.

I found none of yours in my list, nor weapons Custo mods, thanks for the answer ;)
