### ISSUE TITLE
Bug: Could not find a part of the path when installing on Linux

### ISSUE THREAD

**Issue by t0mtee** [Reloaded-Project/Reloaded-II#479]
**Describe the Bug**
When installing on Linux as described [here](https://reloaded-project.github.io/Reloaded-II/LinuxSetupGuideNew/) gives this error:
![image](https://github.com/user-attachments/assets/a1074e2e-0374-495c-bd7b-c24b2b9d7b2a)
while running Setup-Linux.exe,

**To Reproduce**
Steps to reproduce the behaviour:
1. Right click Setup-Linux.exe
2. Select the Steam game (For me, Persona 3 Reload)
3. Wait

**Expected Behaviour**
Reloaded II installs correctly.

**Comment by Sewer56** [comment]
You probably have Protontricks installed via Flatpak, but didn't give it FileSystem permission.
[See here for details](https://reloaded-project.github.io/Reloaded-II/LinuxSetupGuideNewExtra/#installing-protontricks-via-flatpak)

**Comment by t0mtee** [comment]
You were right - sorry, this was a simple thing!

**Comment by Sewer56** [comment]
Don't worry about it, all is good :p

**Comment by Sewer56** [comment]
Closed with a hack in 4b33b72a5a5061402832f98cddc077022bf81f9a
