### ISSUE TITLE
Help: Please help me with <Unknown Error> for Reloaded II 

### ISSUE THREAD

**Issue by Sakuzyoi** [Reloaded-Project/Reloaded-II#480]
I'm trying to mod P5R (PC) using Reloaded II, but every time I try to install a mod or even add a mod it gives me an error and abruptly closes the application. I will show the following error below with a screenshot, if anyone has any information on how to resolve this issue, I'd greatly appreciate it.

![Screenshot (230)](https://github.com/user-attachments/assets/0297ae9f-2de2-42b6-aa56-83f1f339f695)
![Screenshot (231)](https://github.com/user-attachments/assets/ee5230b6-9e08-486c-935d-7bbb9b9e8a9d)
![Screenshot (232)](https://github.com/user-attachments/assets/0530ce50-fe40-46d5-bd36-8dee8e95a6c2)

I am new to Reloaded II, so I have tried the following to remedy the situation.

1. I deleted everything and reinstalled four times.
2. I made sure I had all the right dependencies and prerequisites installed to use this Mod, courtesy of the site and Gamebanana.
3. I tested to see if installing any other mods would work, only to achieve the same result.
4. I followed numerous modding guides on how the files should look and what folder to make to input the exe.
5. I uninstalled the game and reinstalled it to the main drive.
6. I asked a coder buddy what the error meant, and he said something along the lines of it being an issue with the program itself.
7. I attempted to manually install the mods via gamebanana to the Reloaded II exe, and even that failed. It would say it was successfully downloaded, but wouldn't show up in the mods listing even with the proper game ID.

After having exhausted all my current resources and spending hours troubleshooting, I had to make an account to get some insight on the dilemma.

**Comment by Sewer56** [comment]
Try moving the Reloaded folder to a place without a special character, such as `C:/Reloaded-II`.
The 7z.dll wrapper I use doesn't handle special characters well, and many games don't either.

**Comment by Sakuzyoi** [comment]
YOU'RE MY HERO, THANK YOU SO MUCH! I was pulling my hair hours, and the solution was so simple.

**Comment by Sewer56** [comment]
No worries, had a hunch.
There is an open issue to avoiding that during setup, but I haven't gotten around to that yet :p
