### ISSUE TITLE
Bug: "Create Shortcut" makes an Empty File instead of an actual Shortcut.

### ISSUE THREAD

**Issue by Willshaper** [Reloaded-Project/Reloaded-II#481]
**Describe the Bug**
I have added Metaphor ReFantazio to Reloaded-II, and it can launch the game properly with installed Mods via the Reloaded-II "Launch Application" button.
But trying to use the "Create Shortcut" button will result in a 0 Byte file on my desktop called "Metaphor", no extension or data in it as far as i can see.

**To Reproduce**
Steps to reproduce the behaviour:
1. Click Metaphor ReFantazio Icon in the Sidebar
2. Click the "Create Shortcut" button under "Actions"
3. Find the newly created file on your Desktop
4. File is Empty

**Expected Behaviour**
I expect the shortcut file to be a Shortcut, not an empty file.

**Screenshots**
![billede](https://github.com/user-attachments/assets/8cbe1037-47d0-4075-b5df-470916614ab9)
![billede](https://github.com/user-attachments/assets/263d8be4-56d0-4b6b-96cd-4bfc72de3c71)
![billede](https://github.com/user-attachments/assets/ee35c146-5c78-4219-9bfe-71a05998ea91)

**Additional Context**
This is with a freshly installed and updated Reloaded-II: "2024-10-18T17:42:34 | 1.28.2 | .NET 8.0.10"
I have tested both launching normally, and as Administrator.

**Comment by Sewer56** [comment]
That's a new one.

Does your username have special characters in it? I wonder if it could be related to that.

**Comment by Willshaper** [comment]
> That's a new one.
> 
> Does your username have special characters in it? I wonder if it could be related to that.

It just so happens that my username has an underscore at the end. "name_"
![billede](https://github.com/user-attachments/assets/75115e1f-182d-4b30-92d8-0e80301b03c2)

**Comment by Sewer56** [comment]
Interesting, I'll look into it eventually.

**Comment by Sewer56** [comment]
In the meantime, if you want to make a shortcut manually, you can make a shortcut to `Reloaded-II.exe` and add `--launch "PATH_TO_FULL_GAME_EXE"` as a parameter.

You can do that by right clicking shortcut, going to properties and appending it to the `Target` field.

**Comment by cadewey** [comment]
The problem is that the game has a colon in its name, and that's not a valid character for a Windows file path. `MakeShortcutCommand.Execute()` probably needs some sanitizing.

As a workaround, you can fix this by editing the game config in Reloaded and removing the colon character.

**Comment by kamsai11** [comment]
My workaround was like... if you have another atlus game for example, let's say.... Persona 5R. Just create a shortcut with p5r, edit the path to something like this: C:\Users\ryuuk\Desktop\Reloaded-II\Reloaded-II.exe --launch "F:\SteamLibrary\steamapps\common\METAPHOR\METAPHOR.exe", and just edit the icon to the right exe as well.

Of course this is not ideal, but it works.
