### ISSUE TITLE
Help: Remoteplay issues

### ISSUE THREAD

**Issue by ZeninZZ** [Reloaded-Project/Reloaded-II#482]
Yo!

So, my question is how you use Reloaded II to play games with steam remoteplay? I Tried Sparking Zero with a soundtrack mod to play in offline mode but for friends in steam get the "Input is temporarily disabled while the host is busy" message

I think it has something to do with the CMD loader being recognized in remote instead of the actual game, I've tried to make a shortcut and Deploy ASI Loader but it doesn't seem to work either

**Comment by Sewer56** [comment]
ASI Loader and booting via Steam would usually do the trick in these sorts of situations where 'something else' is assumed to be the one launching the game.

I've never used Remote Play, but if it's one of these cases where it assumes the first window is the main window then try disabling the console window. In the main/startup page of the launcher there is a 'Show Console' checkbox.

**Comment by ZeninZZ** [comment]
> ASI Loader and booting via Steam would usually do the trick in these sorts of situations where 'something else' is assumed to be the one launching the game.
> 
> I've never used Remote Play, but if it's one of these cases where it assumes the first window is the main window then try disabling the console window. In the main/startup page of the launcher there is a 'Show Console' checkbox.

Oh yes! That was the major issue, after some tries It finally worked
