### ISSUE TITLE
Update required popup for dotnet x86 on launch when already installed. 

### ISSUE THREAD

**Issue by skypanda64** [Reloaded-Project/Reloaded-II#485]
Following the latest update I was prompted to update dot net - both x64 and x86. While both have been installed, the below pop-up persists on launch. Closing it and using reloaded as normal remains possible. I have also tried re-installing reloaded from the setup.exe and the popup persists.

![Screenshot 2024-11-14 013954](https://github.com/user-attachments/assets/b4f67733-c462-4366-a249-2cdaf9ec1a93)

Appears to be just a minor inconvenience but flagging in case it's anything more serious. Any input on a fix would be much appreciated! Thanks :)

**Comment by Sewer56** [comment]
Manually installing the runtimes listed in the changelog will probably do the trick:

- [.NET 9 x64 Desktop Runtime](<https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-9.0.0-windows-x64-installer>)
- [.NET 9 x86 Desktop Runtime](<https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-9.0.0-windows-x86-installer>)

It's possible Microsoft didn't update the runtime links on their servers, so it's sending them to the wrong runtime. This happened last year too.

**Comment by skypanda64** [comment]
This worked perfect. Thanks!
