### ISSUE TITLE
Persona 3 Reload Mismatching Hash - Can't launch game with Reloaded II

### ISSUE THREAD

**Issue by retr0phant0m** [Reloaded-Project/Reloaded-II#491]
Yes, I have the prerequisites - I can launch Persona 5 Royal with zero issues whatsoever.

For whatever reason, when trying to even add Persona 3 Reload to my application list, I get the following:

![Image](https://github.com/user-attachments/assets/5512f2ff-7945-466d-8d65-e686455282ef)

I am using the Steam version. If I'm not mistaken, there is only one executable that I could possibly use, and why it isn't working is beyond me. Again, I have absolutely no issues running P5R which is also the Steam version.

This is the message I get when attempting to launch through Reloaded - I get this same message when trying to launch through Reloaded without any mods as well:

![Image](https://github.com/user-attachments/assets/85354b51-63af-492f-b7fc-7992746aa502)

Here are the logs: [2024-11-20 04.51.45 ~ P3R.txt](https://github.com/user-attachments/files/17825090/2024-11-20.04.51.45.P3R.txt)

The mod list in question, though I really don't think that's the issue:
![Image](https://github.com/user-attachments/assets/a038f583-c4d7-4e80-be48-0edb49ec10f9)

Please help a brotha out. I bought this game a second time on my computer with the sole intent of modding.

**Comment by Sewer56** [comment]
Try rebooting your machine.
The issue you're seeing in the big white error box is a bug in one of my libraries and is fairly random, with very low probability. A reboot usually does the trick.

**Comment by retr0phant0m** [comment]
I got curious and did just that right before you replied, and voila. Thank you very much!!!
