### ISSUE TITLE
Help: Sonic Heroes doesn't run with injected loader

### ISSUE THREAD

**Issue by TheExentist151** [Reloaded-Project/Reloaded-II#496]
**Did you install the Prerequisites?**: Yes

**Describe the Issue**
Hi. I'm trying to play Sonic Heroes with these mods: 

![Installed mods](https://github.com/user-attachments/assets/4ae71324-9a5e-4e4e-a9fe-060928fa2e4e)

However, the game doesn't run with these mods and injected mod loader at all. The game process starts and then closes immediately. 
More than that, every time I boot up Reloaded II, it shows me that I don't have .NET 9 installed (I have it installed on my PC)

![Message about .NET 9](https://github.com/user-attachments/assets/9ca3f245-fd6e-4323-a995-2c05bf187af2)

![Installed .NET runtimes](https://github.com/user-attachments/assets/278533aa-1e81-4c2e-b2bd-ea0e45a3453f)

Also, I don't see logs anywhere, which is strange.

**Comment by Sewer56** [comment]
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-9.0.0-windows-x86-installer

This should do the trick.
The Microsoft servers are still giving people RC2 when you request the full runtime, so the Reloaded installer downloads the wrong thing.

I should report it upstream, it's been a whole week.

**Comment by Sewer56** [comment]
Seems someone else actually reported it already:
- https://github.com/dotnet/install-scripts/issues/549

I was opting to wait for a week to see if it was automation hickup.

**Comment by TheExentist151** [comment]
Yes, installing this runtime helped! Thank you for your quick reply!

**Comment by Sewer56** [comment]
👌
