### ISSUE TITLE
Enhancement: Accessible Colors and Consistency with MouseOver

### ISSUE THREAD

**Issue by dreamsyntax** [Reloaded-Project/Reloaded-II#500]
It's no secret I have never been a fan of the default color scheme of Reloaded-II - specifically the 'inactive' text color.

![Image](https://github.com/user-attachments/assets/eb839cfc-0f50-4937-9749-cf56cefaad3f)

In the above image, the mod fields on the bottom left, Search Mods, Search Apps have this text color that I consider hard to read.

On the Download Mods page:
![Image](https://github.com/user-attachments/assets/9921a617-4962-4c9e-896a-a96b7dd45d9e)

- Official Repository (selected - so its red with default theme)
- Search Mods - This one is a preview text so it makes sense to be off-white - I think the gray coloring should be made brighter at least.

Edit Mod page:
![Image](https://github.com/user-attachments/assets/c06ad0a7-e1b5-4258-b9e7-71aa2617f77e)

Very hard to read each field without clicking. ^

On the main splash/settings page:

No hover:
![Image](https://github.com/user-attachments/assets/5464b4f9-d89b-4d94-b9a6-3dc7598e61bd)
With hover:
![Image](https://github.com/user-attachments/assets/27c6d087-e632-4d24-adcc-145b316d772b)

### Fix the inconsistency with the hover tinting
[Mod Loader Settings]
- Powerful software warning ✅
- Show Console text ✅ 

- Any 'preview' text for search etc will still be an off-white gray, but made brighter ✅ 
~~- Split up 'inactive' text to NOT use `<Color x:Key="BorderColor">#4c4c4c</Color>` - keeping this color for borders etc.~~
~~- Any other 'inactive' text that isn't a 'preview' type text will be made white~~

## Update / Final Decisions
* Ultimately brightening `BorderColor` to `#7c7c7c` seems to be a decent compromise for the secondary/inactive text type. This keeps it different from primary White, and doesn't clash too hard with the border lines. Splitting these up had a lot of extra effort that seemed unnecessary after experimenting and settling on `#7c7c7c`. 
* Also adding the two main splash screen/setting page's hover consistency.

**Comment by dreamsyntax** [comment]
![Image](https://github.com/user-attachments/assets/b882a990-f157-4974-b640-54f046610b0a)

All Sources (current)
vs
Search (secondary)

adjustment

**Comment by Sewer56** [comment]
Adjustment is much better, haha.
