### ISSUE TITLE
Bug: Crash 30 seconds after launching Reloaded II

### ISSUE THREAD

**Issue by HakuryuuDom** [Reloaded-Project/Reloaded-II#501]
Hello, I am trying to mod Persona 5 Royal, but I am running into a serious issue. Reloaded II consistently crashes about 30 seconds after launching the tool. I have tried reinstalling it multiple times in different places (side note: auto installing to the desktop without allowing the user to choose a folder is bad design). I have tried different versions. I have tried disabling window defender. All to no avail. A crash log does not get generated, so its really difficult to troubleshoot. Thanks in advance for the help ~Lucy

**Comment by Sewer56** [comment]
Do you not get a crash window at least?

I know of one cause of such crash, some USB controllers behaving weird.

You can try this.

You can try opening the config at (`AppData/Roaming/Reloaded-Mod-Loader-II/Reloaded-II.json`) and change it such that `DisableDInput` is true in text editor in config.

**Comment by HakuryuuDom** [comment]
Thanks, this seems to have fixed it. wonder if it's because I'm using DS4Windows? anyways nope no crash window, it would just close.

**Comment by Sewer56** [comment]
Nah, it's just some DInput device acting unusual, I've seen some controller adapters do it; it's extremely rare and I'm not sure why it happens.
