### ISSUE TITLE
Bug: Running Setup-Linux.exe on a new Non-Steam Game Wineprefix Places Shortcut in Directory of Setup-Linux instead of Desktop

### ISSUE THREAD

**Issue by dreamsyntax** [Reloaded-Project/Reloaded-II#508]
**Describe the Bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a Non-Steam Game Wineprefix (Tsonic_win.exe)
2. Launch the game once in Steam, end process.
3. Download Setup-Linux.exe with R-II v1.28.4 and run
4. See bad shortcut path created

**Expected Behaviour**
Create desktop on /home/core/Desktop

**Screenshots**
This was created in my /home/core/Downloads folder:
![Image](https://github.com/user-attachments/assets/e484c36d-2101-4278-9115-998f57ccbf8a)

**Comment by Sewer56** [comment]
Pretty sure the issue is the backslash.
I'm not sure how it got there, but I'll try patch it up.

**Comment by Sewer56** [comment]
That was an accident by me, I used the file name sanitizer on the whole path, and it stripped out the slashes, oops!

**Comment by Sewer56** [comment]
It takes a bit to get builds out of CI to test, but I think e7f7b82da6331a610c7ae4ce95e23d9dddad2e51 should fix it.

**Comment by Sewer56** [comment]
I confirmed that I fixed it. Feel free to doublecheck.

**Comment by dreamsyntax** [comment]
Confirmed the same above scenario for me works in 1.28.5.
