### ISSUE TITLE
Help: Please help me with <X>

### ISSUE THREAD

**Issue by louiseechoes** [Reloaded-Project/Reloaded-II#511]
**Did you install the Prerequisites?**
Yes, I've installed all the requisites needed.

**Describe the Issue**
The application simply doesn't work; I attempt to launch Reloaded II and shortly after it begins Setting Up Resources, I get a prompt from my OS telling me the program stopped working.

**Screenshots**
![Image](https://github.com/user-attachments/assets/a8276f80-4f9b-4100-9b30-6ec1520e025e)

**Additional Resources**
I believe I am running the latest version of the program, 1.28.5.0 if I'm not mistaken.

**Comment by Sewer56** [comment]
Don't expect it to work on Windows 7.

.NET dropped support for it just over 2 years ago, every release more and more things break. While my code itself doesn't do anything specifically incompatible, the newer runtimes do.

Some mods may rely on newer runtime features, so although you could technically downgrade Reloaded, more and more mods would eventually become incompatible.

**Comment by louiseechoes** [comment]
I can probably live with incompatible mods, what version of Reloaded would you recommend I downgrade to in order to get it running on Windows 7?

**Comment by louiseechoes** [comment]
> Don't expect it to work on Windows 7.
> 
> .NET dropped support for it just over 2 years ago, every release more and more things break. While my code itself doesn't do anything specifically incompatible, the newer runtimes do.
> 
> Some mods may rely on newer runtime features, so although you could technically downgrade Reloaded, more and more mods would eventually become incompatible.

**Comment by Sewer56** [comment]
Versions 
1.27.X and below use .NET 8
1.24.X and below use .NET 7
1.20.X and below use .NET 5

The .NET 5 version is technically last supported version, but you may have luck with .NET 7 builds.

You can also try running current builds with something like VxKex , but it really depends on your luck.

**Comment by louiseechoes** [comment]
Where am I able to download earlier versions of Reload II?

**Comment by Sewer56** [comment]
The `Releases` section https://github.com/Reloaded-Project/Reloaded-II/releases
