### ISSUE TITLE
Help: Reloaded-II don't open.

### ISSUE THREAD

**Issue by Siegmur** [Reloaded-Project/Reloaded-II#521]
Hello!

Downloaded the Release zip because the installation would only create an empty folder. On task manager it shows for a second, but doesn't open at all and doesn't show any error messages either. 

Not sure if helps, but here's the event viewers for both, Reloaded and NET Runtime:

Faulting application name: Reloaded-II.exe, version: 1.28.6.0, time stamp: 0x67200000
Faulting module name: d3d9.dll, version: 10.0.19041.5198, time stamp: 0x46271fbd
Exception code: 0xc0000005
Fault offset: 0x000000000000f6f2
Faulting process id: 0x26d4
Faulting application start time: 0x01db57dd8a9fa4ba
Faulting application path: C:\Users\Igor\Desktop\Release\Reloaded-II.exe
Faulting module path: C:\Windows\SYSTEM32\d3d9.dll
Report Id: 46a94565-edea-4851-8f3b-8a6b358661e2
Faulting package full name: 
Faulting package-relative application ID: 

Application: Reloaded-II.exe
CoreCLR Version: 9.0.24.52809
.NET Version: 9.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 00007FF8DE4DF6F2

Thank you in advance!

**Comment by Sewer56** [comment]
I got no clue myself, since the faulting module is `d3d9.dll`. 
Could be graphic driver, could be unsupported/modified OS, could be something else.

**Comment by Siegmur** [comment]
Damn, you are fast! Thank you so much.

Weird, although still using windows 10, both graphic driver and OS are updated.

Could be something else?

**Comment by Sewer56** [comment]
No idea, you may have luck with dxwebsetup, maybe it'll drop a clean d3d9.dll to your windows folder 
https://www.microsoft.com/en-gb/download/details.aspx?id=35

But that's just a wild guess.
Worst case scenario, you could try dropping something like dxvk to Reloaded folder, or if you're on something like a laptop force integrated/dedicated graphics in your graphics card's control panel.

**Comment by Siegmur** [comment]
Holy shit, putting the dxvk dlls into the reloaded folder worked. 
Thank you so very much!
