### ISSUE TITLE
Linux Bug: wine icu.dll error(export module not found for icuuc68.u_charsToUChars_68)

### ISSUE THREAD

**Issue by Erwin-Iosef** [Reloaded-Project/Reloaded-II#523]
**Describe the Bug**
Running reloaded II(and its 32 bit app) after installing the 9.0 Desktop runtime shows this error:

**To Reproduce**
Steps to reproduce the behaviour:
1. Extract Reloaded.zip(latest as of now) to a folder.
2. run`wine reloaded-ii` in CLI.
3. See last line error where it says `00d0:err:module:find_forwarded_export module not found for forward 'icuuc68.u_charsToUChars_68' used by L"C:\\windows\\system32\\icu.dll"`

**Console log**

`$ wine reloaded-ii
fsync: up and running.
002c:fixme:winediag:loader_init wine-staging 9.0 is a testing version containing experimental patches.
002c:fixme:winediag:loader_init Please mention your exact version when filing bug reports on winehq.org.
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2).
006c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
006c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
006c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
006c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
00d0:fixme:process:GetProcessGroupAffinity (FFFFFFFFFFFFFFFF,000000000019F294,0000000000000000): stub
00d0:fixme:heap:GetNumaHighestNodeNumber semi-stub: 000000000019F260
00d0:fixme:process:GetProcessGroupAffinity (FFFFFFFFFFFFFFFF,000000000019F260,0000000000000000): stub
00d0:fixme:seh:WerRegisterRuntimeExceptionModule (L"C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\9.0.0\\mscordaccore.dll", 00006FFFFE430000) stub
00d0:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00dc:fixme:ntdll:RtlGetCurrentProcessorNumberEx (0000000001EDEA10) :semi-stub
00d0:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 00000001006266B8, 34) stub
00d0:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 000000010061A5F8, 17) stub
00d0:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0000000142C0EB70, 29) stub
0128:fixme:oleacc:find_class_data unhandled window class: L"#32769"
0128:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
0128:fixme:uiautomation:default_uia_provider_callback Default ProviderType_NonClientArea provider unimplemented.
0128:fixme:oleacc:find_class_data unhandled window class: L"#32769"
0128:fixme:uiautomation:base_hwnd_fragment_get_FragmentRoot 0000000000906418, 000000000011FA88: stub!
0128:fixme:uiautomation:base_hwnd_fragment_GetEmbeddedFragmentRoots 0000000000906418, 000000000011FA80: stub!
00d0:err:module:find_forwarded_export module not found for forward 'icuuc68.u_charsToUChars_68' used by L"C:\\windows\\system32\\icu.dll"`

**Comment by Sewer56** [comment]
I think it may be an issue with your Wine setup, see what you get when you run

`readelf -a /usr/lib/x86_64-linux-gnu/libicuuc.so | grep charsToUChars`

(path may vary slightly).

Chances are the version of `libicuuc` Wine expects is a big newer or older than what you have .

**Comment by Erwin-Iosef** [comment]
`$ readelf -a /usr/lib/x86_64-linux-gnu/libicuuc.so | grep charsToUChars
readelf: Error: '/usr/lib/x86_64-linux-gnu/libicuuc.so': No such file`
No such file it reports. Using wine-cahyos btw

**Comment by Erwin-Iosef** [comment]
@Sewer56 I got it!
It's in:
$ readelf -a /usr/lib/libicuuc.so | grep charsToUChars
  1312: 00000000000f93f0    34 FUNC    GLOBAL DEFAULT   11 u_charsToUChars_75
for Arch distros.

**Comment by Sewer56** [comment]
Yeah, figures.
@Erwin-Iosef 

Your version of wine-staging was simply built against a different version of `libicuuc` on arch (btw).

Use a more wine build if you can :p

**Comment by Erwin-Iosef** [comment]
Ah damn.
Do you still CachyOS?

**Comment by Sewer56** [comment]
Yeah, I still have CachyOS.
Not on my machine ATM, but could check what is up there later.

**Comment by Erwin-Iosef** [comment]
Okay, I'll look into what I can do at the moment and report back if I can, I assume normal wine has it's icu updated? Maybe cachyos needs to update it's icu?

**Comment by Sewer56** [comment]
It's rather that wine-staging build used here is out of date. Your system library is newer than what it's looking for.

**Comment by Erwin-Iosef** [comment]
I fixed it. You maybe right as somehow the wine-staging build I just tested didn't have `icu.dll` in its system32 or syswow64 folder. But my cachyos build did, I deleted two of them and reloaded ran nicely.

**Comment by Erwin-Iosef** [comment]
Maybe some dependency install by-product that came about.
Thanks for your help man, really appreciated :) Closing issue.

**Comment by Sewer56** [comment]
No worries, have fun :p

**Comment by sylv256** [comment]
I'm getting this problem again on Arch Linux. All versions of wine (dev, staging, *and* stable) give this same error, and `readelf -a /usr/lib/libicuuc.so | grep charsToUChars` returns the following:
```
   692: 00000000000fca30    34 FUNC    GLOBAL DEFAULT    9 u_charsToUChars_76
```
This is the error it's giving me:
```
0024:err:module:find_forwarded_export module not found for forward 'icuuc68.u_charsToUChars_68' used by L"C:\\windows\\system32\\icu.dll"
Cannot get symbol u_charsToUChars from libicuuc
Error: 127
```

**Comment by Sewer56** [comment]
@sylv256 Have you tried the steps above?

**Comment by sylv256** [comment]
Unrelated to this repository.
