### ISSUE TITLE
[P4G] Application Has Crashed

### ISSUE THREAD

**Issue by ariktsuno** [Reloaded-Project/Reloaded-II#55]
I already instaled all the prequisites and the aplicacion opens and runs smothly, the issue comes when i open Persona 4 Golden after i instaled steak hook and the p4g modloader, every time i open the reloaded version of the game it just pops a error saying Aplicacion has crashed
![Captura de pantalla (2)](https://user-images.githubusercontent.com/71191244/93003040-a9c91c00-f511-11ea-8300-4572a4b6c67a.png)

i have very little knowledge on codes or coding in general. if any more informacion is needed, i'll gladly try to give it.

**Comment by Sewer56** [comment]
Seeing someone this polite is actually heartwarming. Awwww.

I don't personally own the game so the best I can do is provide help with some basic diagnostics; but it's weird that the game's own crash handler/dialog would show up.

I'd recommend jumping into the general P4G modding server on Discord https://discord.gg/zzck4FR and visiting the help section.

Here's a bunch of stuff that might be useful to post:
- List of Enabled Mods (screenshot)
- Console/Command Prompt (Big Box with Text) Printouts
- Maybe Game Folder

**Comment by ariktsuno** [comment]
Thank you very much anyways!, i'll check out the discord server you sent, so i guess i'll just close this issue. thank you again!

**Comment by Sewer56** [comment]
I'm actually going to keep this open 😉 so the solution for the issue might be posted here.
Might be useful for future reference.
