### ISSUE TITLE
Bug: Error when launching Sonic Heroes on network drive.

### ISSUE THREAD

**Issue by DylanTweedy** [Reloaded-Project/Reloaded-II#56]
Launching the game works as intended when launched from a local drive (D:\ in my case), however when the game is located on a network drive (G:\) I get an error message and the game proceeds to launch without mods.
If I set the executable location to its UNC path (\\\\StorageServer) it gets worse! In that situation it tells me "the path to the application to be launched is invalid." and won't even launch the game.
I have also tried using symbolic links and get the same results.

**executable location G:\\**
![image](https://user-images.githubusercontent.com/5881259/93918557-70a85d00-fd04-11ea-8328-689ed3b513bd.png)

**executable location \\\\StorageServer**
![image](https://user-images.githubusercontent.com/5881259/93923217-fb8c5600-fd0a-11ea-95c4-e4eb2cd4dd96.png)

**Comment by Sewer56** [comment]
Although I knew about this issue for months; nobody else actually ever tried running Reloaded from a NAS aside me testing with VirtualBox long ago and one other person.

Either way, with a small helper on Discord ( @HyperPolygon64 ), I fixed this issue today as of commit ee088d4fc8fe0c3c97837250293639e5833f2a20 .

![](https://cdn.discordapp.com/attachments/493474309365563392/758119896130781284/unknown.png)

It's not an ideal solution for now; and I can't 100% guarantee all scenarios to work (things are tricky and I'm kind of half cheating here) but at least in the short term; things should run fine for most users as of next update.

[Release.zip](https://github.com/Reloaded-Project/Reloaded-II/files/5264822/Release.zip)

Feel free to try this build. If it works; I'll close the issue for now.

**Comment by DylanTweedy** [comment]
Brilliant! Works fine for me, awesome job!
