### ISSUE TITLE
I keep getting this error even though i have every prerequisite downloaded

### ISSUE THREAD

**Issue by Eskimoisgay** [Reloaded-Project/Reloaded-II#57]
![image](https://user-images.githubusercontent.com/71811341/94108160-0b379780-fdfc-11ea-9249-8c9ecb7a97e7.png)
I keep getting this error even though i have downloaded all prerequisites. I am running this with admin too

**Comment by Sewer56** [comment]
It was your Antivirus (as per chat logs on `Persona 4 Golden Modding` Discord).
Please close next time if the issue is resolved.
