### ISSUE TITLE
Bug: [P4G] Softlocking in battles & Unable to close via overlay

### ISSUE THREAD

**Issue by firelad97** [Reloaded-Project/Reloaded-II#63]
**Describe the Bug**
Apparently, Persona 4 Golden softlocks in battles after landing a weakness hit or All-Out Attack after the game is loaded using Reloaded-II. Only Reloaded-II with or without mods (including modloader). Clean launch of P4G doesn't softlock in battles. Literally any battles, including the tutorial battle (just before Yosuke boss battle), will softlock when conditions are met.

I had tried reinstalling Reloaded-II, P4G, and even adding both to anti-virus exclusions / exceptions. Battles are still softlocked. I also should mention that if Reloaded-II shortcut is loaded through Steam as a non-game to start up P4G, controller doesn't work when loaded in Big Picture mode but works fine when loaded in non-BP mode. Closing the game from Steam Overlay does nothing (only clicking X on window or selecting quit game in-game will take effect, clean launch of the game can be closed from overlay) as well. All of those works fine if loaded without Reloaded-II.

By the way, you can tell when softlock is going to occur by checking if Teddie's (or Rise's) dialogues are loaded and became stuck (usually after one or two appears).

EDIT: I should mention that I am using Boot Camp on a MacBook Air. This issue might be related to Boot Camp, from what I can gather based on people being able to play the game normally with mods and/or Reloaded-II just fine.

**To Reproduce**
Steps to reproduce the behaviour (for battles softlocking):
1. Launch P4G through Reloaded-II (or as a non-Steam game shortcut)
2. Go into the battle
3. Land a weakness hit or All-Out Attack
4. After animations, battle stops and is stuck there forever

Steps to reproduce the behaviour (for running non-Steam game):
1. Launch Reloaded-II non-Steam game shortcut with launch command arguments to open P4G in Big Picture mode
2. Try using controller directly in game or close the game from Overlay

**Expected Behaviour**
Battle resumes or ends with a victory screen if all enemies are defeated. Controller in Big Picture mode and closing from Steam Overlay also works as intended.

**Screenshots**
I hope those screenshots are good examples of what I'm trying to describe.
![image0](https://user-images.githubusercontent.com/10987201/101541391-6a269a80-396f-11eb-8bbd-6b753dc73ed3.png)
![unknown (1)](https://user-images.githubusercontent.com/10987201/101541394-6abf3100-396f-11eb-970d-664f239a059e.png)
![unknown](https://user-images.githubusercontent.com/10987201/101541400-6b57c780-396f-11eb-9303-e552c4bc262f.png)
![unknown (2)](https://user-images.githubusercontent.com/10987201/101541397-6b57c780-396f-11eb-9b23-c7c954efce28.png)

**Comment by Sewer56** [comment]
Tagging @TGEnigma , maybe they have a clue I actually haven't played Persona or SMT for that matter so this is outside of my expertise.

That said, this is weird. If you are running no mods (that includes modloader), then Reloaded shouldn't make any changes to the game/program. Reloaded actually doesn't do anything on its own outside of injecting a DLL to load itself; all game modification is always done inside mods loaded by it.

Thanks for the detailed report.

**Comment by Sewer56** [comment]
Forgot to mention.

Some ideas could also be trying a different game version, validating game files and asking in the Persona modding community on Discord https://discord.gg/PaVqeqB9

I do have the game (despite my distaste for DRM), however I don't think I can personally reproduce the issue. 

On that note; I do remember that game softlock after All Out Attack was reportedly a game bug on release which was later fixed however you seem to be on latest version as indicated by the title bar (rev 2033)

**Comment by firelad97** [comment]
Apologies, it seems like I forgot to add some things in my report.

I already received support though P4G Community Enhancement Pack discord server. I can try the one you provided later. I am honestly frustrated with it and tired of constantly trying to find a solution.

I dunno how I can change to a different game version as they do not provide that on Steam for P4G. I also already tried validating game files. Same reason why I tried reinstalling the game.

I should also mention again that this issue might be related to Boot Camp, but I have no idea if that is the case.

**Comment by firelad97** [comment]
@Sewer56 The discord invite you provided is invalid.

**Comment by firelad97** [comment]
An update. I did do more testing today, and apparently I found out that it's not R2 causing softlocks this time around, although that is odd considering I tested this a few days ago without modloader.  So now it seems like this is the modloader issue, so closing this and posting in a correct repository.
