### ISSUE TITLE
app freezes when i click download mods

### ISSUE THREAD

**Issue by AkariLovesDrue** [Reloaded-Project/Reloaded-II#66]
when i click download mods it just freezes the app and i cant click anything. this is what i get when i launch https://prnt.sc/wb1kb2

**Comment by Sewer56** [comment]
What is your version? 1.8.0 or 1.7.2?
Is it a fresh install or an update?

The menu is asynchronous; so things should be fetched in the background without freezing anything; as such this is very weird.

**Comment by AkariLovesDrue** [comment]
> What is your version? 1.8.0 or 1.7.2?
> Is it a fresh install or an update?
> 
> The menu is asynchronous; so things should be fetched in the background without freezing anything; as such this is very weird.

1.8.0 fresh install

**Comment by Sewer56** [comment]
Lemme test a quick install on a virtual machine; back in 10-20 minutes.

**Comment by Sewer56** [comment]
I can reproduce this on a virtual machine it seems.
@AkariLovesDrue Please downgrade to 1.7.2 for now; I'll try to see how I can fix it. 1.8.0 is experimental as stated on release page.

**Comment by Sewer56** [comment]
@AkariLovesDrue Likely is fixed with 1.8.1; please check.
