### ISSUE TITLE
I encountered a bug

### ISSUE THREAD

**Issue by Tartellu** [Reloaded-Project/Reloaded-II#70]
When I was installing the e3 title screen mod for sonic heroes and then when I went to boot up the mod manager it said that I had encountored a rare bug and I should report it.

**To Reproduce**
Steps to reproduce the behaviour:
I am not to sure of how to reproduce it so it might not be helpful 

**Expected Behaviour**
I thought it would boot up as normal but I got this

**Screenshots**
https://media.discordapp.net/attachments/700526120331640996/796022478060781588/unknown.png?width=960&height=254

**Additional Context**
also ever time it says install the net boot x86 I do but it still says I need to install it I also haven't updated it to the newest version it's on the december 29th 2020 build, 1.8.2 .
if you want you can message me on discord I am not sure how major the problem is but you can if you want to at Tartellu#9046

**Comment by Sewer56** [comment]
Another one for https://github.com/Reloaded-Project/Reloaded-II/issues/34 , still not really sure what causes this to this day.
