### ISSUE TITLE
Persona 4 Golden freezes only when the Mod Loader is enabled

### ISSUE THREAD

**Issue by ethanpierce2001** [Reloaded-Project/Reloaded-II#72]
Hi. I can't launch Persona 4 Golden with mods or else it freezes on startup. I know I downloaded all the prerequisites and restarted my computer two times! When I turn the mod loader off, the game launches like normal, but when I turn the mod loader back on, it goes back to "Not Responding" on launch.

And as usual, Google doesn't know what the heck I'm talking about (no relevant results).

Any help would be appreciated. Thanks.

**Comment by Sewer56** [comment]
No restarts are necessary for Reloaded or any of its components; any guide which says otherwise is misinformed.

There is a console window which appears when you launch the game with Reloaded. Can you go to `%appdata%/Reloaded-Mod-Loader-II/Logs` in explorer 
![image](https://user-images.githubusercontent.com/6697380/104397688-34b03680-5545-11eb-8c57-891fdee2d247.png)
 and send the most recent console log?

(If a console log doesn't show up, or there are no logs, make sure `Show Console` is enabled in the default page of Reloaded).

**Comment by ethanpierce2001** [comment]
[OldLogs.zip](https://github.com/Reloaded-Project/Reloaded-II/files/5805956/OldLogs.zip)
 This is all that shows up in this folder.

Also, the restart... Well, the first one was for the prerequisites. The installers said I had to restart to finish installing them. The second one was just to see if it would fix my problem...... It didn't. :\

(Also thanks for the surprisingly quick reply.)

**Comment by Sewer56** [comment]
Hmm yeah, nothing in here. Make sure `Show Console` is enabled 
![image](https://user-images.githubusercontent.com/6697380/104398311-64137300-5546-11eb-9f0e-18e7ff2256b9.png)

in the main screen and try running the game again.

Then grab any new log file that appears in the folder, if possible.

**Comment by ethanpierce2001** [comment]
[2021-01-12 21.25.11 ~ P4G.txt](https://github.com/Reloaded-Project/Reloaded-II/files/5805982/2021-01-12.21.25.11.P4G.txt)

**Comment by Sewer56** [comment]
Does the game straight up lock up and freeze? Does it crash?
Are there any other errors in the console other than what's in this text file?

**Comment by ethanpierce2001** [comment]
The window opens, hangs for a while, then goes "Not Responding". Only thing I can do is close it. I didn't see anything else in the console.

**Comment by Sewer56** [comment]
Hmm... this is strange; can you maybe screenshot your game folder?

**Comment by ethanpierce2001** [comment]
![bandicam 2021-01-12 21-36-29-788](https://user-images.githubusercontent.com/68626398/104399237-44685480-551e-11eb-9ca3-ce2e7cfb9c06.png)

**Comment by Sewer56** [comment]
Are you using Special K by any chance?

There is a well known conflict between Special K and (P4GPC Modloader)'s Xact (XSB, XWB) Archive Emulator when the startup movie plays.

You can work around it by skipping the intro movie (e.g. use Tiny Fixes) or delay injection of either Special K or Reloaded.

**Comment by ethanpierce2001** [comment]
That didn't work either, and I already disabled Special K.

Plus, I found something interesting in the log. I just saw it:
[SteamHook] Checking for steam_appid.txt.
[SteamHook] Exists, not overwriting.
[SteamHook] Hooking SteamAPI_RestartAppIfNecessary (newer games) and SteamAPI_IsSteamRunning (older games).

**Comment by Sewer56** [comment]
Oh don't worry, no problem there. Everything as expected.

Is the SpecK injector completely disabled; or are you overriding via file? Try killing it completely out of curiosity.

**Comment by ethanpierce2001** [comment]
Just checking the "Disable Special K" checkbox isn't enough?

**Comment by Sewer56** [comment]
Not sure, I don't use it personally.

**Comment by ethanpierce2001** [comment]
It takes a while for it to be stuck on "Stopping..." though. I don't think it's stopping at all.

**Comment by ethanpierce2001** [comment]
Didn't mean to close it. Whoops.

**Comment by ethanpierce2001** [comment]
I can't believe I forgot to post my specs! lol 🤣 

Here they are:
Device name	DESKTOP-LDJFL6B
Processor	AMD Ryzen 5 3600 6-Core Processor                 3.59 GHz
Installed RAM	7.95 GB
Device ID	63BFB7DC-67A3-4B28-8464-8301903E958A
Product ID	00325-81634-28905-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

**Comment by ethanpierce2001** [comment]
bump (sorry for impatience)

**Comment by Sewer56** [comment]
Still not sure what to do here; but I'll transfer this issue to the correct repository since it's a mod issue and not a Reloaded issue.

**Comment by ethanpierce2001** [comment]
Update: Still looks like it's freezing even after the 1.5 Reloaded II update, unless I skipped many steps with the update process.

:(

**Comment by Sewer56** [comment]
I don't like to leave people hanging so I'm going to direct you to the Persona Modding Discord server https://discord.gg/udJdnmWSFc since this is technically not a Reloaded issue anymore but a mod issue.
