### ISSUE TITLE
Reloaded won't launch P4G

### ISSUE THREAD

**Issue by ASimpleShadow** [Reloaded-Project/Reloaded-II#73]
After setting up some mods and tried launching P4G through the shortcut and Reloaded, but the game wouldn't load. I restarted my laptop and tried opening through the shortcut, but nothing happens. When trying to launch through Reloaded, I got this message:
![Capture](https://user-images.githubusercontent.com/77460402/104637110-3dffe700-569c-11eb-8547-c857c064f869.JPG)
Any help is appreciated.

**Comment by Sewer56** [comment]
Most likely you have either moved the game folder since you have added it to Reloaded or the game is set to run as admin (Right Click P4G.exe -> Properties) and Reloaded isn't running as admin hence Windows wouldn't allow Reloaded to launch the game.

**Comment by ASimpleShadow** [comment]
I can get the game to launch through Reloaded now, but none of my mods appear to working. I made sure I got them set up before.
