### ISSUE TITLE
Bug: failing to launch P4G, failed to parce launcher configuration, asked that i report it

### ISSUE THREAD

**Issue by axpxion** [Reloaded-Project/Reloaded-II#74]
I an setting up a mod profile for P4G for the first time, using the community enhancement pack. all the prerequisites were downloaded and i changed my .exe to match my actual install location. and when i launched it, i first got a error message about my executable path being wrong, which it isnt, then after double checking and relaunching the program i got this fine crash log. 

Steps to reproduce the behaviour:
1. launched reloaded as admin
2. turned off show console
3. went to the p4G, changed exe path to match mine (C:\Games\Persona 4 Golden\P4G.exe)
4. I did click on all the default mods and clicked configure mods to look at them, but didn't change anything
5. clicked create shortcut, at this point my Avast antivirus caught it and locked it, added an exception and relaunched, added shortcut with no problem.
6. Clicked launch application within reloaded to get the incorrect pathing log, relaunched and double checked location, hit launch application again and got this one.

Pictures to show off not only the logs, but that my path is correct and that i'm still getting incorrect path issues

<img width="245" alt="Screenshot_151" src="https://user-images.githubusercontent.com/77502914/104754318-13a73b80-5727-11eb-9163-b32d30db88dd.png">

<img width="877" alt="Screenshot_150" src="https://user-images.githubusercontent.com/77502914/104754302-0e49f100-5727-11eb-8873-e7cebb591c2b.png">

<img width="804" alt="Screenshot_152" src="https://user-images.githubusercontent.com/77502914/104754331-17d35900-5727-11eb-8e6a-39308a4c4fd0.png">

<img width="287" alt="Screenshot_153" src="https://user-images.githubusercontent.com/77502914/104754648-78fb2c80-5727-11eb-8f88-e5bb48c63df3.png">

I havent changed the game in any significant way, however i did use a trainer on a previous play through, dont know why that would affect but figured id mention it. I have also tried basic troubleshooting, restarting PC and turning off antivirus entirely. redownloaded it, havent reinstalled P4G, and the game launches and runs fine without reloaded. I also get the bug consistently when retrying, not just the once

**Comment by Sewer56** [comment]
I'm about to fall asleep so apologies if I don't respond to any post below in a quick manner.

The error is `Failed to Start The Process` and generally happens due to one of 3 reasons:

- Game folder is incorrect (not the case here)
- Reloaded is running as user process while application (P4G) is set to run as admim (see Properties->Compatibility) [also not the case here?]
- 3rd party system hooks e.g. antivirus

This happens when the operating system refuses to allow Reloaded to start the game. Most likely it might be possible it's still your AV so I'd recommend checking that a second time. 

In all fairness I should probably include the error code windows returns in the error message, even when 99% of the time the user simply had moved the game folder. This post might not be that useful but it's essential background info.

**Comment by axpxion** [comment]
No problem, I have been messing with it, i have restarted and and turned off AV entirely. i have found that if i turn the mods off, it launches fine through reloaded, and i only get the crash when the modloader is active, though without it i assume the other 4 aren't doing anything. and even if the modloader is the only one active it still doesn't launch.

**Comment by Sewer56** [comment]
Sounds more like a mod than a Reloaded issue.
I recommend enabling the console (`Show Console` in main screen) and posting a log file or screenshot.

You can find log files (from sessions where console was enabled) by pasting this in the address bar of your explorer window `%appdata%/Reloaded-Mod-Loader-II/Logs` and pressing enter.

**Comment by axpxion** [comment]
So, I am sorry, i fixed the issue. Couldn't really tell you how though. I just deleted the game and reinstalled in in the regular steam location and now it works fine, my only thoughts are i sometimes use a offline bat script to detach my steam so i can use my friends game when they are using it. or the obvious reinstalling it fixed it, but i don't know how it would. Can no longer replicate the issue and couldn't tell you how i fixed it. but yeah
