### ISSUE TITLE
Bug: Black screen when launching from Reloaded-II

### ISSUE THREAD

**Issue by Wilburrito-Ultra** [Reloaded-Project/Reloaded-II#75]
**Describe the Bug**
When clicking "launch program", Persona 4 is launched, but it immediately opens to a black screen and hangs there, not loading.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Reloaded-II
2. Click launch program on Persona 4

**Expected Behaviour**
I expected the game to launch.

Here are screenshots:

This is my log:

![help](https://user-images.githubusercontent.com/61133315/104884689-c8fb0e80-5934-11eb-985c-fd1ea07b8047.png)

Here's what happens when I attempt to launch the game.

![image](https://user-images.githubusercontent.com/61133315/104884805-f8118000-5934-11eb-9752-89021b04a404.png)

Here's some pictures of the modloader itself:

![image](https://user-images.githubusercontent.com/61133315/104885056-5f2f3480-5935-11eb-87ad-66e246f2f36e.png)

![image](https://user-images.githubusercontent.com/61133315/104885110-78d07c00-5935-11eb-8680-9de17988965f.png)

I have downloaded the prerequisites several times. I have uninstalled and then reinstalled them 4 times now. I have tried to get this to work for 5 hours now. Please help me.

**Comment by Sewer56** [comment]
Technically speaking this is not a Reloaded issue but a mod issue judging by the log.
Ask in the Persona Modding Discord server https://discord.gg/udJdnmWSFc

**Comment by Wilburrito-Ultra** [comment]
> 
> 
> Technically speaking this is not a Reloaded issue but a mod issue judging by the log.
> I haven't personally played the game so you're best off asking in the Persona Modding Discord server https://discord.gg/udJdnmWSFc

Hi there. Thanks for the reply, especially the Discord link. 

During attempts to launch the game, I have launched it with no mods loaded at all to see if I could just get the game to run through the program. I didn't have any success either. I have also tried to load it with 2 mods through Aemulus, but also had no success. I tried only 1 mod which was a simple font change mod, which also didn't work. Finally, I started just trying to get Reloaded-II to work.

**Comment by Sewer56** [comment]
> During attempts to launch the game, I have launched it with no mods loaded at all to see if I could just get the game to run through the program. I didn't have any success either. 

Really? Nothing enabled in Reloaded?
That does sound super, super strange.

The log posted earlier looked completely fine and Reloaded doesn't do any modifications to game code; so the chances of that being the case are almost effectively 0. That is super unusual.

Throw a log file for that just in case, kind of curious.

**Comment by Sewer56** [comment]
Closed due to inactivity.
