### ISSUE TITLE
Bug: Persona 4 Golden not working with any version of mod loader, boots into a black screen

### ISSUE THREAD

**Issue by SPARKisnumber1** [Reloaded-Project/Reloaded-II#76]
When I boot P4G with any version of mod loader installed (trust me, I've tried all of them), I get a black screen and windows tells me it isn't responding. I get this error in the console: "Couldn't fit all the environmental variables in allotted space," and I'm not really sure what it relates to or what it's addressing. If it has to do with storage or memory, I have 70gb free on the ssd it's installed on and 16gb of ram, so I theoretically should be good there.
![image](https://user-images.githubusercontent.com/77805126/105430786-f20fed80-5c19-11eb-9f21-b5a283a00ed9.png)

**Steps to reproduce the behavior**
1. Install Reloaded, Install Runtime 5.0.2
2. Boot up Reloaded as admin, download steam hook and p4g mod loader
3. Enable both with steam hook on top, and load up the game
4. See frozen black screen

**Expected Behaviour**
Game boots up as normal

**Screenshots**

![image](https://user-images.githubusercontent.com/77805126/105429284-b9224980-5c16-11eb-90dc-d0b52f3494f1.png)
![image](https://user-images.githubusercontent.com/77805126/105429329-ce977380-5c16-11eb-9749-00e38a4a07b0.png)
![image](https://user-images.githubusercontent.com/77805126/105429337-d6571800-5c16-11eb-87d2-37583e461e5b.png)

**Additional Context**
Works with just the steam hook enabled, so I thought it was just a problem with the most recent version of the mod loader. Can't be though, I tried every possible mod loader version and nothing changed. Any help would be appreciated.

**Comment by SPARKisnumber1** [comment]
Downloaded the community pack and everything worked, so closing issue

**Comment by DrWolfnstine13** [comment]
Nvm I solved this issue by deleting any file in the "mods" directory that was not in a folder. In my case a readme was in there and deleting it stopped the issue.

**Comment by luminous030** [comment]
Try to make sure this folder is empty
"*\Steam\steamapps\common\Persona 4 Golden\mods"
Don't put P4G-CEP in this folder.
works for me.
