### ISSUE TITLE
Persona 4 Golden randomly crashes with Special K + Reloaded-II paired

### ISSUE THREAD

**Issue by AkiraJkr** [Reloaded-Project/Reloaded-II#78]
There has been reports from users that trying to start Persona 4 Golden with Special K ends up in the game crashing, though I've spent some time testing both Global, and Local injection of it, and it appears there's some sort of incompatibility between the two that is causing the crashes.

Steps to reproduce the behaviour:
1. Load up SKIF and enable Global Injection/Grab SpecialK32.dll, place in the game's folder and rename to dxgi.dll
2. Start the game with Reloaded-II.
3. Expect a crash that inconsistently happens every now and then at startup.

**Expected Behaviour**
The game launches normally, without any issues.

**Screenshots**
There are no screenshots I can provide, since there's no error.

**Additional Context**
Special K's a injection method that's used in games, and has special functions for Persona 4 Golden, allowing the player to disable the Motion Blur that the game has, along fixing other issues.

It appears that running the game normally through Steam, the crash appears to never happen.

I've used the Persona 4 Golden Community Enhancement Pack for this test.

**Comment by Sewer56** [comment]
This is a well known issue.

This crash has to do with an unknown nontrivial conflict between Special K and P4GPC ModLoader (a Reloaded Mod)'s Xact (XSB, XWB) Archive Emulator when the startup movie plays.

You can work around it by skipping the intro movie (e.g. using Tiny Fixes mod) or delay injection of Special K.

Relevant Tweet: https://twitter.com/TheSewer56/status/1315945480740896768

-------------

As this is technically not a Reloaded issue however, you should post it to [p4gpc.modloader](https://github.com/TGEnigma/p4gpc.modloader) as it's specifically a conflict between that mod and Special K.

[There is also a bug report on the Special K forums](https://discourse.differentk.fyi/t/using-special-k-in-combination-with-reloaded-ii-mod-loader-with-steam-hook-mod-enabled-and-persona-4-mod-loader-will-trigger-the-warning-and-close-the-game/140/9) but Kaldaien, the author of Special K wasn't very keen into looking what's up. They pointed the finger elsewhere while manufacturing a crappy excuse about memory usage without even providing any kind of numbers (hint: it's not memory usage).
