### ISSUE TITLE
Documentation: ReloadedII bootstrapping is not Documented

### ISSUE THREAD

**Issue by javster101** [Reloaded-Project/Reloaded-II#79]
**Is your request related to a feature? Please describe.**
From what I can tell from the documentation, ReloadedII has a bootstrapper to access dll injection through from other mod loaders. It isn't evident how one would use this bootloader, as neither the loader's source nor the documentation have anything describing how this is used . 

**Describe the solution you'd like**
It would be great if there was documentation, either in Reloaded.Mod.Loader.Bootstrap/dllmain.cpp (I assume that's the entry point into the bootstrapper) or in the documentation website as to how to call the API to inject DLLs into a given executable 

**Additional context**
The Lego game modding community currently relies on Reloaded for Dll injection, and there's a new mod loader in development. It would be great if existing Dll injection mods worked through the bootstrapper with the new mod loader.

**Comment by Sewer56** [comment]
You're very close here but just a slight bit off.

`Reloaded.Bootstrapper` has no API. Its only purpose is to load Reloaded (Mod Loader) `Reloaded.Mod.Loader` into the target process. It has no control over the actual loader itself.

If you use a DLL Injector and inject this DLL, Reloaded will be automatically loaded into the target process in the background; that's all there is to it.

Note/Warning
=========

For the sake of code mods with hooks/detours (if there are any you use outside of file redirector etc.), it's recommended you make sure you allow Reloaded to fully initialize before game code starts running. 

The simplest way to do that is probably to use the export intended for Ultimate ASI Loader integration `InitializeASI` ([here](https://github.com/Reloaded-Project/Reloaded-II/blob/2d3048140ee6c10d705e3d07c2f67720ac4fd162/source/Reloaded.Mod.Loader.Bootstrapper/dllmain.cpp#L250)).
Start the game in a suspended state from your loader, inject the DLL and call this export; it will wait until Reloaded finishes initializing.

API
==
As mentioned above, `Reloaded.Bootstrapper` doesn't have any kind of API whatsoever except for a few exports intended for stalling until loading is ready (e.g. `InitializeASI`).

If for whatever reason you want to interface with the Loader after it's been loaded by the bootstrapper, it hosts a local server which you can connect to via the `Client` class in [Reloaded.Mod.Loader.Server](https://github.com/Reloaded-Project/Reloaded-II/tree/master/source/Reloaded.Mod.Loader.Server); it provides an extremely minimal API for loading/unloading/querying mod state etc. at runtime.

This is technically an internal component subject to change at any time but I doubt I'd ever update it, and I'd probably maintain backwards compatibility if I ever were to.

Misc Note
==
PS. It's not thoroughly mentioned but there is a tiny bit about integrating the bootstrapper, [Injection Methods -> DLL Loader](https://reloaded-project.github.io/Reloaded-II/InjectionMethods/#dll-loader) for integrating it with external mod loaders.

I could probably rewrite the text a bit; it may be hard to swallow.

**Comment by javster101** [comment]
Alright, I'll check out that link at the end. Greatly appreciate the help!

**Comment by Sewer56** [comment]
Suppose I should also ask.
If you may, could you please state some of the reasons why you are working on a dedicated loader.

I may be focusing more on mods these days but knowing what the target audience desires makes for good feedback on the things I could be working on in the future :P

**Comment by javster101** [comment]
One example is that there a a bunch of specific files in the lego directory structure that need to be modified when adding stuff like characters (eg, editing CHARS.TXT), and alot of mods overwrite that specific file to add characters. Since the file redirect system only allows for one file to be selected, we'd need some system to merge these conficted files before using them, and alot of these merges are very specific to each file and each game so they can't necessarily be made as a general plugin.
