### ISSUE TITLE
Bug: Persona 4 crashes on load when using modloader. 

### ISSUE THREAD

**Issue by DrWolfnstine13** [Reloaded-Project/Reloaded-II#80]
**Describe the Bug**
Persona 4 when launched with the persona 4 golden modloader mod will crash to a black screen with the error message: Sorry Crashed.

**To Reproduce**
Run Reloaded II with admin privileges, Download Persona 4 Golden modloader and all dependencies. Run the application.

**Expected Behavior**
Game to load up as normal.

**Screenshots**

**Additional Context**
When loading without modloader game loads normally. It is only when modloader is selected that it fails.

**Comment by DrWolfnstine13** [comment]
For anyone who comes across this I found the issue. It is NOT a Reloaded issue. The problem is with P4 modloader crashing if there is a file NOT in a folder in the "mods" directory.
 
To solve: Navigate the "mods" directory where you keep your mods and deleted anything not in a folder, such as a text file, or whatever. In my case there was a readme in there and deleting it soved the issue.

**Comment by Sewer56** [comment]
Yeah, pretty much.

It's been fixed on the git version of modloader a while back; not really sure why the update with the hotfix hasn't been pushed out to end users by the author yet.

**Comment by DrWolfnstine13** [comment]
Yes it would be cool if they did, I spent hours tracking down the source of this issue and trying various fixes till I came across the solution.

**Comment by DrWolfnstine13** [comment]
Thanks so much for this program btw, it's really nice to able to mod p4 so easy.
