### ISSUE TITLE
Bug:Settings Reset When Reloded Launched

### ISSUE THREAD

**Issue by smokGH** [Reloaded-Project/Reloaded-II#81]
When I launch Reloaded II this error appears and not allowing me to run any games
![error](https://user-images.githubusercontent.com/81000492/111858600-a1163000-8910-11eb-8d7e-d97831634afe.PNG)

**Comment by Sewer56** [comment]
Please define: Not Allowing me to Launch Games.

=======

RE. Config Issue

This is probably Reloaded's longest standing bug  https://github.com/Reloaded-Project/Reloaded-II/issues/34 because it's rare, I'm lazy and nobody appears to know how to reliably reproduce it.

If you know how to reliably reproduce it, please let me know.

**Comment by smokGH** [comment]
"Not Allowing me to Launch Games" I cannot launch a game within Reloaded II with the mods installed on it

**Comment by Sewer56** [comment]
> "Not Allowing me to Launch Games" I cannot launch a game within Reloaded II with the mods installed on it

Do you have console enabled? Is there anything in the console?
Try giving it a screenshot before it disappears.

**Comment by smokGH** [comment]
![console](https://user-images.githubusercontent.com/81000492/111859010-fdc71a00-8913-11eb-87eb-d235e090b3ba.PNG)

**Comment by Sewer56** [comment]
> ![console](https://user-images.githubusercontent.com/81000492/111859010-fdc71a00-8913-11eb-87eb-d235e090b3ba.PNG)

Hmm, everything looks good.

I'd suggest checking the `mods` folder inside your P4G folder.
The p4g modloader mod is known for crashing if there are any files lying around in there without a folder.

**Comment by smokGH** [comment]
I have discovered something rather odd. Even though I've selected the p4g.exe the mods have been going to the complete wrong directory
![wrongdirectiry](https://user-images.githubusercontent.com/81000492/111859314-6adbaf00-8916-11eb-898e-dbd71d973a30.PNG) Do you know if there's a way to change the directory?

**Comment by Sewer56** [comment]
> I have discovered something rather odd. Even though I've selected the p4g.exe the mods have been going to the complete wrong directory
> ![wrongdirectiry](https://user-images.githubusercontent.com/81000492/111859314-6adbaf00-8916-11eb-898e-dbd71d973a30.PNG) Do you know if there's a way to change the directory?

Nothing wrong here.
See https://github.com/Reloaded-Project/Reloaded-II/issues/71#issuecomment-756559566 for a simple explanation.

**Comment by smokGH** [comment]
well my issue is there is nothing in the mods folder in the p4g steam files
