### ISSUE TITLE
Bug: I can't launch the application

### ISSUE THREAD

**Issue by gt7ujjb** [Reloaded-Project/Reloaded-II#83]
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Reloaded-II
2. Click on launch application
3.See error."アクセスが拒否されました" mean
"Access was denied".
**Additional Context**
same bug happened when mod didn't put in Reloaded-II .I've verified in Add/Remove Programs that my I have the correct VC C++ versions for both x86 and x64, and the .NET installer reports that it they are also both successfully installed.
![EB7C16C3-E7D4-4EAC-97EF-022E55336F58](https://user-images.githubusercontent.com/82384839/114394184-e1966000-9bd5-11eb-9a26-2f2a22e1ee19.jpeg)

**Comment by Sewer56** [comment]
Check for `Loader/Kernel32AddressDumper.exe` in your Reloaded II folder.
If it's there, maybe check antivirus logs.

![image](https://user-images.githubusercontent.com/6697380/114403885-1639f580-9b9d-11eb-86d6-43ecfa9950c1.png)

**Comment by gt7ujjb** [comment]
thanks!
it dues to antivirus program.
