### ISSUE TITLE
Bug: Release.zip is a badly-formed .zip file

### ISSUE THREAD

**Issue by jjbarr** [Reloaded-Project/Reloaded-II#86]
**Describe the Bug**
The `Release.zip` file uses backslashes as path separators. In the .zip file specification, it clearly states that forward slashes and only forward slashes should be used as path specifiers. Thus, conformant zip compression software will not correctly extract the Reloaded II release archive, causing difficulties running the software, particularly on non-Windows systems (where running Reloaded II inside of something like Wine may be desirable)

**To Reproduce**
Steps to reproduce the behaviour:
1. Download the latest Release.zip
2. Extract on any non-windows system (correct ZIP implementations on windows may also experience this issue, untested)
3. Notice instead of there being a `Colours.xaml` file inside `Theme/Default`, there is a file called `Theme\Default\Colours.xaml`, and various other similar examples.

**Expected Behaviour**
Folders should be extracted from the .zip file correctly, regardless of the software used to extract them, and regardless of system type.

**Comment by Sewer56** [comment]
Thanks for letting me know, I'll see what I can do to fix it by next release.
Here's the culprit:

![powershell_XkT9cik2IF](https://user-images.githubusercontent.com/6697380/116930722-04a5b400-ac58-11eb-8beb-ae3e5d12d876.png)

I use Powershell for my build script but it seems like PS targets the rather ancient .NET 4.0; which doesn't have the fix for changing the path separator in the `System.IO.Compression.ZipFile` namespace.

I'll probably just build with PS-Core and all will be good.

**Comment by Sewer56** [comment]
![image](https://user-images.githubusercontent.com/6697380/116931774-5733a000-ac59-11eb-8eab-812dd9fe6a0b.png)

Just confirming that running the build script with Powershell 7 fixes the issue.
I'll make sure to do so next update.

**Comment by Sewer56** [comment]
Pushing an update with a correctly formatting .zip.

**Comment by magomagal** [comment]
Same thing seems to be happening on Release 1.19.2, tried extracting via Engrampa Archive Manager on Manjaro and got the same results as OP.
On Windows via Winrar everything extracted just fine.

**Comment by Sewer56** [comment]
If I were to guess this happened when I started publishing automated builds using CI/CD around 1.19 (don't exactly remember when).  

I'm currently on vacation but I fixed the download manually in the meantime,

**Comment by Sewer56** [comment]
Fixed in: https://github.com/Sewer56/Update/commit/dd7b5250b2f0b1ca238f78f438aa269a4eb644c2
