### ISSUE TITLE
Bug: Controller constantly disconnects when using Reloaded II and DS4Windows

### ISSUE THREAD

**Issue by SlyCooperReloadCoded** [Reloaded-Project/Reloaded-II#87]
**Describe the Bug**
When launching games through Reloaded II with a controller connected with DS4Windows, the controller will constantly disconnect during gameplay.  When the same game is launched without Reloaded II, this does not happen.

**To Reproduce**
Steps to reproduce the behaviour:
1. Connect a PS4 controller.
2. Launch DS4Windows.
3. Start any game through Reloaded II.
4. Play for a bit.

**Expected Behaviour**
Controller works as expected and stays connected 100% of the time.

**Additional Context**
I wanted to use DS4Windows because no game launched through Reloaded II detects my PS4 controller, even though they do when launched normally through Steam.  There's a closed issue here, but the first solution didn't work for me, and the link to the second solution is a dead link:
https://github.com/Reloaded-Project/Reloaded-II/issues/38  So DS4Windows is my only choice, too bad this is happening to me.

**Comment by Sewer56** [comment]
Reloaded II itself does not interact with any USB Devices, DirectInput, Xinput or other related technology/api of the sort.
This is probably not a Reloaded issue.

I suggest the following:
- Test with mods disabled.
- Check for ASI Loader

If the issue happens only when using ASI Loader, please report to https://github.com/ThirteenAG/Ultimate-ASI-Loader instead.
You should also test with vanilla game (no steam, no reloaded) to see what happens.

**Comment by SlyCooperReloadCoded** [comment]
This issue can be closed.  The culprit was Steam constantly trying to apply its DS4 controller config during gameplay.  Why it only started doing this now is a mystery.  After turning off Steam controller support entirely, the issue stopped.
