### ISSUE TITLE
Bug: ASI Loader Method Not Capable of Loading P4G Mods

### ISSUE THREAD

**Issue by SlyCooperReloadCoded** [Reloaded-Project/Reloaded-II#88]
**Describe the Bug**
I've been desperately trying to get my PS4 controller to work with Reloaded II, as Steam games launched through Reloaded II refuse to detect it.  I finally tried the ASI Loader method, and it works.  There's one problem though - no mods actually load!  If I launch P4G through Reloaded II, the mods I have installed load properly but my PS4 controller is not detected and doesn't work.  If I set up the ASI loader and launch through Steam my PS4 controller works, Reloaded II loads and the mods are recognized by the loader, but the mods don't actually load ingame.

**To Reproduce**
Steps to reproduce the behaviour:
1. Set up P4G mods.
2. Launch through Reloaded II.
3. Mods will load, but PS4 controller will not work.
4. Quit game.
5. Open Reloaded II again and click on "Deploy ASI Loader".
6. Launch game through Steam.
7. Reloaded II will recognize and load your mods.
8. Mods won't actually load and you'll be playing the vanilla, unmodded game.

**Expected Behaviour**
ASI Loader method loads mods no matter where the game is launched from.

**Additional Context**
I've done hours and hours of Google searching.  I seem to be the only one who's suffering with this issue.

**Comment by Sewer56** [comment]
This sounds like more of a mod issue rather than a Reloaded issue however, that said.

Can you upload a log from the `Logs` folder?
You can access `Logs` from the settings menu in the launcher.

Consider using Verbose Mode 
![image](https://user-images.githubusercontent.com/6697380/118306147-e86c0780-b4e0-11eb-9f62-4a47caf90be5.png)

**Comment by Sewer56** [comment]
Closed due to inactivity.
