### ISSUE TITLE
I can't select the shared library option in Reloader for P4G

### ISSUE THREAD

**Issue by FN-Sayori** [Reloaded-Project/Reloaded-II#89]
I am trying to mod P4G and while following a guide I ran into an issue where it will not let me select [ Reloaded II Shared Lib: Reloaded.Hooks ] 

![Reloaded Rex Box](https://user-images.githubusercontent.com/84264067/118388969-75a08080-b5f5-11eb-8658-5868a508ee21.png)

And whenever the game launches I get this

![code](https://user-images.githubusercontent.com/84264067/118388999-9963c680-b5f5-11eb-9eb9-e11a54db3155.png)

What can be causing this issue and how can I fix it?

**Comment by Sewer56** [comment]
This is by design.

Some mods like this one exist only to provide services to other mods and will be loaded automatically when another mod needs them.

If you check the console printout you'll notice that the mod as in fact loaded (first lime after preparing mods finishes).

GLHF :)
