### ISSUE TITLE
hello having trouble trying to load persona 4 using P4G Music Manager

### ISSUE THREAD

**Issue by cookinv** [Reloaded-Project/Reloaded-II#90]
I get a error code assertion failed: couldn't fit all the environmental in allotted space 

is there anyway you could step by step fix thank you!

**Comment by cookinv** [comment]
![Capture](https://user-images.githubusercontent.com/85389949/120886334-4cdf2b80-c5a2-11eb-9823-c2ca3859e866.PNG)

**Comment by Sewer56** [comment]
This is game specific, ask in https://discord.gg/udJdnmWSFc
