### ISSUE TITLE
Help: Running under Wine

### ISSUE THREAD

**Issue by TheGag96** [Reloaded-Project/Reloaded-II#92]
Hi. I'm trying ultimately to set up mods for Persona 4 Golden. The big issue, of course, is that I'm doing this running on Linux Mint 20.1 x64 with Wine 6.11. Upon launching, I'm prompted to download and install .NET 5.0. I try the installer for "desktop" apps, version 5.0.7 x64, but it doesn't boot. I've seen [elsewhere](https://twitter.com/rudiger__tw/status/1381036704648298502) that you guys support Linux/Mac - how exactly are you supposed to go about it? Thank you!

**Comment by Sewer56** [comment]
I haven't used Wine in years so I'm not sure how much of help I might be, I've never used my mod loader under Wine. Might be something related to the wine prefix or some unknown dependency, god knows.

Generally when it comes to Wine, I rely on help from other people to report issues they encounter and test wine specific fixes/workarounds.

Fear not, communities are great. I've pinged a person who I know runs P4G on Wine with Reloaded; they may show up here sooner or later.

**Comment by monyarm** [comment]
I was running Gentoo linux with the latest proton-tkg, but it should be the same with the latest wine.
First I made sure the game was running properly. Then I downloaded https://gamebanana.com/mods/50961 which includes Install_Prerequisites.exe , which downloads and installs all the .net stuff you need.
After that I tried running the game with Reloaded II, but ran into issues, after talking with the devs on Discord, I helped them fix those issues.

So, so long as you have the prerequisites installed, it should run, authough some mods make the game crash.

I can't really be more helpful, cause I haven't touched P4G or Reloaded II in months.

**Comment by TheGag96** [comment]
This doesn't work for me... The prereq installer finishes "successfully" (seemingly rather too quickly) but changes nothing. Launching Reloaded-II.exe still prompts me to install .NET.

**Comment by n8jadams** [comment]
Is there a Discord channel? I got all the dependencies to work (eventually after installing a bunch of installers) but when I play Sonic Heroes, the menu seems fine but in-game it seems like it's not repainting/rerendering after the first frame.

**Comment by Sewer56** [comment]
> Is there a Discord channel? I got all the dependencies to work (eventually after installing a bunch of installers) but when I play Sonic Heroes, the menu seems fine but cutscene videos don't play and in-game it seems like it's not repainting/rerendering after the first frame. 

The first person to run Reloaded under Wine was @DeaTh-G (DeaThProj) and experienced that at some point too.

I'm not quite sure what they did to fix it; but I remember they did get it working eventually. IIRC it was related to Wine itself as opposed to Reloaded.

> I'd love to ask the devs on Discord and troubleshoot this.

For better or worse, it's just me :)

I don't test on Wine myself but I try to help out wherever I can and add workarounds as people report issues etc.

Having a Wine setup guide is something that is missing and quite frankly would be appreciated in the Wiki.

**Comment by Sewer56** [comment]
Forgot to close this.
