### ISSUE TITLE
reloaded II won't open at all

### ISSUE THREAD

**Issue by not-avai** [Reloaded-Project/Reloaded-II#96]
**Did you install the Prerequisites?**
yes,ALL of them,64x and 86x i searched the latest version myself,and also downloaded other things made by the same person or whatever created it.

**Describe the Issue**
When i click it,it won't open. No error message,no virus,no warning,anything. it just won't open.

**information**
my pc is a bit bad,but it can load sonic mania,sadx and sonic heroes,so it should be able to run it.
my pc is a windows 7 64 bits

**which version of reloaded**
latest,downloaded in github,reloaded II

**Comment by Sewer56** [comment]
Can you click on an empty space in your Reloaded folder while holding shift: 
![image](https://user-images.githubusercontent.com/6697380/127063461-98d6a0ea-8385-4870-aa1c-03247b1c052f.png)

And click `Open Command Prompt Here` or `Open PowerShell Here` (whichever is available).
Then type `dotnet Reloaded-II.dll` and press enter.

![image](https://user-images.githubusercontent.com/6697380/127063579-60fffe5f-9d45-45cf-a325-265a9ff2a678.png)

Does anything unusual happen?
If there is an error message, can you screenshot it?

**Comment by not-avai** [comment]
> Can you click on an empty space in your Reloaded folder while holding shift:
> ![image](https://user-images.githubusercontent.com/6697380/127063461-98d6a0ea-8385-4870-aa1c-03247b1c052f.png)
> 
> And click `Open Command Prompt Here` or `Open PowerShell Here` (whichever is available).
> Then type `dotnet Reloaded-II.dll` and press enter.
> 
> ![image](https://user-images.githubusercontent.com/6697380/127063579-60fffe5f-9d45-45cf-a325-265a9ff2a678.png)
> 
> Does anything unusual happen?
> If there is an error message, can you screenshot it?

![image](https://user-images.githubusercontent.com/88006155/127065165-a77e2786-548f-4f26-b8f3-6c6db1e83dc9.png)

**Comment by Sewer56** [comment]
> > Can you click on an empty space in your Reloaded folder while holding shift:
> > ![image](https://user-images.githubusercontent.com/6697380/127063461-98d6a0ea-8385-4870-aa1c-03247b1c052f.png)
> > And click `Open Command Prompt Here` or `Open PowerShell Here` (whichever is available).
> > Then type `dotnet Reloaded-II.dll` and press enter.
> > ![image](https://user-images.githubusercontent.com/6697380/127063579-60fffe5f-9d45-45cf-a325-265a9ff2a678.png)
> > Does anything unusual happen?
> > If there is an error message, can you screenshot it?
> 
> ![image](https://user-images.githubusercontent.com/88006155/127065165-a77e2786-548f-4f26-b8f3-6c6db1e83dc9.png)

I've seen that error a long, long time ago; I remember someone else getting it.
If I recall correctly, installing Wiindows Updates fixed it for them.

**Comment by not-avai** [comment]
> > > Can you click on an empty space in your Reloaded folder while holding shift:
> > > ![image](https://user-images.githubusercontent.com/6697380/127063461-98d6a0ea-8385-4870-aa1c-03247b1c052f.png)
> > > And click `Open Command Prompt Here` or `Open PowerShell Here` (whichever is available).
> > > Then type `dotnet Reloaded-II.dll` and press enter.
> > > ![image](https://user-images.githubusercontent.com/6697380/127063579-60fffe5f-9d45-45cf-a325-265a9ff2a678.png)
> > > Does anything unusual happen?
> > > If there is an error message, can you screenshot it?
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/88006155/127065165-a77e2786-548f-4f26-b8f3-6c6db1e83dc9.png)
> 
> I've seen that error a long, long time ago; I remember someone else getting it.
> If I recall correctly, installing Wiindows Updates fixed it for them.

okay,thank you very much

**Comment by not-avai** [comment]
> > > Can you click on an empty space in your Reloaded folder while holding shift:
> > > ![image](https://user-images.githubusercontent.com/6697380/127063461-98d6a0ea-8385-4870-aa1c-03247b1c052f.png)
> > > And click `Open Command Prompt Here` or `Open PowerShell Here` (whichever is available).
> > > Then type `dotnet Reloaded-II.dll` and press enter.
> > > ![image](https://user-images.githubusercontent.com/6697380/127063579-60fffe5f-9d45-45cf-a325-265a9ff2a678.png)
> > > Does anything unusual happen?
> > > If there is an error message, can you screenshot it?
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/88006155/127065165-a77e2786-548f-4f26-b8f3-6c6db1e83dc9.png)
> 
> I've seen that error a long, long time ago; I remember someone else getting it.
> If I recall correctly, installing Wiindows Updates fixed it for them.

okay,now the problem is that windows won't let me update because i'm "not the admin" even tho i am
guess i'll have to search for mods that doesnt use mod loader then
