### ISSUE TITLE
Unknown error appears after last update

### ISSUE THREAD

**Issue by TyT-NICK** [Reloaded-Project/Reloaded-II#97]
Getting this on start after the last update. Have seen that it could be helpfull to update Windows but I dont have one.
![image](https://user-images.githubusercontent.com/53619450/127531333-bc849274-8c0e-4eee-b48f-088009fc0ce3.png)

The list of modes, all of them are installed from Banana and have been worked till the last update:
![image](https://user-images.githubusercontent.com/53619450/127531884-235711e2-0a75-4711-9ee0-5b5022bf8a2d.png)

Nevertheless, Reloaded-II opens but it misses user settings

**Comment by Sewer56** [comment]
Happened only once right?
I could have sworn I fixed this, but maybe there's really another edge case somewhere in there.

**Comment by TyT-NICK** [comment]
Nope, got this several times. I can reload again to check if it will appear again

**Comment by TyT-NICK** [comment]
Not getting 'unknown' issue, but now getting this:
![image](https://user-images.githubusercontent.com/53619450/127533746-a921590f-ed0d-4ae6-bc6f-5e2921a7be21.png)

**Comment by Sewer56** [comment]
Any specific reproduction steps?
Would be useful if this can somehow be repeated.

Anything unusual happen after the error?
I haven't changed anything related to file handling in a long while, so strange it'd only happen now.

**Comment by Sewer56** [comment]
> Not getting 'unknown' issue, but now getting this:
> ![image](https://user-images.githubusercontent.com/53619450/127533746-a921590f-ed0d-4ae6-bc6f-5e2921a7be21.png)

That's normal, don't worry about it. R-II uses GitHub for checking updates every boot and GitHub has a limit of 60 checks per hour.

I should maybe limit it to once per 5 minutes to avoid people exhausting the limit by turning the launcher off and on again.

**Comment by TyT-NICK** [comment]
The only unusual step on load is launching via Steam (I need this to use Steam-controller). Dont think this may cause the bug. 

During first launch after update got that error message window about 30 times (cant say exactly because had to close it with task manager). I think this is why i reached updates check

**Comment by Sewer56** [comment]
Only Reloaded's launcher actually writes to the config file in question. The loader only reads from it.

So the bug or culprit is somewhere in the launcher itself.
