### ISSUE TITLE
Bug: Error when I try launch the launcher :v

### ISSUE THREAD

**Issue by ElMaisi** [Reloaded-Project/Reloaded-II#98]
![image](https://user-images.githubusercontent.com/88168823/127577374-d84fec20-3d44-4076-9a30-0ff78a28485f.png)

It ocurres when i tries to open the Reloaded II, I dont know what is my error.
I install he repositories and well... nothing new

**Comment by ElMaisi** [comment]
Hello everyone!
Simply: if you have this error, you are then dumb equal I.
You only needs rename the folder to "Reloaded II" and now should work.

**Comment by Sewer56** [comment]
The error here was the failure to write to the Windows Registry.
Reloaded does this to install the `r2` custom URL handler used for 1 click installs on GameBanana.

If this operation failed as shown above, yet somehow worked after renaming the folder, then chances are that either:
- You have some weird OS Permissions and ran Reloaded as admin the second time.
- Your antivirus got in the way.

**Comment by ElMaisi** [comment]
> El error aquí fue el error al escribir en el registro de Windows.
> 
> Reloaded hace esto para instalar el controlador de URL personalizado utilizado para 1 clic instala en GameBanana.`r2`
> 
> Si esta operación falló como se muestra arriba, pero de alguna manera funcionó después de cambiar el nombre de la carpeta, entonces lo más probable es que:
> 
> * Tiene algunos permisos de sistema operativo extraños y ejecutó Reloaded como administrador la segunda vez.
> * Su antivirus se puso en el camino.

Anyways, i make an exception for the folder and the .exe in my antivirus, and everything is right. Thanks.
